import type { Question } from '../../types'

// Stage 8 review: interleaved questions mixing physiology with Stage 1 foundations
// (priorities, heat balance, clothing, water, stay-or-move, daylight, risk).
export const stage8Review: Question[] = [
  {
    id: 's8-rev-1',
    kind: 'single',
    prompt: 'Moorland, 4 °C, rain, 30 km/h wind, 16:00, sunset 17:10. Your partner has twisted an ankle and cannot walk far; she is soaked in cotton and starting to shiver. You carry a tarp, foam pads, a dry synthetic layer set, food and a phone with weak signal. What is the highest-value first action?',
    choices: [
      { id: 'a', text: 'Help her hobble the 6 km back to the car before it gets dark.', why: 'Slow, in wind and rain, in wet cotton — she will cool faster than she walks.' },
      { id: 'b', text: 'Shelter her from the wind on pads in dry layers under the tarp, feed her, then message.', why: 'Best: the largest heat losses (wet, wind, ground) are cut in minutes; communication with your position follows immediately.' },
      { id: 'c', text: 'Climb to high ground first to get a better phone signal out.', why: 'Communication matters, but leaving her wet in the wind lets hypothermia start.' },
      { id: 'd', text: 'Wait for the rain to ease before starting to sort anything out.', why: 'The losses are happening now.' },
    ],
    answer: 'b',
    concepts: ['priorities', 'wet-wind', 'hypothermia', 'stay-or-move'],
    explanation: 'Name the mechanisms (evaporation, convection, conduction) and cut them cheaply; then communicate. Stay-or-move with an injured, cooling person usually means stay and call.',
  },
  {
    id: 's8-rev-2',
    kind: 'single',
    prompt: 'Using the 2001 formula $WC = 13.12 + 0.6215T - 11.37V^{0.16} + 0.3965TV^{0.16}$, what is the wind chill at −15 °C with 20 km/h wind? ($20^{0.16} \\approx 1.615$.)',
    choices: [
      { id: 'a', text: '≈ −24 °C', why: 'Correct — 13.12 − 9.32 − 18.36 − 9.61.' },
      { id: 'b', text: '≈ −15 °C', why: 'This drops the last term, 0.3965 × (−15) × 1.615 ≈ −9.61.' },
      { id: 'c', text: '≈ −5 °C', why: 'This adds the last term as +9.61; with T negative it is −9.61.' },
      { id: 'd', text: '≈ −19 °C', why: 'This enters the wind in m/s (5.6) instead of km/h.' },
    ],
    answer: 'a',
    concepts: ['wind-chill'],
    explanation: '13.12 + 0.6215(−15) − 11.37(1.615) + 0.3965(−15)(1.615) = 13.12 − 9.32 − 18.36 − 9.61 ≈ **−24 °C**.',
  },
  {
    id: 's8-rev-3',
    kind: 'single',
    prompt: 'A hiker in 38 °C heat becomes confused and stumbles. What is the right response?',
    choices: [
      { id: 'a', text: 'Cool them at once, by immersion if possible, and call for evacuation now.', why: 'Correct — confusion in heat = heat stroke until proven otherwise; cool first, transport second, but call now.' },
      { id: 'b', text: 'Check first whether their skin is dry before deciding it is heat stroke.', why: 'Exertional heat stroke victims often sweat; do not wait on dry skin.' },
      { id: 'c', text: 'Walk them slowly to the trailhead so that transport can take over.', why: 'Exertion adds heat; cool on the spot.' },
      { id: 'd', text: 'Rest them in shade with sips of water and reassess in 30 minutes.', why: 'That is care for heat exhaustion; confusion means heat stroke and needs immediate cooling.' },
    ],
    answer: 'a',
    concepts: ['heat-illness', 'priorities'],
    explanation: 'CNS dysfunction separates heat stroke from exhaustion. Time above ~40 °C drives the damage, so cool immediately and call early.',
  },
  {
    id: 's8-rev-4',
    kind: 'single',
    prompt: 'Desert, 40 °C, 10 km from the road, 3 L of water. Which plan best reflects both Stage 1 water rules and heat physiology?',
    choices: [
      { id: 'a', text: 'Walk now at midday, sipping sparingly to make the water last.', why: 'Midday walking maximises sweat; rationing water while sweating is the classic error.' },
      { id: 'b', text: 'Rest in shade through the heat, drink to thirst, stay clothed; walk evening and morning.', why: 'Best: ration sweat, not water.' },
      { id: 'c', text: 'Strip to shorts to stay cool, and walk out now while you can.', why: 'Bare skin gains more radiant heat and loses more water.' },
      { id: 'd', text: 'Drink all 3 L now to “bank” it in your body, then walk out.', why: 'Excess is excreted; drink to need.' },
    ],
    answer: 'b',
    concepts: ['water-needs', 'dehydration', 'heat-illness'],
    explanation: 'Resting in shade cuts metabolic and solar heat — the biggest water saving available.',
  },
  {
    id: 's8-rev-5',
    kind: 'single',
    prompt: 'You are first on scene: a kayaker has just been pulled onto a dock after 40 minutes in 6 °C water. He is drowsy and not shivering. What do you do **first**?',
    choices: [
      { id: 'a', text: 'Keep him lying down and handle him gently', why: 'Correct — from the first second, to prevent circum-rescue collapse.' },
      { id: 'b', text: 'Sit him up to check his airway and breathing', why: 'Check airway and breathing next — but keep him horizontal while you do it.' },
      { id: 'c', text: 'Call emergency services before touching him', why: 'Call early, but gentle horizontal handling and airway come first.' },
      { id: 'd', text: 'Wrap him in insulation with heat to the trunk', why: 'Packaging comes after airway, breathing and the call.' },
    ],
    answer: 'a',
    concepts: ['afterdrop', 'immersion-hypothermia', 'hypothermia'],
    explanation: 'Gentle, horizontal handling from the first second (circum-rescue collapse), then airway and breathing (he may have inhaled water), call, then package. Learn it on a WFA course.',
  },
  {
    id: 's8-rev-6',
    kind: 'single',
    prompt: 'On a clear, calm night, how does adding a tarp overhead affect your heat loss?',
    choices: [
      { id: 'a', text: 'It cuts radiative loss by replacing the cold sky with a warmer surface.', why: 'Correct — the tarp is near air temperature, the clear sky is far colder (Stefan–Boltzmann).' },
      { id: 'b', text: 'It does nothing, because the air temperature under it is unchanged.', why: 'Air temperature is not the only route; radiation to the sky is cut.' },
      { id: 'c', text: 'It helps only by blocking wind, which matters little on a calm night.', why: 'On a calm night its main effect is on radiation, not wind.' },
      { id: 'd', text: 'It traps warm air like a tent and raises the air temperature a lot.', why: 'It does nothing about the air temperature; it changes what you radiate to.' },
    ],
    answer: 'a',
    concepts: ['radiative-loss', 'shelter-types'],
    explanation: 'The tarp replaces a very cold sky with a surface near air temperature, cutting radiative loss (Stefan–Boltzmann) even though the air temperature is unchanged.',
  },
  {
    id: 's8-rev-7',
    kind: 'single',
    prompt: 'A 60 kg walker loses 1.5 L more than she drinks. What % of body mass is that?',
    choices: [
      { id: 'a', text: '2.5 %', why: 'Correct — 1.5 kg of 60 kg.' },
      { id: 'b', text: '2.6 %', why: 'This divides by the reduced mass (58.5 kg) instead of 60 kg.' },
      { id: 'c', text: '0.025 %', why: 'This leaves the fraction (0.025) without multiplying by 100.' },
      { id: 'd', text: '40 %', why: 'This inverts the ratio (60 ÷ 1.5).' },
    ],
    answer: 'a',
    concepts: ['dehydration', 'water-needs'],
    explanation: '1.5 / 60 × 100 = **2.5 %** — past the ~2 % point where endurance and judgment suffer.',
  },
  {
    id: 's8-rev-8',
    kind: 'single',
    prompt: 'Night 2 of a winter bivouac. You slept 3 hours last night, have eaten little, and at 03:00 your partner proposes descending an unknown icy gully by headlamp. Your shelter is adequate. What is the best reasoning?',
    choices: [
      { id: 'a', text: 'Go now: moving down the gully will warm you both up again.', why: 'Warmth from moving does not offset impaired judgment, poor night vision and a high-consequence, irreversible choice.' },
      { id: 'b', text: 'Eat, make a warm drink, stay put until first light, then decide with a checklist.', why: 'Best: reversible, fuels shivering and thinking, and moves the big decision out of the circadian low.' },
      { id: 'c', text: 'Split up so that one of you can go on ahead and get help.', why: 'Separating impaired people adds risk.' },
      { id: 'd', text: 'Stay awake all night to be sure you do not get too cold.', why: 'Sleeping in adequate insulation is safe and repays sleep debt.' },
    ],
    answer: 'b',
    concepts: ['sleep-deprivation', 'glycogen', 'reversibility', 'decisions'],
    explanation: 'Fatigue, hunger and darkness stack. Prefer reversible options and make irreversible decisions in daylight after food.',
  },
  {
    id: 's8-rev-9',
    kind: 'single',
    prompt: 'You planned a trek that sleeps at 3,000, 3,900 and 4,600 m on consecutive nights. What is the main problem?',
    choices: [
      { id: 'a', text: 'Gains of 900 and 700 m a night exceed ~500 m/day, with no rest day.', why: 'Correct — above 3,000 m this gives a high AMS risk.' },
      { id: 'b', text: 'Nothing, as long as everyone in the group is fit.', why: 'Fitness does not protect.' },
      { id: 'c', text: 'Only that the nights at 4,600 m will be very cold.', why: 'Cold matters, but ascent rate is the main issue.' },
      { id: 'd', text: 'The first night, at 3,000 m, is set too low to be useful.', why: 'A low start is good.' },
    ],
    answer: 'a',
    concepts: ['ascent-rate', 'trip-plan'],
    explanation: 'Fix the plan before you go: add nights so sleeping gain is ≤ 500 m/day above 3,000 m with rest days — a trip-plan decision, not a mountain one.',
  },
  {
    id: 's8-rev-10',
    kind: 'single',
    prompt: 'Someone may fall into 8 °C water from a small boat on a warm spring day. Which clothing or kit choice is a **mistake**?',
    choices: [
      { id: 'a', text: 'Wearing (not just carrying) a PFD', why: 'Right choice — it holds the airway up through cold shock and after swim failure.' },
      { id: 'b', text: 'Dressing for the water temperature (wetsuit or drysuit)', why: 'Right choice — it cuts cold shock and lengthens every window.' },
      { id: 'c', text: 'A whistle and a waterproof way to call for help', why: 'Right choice — rescue time is the other half of the equation.' },
      { id: 'd', text: 'Cotton layers, because the air is warm', why: 'Correct — this is the mistake: cotton gives little insulation wet.' },
    ],
    answer: 'd',
    concepts: ['cold-shock', 'clothing', 'kit'],
    explanation: 'Dress for immersion, wear flotation, carry signalling: the Stage 1 kit logic applied to water.',
  },
]
