import type { Question } from '../../types'

// Stage 8 review: interleaved questions mixing physiology with Stage 1 foundations
// (priorities, heat balance, clothing, water, stay-or-move, daylight, risk).
export const stage8Review: Question[] = [
  {
    id: 's8-rev-1',
    kind: 'single',
    prompt: 'Moorland, 4 °C, rain, 30 km/h wind, 16:00, sunset 17:10. Your partner has twisted an ankle and cannot walk far; she is soaked in cotton and starting to shiver. You carry a tarp, foam pads, a dry synthetic layer set, food and a phone with weak signal. What is the highest-value first action?',
    choices: [
      { id: 'a', text: 'Help her hobble 6 km back to the car before dark.', why: 'Slow, in wind and rain, in wet cotton — she will cool faster than she walks.' },
      { id: 'b', text: 'Get her out of the wind, onto pads, into dry synthetic layers under a shell and the tarp, give food — then send a message with your position.', why: 'Best: the largest heat losses (wet, wind, ground) are cut in minutes; communication follows immediately.' },
      { id: 'c', text: 'Climb to high ground to get a better phone signal first.', why: 'Communication matters, but leaving her wet in the wind lets hypothermia start.' },
      { id: 'd', text: 'Wait for the rain to stop before doing anything.', why: 'The losses are happening now.' },
    ],
    answer: 'b',
    concepts: ['priorities', 'wet-wind', 'hypothermia', 'stay-or-move'],
    explanation: 'Name the mechanisms (evaporation, convection, conduction) and cut them cheaply; then communicate. Stay-or-move with an injured, cooling person usually means stay and call.',
  },
  {
    id: 's8-rev-2',
    kind: 'numeric',
    prompt: 'Using the 2001 formula, what is the wind chill at −15 °C with 20 km/h wind? ($20^{0.16} \\approx 1.615$; nearest °C.)',
    unit: '°C',
    answer: -24,
    tolerance: 1,
    concepts: ['wind-chill'],
    explanation: '13.12 + 0.6215(−15) − 11.37(1.615) + 0.3965(−15)(1.615) = 13.12 − 9.32 − 18.36 − 9.61 ≈ **−24 °C**.',
  },
  {
    id: 's8-rev-3',
    kind: 'multi',
    prompt: 'A hiker in 38 °C heat becomes confused and stumbles. Which actions are right?',
    choices: [
      { id: 'a', text: 'Treat as heat stroke: cool immediately, by immersion if possible', why: 'Yes — confusion in heat = heat stroke until proven otherwise.' },
      { id: 'b', text: 'Call for evacuation early, while cooling', why: 'Yes — cool first, transport second, but call now.' },
      { id: 'c', text: 'Wait to see whether the skin is dry before deciding', why: 'No — exertional heat stroke victims often sweat.' },
      { id: 'd', text: 'Walk them slowly to the trailhead for transport', why: 'No — exertion adds heat; cool on the spot.' },
    ],
    answer: ['a', 'b'],
    concepts: ['heat-illness', 'priorities'],
    explanation: 'CNS dysfunction separates heat stroke from exhaustion. Time above ~40 °C drives the damage.',
  },
  {
    id: 's8-rev-4',
    kind: 'single',
    prompt: 'Desert, 40 °C, 10 km from the road, 3 L of water. Which plan best reflects both Stage 1 water rules and heat physiology?',
    choices: [
      { id: 'a', text: 'Walk now at midday, sipping sparingly to make the water last.', why: 'Midday walking maximises sweat; rationing water while sweating is the classic error.' },
      { id: 'b', text: 'Rest in shade through the heat, drink to thirst, keep clothing on, and walk in the evening and early morning.', why: 'Best: ration sweat, not water.' },
      { id: 'c', text: 'Strip to shorts to stay cool and walk now.', why: 'Bare skin gains more radiant heat and loses more water.' },
      { id: 'd', text: 'Drink all 3 L now to “bank” it.', why: 'Excess is excreted; drink to need.' },
    ],
    answer: 'b',
    concepts: ['water-needs', 'dehydration', 'heat-illness'],
    explanation: 'Resting in shade cuts metabolic and solar heat — the biggest water saving available.',
  },
  {
    id: 's8-rev-5',
    kind: 'order',
    prompt: 'You are first on scene: a kayaker has just been pulled onto a dock after 40 minutes in 6 °C water. He is drowsy and not shivering. Order your actions.',
    items: [
      { id: 'horizontal', text: 'Keep him lying down; handle gently' },
      { id: 'abc', text: 'Check breathing and airway (he may have inhaled water)' },
      { id: 'call', text: 'Call emergency services' },
      { id: 'wrap', text: 'Remove from wind, insulate above and below, vapour barrier, heat to trunk' },
    ],
    answer: ['horizontal', 'abc', 'call', 'wrap'],
    concepts: ['afterdrop', 'immersion-hypothermia', 'hypothermia'],
    explanation: 'Gentle, horizontal handling from the first second (circum-rescue collapse), airway and breathing, call, then package. Learn it on a WFA course.',
  },
  {
    id: 's8-rev-6',
    kind: 'truefalse',
    prompt: 'On a clear, calm night, adding a tarp overhead can reduce heat loss even though it does nothing about the air temperature.',
    answer: true,
    concepts: ['radiative-loss', 'shelter-types'],
    explanation: 'The tarp replaces a very cold sky with a surface near air temperature, cutting radiative loss (Stefan–Boltzmann).',
  },
  {
    id: 's8-rev-7',
    kind: 'numeric',
    prompt: 'A 60 kg walker loses 1.5 L more than she drinks. What % of body mass is that? (One decimal.)',
    unit: '%',
    answer: 2.5,
    tolerance: 0.1,
    concepts: ['dehydration', 'water-needs'],
    explanation: '1.5 / 60 × 100 = **2.5 %** — past the ~2 % point where endurance and judgment suffer.',
  },
  {
    id: 's8-rev-8',
    kind: 'single',
    prompt: 'Night 2 of a winter bivouac. You slept 3 hours last night, have eaten little, and at 03:00 your partner proposes descending an unknown icy gully by headlamp. Your shelter is adequate. What is the best reasoning?',
    choices: [
      { id: 'a', text: 'Go: moving will warm you up.', why: 'Warmth from moving does not offset impaired judgment, poor night vision and a high-consequence, irreversible choice.' },
      { id: 'b', text: 'Eat, refuel the stove for a warm drink, stay put until first light, then decide with a checklist.', why: 'Best: reversible, fuels shivering and thinking, and moves the big decision out of the circadian low.' },
      { id: 'c', text: 'Split up so one can go for help.', why: 'Separating impaired people adds risk.' },
      { id: 'd', text: 'Stay awake all night to be sure you do not get too cold.', why: 'Sleeping in adequate insulation is safe and repays sleep debt.' },
    ],
    answer: 'b',
    concepts: ['sleep-deprivation', 'glycogen', 'reversibility', 'decisions'],
    explanation: 'Fatigue, hunger and darkness stack. Prefer reversible options and make irreversible decisions in daylight after food.',
  },
  {
    id: 's8-rev-9',
    kind: 'single',
    prompt: 'You planned a trek that sleeps at 3,000, 3,900 and 4,600 m on consecutive nights. What is the main problem?',
    choices: [
      { id: 'a', text: 'Sleeping-altitude gains of 900 and 700 m exceed ~500 m/day above 3,000 m, with no rest day.', why: 'Correct — high AMS risk.' },
      { id: 'b', text: 'Nothing, if everyone is fit.', why: 'Fitness does not protect.' },
      { id: 'c', text: 'Only that it will be cold.', why: 'Cold matters, but ascent rate is the main issue.' },
      { id: 'd', text: 'The first night is too low.', why: 'A low start is good.' },
    ],
    answer: 'a',
    concepts: ['ascent-rate', 'trip-plan'],
    explanation: 'Fix the plan before you go: add nights so sleeping gain is ≤ 500 m/day above 3,000 m with rest days — a trip-plan decision, not a mountain one.',
  },
  {
    id: 's8-rev-10',
    kind: 'multi',
    prompt: 'Which clothing and kit choices matter most for someone who may fall into 8 °C water from a small boat on a warm spring day?',
    choices: [
      { id: 'a', text: 'Wearing (not just carrying) a PFD', why: 'Yes — holds the airway up through cold shock and after swim failure.' },
      { id: 'b', text: 'Dressing for the water temperature (wetsuit or drysuit)', why: 'Yes — cuts cold shock and lengthens every window.' },
      { id: 'c', text: 'A whistle and a waterproof way to call for help', why: 'Yes — rescue time is the other half of the equation.' },
      { id: 'd', text: 'Cotton layers because the air is warm', why: 'No — cotton gives little insulation wet.' },
    ],
    answer: ['a', 'b', 'c'],
    concepts: ['cold-shock', 'clothing', 'kit'],
    explanation: 'Dress for immersion, wear flotation, carry signalling: the Stage 1 kit logic applied to water.',
  },
]
