import type { Question } from '../../types'

// Stage 7 review: interleaves bushcraft engineering with earlier-stage concepts
// (fire structure, heat balance, priorities, kit redundancy, water treatment, wind loading).
export const stage7Review: Question[] = [
  {
    id: 's7-rev-1',
    kind: 'single',
    prompt: 'Damp boreal forest, 4 °C, 16:00, dark at 17:30. You are wet from a fall and alone, with a tarp, 10 m of cord, a knife and a lighter. A patch of dead fireweed promises good cordage fiber. What comes first?',
    choices: [
      { id: 'a', text: 'Process the fireweed into cord while there is still light: cord is always useful.', why: 'Sitting still and wet at 4 °C loses heat fast; cord-making is slow and low priority now.' },
      { id: 'b', text: 'Pitch the tarp with your cord, get into dry layers off the ground, then gather fuel.', why: 'Best: stop the heat loss first, then add heat. Cordage can wait for tomorrow.' },
      { id: 'c', text: 'Keep walking briskly to stay warm until dark, then deal with camp.', why: 'Sweat in wet clothes at dusk worsens the heat balance and the night.' },
      { id: 'd', text: 'Build a charcoal retort so you can have a smokeless fire tonight.', why: 'Hours of work for a fuel you do not need.' },
    ],
    answer: 'b',
    concepts: ['priorities', 'heat-balance', 'natural-fibers'],
    explanation: 'Bushcraft projects never outrank shelter and warmth: pitch the tarp, change into dry layers, insulate from the ground, then prepare fire fuel. Use carried kit first; improvise second.',
  },
  {
    id: 's7-rev-2',
    kind: 'single',
    prompt: 'Which conclusion about Stage 1 kit principles does this stage **not** support?',
    choices: [
      { id: 'a', text: 'Carry more cord than you expect: making it costs ~15 min per metre', why: 'It supports this: carried cord is cheap redundancy.' },
      { id: 'b', text: 'Carry two fire-lighting methods; retort char cloth extends a ferro kit', why: 'It supports this: diverse redundancy for a critical function.' },
      { id: 'c', text: 'Carry a fixed-blade knife, since a folder can fail when batoning', why: 'It supports this: the right tool for the job removes a hazard.' },
      { id: 'd', text: 'Once you can make cordage, you no longer need to carry any', why: 'Correct: improvised cordage is slow, weaker and uneven.' },
    ],
    answer: 'd',
    concepts: ['kit', 'redundancy', 'cordage-strength'],
    explanation: 'Skills are backup for kit, not a replacement for it.',
  },
  {
    id: 's7-rev-3',
    kind: 'single',
    prompt: 'A food bag weighs 60 N. You haul it over a branch with half a wrap (θ = π), μ = 0.3. What pull is needed to **raise** it slowly?',
    choices: [
      { id: 'a', text: '≈ 23 N', why: 'This divides by e^(μθ). That is the hold force for lowering; raising works against friction.' },
      { id: 'b', text: '≈ 81 N', why: 'This uses θ = 1 rad. Half a wrap is π radians.' },
      { id: 'c', text: '≈ 154 N', why: 'Correct: 60 × e^(0.3π) = 60 × 2.57 ≈ 154 N.' },
      { id: 'd', text: '≈ 395 N', why: 'This uses a full wrap (θ = 2π). Over a branch the cord wraps only half way.' },
    ],
    answer: 'c',
    concepts: ['capstan-friction'],
    explanation: 'T = 60 × e^(0.3π) = 60 × 2.57 ≈ **154 N**. The hauling side carries 2.6× the load, so size your cord for that, not for the bag.',
  },
  {
    id: 's7-rev-4',
    kind: 'single',
    prompt: 'You need dry kindling from wet, wrist-thick dead-standing wood. Which approach follows both Stage 3 fire structure and Stage 7 knife safety?',
    choices: [
      { id: 'a', text: 'Baton knot-free rounds with a full-tang knife, then carve feather sticks from the dry core', why: 'Correct: dry core, high surface-to-volume, safe technique on a block.' },
      { id: 'b', text: 'Lay whole wet rounds straight on the tinder and wait for them to dry out and catch', why: 'Too thick and too wet: they absorb heat faster than the flame can pyrolyse them.' },
      { id: 'c', text: 'Baton the rounds with a folding knife to save your good fixed blade from wear', why: 'Folding knives fail when batoned.' },
      { id: 'd', text: 'Char the wet rounds first in someone else’s fire, then add them to your own', why: 'Wastes time and heat.' },
    ],
    answer: 'a',
    concepts: ['fire-structure', 'batoning', 'surface-to-volume'],
    explanation: 'Splitting exposes the dry core; feather sticks and pencil-lead shavings climb the fuel ladder; safe batoning keeps you uninjured.',
  },
  {
    id: 's7-rev-5',
    kind: 'single',
    prompt: 'Stone boiling: how many **kg** of stones at 500 °C (c = 0.8 kJ/(kg·°C)) bring 3 L of water from 20 °C to 100 °C with η = 0.7? Water c = 4.18 kJ/(kg·°C).',
    choices: [
      { id: 'a', text: '≈ 3.1 kg', why: 'This forgets the efficiency η = 0.7: 1,003/320.' },
      { id: 'b', text: '≈ 3.6 kg', why: 'This lets the stone cool by 500 °C. It only cools to 100 °C, so ΔT is 400 °C.' },
      { id: 'c', text: '≈ 4.5 kg', why: 'Correct: 1,003 kJ needed ÷ 224 kJ per kg of stone ≈ 4.5 kg.' },
      { id: 'd', text: '≈ 5.6 kg', why: 'This heats the water from 0 °C instead of 20 °C (ΔT 100 instead of 80).' },
    ],
    answer: 'c',
    concepts: ['stone-boiling', 'water-treatment'],
    explanation: 'Water: 3 × 4.18 × 80 = 1,003 kJ. Stone: 0.8 × 400 × 0.7 = 224 kJ/kg. 1,003/224 ≈ **4.5 kg**. Then hold a rolling boil for 1 minute.',
  },
  {
    id: 's7-rev-6',
    kind: 'single',
    prompt: 'A 4 m ridgeline with 20 cm of sag carries 300 N in a steady wind. Gusts are forecast. Which change **most** reduces the risk of breaking hand-made cord?',
    choices: [
      { id: 'a', text: 'Tighten it to 10 cm of sag so it flaps less in the gusts', why: 'Halving the sag doubles the tension.' },
      { id: 'b', text: 'Pitch lower, add guys, allow more sag, take turns round each tree', why: 'Correct: less force, lower tension, and the load moved onto friction before the knot.' },
      { id: 'c', text: 'Replace the figure-eight at each tree with a stronger reef knot', why: 'A reef knot is weaker, and it capsizes.' },
      { id: 'd', text: 'Wet the cord, since bast fiber gains a little strength when wet', why: 'Bast fiber gains a little strength wet, but this does not address the load.' },
    ],
    answer: 'b',
    concepts: ['wind-loading', 'capstan-friction', 'knot-efficiency'],
    explanation: 'Control the load first (area, sag, guys), then the weak point (two turns round the tree before the knot).',
  },
  {
    id: 's7-rev-7',
    kind: 'single',
    prompt: 'Why is a reverse-wrapped two-ply cord stronger than a single twisted strand of the same fiber?',
    choices: [
      { id: 'a', text: 'Its balanced torque keeps the twist, and so the fiber friction, under load', why: 'Correct: a single strand unwinds under load and loses the squeeze that makes fibers grip.' },
      { id: 'b', text: 'Plying bonds the fibers chemically so they stop sliding past each other', why: 'Nothing chemical happens; the gain is purely structural.' },
      { id: 'c', text: 'Each ply is twisted tighter, and more twist always means more strength', why: 'Past roughly 30° of surface twist, more twist makes cord weaker.' },
      { id: 'd', text: 'Plying straightens the fibers so they lie parallel to the cord’s axis', why: 'Plied fibers still run as helices; it is the locked-in twist that grips them.' },
    ],
    answer: 'a',
    concepts: ['reverse-wrap', 'cordage-twist'],
    explanation: 'A single strand unwinds under load and loses the squeeze that makes fibers grip. Plying balances the torque and locks the twist in.',
  },
  {
    id: 's7-rev-8',
    kind: 'single',
    prompt: 'You make charcoal from wood at 35 % moisture instead of dry wood. What happens, and why?',
    choices: [
      { id: 'a', text: 'Higher yield, because the water turns into extra charcoal', why: 'Water contains no carbon.' },
      { id: 'b', text: 'Lower yield: extra wood burns to supply ~2.4 MJ per kg of water', why: 'Correct: the Stage 3 moisture penalty applies to charcoal too.' },
      { id: 'c', text: 'No difference, because the sealed tin keeps the water inside', why: 'The water still has to be evaporated with heat.' },
      { id: 'd', text: 'Better charcoal, because the steam activates the carbon inside', why: 'Activation needs far more controlled conditions.' },
    ],
    answer: 'b',
    concepts: ['charcoal', 'moisture-content'],
    explanation: 'About 2.4 MJ per kg of water must be supplied by burning more of the wood, so yield drops and the burn is slower. Dry fuel matters for every fire process: warmth, cooking and charcoal alike.',
  },
  {
    id: 's7-rev-9',
    kind: 'single',
    prompt: 'Which bushcraft activity does **not** need a legal fire site and a check for fire bans?',
    choices: [
      { id: 'a', text: 'Heating stones for stone boiling', why: 'It does: it is a fire.' },
      { id: 'b', text: 'Running a charcoal retort', why: 'It does: the retort sits in a fire.' },
      { id: 'c', text: 'Warming pitch glue to haft a blade', why: 'It does: and keep the glue beside, not over, the flame.' },
      { id: 'd', text: 'Making cordage from dead nettle stalks', why: 'Correct: no fire is involved, though harvesting still needs permission.' },
    ],
    answer: 'd',
    concepts: ['fire-law', 'harvest-law'],
    explanation: 'Fire law covers every open flame, including craft fires. Harvest law covers the materials.',
  },
  {
    id: 's7-rev-10',
    kind: 'single',
    prompt: 'Which priority order fits an evening camp in cold drizzle?',
    choices: [
      { id: 'a', text: 'Fire → tarp and dry layers → treat water → carve a pot hook', why: 'Shelter and dry insulation stop the heat loss first; fire comes next.' },
      { id: 'b', text: 'Tarp and dry layers → fire → treat water → carve a pot hook', why: 'Correct: stop heat loss, add heat, then use the fire to help treat water.' },
      { id: 'c', text: 'Tarp and dry layers → treat water → fire → carve a pot hook', why: 'In cold and wet conditions fire comes before water, and it helps you treat it.' },
      { id: 'd', text: 'Treat water → tarp and dry layers → fire → carve a pot hook', why: 'Water moves up in hot desert conditions; here heat loss is the faster threat.' },
    ],
    answer: 'b',
    concepts: ['priorities', 'heat-balance'],
    explanation: 'In cold and wet conditions, heat loss is the fastest threat. Fire adds heat and helps you treat water. Craft projects come last. In hot desert conditions, water would move up.',
  },
]
