import type { Question } from '../../types'

// Stage 7 review: interleaves bushcraft engineering with earlier-stage concepts
// (fire structure, heat balance, priorities, kit redundancy, water treatment, wind loading).
export const stage7Review: Question[] = [
  {
    id: 's7-rev-1',
    kind: 'single',
    prompt: 'Damp boreal forest, 4 °C, 16:00, dark at 17:30. You are wet from a fall and alone, with a tarp, 10 m of cord, a knife and a lighter. A patch of dead fireweed promises good cordage fiber. What comes first?',
    choices: [
      { id: 'a', text: 'Process fireweed into cord while there is light: cord is always useful.', why: 'Sitting still and wet at 4 °C loses heat fast; cord-making is slow and low priority now.' },
      { id: 'b', text: 'Pitch the tarp with the cord you carry, change into dry layers, insulate from the ground, then prepare fire fuel.', why: 'Best: stop the heat loss first, then add heat. Cordage can wait for tomorrow.' },
      { id: 'c', text: 'Walk briskly to stay warm until dark.', why: 'Sweat in wet clothes at dusk worsens the heat balance and the night.' },
      { id: 'd', text: 'Build a charcoal retort for a smokeless fire.', why: 'Hours of work for a fuel you do not need.' },
    ],
    answer: 'b',
    concepts: ['priorities', 'heat-balance', 'natural-fibers'],
    explanation: 'Bushcraft projects never outrank shelter and warmth. Use carried kit first; improvise second.',
  },
  {
    id: 's7-rev-2',
    kind: 'multi',
    prompt: 'Which Stage 1 kit principles does this stage support?',
    choices: [
      { id: 'a', text: 'Carry more cord than you expect to need: making it costs ~15 min per metre or more', why: 'Yes: carried cord is cheap redundancy.' },
      { id: 'b', text: 'Carry two different fire-lighting methods; char cloth from a retort extends a flint-and-steel or ferro rod kit', why: 'Yes: diverse redundancy for a critical function.' },
      { id: 'c', text: 'A fixed-blade knife in the kit makes batoning safe, where a folder would fail', why: 'Yes: the right tool for the job removes a hazard.' },
      { id: 'd', text: 'Once you can make cordage, you no longer need to carry any', why: 'No: improvised cordage is slow, weaker and uneven.' },
    ],
    answer: ['a', 'b', 'c'],
    concepts: ['kit', 'redundancy', 'cordage-strength'],
    explanation: 'Skills are backup for kit, not a replacement for it.',
  },
  {
    id: 's7-rev-3',
    kind: 'numeric',
    prompt: 'A food bag weighs 60 N. You haul it over a branch with half a wrap (θ = π), μ = 0.3. What pull (N) is needed to **raise** it slowly? (Nearest newton.)',
    unit: 'N',
    answer: 154,
    tolerance: 4,
    concepts: ['capstan-friction'],
    explanation: 'T = 60 × e^(0.3π) = 60 × 2.57 ≈ **154 N**. The hauling side carries 2.6× the load, so size your cord for that, not for the bag.',
  },
  {
    id: 's7-rev-4',
    kind: 'single',
    prompt: 'You need dry kindling from wet, wrist-thick dead-standing wood. Which approach follows both Stage 3 fire structure and Stage 7 knife safety?',
    choices: [
      { id: 'a', text: 'Baton knot-free rounds with a full-tang knife on a block, then carve feather sticks and pencil-lead shavings from the dry core', why: 'Correct: dry core, high surface-to-volume, safe technique.' },
      { id: 'b', text: 'Put whole wet rounds on the tinder and wait', why: 'Too thick and too wet: they absorb heat faster than the flame can pyrolyse them.' },
      { id: 'c', text: 'Baton with a folding knife to save the good one', why: 'Folding knives fail when batoned.' },
      { id: 'd', text: 'Char the wet rounds first in someone else’s fire', why: 'Wastes time and heat.' },
    ],
    answer: 'a',
    concepts: ['fire-structure', 'batoning', 'surface-to-volume'],
    explanation: 'Splitting exposes the dry core; thin shavings climb the fuel ladder; safe batoning keeps you uninjured.',
  },
  {
    id: 's7-rev-5',
    kind: 'numeric',
    prompt: 'Stone boiling: how many **kg** of stones at 500 °C (c = 0.8 kJ/(kg·°C)) bring 3 L of water from 20 °C to 100 °C with η = 0.7? Water c = 4.18 kJ/(kg·°C). (One decimal.)',
    unit: 'kg',
    answer: 4.5,
    tolerance: 0.2,
    concepts: ['stone-boiling', 'water-treatment'],
    explanation: 'Water: 3 × 4.18 × 80 = 1,003 kJ. Stone: 0.8 × 400 × 0.7 = 224 kJ/kg. 1,003/224 ≈ **4.5 kg**. Then hold a rolling boil for 1 minute.',
  },
  {
    id: 's7-rev-6',
    kind: 'single',
    prompt: 'A 4 m ridgeline with 20 cm of sag carries 300 N in a steady wind. Gusts are forecast. Which change **most** reduces the risk of breaking hand-made cord?',
    choices: [
      { id: 'a', text: 'Tighten it to 10 cm of sag', why: 'Doubles the tension.' },
      { id: 'b', text: 'Lower the pitch, add guy lines, allow more sag, and take two turns round each tree before the knot', why: 'Correct: less force, lower tension, and the load moved onto friction before the knot.' },
      { id: 'c', text: 'Replace the figure-eight with a reef knot', why: 'Weaker, and it capsizes.' },
      { id: 'd', text: 'Wet the cord', why: 'Bast fiber gains a little strength wet, but this does not address the load.' },
    ],
    answer: 'b',
    concepts: ['wind-loading', 'capstan-friction', 'knot-efficiency'],
    explanation: 'Control the load first (area, sag, guys), then the weak point (friction before the knot).',
  },
  {
    id: 's7-rev-7',
    kind: 'truefalse',
    prompt: 'A reverse-wrapped two-ply cord is stronger than a single twisted strand of the same fiber, mainly because its balanced torque keeps the twist, and therefore the fiber friction, under load.',
    answer: true,
    concepts: ['reverse-wrap', 'cordage-twist'],
    explanation: 'A single strand unwinds under load and loses the squeeze that makes fibers grip. Plying locks the twist in.',
  },
  {
    id: 's7-rev-8',
    kind: 'single',
    prompt: 'You make charcoal from wood at 35 % moisture instead of dry wood. What happens, and why?',
    choices: [
      { id: 'a', text: 'Higher yield: water turns into charcoal', why: 'Water contains no carbon.' },
      { id: 'b', text: 'Lower yield and a slower burn: about 2.4 MJ per kg of water must be supplied by burning more of the wood', why: 'Correct: the Stage 3 moisture penalty applies to charcoal too.' },
      { id: 'c', text: 'No difference: the tin is sealed', why: 'The water still has to be evaporated with heat.' },
      { id: 'd', text: 'Better charcoal, because steam activates it', why: 'Activation needs far more controlled conditions.' },
    ],
    answer: 'b',
    concepts: ['charcoal', 'moisture-content'],
    explanation: 'Dry fuel matters for every fire process: warmth, cooking and charcoal alike.',
  },
  {
    id: 's7-rev-9',
    kind: 'multi',
    prompt: 'Which bushcraft activities need a **legal fire site** and a check for fire bans?',
    choices: [
      { id: 'a', text: 'Heating stones for stone boiling', why: 'Yes: it is a fire.' },
      { id: 'b', text: 'A charcoal retort', why: 'Yes.' },
      { id: 'c', text: 'Warming pitch glue', why: 'Yes: and keep it beside, not over, the flame.' },
      { id: 'd', text: 'Making cordage from dead nettle stalks', why: 'No fire involved, though harvesting still needs permission.' },
    ],
    answer: ['a', 'b', 'c'],
    concepts: ['fire-law', 'harvest-law'],
    explanation: 'Fire law covers every open flame, including craft fires. Harvest law covers the materials.',
  },
  {
    id: 's7-rev-10',
    kind: 'order',
    prompt: 'Order these actions for an evening camp in cold drizzle, by priority.',
    items: [
      { id: 'shelter', text: 'Pitch the tarp and change into dry insulation' },
      { id: 'water', text: 'Collect and treat water' },
      { id: 'fire', text: 'Build the fire from a prepared fuel ladder' },
      { id: 'craft', text: 'Carve a pot hook and spoon' },
    ],
    answer: ['shelter', 'fire', 'water', 'craft'],
    concepts: ['priorities', 'heat-balance'],
    explanation: 'In cold and wet conditions, heat loss is the fastest threat. Fire adds heat and helps you treat water. Craft projects come last. In hot desert conditions, water would move up.',
  },
]
