import type { Question } from '../../types'

// Stage 6 review: interleaved questions mixing food topics with earlier concepts (heat balance,
// water treatment, stay-or-move, reversibility, fire law, daylight, risk).
export const stage6Review: Question[] = [
  {
    id: 's6-rev-1',
    kind: 'single',
    prompt: 'Subarctic, −18 °C, snowmobile failure, rescue expected in 36 hours. You have a stove, fuel, 3,000 kcal of food for two people, and good clothing. Which plan best combines warmth, water and food?',
    choices: [
      { id: 'a', text: 'Eat snow for water and save all the food for the ride out.', why: 'Eating snow costs body heat, and unfed people shiver less effectively.' },
      { id: 'b', text: 'Melt snow on a vented stove, eat regular rations, more in the evening.', why: 'Best: water, warmth and fuel for shivering together, without carbon-monoxide risk — and stay insulated from the ground.' },
      { id: 'c', text: 'Keep walking around to stay warm instead of eating your food.', why: 'Burns glycogen and makes sweat that chills you later.' },
      { id: 'd', text: 'Fast for the first 24 hours to stretch the food over the wait.', why: 'Not helpful with water available; cold and hunger compound.' },
    ],
    answer: 'b',
    concepts: ['energy-stores', 'heat-balance', 'water-needs'],
    explanation: 'In cold, food is part of your heating system. Melt, don’t eat, snow; ventilate any stove use.',
  },
  {
    id: 's6-rev-3',
    kind: 'single',
    prompt: 'Desert, 42 °C, vehicle breakdown, 8 L of water for two people, rescue expected tomorrow. You have salty crackers, jerky and dried fruit. What about food?',
    choices: [
      { id: 'a', text: 'Eat the jerky first, since protein will keep your strength up.', why: 'Protein and salt increase water needs.' },
      { id: 'b', text: 'Eat little, mostly dried fruit; rest in shade; ration sweat, not water.', why: 'Correct — water before food; carbohydrate needs least extra water.' },
      { id: 'c', text: 'Walk to look for edible desert plants to save your own food.', why: 'Costs far more water than any plant could repay.' },
      { id: 'd', text: 'Eat nothing and drink nothing until rescue arrives tomorrow.', why: 'Rationing water in heat is dangerous.' },
    ],
    answer: 'b',
    concepts: ['water-before-food', 'dehydration'],
    explanation: 'In heat, water is the limiting resource. Eat lightly, avoid salty/protein-heavy food, reduce sweat.',
  },
  {
    id: 's6-rev-4',
    kind: 'single',
    prompt: 'Every control has gaps. Which method **does** reliably remove the hazard it is paired with?',
    choices: [
      { id: 'a', text: 'Boiling water — chemical pollutants', why: 'No (Stage 1): boiling does not remove chemicals.' },
      { id: 'b', text: 'Cooking shellfish — paralytic shellfish toxins', why: 'No: these toxins are heat-stable.' },
      { id: 'c', text: 'Freezing Arctic bear meat — Trichinella', why: 'No: freeze-resistant species occur in Arctic game.' },
      { id: 'd', text: 'Cooking chicken to 74 °C — Salmonella', why: 'Correct — proper cooking does kill Salmonella.' },
    ],
    answer: 'd',
    concepts: ['water-treatment', 'food-poisoning', 'parasites'],
    explanation: 'Every control has gaps. Know which hazards each one leaves behind — for water and for food.',
  },
  {
    id: 's6-rev-5',
    kind: 'single',
    prompt: 'Lost for 20 hours in a temperate forest with water, you find a plant you are “about 90 % sure” is edible. Which Stage 1 principle decides this?',
    choices: [
      { id: 'a', text: 'Rule of threes: food matters after three weeks, so it doesn’t matter either way.', why: 'Food timing is not the deciding issue; the downside is.' },
      { id: 'b', text: 'Reversibility: a poisoning is irreversible and the benefit is tiny — refuse.', why: 'Correct — irreversible, high-consequence actions need near-certainty.' },
      { id: 'c', text: 'Stay or move: eat it and then move.', why: 'Unrelated to the decision, and moving is rarely right here.' },
      { id: 'd', text: 'Redundancy: eat two different plants to spread the risk.', why: 'Doubles the chance of poisoning.' },
    ],
    answer: 'b',
    concepts: ['reversibility', 'plant-id-discipline', 'decisions'],
    explanation: 'A 10 % chance of a possibly fatal error for a few dozen kcal is a terrible trade.',
  },
  {
    id: 's6-rev-6',
    kind: 'single',
    prompt: 'You follow every step of the universal edibility test on a plant and wait the full time with no reaction. What does that tell you?',
    choices: [
      { id: 'a', text: 'The plant is safe to eat in normal amounts from now on.', why: 'The test cannot show that — some toxins are delayed or cumulative.' },
      { id: 'b', text: 'Little — delayed toxins and lethal small doses defeat the test.', why: 'Correct — and taste does not reveal toxicity either.' },
      { id: 'c', text: 'The plant is safe, provided you eat only the part you tested.', why: 'Passing the test does not make any part safe; delayed toxins can still strike.' },
      { id: 'd', text: 'The plant is safe for you, though not yet for the rest of your group.', why: 'It proves no one safe — the test itself is unreliable.' },
    ],
    answer: 'b',
    concepts: ['edibility-test-myth'],
    explanation: 'Small doses of some plants kill, some toxins are delayed or cumulative, and taste does not reveal toxicity.',
  },
  {
    id: 's6-rev-7',
    kind: 'single',
    prompt: 'You want to cook a legally caught fish on a campfire in a national forest in late summer. What must you check first?',
    choices: [
      { id: 'a', text: 'Only the fishing regulations, since the fish was caught legally.', why: 'Fire rules apply separately — and can change daily.' },
      { id: 'b', text: 'Current fire restrictions there, then cook the fish to 63 °C.', why: 'Correct — fires may be banned and stoves required; fire law (Stage 1) and food safety together.' },
      { id: 'c', text: 'Nothing, since small cooking fires are always allowed in forests.', why: 'Fire bans often include campfires and sometimes stoves.' },
      { id: 'd', text: 'Whether the fish is big enough to be worth the firewood.', why: 'Relevant, but it doesn’t make an illegal fire legal.' },
    ],
    answer: 'b',
    concepts: ['fire-safety', 'fishing-law', 'food-safety-temps'],
    explanation: 'Every food activity sits inside other rules: fire, land access, and wildlife law.',
  },
  {
    id: 's6-rev-9',
    kind: 'single',
    prompt: 'A group is stranded for an uncertain 3–6 days with water and shelter. Which order of food actions, by priority, is right?',
    choices: [
      { id: 'a', text: 'Inventory → daily ration with reserve → hygiene → low-cost legal food-getting', why: 'Correct — manage what you have, protect it from illness, then consider more.' },
      { id: 'b', text: 'Low-cost legal food-getting → inventory → daily ration with reserve → hygiene', why: 'Getting more food before knowing what you have puts effort in the wrong place.' },
      { id: 'c', text: 'Inventory → low-cost legal food-getting → daily ration with reserve → hygiene', why: 'Rationing what you have comes before trying to acquire more.' },
      { id: 'd', text: 'Daily ration with reserve → inventory → hygiene → low-cost legal food-getting', why: 'You cannot set a ration before counting the food.' },
    ],
    answer: 'a',
    concepts: ['rationing', 'food-poisoning', 'energy-return'],
    explanation: 'Inventory, then a daily ration with a reserve, then hand washing and safe handling, and only then low-cost legal food-getting (e.g., licensed fishing). Manage what you have before trying to get more; illness would cost more than any catch.',
  },
  {
    id: 's6-rev-10',
    kind: 'single',
    prompt: 'A companion ate foraged mushrooms 8 hours ago and now has vomiting and diarrhoea. You are 2 days’ walk from a road but have a satellite messenger. What now?',
    choices: [
      { id: 'a', text: 'Treat it as gastroenteritis and walk out tomorrow if it gets worse.', why: 'Delayed onset suggests amatoxin; walking 2 days loses the window for care.' },
      { id: 'b', text: 'SOS for evacuation now, report suspected amatoxin, keep remains, give fluids.', why: 'Correct — this is a time-critical emergency even if the patient improves.' },
      { id: 'c', text: 'Wait and watch: if they improve by tomorrow, the danger has passed.', why: 'The false-recovery phase is part of amatoxin poisoning.' },
      { id: 'd', text: 'Induce vomiting to clear the stomach, then continue the trip.', why: 'Too late to help and may cause harm.' },
    ],
    answer: 'b',
    concepts: ['amatoxins', 'signaling'],
    explanation: 'Late-onset GI symptoms after wild mushrooms = assume amatoxin; communication (Stage 1) is the decisive action.',
  },
  {
    id: 's6-rev-11',
    kind: 'single',
    prompt: 'Which statement about food-getting in a short emergency is **not** correct?',
    choices: [
      { id: 'a', text: 'Passive, legal methods can return more energy than they cost.', why: 'True.' },
      { id: 'b', text: 'Stalking game is usually energy-negative for an untrained person.', why: 'True.' },
      { id: 'c', text: 'Insect gathering in cold weather usually costs more than it returns.', why: 'True.' },
      { id: 'd', text: 'Leaving the shelter area to hunt improves your chance of rescue.', why: 'Correct — this is the false one: it moves you away from the search area and costs energy.' },
    ],
    answer: 'd',
    concepts: ['energy-return', 'stay-or-move'],
    explanation: 'Expected return minus cost, adjusted for risk and the effect on being found.',
  },
  {
    id: 's6-rev-12',
    kind: 'single',
    prompt: 'A storm knocks out power for 3 days. What is the best order for eating your household food?',
    choices: [
      { id: 'a', text: 'Pantry first, then the freezer, and the fridge contents last.', why: 'The fridge spoils first.' },
      { id: 'b', text: 'Fridge perishables first, then thawing freezer food, then pantry.', why: 'Correct — eat in order of how fast things spoil: fridge within ~4 h, freezer food while still ≤ 4 °C or icy.' },
      { id: 'c', text: 'Freezer first, because it holds the most valuable food.', why: 'A full, closed freezer stays safe longest.' },
      { id: 'd', text: 'Whatever still smells and looks fine, in any order you like.', why: 'Never use smell or taste to judge safety.' },
    ],
    answer: 'b',
    concepts: ['spoilage', 'food-storage'],
    explanation: 'Fridge ~4 h, full freezer ~48 h, pantry indefinitely. Keep doors shut and use a thermometer.',
  },
  {
    id: 's6-rev-2',
    kind: 'single',
    prompt: 'A 65 kg, 170 cm, 25-year-old woman does camp work in cool weather (PAL 1.55, environment factor 1.05). Estimate her daily expenditure (Mifflin–St Jeor).',
    choices: [
      { id: 'a', text: '≈ 2,211 kcal', why: 'That is BMR × 1.55 — the environment factor was left out.' },
      { id: 'b', text: '≈ 2,592 kcal', why: 'That uses the men’s constant (+5) instead of the women’s (−161).' },
      { id: 'c', text: '≈ 2,322 kcal', why: 'Correct — 1,426.5 × 1.55 × 1.05.' },
      { id: 'd', text: '≈ 3,709 kcal', why: 'That adds the factors (× 2.6) instead of multiplying them.' },
    ],
    answer: 'c',
    concepts: ['bmr', 'energy-needs'],
    explanation: 'BMR = 650 + 1,062.5 − 125 − 161 = 1,426.5 kcal. × 1.55 × 1.05 ≈ **2,322 kcal**.',
  },
  {
    id: 's6-rev-8',
    kind: 'single',
    prompt: 'You can fish for the 2 hours before dark. At 0.4 fish per hour, what is the chance you catch nothing?',
    choices: [
      { id: 'a', text: '≈ 64 %', why: 'That is 1 − 0.6² — the chance of catching at least one.' },
      { id: 'b', text: '≈ 16 %', why: 'That is 0.4² — it uses the catch chance instead of the miss chance.' },
      { id: 'c', text: '≈ 20 %', why: 'That subtracts 2 × 0.4 from 1; hourly chances multiply, they do not add.' },
      { id: 'd', text: '≈ 36 %', why: 'Correct — 0.6² = 0.36.' },
    ],
    answer: 'd',
    concepts: ['fishing-energy', 'daylight'],
    explanation: '0.6² = 0.36 → **36 %**. And stop early enough to get back to camp in daylight.',
  },
]
