import type { Question } from '../../types'

// Stage 6 review: interleaved questions mixing food topics with earlier concepts (heat balance,
// water treatment, stay-or-move, reversibility, fire law, daylight, risk).
export const stage6Review: Question[] = [
  {
    id: 's6-rev-1',
    kind: 'single',
    prompt: 'Subarctic, −18 °C, snowmobile failure, rescue expected in 36 hours. You have a stove, fuel, 3,000 kcal of food for two people, and good clothing. Which plan best combines warmth, water and food?',
    choices: [
      { id: 'a', text: 'Eat snow for water and save food for the ride out.', why: 'Eating snow costs body heat, and unfed people shiver less effectively.' },
      { id: 'b', text: 'Melt snow on the stove (ventilated), drink warm, eat modest regular rations with more in the evening, stay insulated from the ground.', why: 'Best: water, warmth and fuel for shivering together, without carbon-monoxide risk.' },
      { id: 'c', text: 'Walk around to stay warm instead of eating.', why: 'Burns glycogen and makes sweat that chills you later.' },
      { id: 'd', text: 'Fast for the first 24 hours to save food.', why: 'Not helpful with water available; cold and hunger compound.' },
    ],
    answer: 'b',
    concepts: ['energy-stores', 'heat-balance', 'water-needs'],
    explanation: 'In cold, food is part of your heating system. Melt, don’t eat, snow; ventilate any stove use.',
  },
  {
    id: 's6-rev-2',
    kind: 'numeric',
    prompt: 'A 65 kg, 170 cm, 25-year-old woman does camp work in cool weather (PAL 1.55, environment factor 1.05). Estimate her daily expenditure in kcal (Mifflin–St Jeor).',
    unit: 'kcal',
    answer: 2322,
    tolerance: 30,
    concepts: ['bmr', 'energy-needs'],
    explanation: 'BMR = 650 + 1,062.5 − 125 − 161 = 1,426.5 kcal. × 1.55 × 1.05 ≈ **2,322 kcal**.',
  },
  {
    id: 's6-rev-3',
    kind: 'single',
    prompt: 'Desert, 42 °C, vehicle breakdown, 8 L of water for two people, rescue expected tomorrow. You have salty crackers, jerky and dried fruit. What about food?',
    choices: [
      { id: 'a', text: 'Eat the jerky first — protein keeps you strong.', why: 'Protein and salt increase water needs.' },
      { id: 'b', text: 'Eat little, preferring dried fruit; rest in shade; ration sweat, not water.', why: 'Correct — water before food; carbohydrate needs least extra water.' },
      { id: 'c', text: 'Walk to look for edible desert plants.', why: 'Costs far more water than any plant could repay.' },
      { id: 'd', text: 'Eat nothing and drink nothing to conserve.', why: 'Rationing water in heat is dangerous.' },
    ],
    answer: 'b',
    concepts: ['water-before-food', 'dehydration'],
    explanation: 'In heat, water is the limiting resource. Eat lightly, avoid salty/protein-heavy food, reduce sweat.',
  },
  {
    id: 's6-rev-4',
    kind: 'multi',
    prompt: 'Which pairs of **method and hazard it does NOT fix** are correct?',
    choices: [
      { id: 'a', text: 'Boiling water — chemical pollutants', why: 'Correct (Stage 1): boiling does not remove chemicals.' },
      { id: 'b', text: 'Cooking shellfish — paralytic shellfish toxins', why: 'Correct: heat-stable.' },
      { id: 'c', text: 'Freezing Arctic bear meat — Trichinella', why: 'Correct: freeze-resistant species.' },
      { id: 'd', text: 'Cooking chicken to 74 °C — Salmonella', why: 'Incorrect — proper cooking does kill Salmonella.' },
    ],
    answer: ['a', 'b', 'c'],
    concepts: ['water-treatment', 'food-poisoning', 'parasites'],
    explanation: 'Every control has gaps. Know which hazards each one leaves behind — for water and for food.',
  },
  {
    id: 's6-rev-5',
    kind: 'single',
    prompt: 'Lost for 20 hours in a temperate forest with water, you find a plant you are “about 90 % sure” is edible. Which Stage 1 principle decides this?',
    choices: [
      { id: 'a', text: 'Rule of threes: food matters after three weeks, so it doesn’t matter either way.', why: 'Food timing is not the deciding issue; the downside is.' },
      { id: 'b', text: 'Reversibility: a poisoning is irreversible and the benefit is tiny — refuse.', why: 'Correct — irreversible, high-consequence actions need near-certainty.' },
      { id: 'c', text: 'Stay or move: eat it and then move.', why: 'Unrelated to the decision, and moving is rarely right here.' },
      { id: 'd', text: 'Redundancy: eat two different plants to spread the risk.', why: 'Doubles the chance of poisoning.' },
    ],
    answer: 'b',
    concepts: ['reversibility', 'plant-id-discipline', 'decisions'],
    explanation: 'A 10 % chance of a possibly fatal error for a few dozen kcal is a terrible trade.',
  },
  {
    id: 's6-rev-6',
    kind: 'truefalse',
    prompt: 'The universal edibility test is a reliable way to identify safe plants if you follow every step and wait the full time.',
    answer: false,
    concepts: ['edibility-test-myth'],
    explanation: 'Small doses of some plants kill, some toxins are delayed or cumulative, and taste does not reveal toxicity.',
  },
  {
    id: 's6-rev-7',
    kind: 'single',
    prompt: 'You want to cook a legally caught fish on a campfire in a national forest in late summer. What must you check first?',
    choices: [
      { id: 'a', text: 'Only the fishing regulations.', why: 'Fire rules apply separately — and can change daily.' },
      { id: 'b', text: 'Current fire restrictions for that forest (fires may be banned; stoves may be required), then cook the fish to 63 °C.', why: 'Correct — fire law (Stage 1) and food safety together.' },
      { id: 'c', text: 'Nothing: cooking fires are always allowed.', why: 'Fire bans often include campfires and sometimes stoves.' },
      { id: 'd', text: 'Whether the fish is big enough to be worth it.', why: 'Relevant, but it doesn’t make an illegal fire legal.' },
    ],
    answer: 'b',
    concepts: ['fire-safety', 'fishing-law', 'food-safety-temps'],
    explanation: 'Every food activity sits inside other rules: fire, land access, and wildlife law.',
  },
  {
    id: 's6-rev-8',
    kind: 'numeric',
    prompt: 'You can fish for the 2 hours before dark. At 0.4 fish per hour, what is the chance (in %) you catch nothing?',
    unit: '%',
    answer: 36,
    tolerance: 1,
    concepts: ['fishing-energy', 'daylight'],
    explanation: '0.6² = 0.36 → **36 %**. And stop early enough to get back to camp in daylight.',
  },
  {
    id: 's6-rev-9',
    kind: 'order',
    prompt: 'A group is stranded for an uncertain 3–6 days with water and shelter. Order these food actions by priority.',
    items: [
      { id: 'inventory', text: 'Inventory all food and its energy' },
      { id: 'ration', text: 'Set a daily ration with a reserve' },
      { id: 'hygiene', text: 'Set up hand washing and safe food handling' },
      { id: 'acquire', text: 'Consider low-cost, legal food-getting (e.g., licensed fishing)' },
    ],
    answer: ['inventory', 'ration', 'hygiene', 'acquire'],
    concepts: ['rationing', 'food-poisoning', 'energy-return'],
    explanation: 'Manage what you have before trying to get more; illness would cost more than any catch.',
  },
  {
    id: 's6-rev-10',
    kind: 'single',
    prompt: 'A companion ate foraged mushrooms 8 hours ago and now has vomiting and diarrhoea. You are 2 days’ walk from a road but have a satellite messenger. What now?',
    choices: [
      { id: 'a', text: 'Treat for gastroenteritis and walk out tomorrow if needed.', why: 'Delayed onset suggests amatoxin; walking 2 days loses the window for care.' },
      { id: 'b', text: 'Send an SOS for evacuation now, describe a suspected amatoxin ingestion, keep any mushroom remains, and manage fluids.', why: 'Correct — this is a time-critical emergency even if the patient improves.' },
      { id: 'c', text: 'Wait: if they improve tomorrow, the danger is over.', why: 'The false-recovery phase is part of amatoxin poisoning.' },
      { id: 'd', text: 'Induce vomiting and continue.', why: 'Too late to help and may cause harm.' },
    ],
    answer: 'b',
    concepts: ['amatoxins', 'signaling'],
    explanation: 'Late-onset GI symptoms after wild mushrooms = assume amatoxin; communication (Stage 1) is the decisive action.',
  },
  {
    id: 's6-rev-11',
    kind: 'multi',
    prompt: 'Which statements about food-getting in a short emergency are correct?',
    choices: [
      { id: 'a', text: 'Passive, legal methods can return more energy than they cost.', why: 'Correct.' },
      { id: 'b', text: 'Stalking game is usually energy-negative for an untrained person.', why: 'Correct.' },
      { id: 'c', text: 'Insect gathering in cold weather usually costs more than it returns.', why: 'Correct.' },
      { id: 'd', text: 'Leaving the shelter area to hunt improves your chance of rescue.', why: 'No — it moves you away from the search area and costs energy.' },
    ],
    answer: ['a', 'b', 'c'],
    concepts: ['energy-return', 'stay-or-move'],
    explanation: 'Expected return minus cost, adjusted for risk and the effect on being found.',
  },
  {
    id: 's6-rev-12',
    kind: 'single',
    prompt: 'A storm knocks out power for 3 days. What is the best order for eating your household food?',
    choices: [
      { id: 'a', text: 'Pantry first, then freezer, then fridge.', why: 'The fridge spoils first.' },
      { id: 'b', text: 'Fridge perishables first (within ~4 h), then freezer foods as they thaw (still ≤ 4 °C or with ice crystals), then pantry.', why: 'Correct — eat in order of how fast things spoil.' },
      { id: 'c', text: 'Freezer first because it is the most valuable.', why: 'A full, closed freezer stays safe longest.' },
      { id: 'd', text: 'Whatever smells fine.', why: 'Never use smell or taste to judge safety.' },
    ],
    answer: 'b',
    concepts: ['spoilage', 'food-storage'],
    explanation: 'Fridge ~4 h, full freezer ~48 h, pantry indefinitely. Keep doors shut and use a thermometer.',
  },
]
