import type { Question } from '../../types'

// Stage 14 review: interleaves signaling and search with earlier stages — daylight and trip plans,
// coordinates, heat balance, water, fire law, first aid and heuristic traps.
export const stage14Review: Question[] = [
  {
    id: 's14-rev-1',
    kind: 'single',
    prompt: 'You are sending a satellite-messenger SOS follow-up. Which location is most useful to rescuers?',
    choices: [
      { id: 'a', text: '“Near the lake, north side”', why: 'Useful as a description, but not enough on its own.' },
      { id: 'b', text: '“47.1234, 11.5678 (decimal degrees, WGS84) — north shore, below the red cliff”', why: 'Correct — coordinates with their format and datum, plus a landmark.' },
      { id: 'c', text: '“47 12 34, 11 56 78”', why: 'No format stated, and 78 is not a valid number of minutes or seconds — ambiguous and probably wrong.' },
      { id: 'd', text: '“About 3 hours from the car”', why: 'Rescuers cannot plot this.' },
    ],
    answer: 'b',
    concepts: ['coordinate-formats', 'distress-procedure'],
    explanation: 'Stage 2: always say the coordinate format (and datum where relevant). Add a landmark description as a cross-check.',
  },
  {
    id: 's14-rev-2',
    kind: 'multi',
    prompt: 'Day 2, stranded in hot desert with a vehicle and a satellite messenger. Which actions both extend your survival window and shorten the time to rescue?',
    choices: [
      { id: 'a', text: 'Resting in shade by the vehicle during the heat of the day', why: 'Yes — lowers sweat loss (Stage 8) and keeps you with the biggest visual target.' },
      { id: 'b', text: 'Sending position and status by messenger at agreed times', why: 'Yes — rescuers know where and how you are; scheduled checks save battery.' },
      { id: 'c', text: 'Walking to a road 30 km away at noon', why: 'No — large water cost in heat, and you leave the vehicle where rescuers will go.' },
      { id: 'd', text: 'Laying out a large dark V on pale ground near the vehicle', why: 'Yes — a static signal that works while you rest.' },
      { id: 'e', text: 'Rationing water severely while working hard in the sun', why: 'No — rationing does not reduce need; reduce sweat loss instead (Stage 4).' },
    ],
    answer: ['a', 'b', 'd'],
    concepts: ['rescue-timeline', 'water-budget', 'heat-balance', 'ground-air-signals'],
    explanation: 'The best actions work on both sides of the ledger: conserve water and heat, and make the rescue faster and more certain.',
  },
  {
    id: 's14-rev-3',
    kind: 'single',
    prompt: 'It is dry and windy in a pine forest with a posted fire ban. You hear an aircraft. Which signal do you use?',
    choices: [
      { id: 'a', text: 'A smoke fire of green boughs', why: 'A fire ban and dry wind: a wildfire risk to you, the searchers and the region (Stage 3).' },
      { id: 'b', text: 'Mirror sweeps toward the sound from the nearest open spot, then a bright tarp laid out and waved', why: 'Correct — long-range, safe and legal.' },
      { id: 'c', text: 'The whistle', why: 'Aircrews cannot hear it.' },
      { id: 'd', text: 'Nothing until the aircraft is overhead', why: 'It may never come overhead; signal early.' },
    ],
    answer: 'b',
    concepts: ['fire-law', 'wildfire-risk', 'signal-mirror'],
    explanation: 'A signal fire is never worth starting a wildfire. On a sunny day, the mirror outranges smoke anyway.',
  },
  {
    id: 's14-rev-4',
    kind: 'truefalse',
    prompt: 'A promptly reported accidental activation of a registered PLB is routine; an unreported one can launch a search.',
    answer: true,
    concepts: ['false-alerts', 'beacon-registration'],
    explanation: 'Switch it off and call the RCC or registry immediately. Registration lets them resolve it with a phone call.',
  },
  {
    id: 's14-rev-5',
    kind: 'numeric',
    prompt: 'Planners assign segment D a POA of 20 %. A team searches it with coverage C = 1.5. What is the POS of that search, in %? Use POD = 1 − e^(−C). (Nearest whole number.)',
    unit: '%',
    answer: 16,
    tolerance: 1,
    concepts: ['poa-pod'],
    explanation: 'POD = 1 − e^(−1.5) ≈ 0.78; POS = 0.20 × 0.78 ≈ **16 %**.',
  },
  {
    id: 's14-rev-6',
    kind: 'single',
    prompt: 'Your group has a casualty with a suspected broken ankle, far from roads, with no signal. It is 13:00 in summer. There are four of you and a PLB. What is the best plan?',
    choices: [
      { id: 'a', text: 'Activate the PLB only if the casualty’s condition worsens; meanwhile splint, insulate and shelter, and send two people with a written note of location and condition to the nearest point with signal', why: 'Reasonable if a certain route to signal exists and the casualty is stable — but consider whether this is already grave danger.' },
      { id: 'b', text: 'Activate the PLB now if you cannot evacuate the casualty yourselves; then splint, insulate, shelter and signal, and keep the group together', why: 'Correct — a non-walking casualty far from roads is a situation you cannot self-rescue from; beacons exist for this. Stay together and manage the patient (Stage 9).' },
      { id: 'c', text: 'Send one person alone to run for help', why: 'Creates a second lone, possibly lost, person.' },
      { id: 'd', text: 'Carry the casualty out over rough ground together', why: 'Improvised carries over long distances exhaust groups and risk more injuries; call for help.' },
    ],
    answer: 'b',
    concepts: ['distress-beacons', 'stay-or-move', 'patient-assessment'],
    explanation: 'If you cannot self-evacuate and life or limb could be at risk while you wait, alert early. Keep the group together; take a hands-on WFA course to learn splinting and casualty care.',
  },
  {
    id: 's14-rev-7',
    kind: 'single',
    prompt: 'After two hours lost, you think “I’ve come this far, the road must be just over the next rise” and keep walking. Which heuristic trap from Stage 1 is this?',
    choices: [
      { id: 'a', text: 'Commitment / plan continuation', why: 'Correct — continuing because of effort already invested rather than current evidence.' },
      { id: 'b', text: 'Social proof', why: 'That is following what others do.' },
      { id: 'c', text: 'Scarcity', why: 'That is rushing for a scarce opportunity.' },
      { id: 'd', text: 'Expert halo', why: 'That is deferring to a perceived leader.' },
    ],
    answer: 'a',
    concepts: ['human-factors', 'stay-or-move'],
    explanation: 'Pre-set triggers are the antidote: they decide in advance what evidence makes you stop and stay.',
  },
  {
    id: 's14-rev-8',
    kind: 'order',
    prompt: 'You are lost in a forest late in the afternoon with a trip plan filed. Order your first actions.',
    items: [
      { id: 'stop', text: 'STOP: sit, breathe, think; check for immediate danger' },
      { id: 'decide', text: 'Decide to stay (someone will look); pick the nearest open spot' },
      { id: 'shelter', text: 'Shelter and ground insulation while there is daylight' },
      { id: 'signal', text: 'Static signals out; mirror, whistle and light ready' },
      { id: 'routine', text: 'Signal-and-listen routine; phone on a battery schedule' },
    ],
    answer: ['stop', 'decide', 'shelter', 'signal', 'routine'],
    concepts: ['stop', 'stay-or-move', 'daylight', 'signaling'],
    explanation: 'Stage 1’s first hour, with this stage’s signal routine: think, decide, protect, then make yourself findable.',
  },
  {
    id: 's14-rev-9',
    kind: 'single',
    prompt: 'You carry a licence-free walkie-talkie. Your partner is 6 km away on the other side of a ridge and you cannot reach them. What is most likely to help?',
    choices: [
      { id: 'a', text: 'Move to the ridge crest or another spot with line of sight to their area', why: 'Correct — VHF/UHF is line of sight; height beats power.' },
      { id: 'b', text: 'Hold the transmit button longer', why: 'It does not change range.' },
      { id: 'c', text: 'Switch to an aviation or marine channel', why: 'Illegal without a licence (outside genuine distress) and won’t fix terrain blocking.' },
      { id: 'd', text: 'Go down into the valley to get closer', why: 'Valleys are usually worse for line of sight.' },
    ],
    answer: 'a',
    concepts: ['radio-range', 'radio-licensing'],
    explanation: 'Radio horizon $d \\approx 4.1(\\sqrt{h_1}+\\sqrt{h_2})$ km; terrain blocks more than distance.',
  },
  {
    id: 's14-rev-10',
    kind: 'multi',
    prompt: 'A night search is under way for you. It is 2 °C and damp. Which actions help?',
    choices: [
      { id: 'a', text: 'Staying in your insulated shelter but keeping a light and whistle at hand', why: 'Yes — protects your heat balance and lets you respond.' },
      { id: 'b', text: 'Answering calls with three whistle blasts and pointing your light toward voices', why: 'Yes — a responsive subject has a wide sweep width.' },
      { id: 'c', text: 'Walking toward distant lights through the forest', why: 'No — falls, sweat and chilling, and you may walk away from their path.' },
      { id: 'd', text: 'Running your strobe continuously all night', why: 'No — flat batteries when searchers are close; signal when you hear them.' },
      { id: 'e', text: 'Keeping a bright item outside the shelter where the path passes', why: 'Yes — a static clue that points to you.' },
    ],
    answer: ['a', 'b', 'e'],
    concepts: ['responsive-subject', 'night-signals', 'heat-balance'],
    explanation: 'Stay warm (Stage 8), stay put, respond when searchers are near and leave static clues.',
  },
]
