import type { Question } from '../../types'

// Stage 14 review: interleaves signaling and search with earlier stages — daylight and trip plans,
// coordinates, heat balance, water, fire law, first aid and heuristic traps.
export const stage14Review: Question[] = [
  {
    id: 's14-rev-1',
    kind: 'single',
    prompt: 'You are sending a satellite-messenger SOS follow-up. Which location is most useful to rescuers?',
    choices: [
      { id: 'a', text: '“North side of the lake, below the red cliff”', why: 'Useful as a description, but not enough on its own.' },
      { id: 'b', text: '“47.1234, 11.5678 (decimal degrees, WGS84), below the red cliff”', why: 'Correct — coordinates with their format and datum, plus a landmark.' },
      { id: 'c', text: '“47 12 34, 11 56 78 — north shore of the lake”', why: 'No format stated, and 78 is not a valid number of minutes or seconds — ambiguous and probably wrong.' },
      { id: 'd', text: '“About 3 hours’ walk north of the car park”', why: 'Rescuers cannot plot this.' },
    ],
    answer: 'b',
    concepts: ['coordinate-formats', 'distress-procedure'],
    explanation: 'Stage 2: always say the coordinate format (and datum where relevant). Add a landmark description as a cross-check.',
  },
  {
    id: 's14-rev-2',
    kind: 'single',
    prompt: 'Day 2, stranded in hot desert with a vehicle and a satellite messenger. Which action both extends your survival window and shortens the time to rescue?',
    choices: [
      { id: 'a', text: 'Resting in shade by the vehicle during the heat of the day', why: 'Correct — lowers sweat loss (Stage 8) and keeps you with the biggest visual target.' },
      { id: 'b', text: 'Walking to a road 30 km away at noon to flag down help', why: 'Large water cost in heat, and you leave the vehicle where rescuers will go.' },
      { id: 'c', text: 'Rationing water severely while working hard in the sun', why: 'Rationing does not reduce need; reduce sweat loss instead (Stage 4).' },
      { id: 'd', text: 'Sending long status updates and photos every hour', why: 'Drains the battery of your only link; send short, factual updates at agreed times.' },
    ],
    answer: 'a',
    concepts: ['rescue-timeline', 'water-budget', 'heat-balance', 'ground-air-signals'],
    explanation: 'The best actions work on both sides of the ledger: conserve water and heat, and make the rescue faster and more certain — shade by the vehicle, scheduled position messages and a large dark V on pale ground.',
  },
  {
    id: 's14-rev-3',
    kind: 'single',
    prompt: 'It is dry and windy in a pine forest with a posted fire ban. You hear an aircraft. Which signal do you use?',
    choices: [
      { id: 'a', text: 'A small smoke fire of green boughs to show your position', why: 'A fire ban and dry wind: a wildfire risk to you, the searchers and the region (Stage 3).' },
      { id: 'b', text: 'Mirror sweeps toward the sound from open ground, then a bright tarp', why: 'Correct — long-range, safe and legal.' },
      { id: 'c', text: 'Long whistle blasts in groups of three toward the sound', why: 'Aircrews cannot hear a whistle over the engine.' },
      { id: 'd', text: 'Wait and save energy until the aircraft is right overhead', why: 'It may never come overhead; signal early.' },
    ],
    answer: 'b',
    concepts: ['fire-law', 'wildfire-risk', 'signal-mirror'],
    explanation: 'A signal fire is never worth starting a wildfire. On a sunny day, the mirror outranges smoke anyway; a bright tarp laid out and waved adds a static signal.',
  },
  {
    id: 's14-rev-4',
    kind: 'single',
    prompt: 'You accidentally activate your registered PLB. Which statement is correct?',
    choices: [
      { id: 'a', text: 'Once you switch it off, the alert is cancelled automatically', why: 'The alert may already have been received; you must call to cancel it.' },
      { id: 'b', text: 'Reported promptly it is routine; unreported, it can launch a search', why: 'Correct — registration lets the RCC resolve a reported accident with a phone call.' },
      { id: 'c', text: 'Because it is registered, the RCC will simply ignore the alert', why: 'Every alert is treated as real until it is resolved; registration only lets them check quickly.' },
      { id: 'd', text: 'Any accidental activation means a full search and a fine', why: 'Promptly reported accidental activations are routine and resolved by phone.' },
    ],
    answer: 'b',
    concepts: ['false-alerts', 'beacon-registration'],
    explanation: 'Switch it off and call the RCC or registry immediately. Registration lets them resolve it with a phone call.',
  },
  {
    id: 's14-rev-5',
    kind: 'single',
    prompt: 'Planners assign segment D a POA of 20 %. A team searches it with coverage C = 1.5. Using POD = 1 − e^(−C), what is the POS of that search?',
    choices: [
      { id: 'a', text: 'About 16 %', why: 'Correct — POD ≈ 0.78, and POS = 0.20 × 0.78 ≈ 16 %.' },
      { id: 'b', text: 'About 78 %', why: 'That is the POD; POS also multiplies by the POA of 20 %.' },
      { id: 'c', text: 'About 30 %', why: 'This takes the coverage C = 1.5 as the POD: 0.20 × 1.5.' },
      { id: 'd', text: 'About 4 %', why: 'This uses e^(−1.5) ≈ 0.22, the chance of missing, instead of 1 − e^(−1.5).' },
    ],
    answer: 'a',
    concepts: ['poa-pod'],
    explanation: 'POD = 1 − e^(−1.5) ≈ 0.78; POS = 0.20 × 0.78 ≈ **16 %**.',
  },
  {
    id: 's14-rev-6',
    kind: 'single',
    prompt: 'Your group has a casualty with a suspected broken ankle, far from roads, with no signal. It is 13:00 in summer. There are four of you and a PLB. What is the best plan?',
    choices: [
      { id: 'a', text: 'Activate the PLB only if the casualty’s condition worsens; meanwhile splint, insulate and shelter, and send two people with a written note of location and condition to the nearest point with signal', why: 'Reasonable if a certain route to signal exists and the casualty is stable — but consider whether this is already grave danger.' },
      { id: 'b', text: 'Activate the PLB now if you cannot evacuate the casualty yourselves; then splint, insulate, shelter and signal, and keep the group together', why: 'Correct — a non-walking casualty far from roads is a situation you cannot self-rescue from; beacons exist for this. Stay together and manage the patient (Stage 9).' },
      { id: 'c', text: 'Send one person alone to run for help', why: 'Creates a second lone, possibly lost, person.' },
      { id: 'd', text: 'Carry the casualty out over rough ground together', why: 'Improvised carries over long distances exhaust groups and risk more injuries; call for help.' },
    ],
    answer: 'b',
    concepts: ['distress-beacons', 'stay-or-move', 'patient-assessment'],
    explanation: 'If you cannot self-evacuate and life or limb could be at risk while you wait, alert early. Keep the group together; take a hands-on WFA course to learn splinting and casualty care.',
  },
  {
    id: 's14-rev-7',
    kind: 'single',
    prompt: 'After two hours lost, you think “I’ve come this far, the road must be just over the next rise” and keep walking. Which heuristic trap from Stage 1 is this?',
    choices: [
      { id: 'a', text: 'Commitment / plan continuation', why: 'Correct — continuing because of effort already invested rather than current evidence.' },
      { id: 'b', text: 'Social proof', why: 'That is following what others do.' },
      { id: 'c', text: 'Scarcity', why: 'That is rushing for a scarce opportunity.' },
      { id: 'd', text: 'Expert halo', why: 'That is deferring to a perceived leader.' },
    ],
    answer: 'a',
    concepts: ['human-factors', 'stay-or-move'],
    explanation: 'Pre-set triggers are the antidote: they decide in advance what evidence makes you stop and stay.',
  },
  {
    id: 's14-rev-8',
    kind: 'single',
    prompt: 'You are lost in a forest late in the afternoon with a trip plan filed. You have done STOP: sat, breathed, thought and checked for immediate danger. What comes next?',
    choices: [
      { id: 'a', text: 'Build shelter and ground insulation while there is daylight', why: 'Soon — but first decide to stay, so you know where to build.' },
      { id: 'b', text: 'Decide to stay, since someone will look, and pick the nearest open spot', why: 'Correct — the decision and the spot come before shelter and signals.' },
      { id: 'c', text: 'Put static signals out and get mirror, whistle and light ready', why: 'This follows shelter, once you know where you will spend the night.' },
      { id: 'd', text: 'Start a signal-and-listen routine and a phone battery schedule', why: 'This is the last step, once shelter and static signals are in place.' },
    ],
    answer: 'b',
    concepts: ['stop', 'stay-or-move', 'daylight', 'signaling'],
    explanation: 'Stage 1’s first hour, with this stage’s signal routine: STOP, decide to stay, shelter while there is daylight, static signals, then a signal-and-listen routine — think, decide, protect, then make yourself findable.',
  },
  {
    id: 's14-rev-9',
    kind: 'single',
    prompt: 'You carry a licence-free walkie-talkie. Your partner is 6 km away on the other side of a ridge and you cannot reach them. What is most likely to help?',
    choices: [
      { id: 'a', text: 'Climb to the ridge crest or any spot with line of sight to them', why: 'Correct — VHF/UHF is line of sight; height beats power.' },
      { id: 'b', text: 'Hold the transmit button longer and speak more slowly', why: 'It does not change range.' },
      { id: 'c', text: 'Switch to an aviation or marine channel for better reach', why: 'Illegal without a licence (outside genuine distress) and won’t fix terrain blocking.' },
      { id: 'd', text: 'Walk down into the valley so you are closer to them', why: 'Valleys are usually worse for line of sight.' },
    ],
    answer: 'a',
    concepts: ['radio-range', 'radio-licensing'],
    explanation: 'Radio horizon $d \\approx 4.1(\\sqrt{h_1}+\\sqrt{h_2})$ km; terrain blocks more than distance.',
  },
  {
    id: 's14-rev-10',
    kind: 'single',
    prompt: 'A night search is under way for you. It is 2 °C and damp. Which of these actions does NOT help?',
    choices: [
      { id: 'a', text: 'Staying in your insulated shelter with light and whistle at hand', why: 'This helps — it protects your heat balance and lets you respond.' },
      { id: 'b', text: 'Answering calls with three whistle blasts and your light', why: 'This helps — a responsive subject has a wide sweep width.' },
      { id: 'c', text: 'Running your strobe continuously all night', why: 'Correct — the batteries go flat before searchers are close; signal when you hear them.' },
      { id: 'd', text: 'Keeping a bright item outside the shelter by the path', why: 'This helps — a static clue that points to you.' },
    ],
    answer: 'c',
    concepts: ['responsive-subject', 'night-signals', 'heat-balance'],
    explanation: 'Stay warm (Stage 8), stay put, respond when searchers are near and leave static clues. Walking toward distant lights or draining your batteries early both work against you.',
  },
]
