import type { Question } from '../../types'

// Stage 12 review: interleaved hazard-recognition questions that also re-test Stage 1 ideas
// (risk, turnaround times, stay-or-move, heat balance, reversibility).
export const stage12Review: Question[] = [
  {
    id: 's12-rev-1',
    kind: 'single',
    prompt: 'Mountain day, 10:15. Cumulus are already towering and your barometer is steady. Your turnaround time was 13:00, set assuming "isolated afternoon storms". What is the best adjustment?',
    choices: [
      { id: 'a', text: 'Keep 13:00. Turnaround times must never change.', why: 'Turnaround times must not be pushed *later* under pressure. Moving them *earlier* on new evidence is exactly right.' },
      { id: 'b', text: 'Bring the turnaround forward so you are off exposed ground before the storms, and set "first thunder = descend".', why: 'Best: new observations update the plan in the safe direction.' },
      { id: 'c', text: 'Ignore the clouds because pressure is steady.', why: 'Convective storms often form without a big pressure change; the clouds are the signal.' },
      { id: 'd', text: 'Push to 14:00 since you are moving well.', why: 'That renegotiates the turnaround in the dangerous direction.' },
    ],
    answer: 'b',
    concepts: ['convection-storms', 'trip-plan', 'go-no-go'],
    explanation: 'A turnaround time is a ceiling, not a target. Evidence can bring it forward; pressure to continue must never push it back.',
  },
  {
    id: 's12-rev-2',
    kind: 'numeric',
    prompt: 'Thunder follows a flash by 21 s. How far away is it, in km? (Use 343 m/s, one decimal.)',
    unit: 'km',
    answer: 7.2,
    tolerance: 0.2,
    concepts: ['flash-to-bang'],
    explanation: '$21 \\times 343 = 7203$ m ≈ **7.2 km**. That is within striking range, so move now.',
  },
  {
    id: 's12-rev-3',
    kind: 'multi',
    prompt: 'You are wet, it is 4 °C, and a cold front has just passed, bringing a 40 km/h wind. Which actions best protect your **heat balance**?',
    choices: [
      { id: 'a', text: 'Put on a windproof shell over your layers now', why: 'Yes: it cuts convective and evaporative loss.' },
      { id: 'b', text: 'Get out of the wind behind terrain or in dense forest', why: 'Yes: wind chill falls quickly with lower wind speed.' },
      { id: 'c', text: 'Sit on a pack or pad rather than wet ground', why: 'Yes: it cuts conduction.' },
      { id: 'd', text: 'Take off wet layers and dry them in the wind while walking', why: 'No: that evaporates water off you in the wind and costs a lot of heat.' },
      { id: 'e', text: 'Eat and keep moving at a steady, non-sweating pace', why: 'Yes: it keeps heat production up without soaking layers in sweat.' },
    ],
    answer: ['a', 'b', 'c', 'e'],
    concepts: ['heat-balance', 'wet-wind', 'weather-fronts'],
    explanation: 'Behind a cold front the problem shifts from rain to wind and cold. Shield from wind, insulate from the ground, keep producing heat.',
  },
  {
    id: 's12-rev-4',
    kind: 'single',
    prompt: 'Day 2 lost in a desert canyon, with a working PLB already activated. Thunderstorms are building over the plateau upstream. Your current spot in the dry wash has shade and good visibility from the air. What should you do?',
    choices: [
      { id: 'a', text: 'Stay exactly where you are: stay-or-move says stay once rescue is alerted.', why: 'Staying is usually right, but not in the flash-flood path.' },
      { id: 'b', text: 'Move a short distance up onto a bench well above the high-water marks, still visible from the air, and lay out signals there.', why: 'Best: the "stay" decision is kept (rescue has your area), and the immediate hazard is removed.' },
      { id: 'c', text: 'Hike out down-canyon to find help.', why: 'Down the flood channel, away from your beacon position, in the heat.' },
      { id: 'd', text: 'Walk upstream toward the storm to find water.', why: 'Into the flash-flood source.' },
    ],
    answer: 'b',
    concepts: ['stay-or-move', 'flash-flood', 'immediate-danger'],
    explanation: '"Stay" means staying near your reported location, not staying in a hazard. Move the minimum needed to get out of danger, and stay visible.',
  },
  {
    id: 's12-rev-5',
    kind: 'order',
    prompt: 'Rank these crossing options from **most** to **least** preferred for a fast, thigh-deep, milky glacial river at 15:00.',
    items: [
      { id: 'wait', text: 'Camp on high ground and reassess at dawn' },
      { id: 'bridge', text: 'Detour 3 h to a bridge' },
      { id: 'braid', text: 'Scout for a wide, braided section and cross there if it is clearly shallower and slower' },
      { id: 'now', text: 'Cross here now, linked together' },
    ],
    answer: ['wait', 'bridge', 'braid', 'now'],
    concepts: ['water-crossing', 'reversibility'],
    explanation: 'Glacial rivers drop overnight. Waiting and detours are reversible and low-risk. A braided section is only an option if it clearly changes the physics. Crossing fast, thigh-deep meltwater is a no-go.',
  },
  {
    id: 's12-rev-6',
    kind: 'single',
    prompt: 'A route crosses a 34° snow slope for 200 m. The forecast is Moderate, with a wind-slab problem on this aspect. You have no avalanche training. Using likelihood × consequence, how should you rate this?',
    choices: [
      { id: 'a', text: 'Low risk: the danger level is only 2.', why: 'Moderate still means human-triggered avalanches are possible on specific terrain, and this slope is that terrain.' },
      { id: 'b', text: 'Unacceptable for you: possible likelihood × catastrophic consequence, with no training or rescue gear. Choose another route.', why: 'Best: the consequence (burial, trauma) is catastrophic and you have no controls that reduce it.' },
      { id: 'c', text: 'Acceptable if you cross quickly.', why: 'Speed reduces exposure time, but it does not bring an untrained party with no rescue gear down to an acceptable level.' },
      { id: 'd', text: 'Acceptable if you cross one at a time.', why: 'A good practice for trained parties with rescue gear. Without gear it does not fix the consequence.' },
    ],
    answer: 'b',
    concepts: ['avalanche', 'risk'],
    explanation: 'Risk = likelihood × consequence (Stage 1). Avalanche consequences are severe, so even a modest likelihood is unacceptable without training, equipment and controls.',
  },
  {
    id: 's12-rev-7',
    kind: 'numeric',
    prompt: 'Your barometric altimeter read 850 m at 21:00 and 874 m at 06:00 while you slept in the same tent. About how many hPa did the pressure fall? (≈ 8 m per hPa)',
    unit: 'hPa',
    answer: 3,
    tolerance: 0.5,
    concepts: ['pressure-trends'],
    explanation: '24 m ÷ 8 m/hPa = **3 hPa**: a moderate fall, signalling a change. Check the sky and update the plan.',
  },
  {
    id: 's12-rev-8',
    kind: 'multi',
    prompt: 'Which are good **pre-committed triggers** (decided before the trip)?',
    choices: [
      { id: 'a', text: '"First thunder: we leave the ridge, no discussion."', why: 'Yes: observable and specific.' },
      { id: 'b', text: '"Gusts over 70 km/h forecast: we take the valley route."', why: 'Yes: numeric.' },
      { id: 'c', text: '"If it looks bad we will think about it."', why: 'No: vague triggers get renegotiated under pressure.' },
      { id: 'd', text: '"Any thunderstorm forecast over the catchment: no slot canyon."', why: 'Yes: specific and based on the catchment, not the local sky.' },
      { id: 'e', text: '"Red-flag warning: change area."', why: 'Yes.' },
    ],
    answer: ['a', 'b', 'd', 'e'],
    concepts: ['go-no-go', 'human-factors'],
    explanation: 'Triggers set by your calm self defeat the commitment and social traps (FACETS) that act on your stressed self.',
  },
  {
    id: 's12-rev-9',
    kind: 'single',
    prompt: 'Summer heatwave, desert hills. Heat index at 14:00: 41 °C in the shade; the trail is in full sun. A group member is flushed and has stopped sweating as much. What is the priority?',
    choices: [
      { id: 'a', text: 'Keep walking to finish before the evening.', why: 'Continuing work in extreme heat with warning signs risks exertional heat stroke.' },
      { id: 'b', text: 'Stop in the best shade, cool the person actively (wet clothing and fanning), give fluids if they are alert, and reassess. Treat any confusion as a medical emergency.', why: 'Best: reduce heat gain, increase loss, and watch for heat stroke (Stage 8 / WMS).' },
      { id: 'c', text: 'Give salt tablets and continue.', why: 'Does not address heat load.' },
      { id: 'd', text: 'Wait until the evening without cooling.', why: 'Passive waiting in 41 °C+ sun can be too slow.' },
    ],
    answer: 'b',
    concepts: ['heat-balance', 'wind-chill-heat-index', 'priorities'],
    explanation: 'Full sun can add up to ~8 °C to the heat index. Treat changes in sweating or mental state as warning signs; cooling is the priority. Take a WFA course.',
  },
  {
    id: 's12-rev-10',
    kind: 'truefalse',
    prompt: 'On a wildfire escape, the shortest route to the ridge top is usually the best choice because smoke and heat rise away from you.',
    answer: false,
    concepts: ['escape-routes', 'fire-behavior'],
    explanation: 'Fire runs uphill, fastest through chimneys and saddles. Escape across or down-slope to a safety zone.',
  },
]
