import type { Question } from '../../types'

// Stage 12 review: interleaved hazard-recognition questions that also re-test Stage 1 ideas
// (risk, turnaround times, stay-or-move, heat balance, reversibility).
export const stage12Review: Question[] = [
  {
    id: 's12-rev-1',
    kind: 'single',
    prompt: 'Mountain day, 10:15. Cumulus are already towering and your barometer is steady. Your turnaround time was 13:00, set assuming "isolated afternoon storms". What is the best adjustment?',
    choices: [
      { id: 'a', text: 'Keep 13:00, because a turnaround time must never be changed.', why: 'Turnaround times must not be pushed *later* under pressure. Moving them *earlier* on new evidence is exactly right.' },
      { id: 'b', text: 'Move the turnaround earlier and set "first thunder = descend".', why: 'Best: new observations update the plan in the safe direction, so you are off exposed ground before the storms.' },
      { id: 'c', text: 'Ignore the clouds, since the barometer has stayed steady.', why: 'Convective storms often form without a big pressure change; the clouds are the signal.' },
      { id: 'd', text: 'Push it to 14:00, since the group is moving well today.', why: 'That renegotiates the turnaround in the dangerous direction.' },
    ],
    answer: 'b',
    concepts: ['convection-storms', 'trip-plan', 'go-no-go'],
    explanation: 'A turnaround time is a ceiling, not a target. Evidence can bring it forward; pressure to continue must never push it back.',
  },
  {
    id: 's12-rev-4',
    kind: 'single',
    prompt: 'Day 2 lost in a desert canyon, with a working PLB already activated. Thunderstorms are building over the plateau upstream. Your current spot in the dry wash has shade and good visibility from the air. What should you do?',
    choices: [
      { id: 'a', text: 'Stay exactly where you are, since rescue has been alerted.', why: 'Staying is usually right, but not in the flash-flood path.' },
      { id: 'b', text: 'Move a short way up to a visible bench above the high-water marks.', why: 'Best: the "stay" decision is kept (rescue has your area), and the immediate hazard is removed. Lay out signals there.' },
      { id: 'c', text: 'Hike out down-canyon along the wash to find help yourself.', why: 'Down the flood channel, away from your beacon position, in the heat.' },
      { id: 'd', text: 'Walk upstream toward the storm to find a source of water.', why: 'Into the flash-flood source.' },
    ],
    answer: 'b',
    concepts: ['stay-or-move', 'flash-flood', 'immediate-danger'],
    explanation: '"Stay" means staying near your reported location, not staying in a hazard. Move the minimum needed to get out of danger, and stay visible from the air.',
  },
  {
    id: 's12-rev-6',
    kind: 'single',
    prompt: 'A route crosses a 34° snow slope for 200 m. The forecast is Moderate, with a wind-slab problem on this aspect. You have no avalanche training or rescue gear. Using likelihood × consequence, how should you rate this?',
    choices: [
      { id: 'a', text: 'Low risk, because the danger level is only 2 (Moderate).', why: 'Moderate still means human-triggered avalanches are possible on specific terrain, and this slope is that terrain.' },
      { id: 'b', text: 'Unacceptable for an untrained party: choose another route.', why: 'Best: possible likelihood × catastrophic consequence (burial, trauma), and you have no controls that reduce it.' },
      { id: 'c', text: 'Acceptable, provided you cross the slope quickly.', why: 'Speed reduces exposure time, but it does not bring an untrained party with no rescue gear down to an acceptable level.' },
      { id: 'd', text: 'Acceptable, provided you cross one at a time.', why: 'A good practice for trained parties with rescue gear. Without gear it does not fix the consequence.' },
    ],
    answer: 'b',
    concepts: ['avalanche', 'risk'],
    explanation: 'Risk = likelihood × consequence (Stage 1). Avalanche consequences are severe, so even a modest likelihood is unacceptable without training, equipment and controls.',
  },
  {
    id: 's12-rev-9',
    kind: 'single',
    prompt: 'Summer heatwave, desert hills. Heat index at 14:00: 41 °C in the shade; the trail is in full sun. A group member is flushed and has stopped sweating as much. What is the priority?',
    choices: [
      { id: 'a', text: 'Keep walking so you finish the route before the evening.', why: 'Continuing work in extreme heat with warning signs risks exertional heat stroke.' },
      { id: 'b', text: 'Stop in shade and actively cool them with wet clothing and fanning.', why: 'Best: reduce heat gain, increase loss, give fluids if they are alert, and watch for heat stroke (Stage 8 / WMS).' },
      { id: 'c', text: 'Give them salt tablets and keep going at a slower pace.', why: 'Does not address heat load.' },
      { id: 'd', text: 'Sit down where you are and wait for the cooler evening air.', why: 'Passive waiting in 41 °C+ sun can be too slow.' },
    ],
    answer: 'b',
    concepts: ['heat-balance', 'wind-chill-heat-index', 'priorities'],
    explanation: 'Full sun can add up to ~8 °C to the heat index. Treat changes in sweating or mental state as warning signs, and any confusion as a medical emergency; cooling is the priority. Take a WFA course.',
  },
  {
    id: 's12-rev-3',
    kind: 'single',
    prompt: 'You are wet, it is 4 °C, and a cold front has just passed, bringing a 40 km/h wind. Which of these actions would **hurt** your heat balance?',
    choices: [
      { id: 'a', text: 'Put a windproof shell on over your layers', why: 'Helps: it cuts convective and evaporative loss.' },
      { id: 'b', text: 'Get out of the wind behind terrain or trees', why: 'Helps: wind chill falls quickly with lower wind speed.' },
      { id: 'c', text: 'Sit on your pack rather than the wet ground', why: 'Helps: it cuts conduction.' },
      { id: 'd', text: 'Take off wet layers to dry them in the wind', why: 'Correct: that evaporates water off you in the wind and costs a lot of heat.' },
    ],
    answer: 'd',
    concepts: ['heat-balance', 'wet-wind', 'weather-fronts'],
    explanation: 'Behind a cold front the problem shifts from rain to wind and cold. Shield from wind, insulate from the ground, and keep producing heat by eating and moving at a steady, non-sweating pace.',
  },
  {
    id: 's12-rev-8',
    kind: 'single',
    prompt: 'Which of these is **not** a good pre-committed trigger (decided before the trip)?',
    choices: [
      { id: 'a', text: '"First thunder: we leave the ridge, no discussion."', why: 'Good: observable and specific.' },
      { id: 'b', text: '"Gusts over 70 km/h forecast: we take the valley route."', why: 'Good: numeric.' },
      { id: 'c', text: '"If it looks bad we will think about it."', why: 'Correct: vague triggers get renegotiated under pressure.' },
      { id: 'd', text: '"Any storm forecast over the catchment: no slot canyon."', why: 'Good: specific and based on the catchment, not the local sky.' },
    ],
    answer: 'c',
    concepts: ['go-no-go', 'human-factors'],
    explanation: 'Specific, observable triggers (thunder, gust limits, catchment storms, red-flag warnings) set by your calm self defeat the commitment and social traps (FACETS) that act on your stressed self.',
  },
  {
    id: 's12-rev-5',
    kind: 'single',
    prompt: 'A fast, thigh-deep, milky glacial river blocks your route at 15:00. Which option is **most** preferred?',
    choices: [
      { id: 'a', text: 'Camp on high ground and reassess at dawn', why: 'Correct: glacial rivers drop overnight, and waiting is reversible and low-risk.' },
      { id: 'b', text: 'Detour 3 hours to reach a bridge', why: 'A good, reversible option, but the overnight drop makes waiting even cheaper.' },
      { id: 'c', text: 'Cross at a wider braided section if clearly shallower', why: 'Only an option if it clearly changes the physics; it still means entering fast meltwater.' },
      { id: 'd', text: 'Cross here now, with the group linked together', why: 'Crossing fast, thigh-deep meltwater is a no-go, linked or not.' },
    ],
    answer: 'a',
    concepts: ['water-crossing', 'reversibility'],
    explanation: 'Preference order: wait, detour, braided section only if clearly shallower and slower, and never cross here now. Glacial rivers drop overnight, so waiting and detours are reversible and low-risk.',
  },
  {
    id: 's12-rev-10',
    kind: 'single',
    prompt: 'A wildfire is burning below you on the slope. Which escape route is usually the best choice?',
    choices: [
      { id: 'a', text: 'Across or down-slope to a safety zone', why: 'Correct: away from the uphill run of the fire.' },
      { id: 'b', text: 'The shortest route straight up to the ridge top', why: 'Fire runs uphill; heat and smoke rise toward you, not away.' },
      { id: 'c', text: 'Up the nearest gully to the saddle above', why: 'Chimneys and saddles are where fire runs fastest.' },
      { id: 'd', text: 'Uphill into the thick, unburned forest', why: 'Dense unburned fuel above the fire is the worst place to be.' },
    ],
    answer: 'a',
    concepts: ['escape-routes', 'fire-behavior'],
    explanation: 'Fire runs uphill, fastest through chimneys and saddles. Escape across or down-slope to a safety zone.',
  },
  {
    id: 's12-rev-2',
    kind: 'single',
    prompt: 'Thunder follows a flash by 21 s. Using 343 m/s, how far away is it?',
    choices: [
      { id: 'a', text: '7.2 km', why: 'Correct: 21 × 343 = 7203 m.' },
      { id: 'b', text: '4.2 km', why: 'This is 21 ÷ 5, the "5 seconds per mile" rule, which gives miles, not km.' },
      { id: 'c', text: '0.7 km', why: 'A unit slip: 7203 m is 7.2 km, not 0.72 km.' },
      { id: 'd', text: '72 km', why: 'A unit slip: 7203 m is 7.2 km, not 72 km.' },
    ],
    answer: 'a',
    concepts: ['flash-to-bang'],
    explanation: '$21 \\times 343 = 7203$ m ≈ **7.2 km**. That is within striking range, so move now.',
  },
  {
    id: 's12-rev-7',
    kind: 'single',
    prompt: 'Your barometric altimeter read 850 m at 21:00 and 874 m at 06:00 while you slept in the same tent. About how much did the pressure fall? (≈ 8 m per hPa)',
    choices: [
      { id: 'a', text: '3 hPa', why: 'Correct: 24 m ÷ 8 m/hPa = 3 hPa.' },
      { id: 'b', text: '24 hPa', why: 'This reads the 24 m altitude change directly as hPa.' },
      { id: 'c', text: '192 hPa', why: 'This multiplies by 8 instead of dividing.' },
      { id: 'd', text: '0.33 hPa', why: 'This inverts the ratio (8 ÷ 24).' },
    ],
    answer: 'a',
    concepts: ['pressure-trends'],
    explanation: '24 m ÷ 8 m/hPa = **3 hPa**: a moderate fall, signalling a change. Check the sky and update the plan.',
  },
]
