import type { Question } from '../../types'

// Stage 18 review: interleaves multi-day budgets, camp systems, maintenance, sleep, morale and planning
// with earlier stages — fire (3), water (4), shelter (5), food and energy (6), physiology (8), first aid (9),
// weather (12), signalling and stay-or-move (1, 14).
export const stage18Review: Question[] = [
  {
    id: 's18-rev-1',
    kind: 'numeric',
    prompt: 'Two people will wait an estimated 4 days and plan for a margin of 1.5× that. Each needs 3.5 L of drinking water a day. How many litres should the plan cover?',
    unit: 'L',
    answer: 42,
    tolerance: 0,
    concepts: ['water-budget', 's18-rolling-plan'],
    explanation: '$2 \\times 3.5 \\times (4 \\times 1.5) = 42$ L. In practice that is usually a stock plus a reliable, treated source — the ledger shows whether income covers it.',
  },
  {
    id: 's18-rev-2',
    kind: 'single',
    prompt: 'Winter camp, day 2. You have plenty of snow, 1 day of stove fuel and a large supply of dead wood. What is the best way to keep making water?',
    choices: [
      { id: 'a', text: 'Eat snow to save fuel', why: 'Eating snow costs body heat and can chill you; it also risks cold injury to the mouth.' },
      { id: 'b', text: 'Melt snow over the wood fire, starting with a little water in the pot, and keep the stove fuel as a reserve', why: 'Correct — wood is the plentiful fuel; the stove becomes the backup.' },
      { id: 'c', text: 'Use up the stove fuel first, then think about the fire', why: 'Spends the reserve first; if the fire plan fails you have nothing.' },
      { id: 'd', text: 'Drink less to make the fuel last', why: 'Ration fuel use, not drinking water.' },
    ],
    answer: 'b',
    concepts: ['snowmelt', 's18-resource-ledger', 'long-duration-fire'],
    explanation: 'Match each need to the most plentiful resource and keep the scarce one as a reserve. A little water in the pot stops the snow scorching.',
  },
  {
    id: 's18-rev-3',
    kind: 'multi',
    prompt: 'Which belong on the evening part of a multi-day routine in a cold forest?',
    choices: [
      { id: 'a', text: 'Tomorrow’s firewood under cover before dark', why: 'Yes.' },
      { id: 'b', text: 'An evening water batch into clean bottles', why: 'Yes.' },
      { id: 'c', text: 'Feet dried and inspected; dry socks for sleep', why: 'Yes — the daily round.' },
      { id: 'd', text: 'A long exploratory walk to look for a better site', why: 'No — exploration belongs in daylight mornings, fed and rested.' },
      { id: 'e', text: 'Update the ledger and plan tomorrow', why: 'Yes.' },
    ],
    answer: ['a', 'b', 'c', 'e'],
    concepts: ['s18-camp-routine', 's18-foot-care', 'daylight'],
    explanation: 'Evenings are for preparing the night and tomorrow; big moves and explorations are morning jobs.',
  },
  {
    id: 's18-rev-4',
    kind: 'single',
    prompt: 'Your latrine is 20 m from the stream you drink from, uphill of it. It rained heavily overnight. What is the most important change?',
    choices: [
      { id: 'a', text: 'Filter the water twice', why: 'Treatment helps, but the source is being contaminated; fix the cause.' },
      { id: 'b', text: 'Close and cover the latrine; dig new catholes downwind and at least 60 m from water, and collect water upstream', why: 'Correct — block the route at the source (F-diagram).' },
      { id: 'c', text: 'Move the water collection point downstream', why: 'Downstream of a latrine is worse.' },
      { id: 'd', text: 'Add sanitiser to the water', why: 'Hand sanitiser is not a water treatment.' },
    ],
    answer: 'b',
    concepts: ['s18-faecal-oral', 's18-camp-zones', 'water-treatment'],
    explanation: 'Rain carries faecal contamination downhill into water. Distance and position are the first barrier; treatment is the second.',
  },
  {
    id: 's18-rev-5',
    kind: 'truefalse',
    prompt: 'Oral rehydration (fluids plus salts) is the first treatment for diarrhoea in camp, and blood in the stool, high fever or inability to keep fluids down are reasons to evacuate.',
    answer: true,
    concepts: ['ors', 'emergency-sanitation', 'evacuation'],
    explanation: 'True (Stages 8 and 9). Replace fluid and salt; recognise the red flags; and take a hands-on wilderness first-aid course.',
  },
  {
    id: 's18-rev-6',
    kind: 'numeric',
    prompt: 'You carry two lighters in separate pockets. Each has an independent 5 % chance per day of being lost or failing. What is the chance that both have failed by the end of 7 days? Give a percentage to the nearest whole number.',
    unit: '%',
    answer: 9,
    tolerance: 1,
    concepts: ['redundancy', 's18-preventive-maintenance'],
    explanation: 'Each fails within a week with probability $1 - 0.95^7 \\approx 0.30$; both: $0.30^2 \\approx 0.09$, about 9 % — versus 30 % with one. Keep them apart so failures stay independent.',
  },
  {
    id: 's18-rev-7',
    kind: 'single',
    prompt: 'Day 3 in a tropical forest. Rain every afternoon; everyone is soaked. What gives the biggest benefit for the rest of the wait?',
    choices: [
      { id: 'a', text: 'A nightly foot routine, dry sleep clothes kept dry, a raised bed with a net, and heavy work in the mornings', why: 'Correct — prevents immersion foot, protects sleep and avoids afternoon heat strain.' },
      { id: 'b', text: 'Working through the afternoons to finish tasks faster', why: 'Afternoon heat and rain add strain and wet clothing.' },
      { id: 'c', text: 'Sleeping on the ground to save effort', why: 'Wet, insects and snakes; raise the bed.' },
      { id: 'd', text: 'Keeping boots on day and night so feet stay protected', why: 'Feet must dry nightly.' },
    ],
    answer: 'a',
    concepts: ['s18-foot-care', 's18-sleep-system', 'tropical-shelter', 's18-work-rest'],
    explanation: 'In the tropics, moisture, feet, heat timing and insects decide comfort and health over several days (Stage 5 and this stage).',
  },
  {
    id: 's18-rev-8',
    kind: 'order',
    prompt: 'A storm is forecast for tomorrow at your several-day camp. Order today’s jobs.',
    items: [
      { id: 'shelter', text: 'Re-tension and reinforce the shelter; clear hazards overhead' },
      { id: 'wood', text: 'Stock two nights of firewood under cover' },
      { id: 'water', text: 'Treat and store an extra day of water' },
      { id: 'signal', text: 'Secure signal markers so they survive the wind' },
      { id: 'plan', text: 'Evening: plan what you will do inside the shelter tomorrow' },
    ],
    answer: ['shelter', 'wood', 'water', 'signal', 'plan'],
    concepts: ['s18-rolling-plan', 'forecast-reading', 'shelter-failure'],
    explanation: 'Shelter first (a failure in the storm is the biggest threat), then the fuel and water you cannot collect tomorrow, then signals; then plan the storm day. Stage 12 taught how to read the signs; this is how you act on them.',
  },
  {
    id: 's18-rev-9',
    kind: 'single',
    prompt: 'On day 5, a search aircraft is expected tomorrow if the weather is clear. Your signal area is half-built; your firewood is fine; food is low but adequate. How do you spend today?',
    choices: [
      { id: 'a', text: 'Finish and test the signals: ground markers in the open, a signal fire laid with dry fuel and something to make smoke, mirror and whistle on your body', why: 'Correct — signals must be ready before the aircraft arrives (Stage 14).' },
      { id: 'b', text: 'Go fishing to top up food', why: 'Food is adequate; missing the aircraft costs days.' },
      { id: 'c', text: 'Rest all day to be fresh for tomorrow', why: 'Rest matters, but half-built signals may not be seen.' },
      { id: 'd', text: 'Walk to a ridge to wave at the aircraft', why: 'Leaves your camp and prepared signals; a single person is hard to see from the air.' },
    ],
    answer: 'a',
    concepts: ['signaling', 'visibility', 's18-rolling-plan'],
    explanation: 'A rolling plan puts rescue windows on the horizon so the work is done in time. The aircraft passes once; signals have to be ready.',
  },
  {
    id: 's18-rev-10',
    kind: 'multi',
    prompt: 'Which of these are myths?',
    choices: [
      { id: 'a', text: '“Ration your drinking water to make it last.”', why: 'Myth — ration sweat and effort; drink to need.' },
      { id: 'b', text: '“Trench foot only happens below freezing.”', why: 'Myth — long hours wet and cool are enough.' },
      { id: 'c', text: '“Hand sanitiser replaces soap even on dirty hands.”', why: 'Myth — it is a backup and works poorly on dirty hands.' },
      { id: 'd', text: '“Morale responds to routine, goals, food, warmth and company.”', why: 'Not a myth — this is how morale is managed.' },
      { id: 'e', text: '“In a short wait, food-getting usually costs more energy than it returns.”', why: 'Not a myth — Stage 6’s energy return.' },
    ],
    answer: ['a', 'b', 'c'],
    concepts: ['water-budget', 's18-foot-care', 's18-faecal-oral', 's18-morale', 'energy-return'],
    explanation: 'Three common myths; two sound principles.',
  },
]
