import type { Question } from '../../types'

// Stage 18 review: interleaves multi-day budgets, camp systems, maintenance, sleep, morale and planning
// with earlier stages — fire (3), water (4), shelter (5), food and energy (6), physiology (8), first aid (9),
// weather (12), signalling and stay-or-move (1, 14).
export const stage18Review: Question[] = [
  {
    id: 's18-rev-9',
    kind: 'single',
    prompt: 'On day 5, a search aircraft is expected tomorrow if the weather is clear. Your signal area is half-built; your firewood is fine; food is low but adequate. How do you spend today?',
    choices: [
      { id: 'a', text: 'Finish and test the signals: ground markers, a laid signal fire, mirror', why: 'Correct — signals must be ready before the aircraft arrives (Stage 14): markers in the open, a fire laid with dry fuel and something to make smoke, mirror and whistle on your body.' },
      { id: 'b', text: 'Go fishing to top up the food supply while the weather holds', why: 'Food is adequate; missing the aircraft costs days.' },
      { id: 'c', text: 'Rest all day so that you are fresh and alert for tomorrow', why: 'Rest matters, but half-built signals may not be seen.' },
      { id: 'd', text: 'Walk to a nearby ridge tomorrow and wave at the aircraft from there', why: 'Leaves your camp and prepared signals; a single person is hard to see from the air.' },
    ],
    answer: 'a',
    concepts: ['signaling', 'visibility', 's18-rolling-plan'],
    explanation: 'A rolling plan puts rescue windows on the horizon so the work is done in time. The aircraft passes once; signals have to be ready.',
  },
  {
    id: 's18-rev-4',
    kind: 'single',
    prompt: 'Your latrine is 20 m from the stream you drink from, uphill of it. It rained heavily overnight. What is the most important change?',
    choices: [
      { id: 'a', text: 'Keep the latrine but filter all drinking water twice from now on', why: 'Treatment helps, but the source is being contaminated; fix the cause.' },
      { id: 'b', text: 'Close it; dig new catholes 60 m+ from water; collect upstream', why: 'Correct — block the route at the source (F-diagram), with new catholes downwind as well as far from water.' },
      { id: 'c', text: 'Move the water collection point further downstream of camp', why: 'Downstream of a latrine is worse.' },
      { id: 'd', text: 'Add a few drops of hand sanitiser to each bottle of water', why: 'Hand sanitiser is not a water treatment.' },
    ],
    answer: 'b',
    concepts: ['fecal-oral-route', 's18-camp-zones', 'water-treatment'],
    explanation: 'Rain carries faecal contamination downhill into water. Distance and position are the first barrier; treatment is the second.',
  },
  {
    id: 's18-rev-2',
    kind: 'single',
    prompt: 'Winter camp, day 2. You have plenty of snow, 1 day of stove fuel and a large supply of dead wood. What is the best way to keep making water?',
    choices: [
      { id: 'a', text: 'Eat snow directly so that no fuel is spent on water at all', why: 'Eating snow costs body heat and can chill you; it also risks cold injury to the mouth.' },
      { id: 'b', text: 'Melt snow over the wood fire; keep stove fuel as a reserve', why: 'Correct — wood is the plentiful fuel; the stove becomes the backup. Start with a little water in the pot.' },
      { id: 'c', text: 'Use up the stove fuel first, then switch over to the wood fire', why: 'Spends the reserve first; if the fire plan fails you have nothing.' },
      { id: 'd', text: 'Drink less each day so that the stove fuel lasts longer', why: 'Ration fuel use, not drinking water.' },
    ],
    answer: 'b',
    concepts: ['snowmelt', 's18-resource-ledger', 'long-duration-fire'],
    explanation: 'Match each need to the most plentiful resource and keep the scarce one as a reserve. A little water in the pot stops the snow scorching.',
  },
  {
    id: 's18-rev-7',
    kind: 'single',
    prompt: 'Day 3 in a tropical forest. Rain every afternoon; everyone is soaked. What gives the biggest benefit for the rest of the wait?',
    choices: [
      { id: 'a', text: 'Nightly foot care, dry sleep clothes, a raised netted bed, morning work', why: 'Correct — prevents immersion foot, protects sleep and avoids afternoon heat strain.' },
      { id: 'b', text: 'Working through the afternoons to get the camp tasks done faster', why: 'Afternoon heat and rain add strain and wet clothing.' },
      { id: 'c', text: 'Sleeping on the ground under the tarp to save building effort', why: 'Wet, insects and snakes; raise the bed.' },
      { id: 'd', text: 'Keeping boots on day and night so that feet stay protected', why: 'Feet must dry nightly.' },
    ],
    answer: 'a',
    concepts: ['s18-foot-care', 's18-sleep-system', 'tropical-shelter', 's18-work-rest'],
    explanation: 'In the tropics, moisture, feet, heat timing and insects decide comfort and health over several days (Stage 5 and this stage).',
  },
  {
    id: 's18-rev-8',
    kind: 'single',
    prompt: 'A storm is forecast for tomorrow at your several-day camp. Today’s jobs: firewood, extra water, securing signal markers, reinforcing the shelter, and planning the storm day. Which job comes first?',
    choices: [
      { id: 'a', text: 'Stock two nights of firewood under cover', why: 'Fuel comes second — right after making sure the shelter will not fail.' },
      { id: 'b', text: 'Re-tension the shelter and clear overhead hazards', why: 'Correct: a shelter failure in the storm is the biggest threat.' },
      { id: 'c', text: 'Treat and store an extra day of drinking water', why: 'Water you cannot collect tomorrow matters, but it follows shelter and fuel.' },
      { id: 'd', text: 'Secure the signal markers against the wind', why: 'Signals come after shelter, fuel and water.' },
    ],
    answer: 'b',
    concepts: ['s18-rolling-plan', 'forecast-reading', 'shelter-failure'],
    explanation: 'Shelter first (a failure in the storm is the biggest threat), then the fuel and water you cannot collect tomorrow, then signals; then plan the storm day in the evening. Stage 12 taught how to read the signs; this is how you act on them.',
  },
  {
    id: 's18-rev-3',
    kind: 'single',
    prompt: 'Which of these does NOT belong in the evening part of a multi-day routine in a cold forest?',
    choices: [
      { id: 'a', text: 'Getting tomorrow’s firewood under cover before dark', why: 'This belongs — it prepares the night and the morning.' },
      { id: 'b', text: 'Drying and inspecting feet; putting on dry socks for sleep', why: 'This belongs — it is part of the daily round.' },
      { id: 'c', text: 'A long exploratory walk to look for a better camp site', why: 'Correct: exploration belongs in daylight mornings, fed and rested.' },
      { id: 'd', text: 'Updating the ledger and planning tomorrow’s work blocks', why: 'This belongs — the plan rolls forward every evening.' },
    ],
    answer: 'c',
    concepts: ['s18-camp-routine', 's18-foot-care', 'daylight'],
    explanation: 'Evenings are for preparing the night and tomorrow — wood, an evening water batch, feet, the ledger. Big moves and explorations are morning jobs.',
  },
  {
    id: 's18-rev-10',
    kind: 'single',
    prompt: 'Which of these statements is a myth?',
    choices: [
      { id: 'a', text: '“Trench foot only happens in temperatures below freezing.”', why: 'Correct — it is a myth: long hours wet and cool are enough.' },
      { id: 'b', text: '“Morale responds to routine, goals, food, warmth and company.”', why: 'Not a myth — this is how morale is managed.' },
      { id: 'c', text: '“In a short wait, food-getting usually costs more than it returns.”', why: 'Not a myth — Stage 6’s energy return.' },
      { id: 'd', text: '“Hand sanitiser is a backup and works poorly on dirty hands.”', why: 'Not a myth — soap and water come first.' },
    ],
    answer: 'a',
    concepts: ['water-budget', 's18-foot-care', 'fecal-oral-route', 's18-morale', 'energy-return'],
    explanation: 'Non-freezing cold injury needs only long hours wet and cool. Other common myths from this stage: rationing drinking water to make it last, and sanitiser replacing soap on dirty hands.',
  },
  {
    id: 's18-rev-5',
    kind: 'single',
    prompt: 'Someone in camp has diarrhoea. Which statement about managing it is correct?',
    choices: [
      { id: 'a', text: 'Oral rehydration comes first; blood, high fever or vomiting fluids mean evacuate', why: 'Correct (Stages 8 and 9): replace fluid and salt, and recognise the red flags.' },
      { id: 'b', text: 'Plain water is enough; salts only matter once the diarrhoea has stopped', why: 'Diarrhoea loses salt as well as water; oral rehydration replaces both.' },
      { id: 'c', text: 'Stop drinking for a day so that the gut can rest and settle down', why: 'Withholding fluid worsens dehydration; fluids plus salts are the first treatment.' },
      { id: 'd', text: 'Evacuation is only needed if it lasts more than a full week', why: 'Blood in the stool, high fever or inability to keep fluids down are reasons to evacuate now.' },
    ],
    answer: 'a',
    concepts: ['ors', 'emergency-sanitation', 'evacuation'],
    explanation: 'Oral rehydration (fluids plus salts) is the first treatment; blood in the stool, high fever or inability to keep fluids down are reasons to evacuate (Stages 8 and 9). Take a hands-on wilderness first-aid course.',
  },
  {
    id: 's18-rev-1',
    kind: 'single',
    prompt: 'Two people will wait an estimated 4 days and plan for a margin of 1.5× that. Each needs 3.5 L of drinking water a day. How many litres should the plan cover?',
    choices: [
      { id: 'a', text: '42 L', why: 'Correct: 2 × 3.5 × (4 × 1.5) = 42 L.' },
      { id: 'b', text: '28 L', why: 'This leaves out the 1.5× margin (2 × 3.5 × 4).' },
      { id: 'c', text: '21 L', why: 'This plans for only one person (3.5 × 6).' },
      { id: 'd', text: '14 L', why: 'This is one person with no margin (3.5 × 4).' },
    ],
    answer: 'a',
    concepts: ['water-budget', 's18-rolling-plan'],
    explanation: '$2 \\times 3.5 \\times (4 \\times 1.5) = 42$ L. In practice that is usually a stock plus a reliable, treated source — the ledger shows whether income covers it.',
  },
  {
    id: 's18-rev-6',
    kind: 'single',
    prompt: 'You carry two lighters in separate pockets. Each has an independent 5 % chance per day of being lost or failing. What is the chance that both have failed by the end of 7 days?',
    choices: [
      { id: 'a', text: 'About 9 %', why: 'Correct: each fails within a week with probability 1 − 0.95⁷ ≈ 0.30; both: 0.30² ≈ 0.09.' },
      { id: 'b', text: 'About 30 %', why: 'This is the chance for one lighter; it forgets the second, independent one.' },
      { id: 'c', text: 'About 49 %', why: 'This squares the chance each lighter survives (0.70²) — that is the chance both still work.' },
      { id: 'd', text: 'About 0.25 %', why: 'This is the chance both fail on a single day (0.05²); it ignores the seven days.' },
    ],
    answer: 'a',
    concepts: ['redundancy', 's18-preventive-maintenance'],
    explanation: 'Each fails within a week with probability $1 - 0.95^7 \\approx 0.30$; both: $0.30^2 \\approx 0.09$, about 9 % — versus 30 % with one. Keep them apart so failures stay independent.',
  },
]
