import type { Question } from '../../types'

// Stage 9 review: interleaved judgment questions mixing first aid with Stage 1 and Stage 8 ideas
// (priorities, immediate danger, heat balance, stay-or-move, daylight).
export const stage9Review: Question[] = [
  {
    id: 's9-rev-1',
    kind: 'order',
    prompt: 'A hiker has fallen into a stream bed below a waterfall; the water is rising after upstream rain. He is bleeding heavily from the thigh and is unresponsive. Order your actions.',
    items: [
      { id: 'scene', text: 'Size up; move him (with help) the minimum distance out of the rising water' },
      { id: 'bleed', text: 'Control the thigh bleeding (tourniquet)' },
      { id: 'airway', text: 'Open/protect the airway; check breathing' },
      { id: 'insulate', text: 'Insulate from ground and wet; call for help' },
      { id: 'secondary', text: 'Secondary survey and vitals' },
    ],
    answer: ['scene', 'bleed', 'airway', 'insulate', 'secondary'],
    concepts: ['immediate-danger', 'scene-safety', 'bleeding-control', 'abc'],
    explanation: 'Immediate danger first (Stage 1), then X-ABC, then protection and communication, then the full picture. With enough rescuers, bleeding and airway are handled at once.',
  },
  {
    id: 's9-rev-2',
    kind: 'single',
    prompt: 'Why does a patient lying still on cold, damp ground cool much faster than a person walking in the same weather?',
    choices: [
      { id: 'a', text: 'Because injured people have lower metabolic rates by definition.', why: 'Not by definition; the main change is loss of exercise heat plus ground contact.' },
      { id: 'b', text: 'Heat production falls from exercise to resting levels while conduction into the ground rises sharply — the heat balance goes negative.', why: 'Correct — Stage 1 heat balance: production down, losses up.' },
      { id: 'c', text: 'Because pain lowers body temperature.', why: 'Not a meaningful mechanism.' },
      { id: 'd', text: 'It doesn’t; lying down conserves heat.', why: 'Only if insulated from the ground.' },
    ],
    answer: 'b',
    concepts: ['heat-balance', 'heat-loss', 'hypothermia'],
    explanation: 'Walking can produce several hundred watts; resting ~100 W. Wet ground conducts heat away quickly. Insulate every patient from the ground.',
  },
  {
    id: 's9-rev-3',
    kind: 'multi',
    prompt: 'Which are current first-aid **myths**?',
    choices: [
      { id: 'a', text: 'A tourniquet is only a last resort.', why: 'Myth — it is an early tool for life-threatening limb bleeding.' },
      { id: 'b', text: 'Suck the venom out of a snakebite.', why: 'Myth.' },
      { id: 'c', text: 'Cool a burn with cool running water for about 20 minutes.', why: 'Correct practice, not a myth.' },
      { id: 'd', text: 'Rub frostbitten fingers with snow.', why: 'Myth — rubbing damages tissue.' },
      { id: 'e', text: 'Give epinephrine early in anaphylaxis.', why: 'Correct practice.' },
      { id: 'f', text: 'Alcohol warms a hypothermic person.', why: 'Myth — it increases heat loss.' },
    ],
    answer: ['a', 'b', 'd', 'f'],
    concepts: ['fa-myths', 'bleeding-control', 'envenomation', 'burns'],
    explanation: 'Each of these myths has caused real harm. Current practice: early tourniquets, no cutting/sucking, cool burns with water, thaw frostbite in warm water without rubbing, no alcohol.',
  },
  {
    id: 's9-rev-4',
    kind: 'single',
    prompt: 'Desert, 14:00, 42 °C. A group member is hot, sweaty, weak and dizzy but thinking clearly. Two hours later, after resting in shade, she is confused and says it is morning. What changed, and what now?',
    choices: [
      { id: 'a', text: 'Nothing important — confusion is common when tired. Carry on at dusk.', why: 'Confusion in heat is the defining sign of heat stroke.' },
      { id: 'b', text: 'Heat exhaustion has progressed to heat stroke: cool aggressively now (immersion if possible), then evacuate.', why: 'Correct — mental status is the dividing line.' },
      { id: 'c', text: 'She is dehydrated — give 2 L of water quickly.', why: 'Confused patients may choke; cooling is the treatment.' },
      { id: 'd', text: 'It is hyponatraemia — withhold all fluids and wait.', why: 'Possible look-alike, but a hot patient after hours of heat exposure must be cooled first; hyponatraemia is suspected with normal temperature and heavy water intake.' },
    ],
    answer: 'b',
    concepts: ['heat-illness', 'monitoring', 'heat-balance'],
    explanation: 'Reassessment caught the change. Cool first, transport second.',
  },
  {
    id: 's9-rev-5',
    kind: 'numeric',
    prompt: 'Using the adult rule of nines, what percentage of body surface is the whole back of the trunk plus the back half of both legs?',
    unit: '%',
    answer: 36,
    tolerance: 0,
    concepts: ['burns'],
    explanation: 'Back of trunk 18 % + half of each leg (9 % + 9 %) = **36 %**. A major burn: keep warm, evacuate emergently.',
  },
  {
    id: 's9-rev-6',
    kind: 'single',
    prompt: 'Subarctic, 15:30, sunset 16:10, −8 °C. Your partner has a stable wrist fracture (splinted, CSM normal) and can walk. The cabin is 3 km on a marked trail; you both have headlamps and warm clothing. Stay or move?',
    choices: [
      { id: 'a', text: 'Stay and bivouac here — never move a patient.', why: 'A walking patient with a stable, splinted wrist and a short, marked trail favours moving to better shelter.' },
      { id: 'b', text: 'Move now, steadily, to the cabin: short, marked route, walking patient, headlamps, warm — and reassess on the way.', why: 'Correct — the move is short, low-risk and reversible, and ends in far better shelter.' },
      { id: 'c', text: 'Call a helicopter.', why: 'Over-triage for a walkable, stable injury.' },
      { id: 'd', text: 'Wait until morning to decide.', why: 'A night out at −8 °C is a bigger risk than a 3 km marked walk now.' },
    ],
    answer: 'b',
    concepts: ['stay-or-move', 'evacuation', 'daylight'],
    explanation: 'The stay-or-move logic from Stage 1 applies to patients: the risk of moving (low here) vs the risk of staying (a cold night).',
  },
  {
    id: 's9-rev-7',
    kind: 'truefalse',
    prompt: 'A patient with a pulse of 96 who had a pulse of 72 thirty minutes ago, at rest, with pale moist skin after a fall, may be in compensated shock even though 96 is within the normal range.',
    answer: true,
    concepts: ['shock', 'monitoring', 'vital-signs'],
    explanation: 'Trends matter more than single values. A 24-beat rise at rest with skin changes suggests blood loss.',
  },
  {
    id: 's9-rev-8',
    kind: 'single',
    prompt: 'Tropical coast, 12:00. You find two people: one screaming with a painful, deformed ankle; one quiet, pale and sweaty, sitting against a rock after falling on it, holding his belly. Whom do you assess first?',
    choices: [
      { id: 'a', text: 'The screaming one — loud pain means serious injury.', why: 'Screaming shows an open airway and good breathing; loudness is not severity.' },
      { id: 'b', text: 'The quiet, pale, sweaty one — possible internal bleeding and shock.', why: 'Correct — the quiet patient is often the sicker one.' },
      { id: 'c', text: 'Whoever is closer.', why: 'Proximity is not a triage criterion.' },
      { id: 'd', text: 'Neither until you have fetched help.', why: 'A quick primary survey on both takes a minute and may save a life.' },
    ],
    answer: 'b',
    concepts: ['patient-assessment', 'shock', 'abdominal-injury', 'priorities'],
    explanation: 'Count patients in the size-up; the quiet one with shock signs gets the first primary survey.',
  },
  {
    id: 's9-rev-9',
    kind: 'multi',
    prompt: 'Which of these can you reasonably practise **at home**, and which need an instructor? Select the **home-practicable** ones.',
    choices: [
      { id: 'a', text: 'Counting pulse and breathing on a partner', why: 'Home-practicable.' },
      { id: 'b', text: 'Reducing a dislocated shoulder', why: 'Formal training only.' },
      { id: 'c', text: 'Splinting a partner’s forearm with a foam pad', why: 'Home-practicable.' },
      { id: 'd', text: 'Writing SOAP notes from case descriptions', why: 'Home-practicable.' },
      { id: 'e', text: 'Clearing a spine using a focused spine assessment', why: 'Formal training only.' },
      { id: 'f', text: 'Tourniquet application on a training aid', why: 'Home-practicable (a real limb needs an instructor).' },
    ],
    answer: ['a', 'c', 'd', 'f'],
    concepts: ['training-scope'],
    explanation: 'Frameworks, vitals, splinting, documentation and training-aid drills are home skills; reductions, spine clearance and real-limb tourniquets are course skills.',
  },
  {
    id: 's9-rev-10',
    kind: 'single',
    prompt: 'Mountain, 16:00, storm arriving. A companion has moderate hypothermia (drowsy, not shivering). You have a tent, sleeping bags, a stove and a satellite messenger. The hut is 2 km away. Best plan?',
    choices: [
      { id: 'a', text: 'Walk him briskly to the hut to warm him up.', why: 'Exertion and upright posture are dangerous in moderate hypothermia.' },
      { id: 'b', text: 'Pitch the tent, full hypothermia wrap with heat sources, keep him horizontal and still, send a message for evacuation, monitor.', why: 'Correct — stop heat loss where you are; moderate hypothermia needs evacuation, not a walk.' },
      { id: 'c', text: 'Give him hot sweet tea and wait to see.', why: 'A drowsy patient may choke; and waiting without a wrap lets him cool further.' },
      { id: 'd', text: 'Rub his limbs vigorously while the others fetch help from the hut.', why: 'Rubbing is a myth; it does not rewarm the core.' },
    ],
    answer: 'b',
    concepts: ['hypothermia', 'stay-or-move', 'evacuation', 'priorities'],
    explanation: 'Here staying is right: moving the patient is the high-risk option. Protection first, then communication.',
  },
]
