import type { Question } from '../../types'

// Stage 9 review: interleaved judgment questions mixing first aid with Stage 1 and Stage 8 ideas
// (priorities, immediate danger, heat balance, stay-or-move, daylight).
export const stage9Review: Question[] = [
  {
    id: 's9-rev-1',
    kind: 'single',
    prompt: 'A hiker has fallen into a stream bed below a waterfall; the water is rising after upstream rain. He is bleeding heavily from the thigh and is unresponsive. Which sequence of actions is correct?',
    choices: [
      { id: 'a', text: 'Move out of the water → tourniquet → airway → insulate and call → secondary survey', why: 'Correct — immediate danger first, then X-ABC, then protection and communication, then the full picture.' },
      { id: 'b', text: 'Tourniquet → airway → move out of the water → insulate and call → secondary survey', why: 'Rising water is the immediate danger; treating him where he lies risks losing both of you.' },
      { id: 'c', text: 'Move out of the water → airway → tourniquet → insulate and call → secondary survey', why: 'X before ABC: heavy bleeding from the thigh is controlled before the airway check.' },
      { id: 'd', text: 'Move out of the water → tourniquet → airway → secondary survey → insulate and call', why: 'Insulating and calling for help come before the detailed secondary survey.' },
    ],
    answer: 'a',
    concepts: ['immediate-danger', 'scene-safety', 'bleeding-control', 'abc'],
    explanation: 'Immediate danger first (Stage 1): size up and move him the minimum distance out of the rising water, then X-ABC, then protection and communication, then the full picture. With enough rescuers, bleeding and airway are handled at once.',
  },
  {
    id: 's9-rev-2',
    kind: 'single',
    prompt: 'Why does a patient lying still on cold, damp ground cool much faster than a person walking in the same weather?',
    choices: [
      { id: 'a', text: 'Injured people have a lower metabolic rate by definition, so they make less heat.', why: 'Not by definition; the main change is loss of exercise heat plus ground contact.' },
      { id: 'b', text: 'Heat production drops to resting levels while conduction into the ground rises.', why: 'Correct — Stage 1 heat balance: production down, losses up, so the balance goes negative.' },
      { id: 'c', text: 'Pain and stress lower the body’s core temperature directly, whatever the ground.', why: 'Not a meaningful mechanism.' },
      { id: 'd', text: 'It doesn’t: lying down curls the body up and conserves heat compared with walking.', why: 'Only if insulated from the ground.' },
    ],
    answer: 'b',
    concepts: ['heat-balance', 'heat-loss', 'hypothermia'],
    explanation: 'Walking can produce several hundred watts; resting ~100 W. Wet ground conducts heat away quickly. Insulate every patient from the ground.',
  },
  {
    id: 's9-rev-3',
    kind: 'single',
    prompt: 'Which of these is correct current first-aid practice rather than a **myth**?',
    choices: [
      { id: 'a', text: 'A tourniquet is only a last resort for limb bleeding.', why: 'Myth — it is an early tool for life-threatening limb bleeding.' },
      { id: 'b', text: 'Suck the venom out of a snakebite as soon as you can.', why: 'Myth — no cutting or sucking.' },
      { id: 'c', text: 'Cool a burn with cool running water for about 20 minutes.', why: 'Correct — this is current practice, not a myth.' },
      { id: 'd', text: 'Rub frostbitten fingers with snow to bring them back.', why: 'Myth — rubbing damages tissue.' },
    ],
    answer: 'c',
    concepts: ['fa-myths', 'bleeding-control', 'envenomation', 'burns'],
    explanation: 'Each of these myths has caused real harm. Current practice: early tourniquets, no cutting/sucking, cool burns with water, thaw frostbite in warm water without rubbing, no alcohol.',
  },
  {
    id: 's9-rev-4',
    kind: 'single',
    prompt: 'Desert, 14:00, 42 °C. A group member is hot, sweaty, weak and dizzy but thinking clearly. Two hours later, after resting in shade, she is confused and says it is morning. What changed, and what now?',
    choices: [
      { id: 'a', text: 'Nothing important: confusion is common when tired, so carry on at dusk.', why: 'Confusion in heat is the defining sign of heat stroke.' },
      { id: 'b', text: 'It has become heat stroke: cool her aggressively now, then evacuate.', why: 'Correct — mental status is the dividing line between heat exhaustion and heat stroke; immerse if possible.' },
      { id: 'c', text: 'She is dehydrated: give her 2 L of water quickly and keep resting in shade.', why: 'Confused patients may choke; cooling is the treatment.' },
      { id: 'd', text: 'It is hyponatraemia: withhold all fluids and wait for her to improve.', why: 'Possible look-alike, but a hot patient after hours of heat exposure must be cooled first; hyponatraemia is suspected with normal temperature and heavy water intake.' },
    ],
    answer: 'b',
    concepts: ['heat-illness', 'monitoring', 'heat-balance'],
    explanation: 'Reassessment caught the change from heat exhaustion to heat stroke. Cool first, transport second.',
  },
  {
    id: 's9-rev-5',
    kind: 'single',
    prompt: 'Using the adult rule of nines, what percentage of body surface is the whole back of the trunk plus the back half of both legs?',
    choices: [
      { id: 'a', text: '36 %', why: 'Correct — 18 % + 9 % + 9 %.' },
      { id: 'b', text: '54 %', why: 'This counts each whole leg (18 %) instead of its back half (9 %).' },
      { id: 'c', text: '27 %', why: 'This adds the back half of only one leg.' },
      { id: 'd', text: '72 %', why: 'This counts the whole trunk (36 %) and both whole legs (36 %), front and back.' },
    ],
    answer: 'a',
    concepts: ['burns'],
    explanation: 'Back of trunk 18 % + half of each leg (9 % + 9 %) = **36 %**. A major burn: keep warm, evacuate emergently.',
  },
  {
    id: 's9-rev-6',
    kind: 'single',
    prompt: 'Subarctic, 15:30, sunset 16:10, −8 °C. Your partner has a stable wrist fracture (splinted, CSM normal) and can walk. The cabin is 3 km on a marked trail; you both have headlamps and warm clothing. Stay or move?',
    choices: [
      { id: 'a', text: 'Stay and bivouac here, since you should never move an injured patient.', why: 'A walking patient with a stable, splinted wrist and a short, marked trail favours moving to better shelter.' },
      { id: 'b', text: 'Move now, steadily, to the cabin, and reassess her on the way.', why: 'Correct — short, marked route, walking patient, headlamps, warm: the move is low-risk and reversible, and ends in far better shelter.' },
      { id: 'c', text: 'Call for a helicopter to fly her out before the light goes.', why: 'Over-triage for a walkable, stable injury.' },
      { id: 'd', text: 'Make a quick shelter here and wait until morning to decide.', why: 'A night out at −8 °C is a bigger risk than a 3 km marked walk now.' },
    ],
    answer: 'b',
    concepts: ['stay-or-move', 'evacuation', 'daylight'],
    explanation: 'The stay-or-move logic from Stage 1 applies to patients: the risk of moving (low here) vs the risk of staying (a cold night).',
  },
  {
    id: 's9-rev-7',
    kind: 'single',
    prompt: 'After a fall, a resting patient’s pulse has gone from 72 to 96 in thirty minutes, and her skin is pale and moist. Which interpretation is correct?',
    choices: [
      { id: 'a', text: 'Possible compensated shock: the rise at rest with skin changes is the warning.', why: 'Correct — trends matter more than single values.' },
      { id: 'b', text: 'No concern yet, because a pulse of 96 is still within the normal range.', why: 'A single value can be normal while the trend is not; a 24-beat rise at rest is a warning.' },
      { id: 'c', text: 'Shock can be ruled out until her blood pressure actually starts to fall.', why: 'Falling blood pressure is a late sign; shock starts long before it.' },
      { id: 'd', text: 'It is just pain and anxiety, so recheck her vitals tomorrow morning.', why: 'Pale moist skin and a rising pulse at rest point to blood loss; recheck every 5–15 minutes.' },
    ],
    answer: 'a',
    concepts: ['shock', 'monitoring', 'vital-signs'],
    explanation: 'Trends matter more than single values. A 24-beat rise at rest with skin changes suggests blood loss, even though 96 is within the normal range.',
  },
  {
    id: 's9-rev-8',
    kind: 'single',
    prompt: 'Tropical coast, 12:00. You find two people: one screaming with a painful, deformed ankle; one quiet, pale and sweaty, sitting against a rock after falling on it, holding his belly. Whom do you assess first?',
    choices: [
      { id: 'a', text: 'The screaming one — loud pain means a serious injury.', why: 'Screaming shows an open airway and good breathing; loudness is not severity.' },
      { id: 'b', text: 'The quiet, pale, sweaty one — possible internal bleeding.', why: 'Correct — the quiet patient is often the sicker one, and these are shock signs.' },
      { id: 'c', text: 'Whoever is closer, so no time is lost moving between them.', why: 'Proximity is not a triage criterion.' },
      { id: 'd', text: 'Neither of them until you have gone and fetched help.', why: 'A quick primary survey on both takes a minute and may save a life.' },
    ],
    answer: 'b',
    concepts: ['patient-assessment', 'shock', 'abdominal-injury', 'priorities'],
    explanation: 'Count patients in the size-up; the quiet one with shock signs gets the first primary survey.',
  },
  {
    id: 's9-rev-9',
    kind: 'single',
    prompt: 'Which of these first-aid skills needs an **instructor** rather than practice at home?',
    choices: [
      { id: 'a', text: 'Counting pulse and breathing on a partner', why: 'Home-practicable.' },
      { id: 'b', text: 'Reducing a dislocated shoulder', why: 'Correct — formal training only.' },
      { id: 'c', text: 'Splinting a partner’s forearm with a foam pad', why: 'Home-practicable.' },
      { id: 'd', text: 'Applying a tourniquet on a training aid', why: 'Home-practicable (a real limb needs an instructor).' },
    ],
    answer: 'b',
    concepts: ['training-scope'],
    explanation: 'Frameworks, vitals, splinting, documentation and training-aid drills are home skills; reductions, spine clearance and real-limb tourniquets are course skills.',
  },
  {
    id: 's9-rev-10',
    kind: 'single',
    prompt: 'Mountain, 16:00, storm arriving. A companion has moderate hypothermia (drowsy, not shivering). You have a tent, sleeping bags, a stove and a satellite messenger. The hut is 2 km away. Best plan?',
    choices: [
      { id: 'a', text: 'Walk him briskly to the hut 2 km away so the exercise warms him up.', why: 'Exertion and upright posture are dangerous in moderate hypothermia.' },
      { id: 'b', text: 'Pitch the tent, wrap him with heat sources, keep him flat, and message for evacuation.', why: 'Correct — stop heat loss where you are, keep him horizontal and still, and monitor; moderate hypothermia needs evacuation, not a walk.' },
      { id: 'c', text: 'Give him hot sweet tea in the tent and wait to see whether he improves.', why: 'A drowsy patient may choke; and waiting without a wrap lets him cool further.' },
      { id: 'd', text: 'Rub his limbs vigorously while the others go to fetch help from the hut.', why: 'Rubbing is a myth; it does not rewarm the core.' },
    ],
    answer: 'b',
    concepts: ['hypothermia', 'stay-or-move', 'evacuation', 'priorities'],
    explanation: 'Here staying is right: moving the patient is the high-risk option. Protection first, then communication.',
  },
]
