import type { Lesson } from '../../types'

export const l03: Lesson = {
  id: 's2-l3',
  stage: 2,
  order: 3,
  title: 'The compass',
  level: 'beginner',
  minutes: 45,
  prerequisites: ['s2-l1'],
  concepts: ['compass', 'declination'],
  objectives: [
    'Name the parts of a **baseplate compass** and what each one does.',
    'Explain the difference between **true, grid and magnetic north**.',
    'Find the current **declination** for a place and update an old map value.',
    'Convert bearings **grid ↔ magnetic** correctly for both **east and west** declination.',
    'Recognise and avoid **deviation** from metal, phones and magnets, and check a compass for reversed polarity.',
  ],
  explanation: [
    {
      type: 'md',
      md: `A compass does one thing: its magnetised needle lines up with the **horizontal part of Earth’s magnetic field** where you stand. Everything else on a baseplate (orienteering) compass is a protractor built around that needle so you can transfer directions between map and ground without calculation.

### Anatomy of a baseplate compass`,
    },
    { type: 'diagram', id: 'compass-anatomy', caption: 'A baseplate compass: baseplate, direction-of-travel arrow, rotating housing with bezel, orienting arrow and lines, needle, index line, romer scales.' },
    {
      type: 'table',
      head: ['Part', 'What it is', 'What it is for'],
      rows: [
        ['**Baseplate**', 'Clear rectangular plate with straight edges', 'Laying along a route on the map; the edges are also rulers'],
        ['**Direction-of-travel arrow**', 'Arrow engraved along the plate’s long axis', 'Points where you will walk (or at the object you are sighting)'],
        ['**Rotating housing and bezel**', 'Liquid-filled capsule that turns; its rim is marked 0–360°', 'Setting and storing a bearing'],
        ['**Index line**', 'Mark where the direction-of-travel line meets the bezel', 'Where you read the bearing'],
        ['**Orienting arrow**', 'Outlined arrow on the floor of the housing', 'The “shed” — you put the red needle in it'],
        ['**Orienting lines**', 'Parallel lines on the housing floor', 'Aligned with the map’s north–south grid lines'],
        ['**Magnetic needle**', 'Red (or luminous) end points to magnetic north', 'The only part that senses direction'],
        ['**Romer scales, ruler**', 'Scales for 1:25,000 / 1:50,000 on the plate', 'Measuring distances and 6/8-figure grid references'],
        ['**Declination adjustment** (some models)', 'A small screw or clutch offsetting the orienting arrow', 'Correct declination once, then read magnetic bearings directly'],
      ],
    },
    {
      type: 'md',
      md: `### Three norths

- **True north** — toward the geographic North Pole, along lines of longitude.
- **Grid north** — the direction of the map’s vertical grid lines. Because a flat grid cannot follow curved meridians everywhere, grid north differs from true north by the **grid convergence**: zero on a UTM zone’s central meridian, a few degrees at the zone edges.
- **Magnetic north** — where the needle points. It differs from true north by the **magnetic declination** (also called variation), which depends on **where you are** and **when**.

Map margins usually show a small diagram of the three arrows and the angles between them — sometimes combined into a single **grid–magnetic angle**, which is the one you need when working from a gridded map.`,
    },
    { type: 'diagram', id: 'three-norths', caption: 'True, grid and magnetic north. Declination is true→magnetic; convergence is true→grid; the grid–magnetic angle combines them.' },
    {
      type: 'md',
      md: `### Declination changes with place and time

Earth’s field is generated by moving molten iron in the outer core and drifts continuously. The north magnetic pole has moved tens of kilometres per year in recent decades, and declination at a given place can change by a fraction of a degree to several tenths of a degree per year. Values range from near zero along the **agonic line** to more than 20° in parts of northern Canada, Greenland and New Zealand.

The value printed on your map is correct **for the date printed** — often with an annual change. For current values use the **NOAA magnetic field calculator** (based on the World Magnetic Model, WMM2025) or your national mapping agency. Most GPS units and phone compass apps also use the WMM.

### Converting bearings

Declination is named **east** or **west** by which side of true (or grid) north the needle points.

- **West declination** — magnetic north is *west* of grid north, so magnetic bearings are **larger**: grid → magnetic, **add**.
- **East declination** — magnetic north is *east* of grid north, so magnetic bearings are **smaller**: grid → magnetic, **subtract**.
- Going magnetic → grid, do the opposite.

A mnemonic that works everywhere: **“Declination east, magnetic least; declination west, magnetic best (biggest).”** The British rhyme **“grid to mag, add”** is only true where declination is **west** — it was taught for decades in the UK, where declination was west; it gives the wrong answer in most of western North America, New Zealand or anywhere the declination is east. Understand the picture, not the rhyme.`,
    },
    { type: 'diagram', id: 'declination', caption: 'Grid → magnetic for west declination (add) and east declination (subtract). Draw the arrows when in doubt.' },
    {
      type: 'callout',
      tone: 'tip',
      title: 'Set it and forget it (carefully)',
      md: 'If your compass has an adjustable declination, set it for your area and the needle will give **grid (or true) bearings directly** when boxed in the orienting arrow — no arithmetic in the rain. Write the setting on the baseplate with tape and check it whenever you travel to a new area. Mixing an adjusted compass with manual corrections doubles the error.',
    },
    {
      type: 'md',
      md: `### Deviation: keep magnets and metal away

Local magnetic fields bend the needle. Phones (speakers and magnetic cases), steel knives, belt buckles, cameras, car bodies, vehicles, rebar, fences and high-voltage lines can all deflect it — by many degrees at close range. Hold the compass at waist or chest height away from them, step well away from vehicles, and test your own kit at home by moving each item toward the compass and watching the needle. Some rock (magnetite, some basalts) causes **local attraction**; maps of volcanic areas sometimes warn of it.

### Dip and global needles

Near the poles the field points steeply into the ground (**magnetic dip**). Manufacturers balance needles for one of several zones — often five — so a compass bought in Europe may drag or stick in Australia. “Global” needles tolerate this. If you travel between hemispheres, check your compass level and free-swinging before you rely on it.

### Checking polarity

Strong magnets (speaker, magnetic clasp) can **weaken or reverse** a needle. Check before each trip against a known direction: the sun at local noon, Polaris, or a straight street on the map. A reversed needle is rare but catastrophic — it sends you 180° wrong with total confidence.`,
    },
  ],
  whyItMatters: 'A compass is light, cheap and needs no battery — the backup that still works when phones die or satellites are obscured by canyon walls. But it is only as good as the corrections you apply. Uncorrected declination is one of the commonest navigation errors, and with 1-in-60 arithmetic (next lesson) even a 10° error sends you about 170 m off line for every kilometre walked.',
  science: [
    {
      type: 'md',
      md: `### The conversion as an equation

With west declination written as positive and east as negative (one common convention):

$$
\\theta_{\\text{mag}} = \\theta_{\\text{grid}} + \\delta_{GM}
$$

where $\\delta_{GM}$ is the grid–magnetic angle. In words: the magnetic bearing is the grid bearing plus the angle from grid north round to magnetic north, counted positive when magnetic north is west. Keep the result between 0° and 360° by adding or subtracting 360°.

**West declination worked example (8° W — as in this stage’s map simulator):**
- Grid 060° → magnetic $60 + 8 = 068^\\circ$.
- Grid 355° → magnetic $355 + 8 = 363 \\to 003^\\circ$.
- Magnetic 250° → grid $250 - 8 = 242^\\circ$.

**East declination worked example (12° E):**
- Grid 060° → magnetic $60 - 12 = 048^\\circ$.
- Magnetic 250° → grid $250 + 12 = 262^\\circ$.
- Grid 005° → magnetic $5 - 12 = -7 \\to 353^\\circ$.

### Updating an old map value

If the margin reads “8° W in 2005, decreasing 0.2° per year”, then in 2026 it has decreased by $21 \\times 0.2 = 4.2^\\circ$: declination $\\approx 8 - 4.2 = 3.8^\\circ$ W. Always cross-check with a current model — the rate itself changes.

### Grid convergence

On a transverse Mercator grid, convergence is approximately

$$
\\gamma \\approx \\Delta\\lambda \\, \\sin\\varphi
$$

where $\\Delta\\lambda$ is the longitude difference from the zone’s central meridian and $\\varphi$ is latitude. Example: 2° from the central meridian at 50° latitude gives $\\gamma \\approx 2 \\times 0.766 \\approx 1.5^\\circ$. Small, but it adds to (or subtracts from) declination — which is why the map’s own grid–magnetic angle is the number to use.`,
    },
  ],
  examples: [
    {
      type: 'md',
      md: `**Subarctic (northern Canada).** Declination can exceed 15–20°. A canoeist who forgets it and follows an uncorrected bearing across a 3 km lake misses the portage by nearly a kilometre.

**Coastal (New Zealand, South Island).** Declination is over 20° east. A visitor using the UK rule “grid to mag, add” doubles the error instead of removing it.

**Mountain (volcanic terrain).** On some basalt and magnetite-rich ground, needles swing several degrees from spot to spot. Navigators rely more on landforms and handrails, and take bearings from several places to spot anomalies.

**Desert.** Near a vehicle the needle is deflected by the steel body. Walk 10 m away before taking a bearing — and put the phone in a different pocket.

**Urban.** Steel-framed buildings, rebar, parked cars and underground services make city compass work unreliable. Street grids and landmarks are better references.

**Tropical and forest.** Humidity does not affect a compass, but a phone clipped to a shoulder strap next to it will. Many people discover this only after a day of mysterious drift.`,
    },
  ],
  mistakes: [
    'Using “grid to mag, add” where declination is east.',
    'Applying declination by hand on a compass already adjusted for it — the correction is applied twice.',
    'Using a declination printed decades ago without updating it.',
    'Taking bearings next to a phone, car, knife, fence or rebar.',
    'Reading the bearing from the needle instead of from the index line.',
    'Myth: “The compass points to the North Pole.” It aligns with the local magnetic field, which points toward neither the geographic pole nor (exactly) the magnetic pole.',
    'Myth: “Compasses don’t work in the southern hemisphere.” They do; a needle balanced for another zone may drag, which a global needle avoids.',
    'Myth: “A compass needle can’t be reversed.” Strong magnets can reverse or weaken it — check polarity before trips.',
  ],
  exercises: [
    {
      id: 's2-l3-e1',
      title: 'Declination lookup and conversion drill',
      level: 1,
      safety: 'home',
      minutes: 30,
      materials: ['Internet access (NOAA magnetic field calculator)', 'A topographic map with a declination diagram', 'Notebook'],
      steps: [
        'Look up today’s declination for your home and for two places on other continents with the NOAA calculator. Note east or west and the annual change.',
        'Compare the map’s printed declination with today’s value; update the map value using its printed annual change.',
        'Convert 10 grid bearings to magnetic and 10 magnetic to grid for **both** an east and a west declination, including bearings near 000°/360°.',
        'Draw the three-norths arrows for each case to check your arithmetic.',
      ],
      success: ['All 40 conversions correct, including wraparound past 360°.', 'You can explain “east least, west best” with a sketch.'],
      skill: 'map-compass',
    },
    {
      id: 's2-l3-e2',
      title: 'Know your compass',
      level: 2,
      safety: 'home',
      minutes: 20,
      materials: ['Baseplate compass', 'Phone', 'Keys, knife, belt buckle'],
      steps: [
        'Name each part aloud and say what it is for.',
        'Set the housing to 000° and let the needle settle. Slowly move each metal item and your phone toward the compass; note the distance at which the needle first moves.',
        'Check polarity: at local solar noon (or with a map of a straight street), confirm the red end points roughly north.',
        'If your compass has declination adjustment, set it for your area and label it.',
      ],
      success: ['You know the “safe distance” for each item you carry.', 'Your needle is confirmed correct polarity and free-swinging when held level.'],
      skill: 'map-compass',
    },
  ],
  quiz: [
    {
      id: 's2-l3-q3',
      kind: 'single',
      prompt: 'A friend trained in the UK says “grid to mag, add — always”. You are navigating where declination is **15° E**. What happens if you follow the rule?',
      choices: [
        { id: 'a', text: 'Nothing — the rule is universal.', why: 'The rule only holds where declination is west.' },
        { id: 'b', text: 'You end up 15° off course.', why: 'Close, but adding instead of subtracting puts you off by twice the declination.' },
        { id: 'c', text: 'You end up about 30° off course.', why: 'Correct — you should subtract 15° but add 15°, a 30° error.' },
        { id: 'd', text: 'You end up 180° off course.', why: 'That is the error from a reversed needle or reading the wrong end, not the declination sign.' },
      ],
      answer: 'c',
      concepts: ['declination'],
      explanation: 'Applying the correction with the wrong sign doubles it: 2 × 15° = 30°. At 1 km that is roughly 500–580 m off line (1-in-60 estimate vs exact).',
    },
    {
      id: 's2-l3-q5',
      kind: 'single',
      prompt: 'Which of these will **not** deflect a compass needle enough to matter?',
      choices: [
        { id: 'a', text: 'A phone in the same hand or chest pocket', why: 'It will — speakers and magnetic cases are strong local fields.' },
        { id: 'b', text: 'Standing right next to a parked vehicle', why: 'It will — a steel body deflects the needle; move several metres away.' },
        { id: 'c', text: 'Rain running over the compass capsule', why: 'Correct — water does not affect the magnetic reading.' },
        { id: 'd', text: 'A steel fence or rebar in concrete nearby', why: 'It will — ferrous metal nearby distorts the local field.' },
      ],
      answer: 'c',
      concepts: ['compass'],
      explanation: 'Deviation comes from magnetic fields and ferrous metal close to the compass — phones, vehicles, fences, even iron-rich volcanic rock. Test your kit at home and hold the compass clear of it.',
    },
    {
      id: 's2-l3-q6',
      kind: 'single',
      prompt: 'Your compass is **adjusted for local declination**. How do you turn a bearing measured on the map into one you can walk?',
      choices: [
        { id: 'a', text: 'Use it as measured; the adjusted compass applies the correction', why: 'Correct — the adjustment already does the conversion; use one method only.' },
        { id: 'b', text: 'Add or subtract the declination by hand, as with any compass', why: 'Doing it again on top of the adjustment doubles the error.' },
        { id: 'c', text: 'Correct by hand only when the declination is several degrees or more', why: 'The adjustment already covers it at any size; a hand correction doubles it.' },
        { id: 'd', text: 'Apply the declination by hand with the opposite sign to undo it', why: 'That cancels the adjustment and leaves the bearing uncorrected.' },
      ],
      answer: 'a',
      concepts: ['compass', 'declination'],
      explanation: 'An adjusted compass already applies the correction; doing it again doubles the error. Use one method — and label which one on the compass.',
    },
    {
      id: 's2-l3-q2',
      kind: 'single',
      prompt: 'Declination is **8° W**. Your compass (not adjusted for declination) gives a **magnetic** bearing of **004°** to a summit. What is the **grid** bearing to plot on the map?',
      choices: [
        { id: 'a', text: '356°', why: 'Correct — west: magnetic is bigger, so subtract: 4 − 8 = −4 → 356°.' },
        { id: 'b', text: '012°', why: 'Wrong sign — added the declination instead of subtracting it.' },
        { id: 'c', text: '004°', why: 'No correction applied — this is still the magnetic bearing.' },
        { id: 'd', text: '176°', why: 'Wrapped −4° by adding 180° instead of 360°.' },
      ],
      answer: 'a',
      concepts: ['declination'],
      explanation: 'West declination: magnetic is bigger than grid, so magnetic → grid subtracts. 4 − 8 = −4 → **356°**.',
    },
    {
      id: 's2-l3-q4',
      kind: 'single',
      prompt: 'A map printed in 2005 says “Declination 8° W, decreasing 0.2° annually”. Estimate the declination in **2026**.',
      choices: [
        { id: 'a', text: '3.8° W', why: 'Correct — 21 years × 0.2° = 4.2°, and 8 − 4.2 = 3.8° W.' },
        { id: 'b', text: '4.2° W', why: 'That is the total change, not the new declination — subtract it from 8°.' },
        { id: 'c', text: '12.2° W', why: 'The change was added, but the map says the declination is decreasing.' },
        { id: 'd', text: '4.0° W', why: 'Counted 20 years instead of 21 (2005 to 2026).' },
      ],
      answer: 'a',
      concepts: ['declination'],
      explanation: '21 years × 0.2° = 4.2°. 8 − 4.2 = **3.8° W**. Cross-check with the NOAA calculator — the rate itself drifts.',
    },
    {
      id: 's2-l3-q1',
      kind: 'single',
      prompt: 'Declination is **12° E**. You measure a **grid** bearing of **060°** on the map. What **magnetic** bearing do you set?',
      diagram: 'declination',
      choices: [
        { id: 'a', text: '048°', why: 'Correct — east declination, magnetic least: 60 − 12 = 48.' },
        { id: 'b', text: '072°', why: 'Wrong sign — adding is the rule for west declination.' },
        { id: 'c', text: '060°', why: 'No correction applied — this is still the grid bearing.' },
        { id: 'd', text: '036°', why: 'The correction was applied twice (60 − 24).' },
      ],
      answer: 'a',
      concepts: ['declination'],
      explanation: 'East declination: magnetic bearings are smaller (“east least”). 60 − 12 = **048°**.',
    },
  ],
  scenario: {
    id: 's2-l3-sc',
    setup: 'You are on a subarctic canoe trip in late August. Your map is 30 years old and shows declination 18° E. Your borrowed compass has an adjustable declination, and a sticker reads “set 2° W”. You must cross a 4 km lake to find a narrow portage before evening wind picks up in 2 hours. The far shore is low, featureless forest.',
    question: 'What do you do before setting off?',
    choices: [
      { id: 'a', text: 'Use the compass as it is, since a few degrees of error won’t matter much on a short lake crossing.', why: 'The setting is about 20° wrong: at 4 km, the 1-in-60 rule gives ≈1.3 km off line (≈1.5 km exactly). You would miss the portage.' },
      { id: 'b', text: 'Check current declination (GPS/phone or updated map value), reset the compass, and aim off to one side of the portage.', why: 'Best: corrects the real error and adds a strategy (aiming off, lesson 6) for the remaining uncertainty.' },
      { id: 'c', text: 'Apply the old map’s 18° E by hand on top of whatever the compass is currently set to.', why: 'Mixes two corrections (2° W already set plus 18° E by hand) and uses a 30-year-old value — the errors may add or cancel unpredictably.' },
      { id: 'd', text: 'Paddle the long way round along the shoreline instead, so you never lose sight of land.', why: 'A reversible, low-risk option if time allows, but it costs hours you do not have before the wind rises; fixing the compass is cheaper.' },
    ],
    best: 'b',
    debrief: 'Two problems hide in this setup: an outdated printed value and a compass set for somewhere else. A few minutes of checking converts a likely kilometre-scale miss into a small, planned one. Crossing water under a time limit also raises the stakes of a wrong decision — a mid-lake error in rising wind is less reversible than a slow start.',
    concepts: ['declination', 'compass', 'reversibility', 'decisions'],
  },
  summary: [
    'The baseplate compass is a protractor around a needle: direction-of-travel arrow, housing, orienting arrow and lines, index line.',
    'True north (meridians), grid north (map lines), magnetic north (needle). Use the map’s grid–magnetic angle.',
    'Declination varies with place and time — check the NOAA/WMM value and update old maps.',
    '“Declination east, magnetic least; declination west, magnetic best.” West: grid → mag add. East: grid → mag subtract.',
    'Keep phones, metal and magnets away; check needle polarity and balance zone before trips.',
  ],
  furtherReading: ['noaa-declination', 'noaa-wmm', 'kjellstrom'],
  references: ['noaa-declination', 'noaa-wmm', 'kjellstrom', 'tc-3-25-26', 'freedom-hills', 'langmuir-mountaincraft'],
}
