import type { Question } from '../../types'

// Stage 2 review: interleaved questions across the stage, deliberately mixed with Stage 1 concepts
// (daylight budgeting, STOP, stay-or-move) in new navigation contexts.
export const stage2Review: Question[] = [
  {
    id: 's2-rev-1',
    kind: 'numeric',
    prompt: 'On a 1:25,000 map you measure 5.2 cm from a bridge to a hut along a straight line. Open ground, no climb, Naismith’s 5 km/h. How many **minutes** will the walk take?',
    unit: 'min',
    answer: 15.6,
    tolerance: 0.5,
    concepts: ['map-scale', 'timing'],
    explanation: '5.2 cm × 250 m/cm = 1.3 km. At 5 km/h: 1.3 / 5 × 60 = **15.6 min**. Add 1 min per 10 m of climb and extra time for rough ground in real life.',
  },
  {
    id: 's2-rev-2',
    kind: 'single',
    prompt: 'You measure a grid bearing of 212° on the map. The map margin says declination 6° E. What do you set on the compass?',
    choices: [
      { id: 'a', text: '218°', why: 'That adds east declination — the rule for west declination. With east declination, magnetic north is east of grid north, so magnetic bearings are smaller.' },
      { id: 'b', text: '206°', why: 'Correct: “declination east, magnetic least” — grid 212° − 6° = 206° magnetic.' },
      { id: 'c', text: '032°', why: 'That is the back bearing of 212°, not a declination correction.' },
      { id: 'd', text: '212° — declination only matters over long distances.', why: 'A 6° error puts you about 100 m off per kilometre (1-in-60 rule). It always matters.' },
    ],
    answer: 'b',
    concepts: ['declination', 'bearings'],
    explanation: 'East declination: magnetic = grid − declination. West declination: magnetic = grid + declination. Draw the three norths if you are unsure.',
  },
  {
    id: 's2-rev-3',
    kind: 'numeric',
    prompt: 'You follow a bearing for 2.4 km, but your compass work is 4° off. Using the **1-in-60 rule**, how far (m) to the side of your target do you arrive?',
    unit: 'm',
    answer: 160,
    tolerance: 10,
    concepts: ['angular-error'],
    diagram: 'one-in-sixty',
    explanation: 'Lateral error ≈ distance × degrees / 60 = 2400 × 4 / 60 = **160 m** (exact: 2400 × tan 4° ≈ 168 m). In forest you might walk past a small target without seeing it — which is why you aim off to a linear feature.',
  },
  {
    id: 's2-rev-4',
    kind: 'order',
    prompt: 'Fog, 15:40, the expected stream has not appeared. Order a sound relocation procedure.',
    items: [
      { id: 'stop', text: 'STOP: stop moving, shelter, eat, calm down' },
      { id: 'lkp', text: 'Identify your last known point and time' },
      { id: 'circle', text: 'Estimate how far you could have gone; draw a circle of possible positions' },
      { id: 'test', text: 'Test candidates against the ground: altitude, slope aspect, features' },
      { id: 'act', text: 'Choose a catching feature or backtrack — with a time trigger for stopping' },
    ],
    answer: ['stop', 'lkp', 'circle', 'test', 'act'],
    concepts: ['relocation', 'stop'],
    explanation: 'STOP first (Stage 1), then work from certainty outward. Every relocation plan should be bounded by the daylight budget.',
  },
  {
    id: 's2-rev-5',
    kind: 'multi',
    prompt: 'Which statements about natural and celestial direction clues are **true**?',
    choices: [
      { id: 'a', text: 'Polaris’s altitude above the horizon is approximately your latitude.', why: 'True — within about 1° in the northern hemisphere.' },
      { id: 'b', text: 'Moss grows reliably on the north side of trees.', why: 'Myth. Moss grows where it is damp and shaded, which can be any side depending on slope, canopy and prevailing wet wind.' },
      { id: 'c', text: 'Mintaka, in Orion’s belt, rises almost exactly due east everywhere on Earth.', why: 'True — it lies almost on the celestial equator.' },
      { id: 'd', text: 'In the southern hemisphere the Sun is due north at local solar noon (outside the tropics).', why: 'True — south of the Tropic of Capricorn the noon sun is always to the north.' },
      { id: 'e', text: 'The Sun rises due east every day of the year.', why: 'False — only near the equinoxes. At 40° N in midsummer it rises about 31° north of east.' },
    ],
    answer: ['a', 'c', 'd'],
    concepts: ['polaris', 'star-navigation', 'solar-direction', 'nav-myths'],
    explanation: 'Celestial clues are precise when understood; many “natural” clues are local tendencies at best, and some are simply myths.',
  },
  {
    id: 's2-rev-6',
    kind: 'numeric',
    prompt: 'Sunset is 17:20 and usable twilight under cloud adds 15 min. You need 70 min to set up a bivouac and want a 15-minute safety margin. It is 15:30. How many **minutes** do you have before you must start setting up?',
    unit: 'min',
    answer: 40,
    tolerance: 0,
    concepts: ['daylight', 'relocation'],
    explanation: 'Latest start = 17:20 + 0:15 − 1:10 − 0:15 = 16:10, which is **40 min** from 15:30. A 50-minute handrail route to the path does not fit with certainty — try it only with a firm 16:10 trigger to stop wherever you are and switch to survival mode.',
  },
  {
    id: 's2-rev-7',
    kind: 'single',
    prompt: 'You are heading for a small hut on a footpath that runs north–south through forest, 1.5 km away. What is the best technique?',
    choices: [
      { id: 'a', text: 'Aim directly at the hut and count paces carefully.', why: 'Even ±3° is ±80 m at 1.5 km: on reaching the path you would not know whether to turn north or south.' },
      { id: 'b', text: 'Aim off deliberately to one side (e.g. 5–6° north), hit the path, then turn south along it to the hut.', why: 'Correct: aiming off plus a handrail turns an uncertain point target into a certain decision.' },
      { id: 'c', text: 'Walk until you see the hut, however long that takes.', why: 'No stopping rule: this is how people walk past targets and keep going.' },
      { id: 'd', text: 'Use the phone map continuously the whole way.', why: 'Works until the battery fails — and it will fail fastest in cold. Use GNSS as a check, not a crutch.' },
    ],
    answer: 'b',
    concepts: ['aiming-off', 'handrails', 'battery-strategy'],
    explanation: 'Aim off to a linear feature, then use it as a handrail. Set a catching feature beyond the target so you know when you have gone too far.',
  },
  {
    id: 's2-rev-8',
    kind: 'single',
    prompt: 'Late afternoon in subarctic forest, −10 °C. You are unsure of your position but your ski tracks are clear behind you and sunset is in 50 minutes. What should you do?',
    choices: [
      { id: 'a', text: 'Head toward the setting sun, which is roughly west, where the road should be.', why: 'Direction without a known destination; and at high latitude in winter the setting sun is far south of west.' },
      { id: 'b', text: 'STOP, then backtrack on your own tracks toward your last known point, with a turn-around time that leaves light for a shelter.', why: 'Best: your tracks are a reliable, reversible handrail to a known point, and the trigger protects your daylight budget.' },
      { id: 'c', text: 'Keep going: the loop must reconnect somewhere.', why: 'Hope is not a plan — this is how the search area grows.' },
      { id: 'd', text: 'Take a GPS fix, then keep the screen on to navigate.', why: 'A fix is useful; continuous screen use in −10 °C will drain the battery fast. Note the fix, then conserve.' },
    ],
    answer: 'b',
    concepts: ['stop', 'relocation', 'daylight', 'solar-direction'],
    explanation: 'Backtracking to the last known point is the most reliable relocation tool — when your trail is still visible. Combine it with a Stage 1 daylight budget.',
  },
  {
    id: 's2-rev-9',
    kind: 'single',
    prompt: 'A lost hiker’s partner reports them overdue. The hiker has water, warm clothes, and a phone at 8 %, but no idea where they are in featureless forest. Which choice best helps the search?',
    choices: [
      { id: 'a', text: 'Keep walking in a straight line to cover ground.', why: 'Without sun or landmarks people drift and even circle (Souman et al., 2009), and moving targets are far harder to find.' },
      { id: 'b', text: 'Use the last of the battery to send one SMS with GNSS coordinates, then stay put in the most visible safe spot nearby and prepare signals.', why: 'Best: a position narrows the search dramatically; staying put makes the search area stop growing.' },
      { id: 'c', text: 'Follow the first stream downhill to find civilisation.', why: 'Streams in unknown terrain often lead into gorges and waterfalls before they lead anywhere useful.' },
      { id: 'd', text: 'Climb the tallest tree to look around.', why: 'An unsupported climb risks a fall far from help. Seek open, safe high ground instead.' },
    ],
    answer: 'b',
    concepts: ['stay-or-move', 'lost-person-behavior', 'phone-use'],
    explanation: 'When someone knows you are missing and you cannot relocate reliably, staying put and being findable usually beats moving.',
  },
  {
    id: 's2-rev-10',
    kind: 'truefalse',
    prompt: 'On a map with contours at 10 m intervals, contour lines that form a V pointing **uphill** show a valley or stream line.',
    answer: true,
    concepts: ['contours', 'landforms'],
    explanation: 'In valleys and re-entrants the contour V’s point upstream (uphill); on spurs they point downhill. Streams on the map confirm it.',
  },
  {
    id: 's2-rev-11',
    kind: 'single',
    prompt: 'A rescuer asks for your position. Your phone shows 45.8326, 6.8652. What should you say?',
    choices: [
      { id: 'a', text: '“Forty-five point eight three two six north, six point eight six five two east — decimal degrees.”', why: 'Correct: numbers, hemisphere letters, and the format name. Format confusion is a classic, avoidable SAR error.' },
      { id: 'b', text: '“Forty-five degrees, eighty-three minutes…”', why: 'Wrong — decimal degrees are not minutes; minutes never exceed 59.' },
      { id: 'c', text: '“I’m near a big rock by a stream.”', why: 'Descriptive details help later, but they cannot replace coordinates.' },
      { id: 'd', text: 'Read only the first two digits of each number to save battery.', why: '45, 6 is a square about 100 km across. Every digit matters: 0.0001° ≈ 11 m.' },
    ],
    answer: 'a',
    concepts: ['coordinate-formats', 'phone-use'],
    explanation: 'Say the format, both numbers, and N/S and E/W. If asked for another format, convert carefully or let the rescuer do it.',
  },
]
