import type { Lesson, Question } from '../../types'

// Final assessment. Ids are `fa-<domain>-<n>`; the domain drives the per-domain breakdown
// (see sims/stage19/FinalAssessment.tsx). Weighted toward judgment and prioritization.

export const finalQuestions: Question[] = [
  // ---------- First 10: one judgment question per domain ----------
  {
    id: 'fa-scen-1',
    kind: 'single',
    prompt: 'It’s 16:20, sunset 17:40, 4 °C with rain forecast at 19:00. You’re lost but someone knows your route, you have an emergency bag and warm layers, and you just sent your coordinates by SMS. Best next action?',
    choices: [
      { id: 'a', text: 'Walk toward a road you think is 5 km away, using the last daylight.', why: 'Irreversible, and it ends in darkness and rain.' },
      { id: 'b', text: 'Pick a sheltered mid-slope site now, build a thick ground bed, ready fuel and signals.', why: 'Correct — protection before dark, then reassess.' },
      { id: 'c', text: 'Spend the remaining daylight foraging so you have calories for the night.', why: 'Wrong priority — food is not what threatens you tonight.' },
      { id: 'd', text: 'Sit under a big tree and wait passively for rescuers until morning.', why: 'Wastes the daylight you need to build protection from the rain.' },
    ],
    answer: 'b',
    concepts: ['integration', 'stay-or-move', 'daylight'],
    explanation: 'Communication is done and someone knows your route, so staying is justified; the remaining daylight goes into protection from the cold rain before dark.',
  },
  {
    id: 'fa-phys-3',
    kind: 'single',
    prompt: 'A hiker in 35 °C heat becomes confused and stops sweating normally, with a very hot body. What is the key field priority?',
    choices: [
      { id: 'a', text: 'Give salt tablets and fluids, then continue slowly to the trailhead.', why: 'Wrong — this looks like heat stroke, a life-threatening emergency.' },
      { id: 'b', text: 'Cool aggressively right away (e.g., cold-water immersion), then evacuate.', why: 'Correct — “cool first, transport second”, per current WMS and ACSM guidance.' },
      { id: 'c', text: 'Let them rest where they are and reassess once they feel better.', why: 'Dangerous — heat stroke worsens without active cooling.' },
      { id: 'd', text: 'Give large amounts of water and wait for sweating to return.', why: 'Hydration alone does not treat heat stroke.' },
    ],
    answer: 'b',
    concepts: ['priorities'],
    explanation: 'Altered mental status with high body temperature in heat means heat stroke until proven otherwise: rapid cooling is the treatment — cool first, transport second.',
  },
  {
    id: 'fa-aid-2',
    kind: 'single',
    prompt: 'A deep thigh wound is spurting blood and firm direct pressure is not controlling it. What does current guidance support?',
    choices: [
      { id: 'a', text: 'Apply a tourniquet high and tight above the wound and note the time.', why: 'Correct — tourniquets are an early, not last-resort, tool for life-threatening limb bleeding.' },
      { id: 'b', text: 'Elevate the leg and keep the same pressure on while you wait.', why: 'Insufficient for arterial bleeding that pressure is already failing to control.' },
      { id: 'c', text: 'Lift the dressing every few minutes to check whether it has stopped.', why: 'Disrupts clotting.' },
      { id: 'd', text: 'Clean the wound thoroughly first so the dressing can seal properly.', why: 'Bleeding control comes first.' },
    ],
    answer: 'a',
    concepts: ['priorities'],
    explanation: 'Life-threatening extremity bleeding: direct pressure/packing, and a tourniquet when pressure fails or cannot be maintained — then get help.',
  },
  {
    id: 'fa-water-3',
    kind: 'single',
    prompt: 'Stranded in desert heat with 3 L of water. Which strategy is best?',
    choices: [
      { id: 'a', text: 'Sip tiny amounts to make it last, and keep walking by day.', why: 'Rations water while wasting sweat.' },
      { id: 'b', text: 'Drink to need, rest in shade by day, move only in cool hours.', why: 'Correct — ration sweat, not water.' },
      { id: 'c', text: 'Drink all 3 L at once now, then walk out during the day.', why: 'Uncontrolled; the excess is urinated and walking by day wastes sweat.' },
      { id: 'd', text: 'Drink your own urine first to save the bottled water for later.', why: 'Myth.' },
    ],
    answer: 'b',
    concepts: ['dehydration', 'water-needs'],
    explanation: 'Reduce losses: water is more useful inside you than in the bottle, and resting in shade by day cuts the sweat you lose.',
  },
  {
    id: 'fa-shelter-1',
    kind: 'single',
    prompt: 'Calm, clear night forecast at −3 °C. Where do you pitch?',
    choices: [
      { id: 'a', text: 'Valley floor by the stream, sheltered by the slopes', why: 'Cold-air pooling.' },
      { id: 'b', text: 'Mid-slope bench under living canopy, clear of dead trees', why: 'Correct.' },
      { id: 'c', text: 'Open ridge top, well away from the damp valley air', why: 'Wind and radiation exposure.' },
      { id: 'd', text: 'In a dry gully, tucked down out of the wind', why: 'Flash-flood and cold-pool risk.' },
    ],
    answer: 'b',
    concepts: ['site-selection'],
    explanation: 'Mid-slope avoids cold pools and wind; canopy reduces radiation to the sky.',
  },
  {
    id: 'fa-risk-3',
    kind: 'single',
    prompt: 'A river on your route is fast and above knee depth after rain. Best decision?',
    choices: [
      { id: 'a', text: 'Cross quickly at the narrowest point with your pack straps done up.', why: 'Dangerous — pack straps can trap you.' },
      { id: 'b', text: 'Don’t cross; wait for it to drop or reroute, and update your contacts.', why: 'Correct.' },
      { id: 'c', text: 'Cross holding hands with another hiker you meet at the bank.', why: 'Still dangerous in fast water above knee depth.' },
      { id: 'd', text: 'Swim across where the current looks slowest.', why: 'Very dangerous.' },
    ],
    answer: 'b',
    concepts: ['risk', 'reversibility'],
    explanation: 'Swift-water crossing is a leading cause of backcountry death; waiting is usually the reversible option.',
  },
  {
    id: 'fa-nav-3',
    kind: 'single',
    prompt: 'You need to reach a bridge on a river, but it is hidden in forest. What is the most reliable technique?',
    choices: [
      { id: 'a', text: 'Take an exact bearing to the bridge and trust it all the way.', why: 'Small errors mean you won’t know which way to turn when you hit the river.' },
      { id: 'b', text: 'Aim off to one side, hit the river, then follow it to the bridge.', why: 'Correct — you know which way to turn.' },
      { id: 'c', text: 'Follow animal trails heading in the rough direction of the river.', why: 'Unreliable.' },
      { id: 'd', text: 'Walk toward the sound of water and look for the bridge there.', why: 'Sound is deceptive.' },
    ],
    answer: 'b',
    concepts: ['integration'],
    explanation: 'Aiming off converts a point target into a linear one with a known direction to turn.',
  },
  {
    id: 'fa-know-3',
    kind: 'single',
    prompt: 'Which kit change most improves the outcome of a solo remote trip with no phone coverage?',
    choices: [
      { id: 'a', text: 'A larger, stronger fixed-blade knife', why: 'Marginal.' },
      { id: 'b', text: 'A registered PLB or satellite messenger', why: 'Correct — it removes the delay before anyone starts searching.' },
      { id: 'c', text: 'A fishing kit for catching food', why: 'Food is rarely limiting.' },
      { id: 'd', text: 'A second identical phone as backup', why: 'Same failure mode — no coverage.' },
    ],
    answer: 'b',
    concepts: ['kit', 'redundancy', 'signaling'],
    explanation: 'Communication independent of cell coverage is the single largest lever for solo remote travel.',
  },
  {
    id: 'fa-psych-1',
    kind: 'single',
    prompt: 'You notice you keep saying “just 10 more minutes” past your turnaround time. What is happening?',
    choices: [
      { id: 'a', text: 'Plan continuation / commitment bias', why: 'Correct.' },
      { id: 'b', text: 'Healthy persistence toward the goal', why: 'Not when it overrides a pre-set limit.' },
      { id: 'c', text: 'Low blood sugar (hypoglycaemia) only', why: 'Could contribute, but the pattern is a bias.' },
      { id: 'd', text: 'Expert halo from deferring to others', why: 'No one is being deferred to.' },
    ],
    answer: 'a',
    concepts: ['human-factors'],
    explanation: 'Name the trap; honour the turnaround trigger you set while calm.',
  },
  {
    id: 'fa-fire-2',
    kind: 'single',
    prompt: 'Which is the most dangerous way to use fire or stoves for warmth?',
    choices: [
      { id: 'a', text: 'A small fire in front of an open lean-to', why: 'Reasonable with care.' },
      { id: 'b', text: 'A stove running inside a closed snow shelter or tent', why: 'Correct — carbon monoxide can kill silently.' },
      { id: 'c', text: 'Warm water bottles inside a sleeping bag', why: 'Safe and effective.' },
      { id: 'd', text: 'A small fire in an existing fire ring at camp', why: 'Appropriate where allowed.' },
    ],
    answer: 'b',
    concepts: ['fire-safety'],
    explanation: 'Combustion in enclosed spaces is a recurring cause of death in winter camping and urban outages.',
  },
  // ---------- Remaining questions ----------
  {
    id: 'fa-scen-2',
    kind: 'single',
    prompt: 'Your partner has a suspected ankle fracture 6 km from the road at 14:00 in good weather. You have phone coverage. Best plan?',
    choices: [
      { id: 'a', text: 'Carry them out yourself now while the weather is still good.', why: 'High injury risk to both.' },
      { id: 'b', text: 'Call with your exact location, splint and insulate them, prepare signals.', why: 'Correct.' },
      { id: 'c', text: 'Leave them and walk out fast to get help, without calling.', why: 'Loses the fastest lever and leaves them alone.' },
      { id: 'd', text: 'Wait to see if the ankle improves before deciding anything.', why: 'Delay wastes daylight and rescue time.' },
    ],
    answer: 'b',
    concepts: ['integration', 'phone-use'],
    explanation: 'Communication first, then patient care and protection: splint, insulate, shelter, monitor and prepare signals.',
  },
  {
    id: 'fa-scen-3',
    kind: 'single',
    prompt: 'After a night earthquake you smell gas in your apartment building. First action?',
    choices: [
      { id: 'a', text: 'Light a candle so you can find the leak in the dark.', why: 'Ignition source.' },
      { id: 'b', text: 'Get everyone out without using switches or flames; report it outside.', why: 'Correct — immediate danger first.' },
      { id: 'c', text: 'Fill the bathtub with water before supplies are cut off.', why: 'Good later; not while gas is leaking.' },
      { id: 'd', text: 'Stay inside and post an update to family before deciding.', why: 'Not now — get out first.' },
    ],
    answer: 'b',
    concepts: ['immediate-danger'],
    explanation: 'Question 1 of 12 — immediate danger — dominates in urban disasters too. Shut off gas at the meter only if trained and safe.',
  },
  {
    id: 'fa-food-1',
    kind: 'single',
    prompt: 'In a 72-hour survival situation, what is the correct role of food?',
    choices: [
      { id: 'a', text: 'Top priority — start hunting and foraging from day 1.', why: 'Burns energy and time for little return.' },
      { id: 'b', text: 'Low priority; use carried food for warmth and morale, not foraging.', why: 'Correct.' },
      { id: 'c', text: 'Avoid all eating so that digestion does not use up water.', why: 'Only if water is extremely scarce — digestion does use water.' },
      { id: 'd', text: 'Eat any berries you find to keep your energy up.', why: 'Poisoning risk.' },
    ],
    answer: 'b',
    concepts: ['priorities'],
    explanation: 'Food rarely limits short survival, but calories help heat production in the cold; don’t spend scarce daylight foraging.',
  },
  {
    id: 'fa-track-2',
    kind: 'single',
    prompt: 'A clear track in mud has crisp edges and small grains that have not yet fallen in; the morning had rain until 07:00. It is 10:00. The track was most likely made…',
    choices: [
      { id: 'a', text: 'Before the rain started early this morning', why: 'Rain would have softened the edges and filled detail.' },
      { id: 'b', text: 'After the rain stopped, within the last few hours', why: 'Correct — reasoning from weather events is the core of aging sign.' },
      { id: 'c', text: 'Several days ago, judging by how clear it is', why: 'Crisp edges argue against it.' },
      { id: 'd', text: 'Impossible to say anything without a reference', why: 'Weather events bracket the time.' },
    ],
    answer: 'b',
    concepts: ['integration'],
    explanation: 'Use known events (rain, frost, dew) as time markers and compare with reference tracks.',
  },
  {
    id: 'fa-aid-1',
    kind: 'single',
    prompt: 'You find an injured climber at the base of a crag. Which sequence of first actions is correct?',
    choices: [
      { id: 'a', text: 'Scene safety → primary survey (ABC) → call for help → secondary survey', why: 'Correct.' },
      { id: 'b', text: 'Primary survey (ABC) → scene safety → call for help → secondary survey', why: 'Rushing in before checking for rockfall risks a second casualty.' },
      { id: 'c', text: 'Call for help → scene safety → primary survey (ABC) → secondary survey', why: 'Check the scene and life threats first so the call can report them.' },
      { id: 'd', text: 'Scene safety → call for help → secondary survey → primary survey (ABC)', why: 'Life threats (airway, breathing, bleeding) come before the detailed exam.' },
    ],
    answer: 'a',
    concepts: ['immediate-danger', 'priorities'],
    explanation: 'Scene safety, then life threats, then help, then the detailed head-to-toe exam. (Take a hands-on WFA/WFR course.)',
  },
  {
    id: 'fa-know-1',
    kind: 'single',
    prompt: 'A person is in cold rain with no immediate danger and no injury. Which order of threats, most to least urgent over the next 3 hours, is correct?',
    choices: [
      { id: 'a', text: 'Soaked insulation → nobody knows your position → 300 ml of water → no food', why: 'Correct.' },
      { id: 'b', text: '300 ml of water → soaked insulation → nobody knows your position → no food', why: 'Water matters over a day; cold-wet exposure acts in hours.' },
      { id: 'c', text: 'Nobody knows your position → soaked insulation → 300 ml of water → no food', why: 'Being findable matters, but cold-wet exposure acts first.' },
      { id: 'd', text: 'Soaked insulation → 300 ml of water → no food → nobody knows your position', why: 'Being findable is the next lever after cold, ahead of water and food.' },
    ],
    answer: 'a',
    concepts: ['priorities', 'rule-of-threes'],
    explanation: 'Cold-wet exposure acts in hours; being findable is the next lever; water matters over a day; food over days to weeks.',
  },
  {
    id: 'fa-know-2',
    kind: 'single',
    prompt: 'Which statement does NOT reflect the course’s decision system?',
    choices: [
      { id: 'a', text: 'Reassess after every action; plans are provisional.', why: 'This is part of the system — the loop never stops.' },
      { id: 'b', text: 'Choose actions by risk removed per unit of time, energy and resources.', why: 'This is part of the system.' },
      { id: 'c', text: 'Irreversible actions need stronger evidence than reversible ones.', why: 'This is part of the system.' },
      { id: 'd', text: 'Once you commit to a plan, changing it signals weakness.', why: 'Correct — adapting to reality is a hallmark of survivors.' },
    ],
    answer: 'd',
    concepts: ['decision-loop', 'reversibility'],
    explanation: 'Observe → Assess → Prioritize → Plan → Act → Reassess, with a bias toward reversible, high-value actions.',
  },
  {
    id: 'fa-nav-1',
    kind: 'single',
    prompt: 'On a 1:25,000 map, two points are 6.4 cm apart. What is the ground distance?',
    choices: [
      { id: 'a', text: '1.6 km', why: 'Correct — 6.4 cm × 25,000 = 160,000 cm = 1.6 km.' },
      { id: 'b', text: '16 km', why: 'Off by a factor of 10 in the cm-to-km conversion.' },
      { id: 'c', text: '0.16 km', why: 'Off by a factor of 10 the other way: 100,000 cm = 1 km.' },
      { id: 'd', text: '3.9 km', why: 'Inverted ratio — 25,000 ÷ 6.4 instead of 6.4 × 25,000.' },
    ],
    answer: 'a',
    concepts: ['integration'],
    explanation: '6.4 cm × 25,000 = 160,000 cm; 100,000 cm = 1 km, so the distance is **1.6 km**.',
  },
  {
    id: 'fa-nav-2',
    kind: 'single',
    prompt: 'You walk 2 km on a bearing that is 3° off. Using the 1-in-60 rule (1° ≈ 1 unit off per 60 units travelled), roughly how far off-line are you?',
    choices: [
      { id: 'a', text: '100 m', why: 'Correct — 3/60 × 2,000 m = 100 m.' },
      { id: 'b', text: '33 m', why: 'Forgets the factor of 3° — that is the error for 1°.' },
      { id: 'c', text: '10 m', why: 'Uses 200 m instead of 2,000 m — a km-to-m slip.' },
      { id: 'd', text: '1,000 m', why: 'Off by a factor of 10 in the km-to-m conversion.' },
    ],
    answer: 'a',
    concepts: ['integration'],
    explanation: '3/60 × 2,000 m = **100 m** — enough to miss a small target, which is why you aim off toward a linear feature.',
  },
  {
    id: 'fa-phys-1',
    kind: 'single',
    prompt: 'Which situation carries the highest hypothermia risk?',
    choices: [
      { id: 'a', text: '−10 °C, calm, dry, in insulated layers and moving', why: 'Well controlled.' },
      { id: 'b', text: '6 °C, rain and 30 km/h wind, soaked cotton, resting', why: 'Correct — wet + wind + low heat production.' },
      { id: 'c', text: '15 °C, sunny, sitting still in the shade for hours', why: 'Low risk.' },
      { id: 'd', text: '−5 °C, in a sleeping bag on a foam pad', why: 'Well insulated.' },
    ],
    answer: 'b',
    concepts: ['wet-wind', 'heat-loss'],
    explanation: 'Most hypothermia happens at 0–10 °C when people are wet, in wind and not producing much heat.',
  },
  {
    id: 'fa-phys-2',
    kind: 'single',
    prompt: 'Evaporating 1 L of water removes ~2.4 MJ. A 70 kg person stores ~245 kJ per °C. Roughly how many °C of core-equivalent heat does evaporating **200 ml** from wet clothing remove?',
    choices: [
      { id: 'a', text: '2.0 °C', why: 'Correct — 0.2 × 2,400 kJ = 480 kJ; 480/245 ≈ 2.0 °C.' },
      { id: 'b', text: '9.8 °C', why: 'Uses the full 1 L instead of 200 ml.' },
      { id: 'c', text: '0.5 °C', why: 'Inverted ratio — 245/480 instead of 480/245.' },
      { id: 'd', text: '0.2 °C', why: 'Off by a factor of 10 in the MJ-to-kJ conversion.' },
    ],
    answer: 'a',
    concepts: ['heat-loss'],
    explanation: '0.2 × 2,400 kJ = 480 kJ; 480/245 ≈ **2.0 °C** — why wet clothing in wind is so dangerous.',
  },
  {
    id: 'fa-aid-3',
    kind: 'single',
    prompt: 'Someone is bitten by a snake. Which action is appropriate rather than a myth?',
    choices: [
      { id: 'a', text: 'Cut over the bite and suck out the venom', why: 'Myth — harmful.' },
      { id: 'b', text: 'Apply ice or a tourniquet to the bite', why: 'Myth for most snakes; can worsen tissue damage.' },
      { id: 'c', text: 'Keep them calm, remove rings, arrange evacuation', why: 'Correct — this is appropriate.' },
      { id: 'd', text: 'Catch the snake so it can be identified', why: 'Dangerous — a photo from a distance at most.' },
    ],
    answer: 'c',
    concepts: ['priorities'],
    explanation: 'Evacuation to antivenom-capable care is the treatment; local guidance on pressure immobilisation varies by region (e.g., Australia).',
  },
  {
    id: 'fa-fire-1',
    kind: 'single',
    prompt: 'Your fire keeps dying after the tinder burns out in wet weather. What is the most likely fix?',
    choices: [
      { id: 'a', text: 'A bigger bundle of tinder so it burns longer', why: 'Tinder is rarely the bottleneck.' },
      { id: 'b', text: 'Finer, drier kindling: split sticks, dead standing twigs', why: 'Correct — the transition from tinder to kindling is where wet fires fail.' },
      { id: 'c', text: 'Larger logs placed on top to hold the heat', why: 'Would smother it.' },
      { id: 'd', text: 'Blowing harder on the flame as the tinder burns', why: 'Airflow helps only if the fuel can catch.' },
    ],
    answer: 'b',
    concepts: ['fire-structure'],
    explanation: 'Surface-to-volume ratio and dryness decide the tinder→kindling handover: use more, finer, drier kindling, e.g., dead twigs from standing trees.',
  },
  {
    id: 'fa-fire-3',
    kind: 'single',
    prompt: 'No fire-ban sign is posted at the trailhead. Which statement about lighting an open fire there is correct?',
    choices: [
      { id: 'a', text: 'With no ban sign posted, you can assume open fires are legal.', why: 'Wrong — the absence of a sign is not permission.' },
      { id: 'b', text: 'Rules vary by land manager and season; check current restrictions.', why: 'Correct.' },
      { id: 'c', text: 'Fires are always legal as long as you use an existing fire ring.', why: 'Wrong — rings are only appropriate where fires are allowed.' },
      { id: 'd', text: 'Only a ranger on site can tell you, so ask one if you meet one.', why: 'Wrong — check the managing agency’s current restrictions before you go.' },
    ],
    answer: 'b',
    concepts: ['fire-safety'],
    explanation: 'Rules vary by land manager and season; check the managing agency’s current restrictions rather than relying on signs.',
  },
  {
    id: 'fa-water-1',
    kind: 'single',
    prompt: 'Stream below a farm and a village; you have a 0.1 µm filter and chlorine dioxide. Best plan?',
    choices: [
      { id: 'a', text: 'Filter only, using the 0.1 µm filter', why: 'Leaves viruses.' },
      { id: 'b', text: 'Chlorine dioxide only, with 30 min contact', why: 'Crypto may survive short contact.' },
      { id: 'c', text: 'Settle/pre-filter, filter, then chlorine dioxide', why: 'Correct — layered methods with non-overlapping gaps.' },
      { id: 'd', text: 'No treatment, since the stream is flowing', why: 'Flow does not mean safe.' },
    ],
    answer: 'c',
    concepts: ['water-treatment'],
    explanation: 'Filter removes protozoa and bacteria; chemical covers viruses; clarifying helps both.',
  },
  {
    id: 'fa-water-2',
    kind: 'single',
    prompt: 'Baseline 2.5 L/day, plus 6 hours of hiking in heat at 1.1 L/h. How much should you plan to drink?',
    choices: [
      { id: 'a', text: '9.1 L', why: 'Correct — 2.5 + 6 × 1.1 = 9.1 L.' },
      { id: 'b', text: '3.6 L', why: 'Forgets to multiply the hourly rate by 6 hours.' },
      { id: 'c', text: '6.6 L', why: 'Forgets the 2.5 L baseline.' },
      { id: 'd', text: '21.6 L', why: 'Multiplies the baseline by 6 hours as well.' },
    ],
    answer: 'a',
    concepts: ['water-needs'],
    explanation: '2.5 + 6 × 1.1 = **9.1 L**.',
  },
  {
    id: 'fa-shelter-2',
    kind: 'single',
    prompt: 'With limited time, which improvement most reduces overnight heat loss for someone lying on cold ground?',
    choices: [
      { id: 'a', text: 'A higher roof to give more room inside', why: 'More volume, not warmer.' },
      { id: 'b', text: 'A thick, dry bed of insulation underneath', why: 'Correct — conduction to the ground is the biggest sink.' },
      { id: 'c', text: 'A brighter, more visible tarp colour', why: 'Visibility, not warmth.' },
      { id: 'd', text: 'A wider doorway for better airflow', why: 'Worse — more heat loss.' },
    ],
    answer: 'b',
    concepts: ['ground-insulation'],
    explanation: 'Q = kAΔT/d: thickness and dryness of what you lie on dominate.',
  },
  {
    id: 'fa-shelter-3',
    kind: 'single',
    prompt: 'In a hot desert, which shade setup is usually best?',
    choices: [
      { id: 'a', text: 'A tarp draped directly over you as you lie down', why: 'Heat conducts and radiates straight through to you.' },
      { id: 'b', text: 'A shade roof raised 30–50 cm off the ground, with airflow', why: 'Correct — the air gap and ventilation cut heat gain.' },
      { id: 'c', text: 'A tarp pegged tight to the ground all around you', why: 'No airflow, and the fabric touches you.' },
      { id: 'd', text: 'Lying directly on the ground in a sealed tent', why: 'No ventilation, and you gain heat from the ground.' },
    ],
    answer: 'b',
    concepts: ['shelter-types'],
    explanation: 'An air gap and ventilation reduce radiant and conductive heat gain.',
  },
  {
    id: 'fa-food-2',
    kind: 'single',
    prompt: 'Which statement about the “universal edibility test” is correct?',
    choices: [
      { id: 'a', text: 'It reliably identifies safe wild plants if done patiently.', why: 'Wrong — toxicologists widely criticise it.' },
      { id: 'b', text: 'It is unreliable: some deadly plants give no early warning.', why: 'Correct.' },
      { id: 'c', text: 'It is safe as long as you only test small amounts.', why: 'Wrong — some deadly plants give no early warning.' },
      { id: 'd', text: 'It is the standard method taught by local plant experts.', why: 'Wrong — experts rely on positive identification.' },
    ],
    answer: 'b',
    concepts: ['priorities'],
    explanation: 'It is widely criticised by toxicologists; some deadly plants give no early warning. Positive identification by a qualified local expert is required.',
  },
  {
    id: 'fa-food-3',
    kind: 'single',
    prompt: 'Why does fishing or trapping often fail as a short-term survival strategy?',
    choices: [
      { id: 'a', text: 'Effort often exceeds the calories gained, and laws restrict it.', why: 'Correct.' },
      { id: 'b', text: 'Fish and small game are not nutritious enough to help.', why: 'They are nutritious; the problem is the effort.' },
      { id: 'c', text: 'You need a fire to cook the catch, which may fail.', why: 'Not the main reason.' },
      { id: 'd', text: 'It works well, but most people simply never try it.', why: 'It often does not pay back the energy spent.' },
    ],
    answer: 'a',
    concepts: ['priorities'],
    explanation: 'Energy economics and legality — plus supervised instruction for any trapping/hunting.',
  },
  {
    id: 'fa-track-1',
    kind: 'single',
    prompt: 'Why can reading animal sign help a lost person?',
    choices: [
      { id: 'a', text: 'Converging game trails often lead to water; sign helps read terrain.', why: 'Correct — tracking as observation and resource-finding.' },
      { id: 'b', text: 'Animal trails usually lead out to roads and settlements.', why: 'No — they lead to animal resources, not people.' },
      { id: 'c', text: 'It mainly lets you hunt animals for food while waiting.', why: 'Not the course’s focus.' },
      { id: 'd', text: 'It rarely helps; animal sign is too hard to interpret.', why: 'It can help you read the landscape.' },
    ],
    answer: 'a',
    concepts: ['integration'],
    explanation: 'Tracking in this course is about ecology, navigation and resources.',
  },
  {
    id: 'fa-track-3',
    kind: 'single',
    prompt: 'You are lost and reach a trail junction. What helps searchers most?',
    choices: [
      { id: 'a', text: 'Leave no trace so you don’t disturb the site.', why: 'Searchers need sign to follow.' },
      { id: 'b', text: 'Leave clear sign such as an arrow or a dated note.', why: 'Correct — it tells searchers direction and time.' },
      { id: 'c', text: 'Stay off soft ground so you leave no footprints.', why: 'Footprints in soft ground are useful sign.' },
      { id: 'd', text: 'Keep moving without stopping, to save daylight.', why: 'Sign at decision points is worth the moment it takes.' },
    ],
    answer: 'b',
    concepts: ['visibility', 'signaling'],
    explanation: 'Searchers value clear sign — arrows, notes, footprints in soft ground — at decision points: it tells them direction and time.',
  },
  {
    id: 'fa-psych-2',
    kind: 'single',
    prompt: 'Which response does NOT help a panicking group member?',
    choices: [
      { id: 'a', text: 'Calm, specific instructions and a small task', why: 'Helps — gives agency.' },
      { id: 'b', text: 'Paced breathing together with them', why: 'Helps — lowers arousal.' },
      { id: 'c', text: 'Arguing with them loudly to snap them out', why: 'Correct — this escalates arousal.' },
      { id: 'd', text: 'Keeping them together with the group', why: 'Helps — separation adds risk.' },
    ],
    answer: 'c',
    concepts: ['stress-control'],
    explanation: 'Lower arousal, give agency, keep the group together.',
  },
  {
    id: 'fa-psych-3',
    kind: 'single',
    prompt: 'Why rehearse emergencies mentally before trips?',
    choices: [
      { id: 'a', text: 'You retrieve a response instead of building one, reducing freezing.', why: 'Correct.' },
      { id: 'b', text: 'It guarantees the right response in a real emergency.', why: 'No guarantee.' },
      { id: 'c', text: 'It can replace physical practice of the same skills.', why: 'It complements it.' },
      { id: 'd', text: 'It mainly benefits professional rescuers, not hikers.', why: 'Everyone benefits.' },
    ],
    answer: 'a',
    concepts: ['freezing'],
    explanation: 'Leach: freezing reflects processing time; rehearsal lets you retrieve a response instead of building one under stress.',
  },
  {
    id: 'fa-risk-1',
    kind: 'single',
    prompt: 'A route has a 1.5 % chance of an incident per hour of exposure. What is the chance of at least one incident over 8 hours?',
    choices: [
      { id: 'a', text: '11.4 %', why: 'Correct — 1 − 0.985⁸ ≈ 11.4 %.' },
      { id: 'b', text: '12.0 %', why: 'Adds 1.5 % × 8 — probabilities do not simply add.' },
      { id: 'c', text: '88.6 %', why: 'That is the chance of no incident (0.985⁸).' },
      { id: 'd', text: '1.5 %', why: 'Ignores the 8 hours of exposure.' },
    ],
    answer: 'a',
    concepts: ['risk'],
    explanation: '1 − 0.985⁸ ≈ 1 − 0.886 = **11.4 %**.',
  },
  {
    id: 'fa-risk-2',
    kind: 'single',
    prompt: 'Which control reduces the **consequence** of getting lost rather than its likelihood?',
    choices: [
      { id: 'a', text: 'Carrying a map and compass', why: 'Reduces likelihood.' },
      { id: 'b', text: 'Leaving a trip plan with an alarm time', why: 'Correct — rescue starts sooner and in the right place.' },
      { id: 'c', text: 'Choosing a well-marked trail', why: 'Reduces likelihood.' },
      { id: 'd', text: 'Starting earlier in the day', why: 'Mostly reduces likelihood.' },
    ],
    answer: 'b',
    concepts: ['trip-plan', 'risk'],
    explanation: 'A trip plan with an alarm time means rescue starts sooner and in the right place; layer controls on both axes.',
  },
]

export const finalLesson: Lesson[] = [
  {
    id: 'final',
    stage: 19,
    order: 13,
    title: 'Final assessment',
    level: 'expert',
    minutes: 60,
    prerequisites: ['cap-1', 'cap-6', 'cap-12'],
    concepts: ['integration'],
    objectives: [
      'Demonstrate **judgment and prioritization** across navigation, physiology, first aid, fire, water, shelter, food, tracking, psychology and risk.',
      'Identify the domains you need to revisit before relying on them in the field.',
      'Plan the **hands-on training** that will turn knowledge into competence.',
    ],
    explanation: [
      {
        type: 'md',
        md: `This assessment tests whether you can **reason** like a survivor, not whether you remember facts. Most questions are short scenarios where several answers sound plausible — the best answer is the one that removes the biggest risk for the least cost, with a bias toward reversible actions.

Your score is broken down by domain. Anything under 80 % points to the stages to revisit; missed questions join your spaced-review queue.`,
      },
      { type: 'sim', id: 'final-assessment' },
      {
        type: 'callout',
        tone: 'warning',
        title: 'What a pass means',
        md: 'A high score means your *decision making* is sound. It does not make you physically competent. Your next steps are on the Skills page: practise every physical skill until you can mark it Practiced, and take a hands-on wilderness first aid course, a navigation course and a bushcraft course.',
      },
    ],
    whyItMatters: 'Unfamiliar emergencies are solved by transferable reasoning. The assessment deliberately mixes domains because real situations do.',
    examples: [
      { type: 'md', md: 'Questions span forest, desert, subarctic, tropical, mountain, coastal and urban settings, and every stage of the course.' },
    ],
    mistakes: [
      'Choosing the most dramatic action instead of the highest-value one.',
      'Ignoring reversibility and daylight.',
      'Treating a good score as proof of physical competence.',
    ],
    exercises: [
      {
        id: 'final-e1',
        title: 'Take the final assessment',
        level: 4,
        safety: 'virtual-only',
        minutes: 60,
        steps: ['Complete the assessment without references.', 'Write down every domain under 80 %.', 'Schedule review of those stages and redo their capstones.'],
        success: ['Overall ≥ 80 % and no domain below 60 %.'],
        skill: 'first-hour',
      },
      {
        id: 'final-e2',
        title: 'Build your training plan',
        level: 3,
        safety: 'home',
        minutes: 45,
        steps: [
          'Open the Skills page and list every physical skill not yet Practiced.',
          'For each, choose where and with whom you will practise it, within its safety class.',
          'Book a hands-on wilderness first aid course (WFA or WAFA) and a navigation course.',
        ],
        success: ['A dated plan for every physical skill.', 'A first aid course booked.'],
        skill: 'decision-loop',
      },
    ],
    simulations: ['final-assessment'],
    quiz: [
      {
        id: 'final-q1',
        kind: 'single',
        prompt: 'What does a high final-assessment score demonstrate?',
        choices: [
          { id: 'a', text: 'Sound decision making and understanding', why: 'Correct.' },
          { id: 'b', text: 'Field competence in every physical skill', why: 'Only real practice demonstrates that.' },
          { id: 'c', text: 'A recognised survival certification', why: 'This course does not certify.' },
          { id: 'd', text: 'That you can skip hands-on first aid training', why: 'No — knowledge does not replace hands-on training.' },
        ],
        answer: 'a',
        concepts: ['integration'],
        explanation: 'Knowledge and judgment are necessary, not sufficient.',
      },
      {
        id: 'final-q2',
        kind: 'single',
        prompt: 'Which next step does NOT help turn this course into real capability?',
        choices: [
          { id: 'a', text: 'A hands-on WFA/WAFA course', why: 'Helps.' },
          { id: 'b', text: 'Logged practice of physical skills within their safety class', why: 'Helps.' },
          { id: 'c', text: 'Local navigation or orienteering events', why: 'Helps.' },
          { id: 'd', text: 'Unsupervised solo testing in extreme conditions', why: 'Correct — escalate gradually and safely instead.' },
        ],
        answer: 'd',
        concepts: ['integration'],
        explanation: 'Train → consolidate → assess, as professional programs do, escalating gradually and safely.',
      },
      {
        id: 'final-q4',
        kind: 'single',
        prompt: 'Which question ends the 12 questions, as the output the others feed?',
        choices: [
          { id: 'a', text: 'Am I in immediate danger?', why: 'That is question 1.' },
          { id: 'b', text: 'Should I stay or move?', why: 'That is question 8.' },
          { id: 'c', text: 'What is my next highest-value action?', why: 'Correct — question 12.' },
          { id: 'd', text: 'What is the biggest risk overnight?', why: 'That is question 11.' },
        ],
        answer: 'c',
        concepts: ['twelve-questions'],
        explanation: 'The 12 questions end with “What is my next highest-value action?” — every other question feeds that one.',
      },
      {
        id: 'final-q3',
        kind: 'single',
        prompt: 'In the decision loop (Observe → Assess → … → Reassess), which step comes right after Assess?',
        choices: [
          { id: 'a', text: 'Plan', why: 'Plan comes after Prioritize.' },
          { id: 'b', text: 'Prioritize', why: 'Correct.' },
          { id: 'c', text: 'Act', why: 'Act comes after Plan.' },
          { id: 'd', text: 'Reassess', why: 'Reassess closes the loop after Act.' },
        ],
        answer: 'b',
        concepts: ['decision-loop'],
        explanation: 'Observe → Assess → Prioritize → Plan → Act → Reassess: the loop that runs through the whole course.',
      },
    ],
    scenario: {
      id: 'final-sc',
      setup: 'You have finished the course and score 85 % overall, but 55 % in first aid.',
      question: 'What is your best next step?',
      choices: [
        { id: 'a', text: 'Plan a remote solo trip to test yourself in real conditions.', why: 'Your weakest domain is the one you would need most if something went wrong alone.' },
        { id: 'b', text: 'Revisit Stage 9, redo capstone 6 and book a hands-on WFA/WAFA course.', why: 'Best: targets the gap with both review and real training before remote trips.' },
        { id: 'c', text: 'Retake the assessment until you pass first aid by memorising answers.', why: 'Memorising answers doesn’t build judgment or hands-on skill.' },
        { id: 'd', text: 'Ignore it; first aid is unlikely to be needed on most trips.', why: 'Injury is among the most common wilderness emergencies.' },
      ],
      best: 'b',
      debrief: 'The assessment exists to find gaps. Close them with review, scenarios and — for first aid especially — hands-on training.',
      concepts: ['integration'],
    },
    summary: [
      'Judgment and prioritization transfer; memorised tricks do not.',
      'Use the domain breakdown to target review.',
      'Knowledge + logged practice + hands-on courses = capability.',
    ],
    furtherReading: ['deep-survival', 'nols-wm', 'freedom-hills'],
    references: ['nols-wm', 'wms-org', 'redcross-wrfa', 'army-atp-3-50-21', 'koester-lpb'],
  },
]
