import type { Lesson, Question } from '../../types'

// Final assessment. Ids are `fa-<domain>-<n>`; the domain drives the per-domain breakdown
// (see sims/stage19/FinalAssessment.tsx). Weighted toward judgment and prioritization.

export const finalQuestions: Question[] = [
  // ---------- Core knowledge ----------
  {
    id: 'fa-know-1',
    kind: 'order',
    prompt: 'Order these threats for a person in cold rain with no immediate danger and no injury, from most to least urgent in the next 3 hours.',
    items: [
      { id: 'wet', text: 'Clothing insulation getting soaked' },
      { id: 'comm', text: 'Nobody knowing your position' },
      { id: 'water', text: 'Having 300 ml of water' },
      { id: 'food', text: 'Having no food' },
    ],
    answer: ['wet', 'comm', 'water', 'food'],
    concepts: ['priorities', 'rule-of-threes'],
    explanation: 'Cold-wet exposure acts in hours; being findable is the next lever; water matters over a day; food over days to weeks.',
  },
  {
    id: 'fa-know-2',
    kind: 'multi',
    prompt: 'Which statements reflect the course’s decision system?',
    choices: [
      { id: 'a', text: 'Reassess after every action; plans are provisional.', why: 'Correct — the loop never stops.' },
      { id: 'b', text: 'Choose actions by risk removed per unit of time, energy and resources.', why: 'Correct.' },
      { id: 'c', text: 'Irreversible actions need stronger evidence than reversible ones.', why: 'Correct.' },
      { id: 'd', text: 'Once you commit to a plan, changing it signals weakness.', why: 'Wrong — adapting to reality is a hallmark of survivors.' },
    ],
    answer: ['a', 'b', 'c'],
    concepts: ['decision-loop', 'reversibility'],
    explanation: 'Observe → Assess → Prioritize → Plan → Act → Reassess, with a bias toward reversible, high-value actions.',
  },
  {
    id: 'fa-know-3',
    kind: 'single',
    prompt: 'Which kit change most improves the outcome of a solo remote trip with no phone coverage?',
    choices: [
      { id: 'a', text: 'A larger knife', why: 'Marginal.' },
      { id: 'b', text: 'A registered PLB or satellite messenger', why: 'Correct — it removes the delay before anyone starts searching.' },
      { id: 'c', text: 'A fishing kit', why: 'Food is rarely limiting.' },
      { id: 'd', text: 'A second identical phone', why: 'Same failure mode — no coverage.' },
    ],
    answer: 'b',
    concepts: ['kit', 'redundancy', 'signaling'],
    explanation: 'Communication independent of cell coverage is the single largest lever for solo remote travel.',
  },
  // ---------- Navigation ----------
  {
    id: 'fa-nav-1',
    kind: 'numeric',
    prompt: 'On a 1:25,000 map, two points are 6.4 cm apart. What is the ground distance in **km**?',
    unit: 'km',
    answer: 1.6,
    tolerance: 0.01,
    concepts: ['integration'],
    explanation: '6.4 cm × 25,000 = 160,000 cm = **1.6 km**.',
  },
  {
    id: 'fa-nav-2',
    kind: 'numeric',
    prompt: 'You walk 2 km on a bearing that is 3° off. Using the 1-in-60 rule (1° ≈ 1 unit off per 60 units travelled), roughly how far off-line are you, in **metres**?',
    unit: 'm',
    answer: 100,
    tolerance: 10,
    concepts: ['integration'],
    explanation: '3/60 × 2,000 m = **100 m** — enough to miss a small target, which is why you aim off toward a linear feature.',
  },
  {
    id: 'fa-nav-3',
    kind: 'single',
    prompt: 'You need to reach a bridge on a river, but it is hidden in forest. What is the most reliable technique?',
    choices: [
      { id: 'a', text: 'Take an exact bearing to the bridge and trust it.', why: 'Small errors mean you won’t know which way to turn when you hit the river.' },
      { id: 'b', text: 'Aim off deliberately to one side, hit the river, then follow it to the bridge.', why: 'Correct — you know which way to turn.' },
      { id: 'c', text: 'Follow animal trails.', why: 'Unreliable.' },
      { id: 'd', text: 'Walk until you hear water.', why: 'Sound is deceptive.' },
    ],
    answer: 'b',
    concepts: ['integration'],
    explanation: 'Aiming off converts a point target into a linear one with a known direction to turn.',
  },
  // ---------- Physiology ----------
  {
    id: 'fa-phys-1',
    kind: 'single',
    prompt: 'Which situation carries the highest hypothermia risk?',
    choices: [
      { id: 'a', text: '−10 °C, calm, dry, dressed in insulated layers and moving', why: 'Well controlled.' },
      { id: 'b', text: '6 °C, rain and 30 km/h wind, soaked cotton, resting', why: 'Correct — wet + wind + low heat production.' },
      { id: 'c', text: '15 °C, sunny, sitting in the shade', why: 'Low risk.' },
      { id: 'd', text: '−5 °C, in a sleeping bag on a foam pad', why: 'Well insulated.' },
    ],
    answer: 'b',
    concepts: ['wet-wind', 'heat-loss'],
    explanation: 'Most hypothermia happens at 0–10 °C when people are wet, in wind and not producing much heat.',
  },
  {
    id: 'fa-phys-2',
    kind: 'numeric',
    prompt: 'Evaporating 1 L of water removes ~2.4 MJ. A 70 kg person stores ~245 kJ per °C. Roughly how many °C of core-equivalent heat does evaporating **200 ml** from wet clothing remove? (one decimal)',
    unit: '°C',
    answer: 2,
    tolerance: 0.1,
    concepts: ['heat-loss'],
    explanation: '0.2 × 2,400 kJ = 480 kJ; 480/245 ≈ **2.0 °C** — why wet clothing in wind is so dangerous.',
  },
  {
    id: 'fa-phys-3',
    kind: 'single',
    prompt: 'A hiker in 35 °C heat becomes confused and stops sweating normally, with a very hot body. What is the key field priority?',
    choices: [
      { id: 'a', text: 'Give salt tablets and continue slowly.', why: 'Wrong — this looks like heat stroke, a life-threatening emergency.' },
      { id: 'b', text: 'Cool aggressively and immediately (e.g., cold-water immersion if available), then evacuate — “cool first, transport second”.', why: 'Correct, per current WMS and ACSM guidance.' },
      { id: 'c', text: 'Let them rest in the sun until they feel better.', why: 'Dangerous.' },
      { id: 'd', text: 'Give large amounts of water only.', why: 'Hydration alone does not treat heat stroke.' },
    ],
    answer: 'b',
    concepts: ['priorities'],
    explanation: 'Altered mental status with high body temperature in heat means heat stroke until proven otherwise: rapid cooling is the treatment.',
  },
  // ---------- First aid ----------
  {
    id: 'fa-aid-1',
    kind: 'order',
    prompt: 'You find an injured climber at the base of a crag. Order your first actions.',
    items: [
      { id: 'scene', text: 'Check the scene for ongoing danger (rockfall)' },
      { id: 'abc', text: 'Primary survey: airway, breathing, circulation / major bleeding' },
      { id: 'help', text: 'Call or signal for help with location and injuries' },
      { id: 'secondary', text: 'Secondary survey: head-to-toe exam, history, vital signs' },
    ],
    answer: ['scene', 'abc', 'help', 'secondary'],
    concepts: ['immediate-danger', 'priorities'],
    explanation: 'Scene safety, then life threats, then help, then the detailed exam. (Take a hands-on WFA/WFR course.)',
  },
  {
    id: 'fa-aid-2',
    kind: 'single',
    prompt: 'A deep thigh wound is spurting blood and firm direct pressure is not controlling it. What does current guidance support?',
    choices: [
      { id: 'a', text: 'Apply a tourniquet high and tight above the wound, note the time, and get help.', why: 'Correct — tourniquets are an early, not last-resort, tool for life-threatening limb bleeding.' },
      { id: 'b', text: 'Elevate the leg and wait.', why: 'Insufficient for arterial bleeding.' },
      { id: 'c', text: 'Remove the dressing to check it repeatedly.', why: 'Disrupts clotting.' },
      { id: 'd', text: 'Clean the wound thoroughly first.', why: 'Bleeding control first.' },
    ],
    answer: 'a',
    concepts: ['priorities'],
    explanation: 'Life-threatening extremity bleeding: direct pressure/packing, and a tourniquet when pressure fails or cannot be maintained.',
  },
  {
    id: 'fa-aid-3',
    kind: 'multi',
    prompt: 'Which snakebite actions are myths that should NOT be done?',
    choices: [
      { id: 'a', text: 'Cutting and sucking the wound', why: 'Myth — harmful.' },
      { id: 'b', text: 'Applying ice or a tourniquet to the bite', why: 'Myth for most snakes; can worsen tissue damage.' },
      { id: 'c', text: 'Keeping the person calm, removing rings, and arranging evacuation', why: 'This is appropriate.' },
      { id: 'd', text: 'Catching the snake to identify it', why: 'Dangerous — a photo from a distance at most.' },
    ],
    answer: ['a', 'b', 'd'],
    concepts: ['priorities'],
    explanation: 'Evacuation to antivenom-capable care is the treatment; local guidance on pressure immobilisation varies by region (e.g., Australia).',
  },
  // ---------- Fire ----------
  {
    id: 'fa-fire-1',
    kind: 'single',
    prompt: 'Your fire keeps dying after the tinder burns out in wet weather. What is the most likely fix?',
    choices: [
      { id: 'a', text: 'More tinder', why: 'Tinder is rarely the bottleneck.' },
      { id: 'b', text: 'More, finer, drier kindling — split sticks and dead twigs from standing trees', why: 'Correct — the transition from tinder to kindling is where wet fires fail.' },
      { id: 'c', text: 'Larger logs', why: 'Would smother it.' },
      { id: 'd', text: 'Blow harder', why: 'Airflow helps only if the fuel can catch.' },
    ],
    answer: 'b',
    concepts: ['fire-structure'],
    explanation: 'Surface-to-volume ratio and dryness decide the tinder→kindling handover.',
  },
  {
    id: 'fa-fire-2',
    kind: 'single',
    prompt: 'Which is the most dangerous way to use fire or stoves for warmth?',
    choices: [
      { id: 'a', text: 'A small fire in front of an open lean-to', why: 'Reasonable with care.' },
      { id: 'b', text: 'A stove running inside a closed snow shelter or tent', why: 'Correct — carbon monoxide can kill silently.' },
      { id: 'c', text: 'Warm water bottles inside a sleeping bag', why: 'Safe and effective.' },
      { id: 'd', text: 'A fire in an existing fire ring', why: 'Appropriate where allowed.' },
    ],
    answer: 'b',
    concepts: ['fire-safety'],
    explanation: 'Combustion in enclosed spaces is a recurring cause of death in winter camping and urban outages.',
  },
  {
    id: 'fa-fire-3',
    kind: 'truefalse',
    prompt: 'If no fire-ban sign is posted at the trailhead, you can assume open fires are legal there.',
    answer: false,
    concepts: ['fire-safety'],
    explanation: 'Rules vary by land manager and season; check the managing agency’s current restrictions.',
  },
  // ---------- Water ----------
  {
    id: 'fa-water-1',
    kind: 'single',
    prompt: 'Stream below a farm and a village; you have a 0.1 µm filter and chlorine dioxide. Best plan?',
    choices: [
      { id: 'a', text: 'Filter only', why: 'Leaves viruses.' },
      { id: 'b', text: 'Chlorine dioxide only, 30 min', why: 'Crypto may survive short contact.' },
      { id: 'c', text: 'Settle/pre-filter, filter, then chlorine dioxide', why: 'Correct — layered methods with non-overlapping gaps.' },
      { id: 'd', text: 'Nothing — it’s flowing', why: 'Flow does not mean safe.' },
    ],
    answer: 'c',
    concepts: ['water-treatment'],
    explanation: 'Filter removes protozoa and bacteria; chemical covers viruses; clarifying helps both.',
  },
  {
    id: 'fa-water-2',
    kind: 'numeric',
    prompt: 'Baseline 2.5 L/day, plus 6 hours of hiking in heat at 1.1 L/h. How many litres should you plan to drink?',
    unit: 'L',
    answer: 9.1,
    tolerance: 0.1,
    concepts: ['water-needs'],
    explanation: '2.5 + 6 × 1.1 = **9.1 L**.',
  },
  {
    id: 'fa-water-3',
    kind: 'single',
    prompt: 'Stranded in desert heat with 3 L of water. Which strategy is best?',
    choices: [
      { id: 'a', text: 'Sip tiny amounts to make it last, keep walking by day.', why: 'Rations water while wasting sweat.' },
      { id: 'b', text: 'Drink to need, rest in shade by day, move (if at all) in the cool hours.', why: 'Correct — ration sweat, not water.' },
      { id: 'c', text: 'Drink it all now.', why: 'Uncontrolled; excess is urinated.' },
      { id: 'd', text: 'Drink urine to save water.', why: 'Myth.' },
    ],
    answer: 'b',
    concepts: ['dehydration', 'water-needs'],
    explanation: 'Reduce losses; water is more useful inside you than in the bottle.',
  },
  // ---------- Shelter ----------
  {
    id: 'fa-shelter-1',
    kind: 'single',
    prompt: 'Calm, clear night forecast at −3 °C. Where do you pitch?',
    choices: [
      { id: 'a', text: 'Valley floor by the stream', why: 'Cold-air pooling.' },
      { id: 'b', text: 'Mid-slope bench under living canopy, clear of dead trees', why: 'Correct.' },
      { id: 'c', text: 'Open ridge top', why: 'Wind and radiation exposure.' },
      { id: 'd', text: 'In a dry gully out of the wind', why: 'Flash-flood and cold-pool risk.' },
    ],
    answer: 'b',
    concepts: ['site-selection'],
    explanation: 'Mid-slope avoids cold pools and wind; canopy reduces radiation to the sky.',
  },
  {
    id: 'fa-shelter-2',
    kind: 'single',
    prompt: 'With limited time, which improvement most reduces overnight heat loss for someone lying on cold ground?',
    choices: [
      { id: 'a', text: 'A higher roof', why: 'More volume, not warmer.' },
      { id: 'b', text: 'A thick, dry bed of insulation underneath', why: 'Correct — conduction to the ground is the biggest sink.' },
      { id: 'c', text: 'Brighter tarp colour', why: 'Visibility, not warmth.' },
      { id: 'd', text: 'Wider doorway', why: 'Worse.' },
    ],
    answer: 'b',
    concepts: ['ground-insulation'],
    explanation: 'Q = kAΔT/d: thickness and dryness of what you lie on dominate.',
  },
  {
    id: 'fa-shelter-3',
    kind: 'truefalse',
    prompt: 'In a hot desert, a shade roof raised 30–50 cm off the ground (with airflow) is usually better than lying under a tarp draped directly over you.',
    answer: true,
    concepts: ['shelter-types'],
    explanation: 'An air gap and ventilation reduce radiant and conductive heat gain.',
  },
  // ---------- Food ----------
  {
    id: 'fa-food-1',
    kind: 'single',
    prompt: 'In a 72-hour survival situation, what is the correct role of food?',
    choices: [
      { id: 'a', text: 'Top priority — hunt and forage from day 1.', why: 'Burns energy and time for little return.' },
      { id: 'b', text: 'Low priority; use carried food to support warmth and morale; don’t spend scarce daylight foraging.', why: 'Correct.' },
      { id: 'c', text: 'Avoid all eating to conserve water.', why: 'Only if water is extremely scarce — digestion does use water.' },
      { id: 'd', text: 'Eat any berries you find.', why: 'Poisoning risk.' },
    ],
    answer: 'b',
    concepts: ['priorities'],
    explanation: 'Food rarely limits short survival, but calories help heat production in the cold.',
  },
  {
    id: 'fa-food-2',
    kind: 'truefalse',
    prompt: 'The “universal edibility test” is a reliable way to identify safe wild plants.',
    answer: false,
    concepts: ['priorities'],
    explanation: 'It is widely criticised by toxicologists; some deadly plants give no early warning. Positive identification by a qualified local expert is required.',
  },
  {
    id: 'fa-food-3',
    kind: 'single',
    prompt: 'Why does fishing or trapping often fail as a short-term survival strategy?',
    choices: [
      { id: 'a', text: 'Energy and time invested often exceed calories returned, and laws often restrict it.', why: 'Correct.' },
      { id: 'b', text: 'Fish are not nutritious.', why: 'They are nutritious.' },
      { id: 'c', text: 'It always works; it is just unpopular.', why: 'No.' },
      { id: 'd', text: 'Because fire is needed.', why: 'Not the main reason.' },
    ],
    answer: 'a',
    concepts: ['priorities'],
    explanation: 'Energy economics and legality — plus supervised instruction for any trapping/hunting.',
  },
  // ---------- Tracking ----------
  {
    id: 'fa-track-1',
    kind: 'single',
    prompt: 'Why can reading animal sign help a lost person?',
    choices: [
      { id: 'a', text: 'Converging game trails often lead to water; sign helps read the landscape.', why: 'Correct — tracking as observation and resource-finding.' },
      { id: 'b', text: 'Animals always lead to roads.', why: 'No.' },
      { id: 'c', text: 'To hunt them.', why: 'Not the course’s focus.' },
      { id: 'd', text: 'It doesn’t.', why: 'It can.' },
    ],
    answer: 'a',
    concepts: ['integration'],
    explanation: 'Tracking in this course is about ecology, navigation and resources.',
  },
  {
    id: 'fa-track-2',
    kind: 'single',
    prompt: 'A clear track in mud has crisp edges and small grains that have not yet fallen in; the morning had rain until 07:00. It is 10:00. The track was most likely made…',
    choices: [
      { id: 'a', text: 'Before the rain', why: 'Rain would have softened the edges and filled detail.' },
      { id: 'b', text: 'After the rain stopped, within the last few hours', why: 'Correct — reasoning from weather events is the core of aging sign.' },
      { id: 'c', text: 'Days ago', why: 'Crisp edges argue against it.' },
      { id: 'd', text: 'Impossible to say anything', why: 'Weather events bracket the time.' },
    ],
    answer: 'b',
    concepts: ['integration'],
    explanation: 'Use known events (rain, frost, dew) as time markers and compare with reference tracks.',
  },
  {
    id: 'fa-track-3',
    kind: 'truefalse',
    prompt: 'Searchers value a lost person leaving clear sign — arrows, notes, footprints in soft ground — at decision points.',
    answer: true,
    concepts: ['visibility', 'signaling'],
    explanation: 'Sign at junctions tells searchers direction and time.',
  },
  // ---------- Psychology ----------
  {
    id: 'fa-psych-1',
    kind: 'single',
    prompt: 'You notice you keep saying “just 10 more minutes” past your turnaround time. What is happening?',
    choices: [
      { id: 'a', text: 'Plan continuation / commitment bias', why: 'Correct.' },
      { id: 'b', text: 'Good persistence', why: 'Not when it overrides a pre-set limit.' },
      { id: 'c', text: 'Hypoglycaemia only', why: 'Could contribute, but the pattern is a bias.' },
      { id: 'd', text: 'Expert halo', why: 'No one is being deferred to.' },
    ],
    answer: 'a',
    concepts: ['human-factors'],
    explanation: 'Name the trap; honour the trigger you set while calm.',
  },
  {
    id: 'fa-psych-2',
    kind: 'multi',
    prompt: 'Which help a panicking group member?',
    choices: [
      { id: 'a', text: 'Calm, specific instructions and a small task', why: 'Yes.' },
      { id: 'b', text: 'Paced breathing together', why: 'Yes.' },
      { id: 'c', text: 'Arguing with them loudly', why: 'Escalates arousal.' },
      { id: 'd', text: 'Keeping them with the group', why: 'Yes — separation adds risk.' },
    ],
    answer: ['a', 'b', 'd'],
    concepts: ['stress-control'],
    explanation: 'Lower arousal, give agency, keep the group together.',
  },
  {
    id: 'fa-psych-3',
    kind: 'single',
    prompt: 'Why rehearse emergencies mentally before trips?',
    choices: [
      { id: 'a', text: 'It lets you retrieve a response instead of building one under stress, reducing freezing.', why: 'Correct.' },
      { id: 'b', text: 'It guarantees success.', why: 'No guarantee.' },
      { id: 'c', text: 'It replaces physical practice.', why: 'It complements it.' },
      { id: 'd', text: 'It is only for professionals.', why: 'Everyone benefits.' },
    ],
    answer: 'a',
    concepts: ['freezing'],
    explanation: 'Leach: freezing reflects processing time; rehearsal shortens it.',
  },
  // ---------- Risk ----------
  {
    id: 'fa-risk-1',
    kind: 'numeric',
    prompt: 'A route has a 1.5 % chance of an incident per hour of exposure. What is the chance (in %) of at least one incident over 8 hours? (one decimal)',
    unit: '%',
    answer: 11.4,
    tolerance: 0.2,
    concepts: ['risk'],
    explanation: '1 − 0.985⁸ ≈ 1 − 0.886 = **11.4 %**.',
  },
  {
    id: 'fa-risk-2',
    kind: 'single',
    prompt: 'Which control reduces the **consequence** of getting lost rather than its likelihood?',
    choices: [
      { id: 'a', text: 'Carrying a map and compass', why: 'Reduces likelihood.' },
      { id: 'b', text: 'Leaving a trip plan with an alarm time', why: 'Correct — rescue starts sooner and in the right place.' },
      { id: 'c', text: 'Choosing a well-marked trail', why: 'Reduces likelihood.' },
      { id: 'd', text: 'Starting earlier', why: 'Mostly reduces likelihood.' },
    ],
    answer: 'b',
    concepts: ['trip-plan', 'risk'],
    explanation: 'Layer controls on both axes.',
  },
  {
    id: 'fa-risk-3',
    kind: 'single',
    prompt: 'A river on your route is fast and above knee depth after rain. Best decision?',
    choices: [
      { id: 'a', text: 'Cross quickly with your pack straps done up.', why: 'Dangerous — pack straps can trap you.' },
      { id: 'b', text: 'Don’t cross; wait for levels to drop or find another route, and update your contacts.', why: 'Correct.' },
      { id: 'c', text: 'Cross holding hands with a stranger.', why: 'Still dangerous.' },
      { id: 'd', text: 'Swim it.', why: 'Very dangerous.' },
    ],
    answer: 'b',
    concepts: ['risk', 'reversibility'],
    explanation: 'Swift-water crossing is a leading cause of backcountry death; waiting is usually the reversible option.',
  },
  // ---------- Scenario decisions ----------
  {
    id: 'fa-scen-1',
    kind: 'single',
    prompt: 'It’s 16:20, sunset 17:40, 4 °C with rain forecast at 19:00. You’re lost but someone knows your route, you have an emergency bag and warm layers, and you just sent your coordinates by SMS. Best next action?',
    choices: [
      { id: 'a', text: 'Walk toward a road you think is 5 km away.', why: 'Irreversible, ends in darkness and rain.' },
      { id: 'b', text: 'Choose a sheltered mid-slope site now, build a thick ground bed, prepare fuel and signals, then reassess.', why: 'Correct.' },
      { id: 'c', text: 'Forage for food before dark.', why: 'Wrong priority.' },
      { id: 'd', text: 'Wait passively under a tree until morning.', why: 'Wastes the daylight you need for protection.' },
    ],
    answer: 'b',
    concepts: ['integration', 'stay-or-move', 'daylight'],
    explanation: 'Communication done, stay decision justified, protection before dark.',
  },
  {
    id: 'fa-scen-2',
    kind: 'single',
    prompt: 'Your partner has a suspected ankle fracture 6 km from the road at 14:00 in good weather. You have phone coverage. Best plan?',
    choices: [
      { id: 'a', text: 'Carry them out yourself immediately.', why: 'High injury risk to both.' },
      { id: 'b', text: 'Call for help with precise location, splint the ankle, insulate and shelter them, monitor, and prepare signals.', why: 'Correct.' },
      { id: 'c', text: 'Leave them and walk out without calling.', why: 'Loses the fastest lever and leaves them alone.' },
      { id: 'd', text: 'Wait to see if it gets better before deciding.', why: 'Delay wastes daylight and rescue time.' },
    ],
    answer: 'b',
    concepts: ['integration', 'phone-use'],
    explanation: 'Communication first, then patient care and protection.',
  },
  {
    id: 'fa-scen-3',
    kind: 'single',
    prompt: 'After a night earthquake you smell gas in your apartment building. First action?',
    choices: [
      { id: 'a', text: 'Light a candle to look for the leak.', why: 'Ignition source.' },
      { id: 'b', text: 'Get everyone out without using switches or flames, shut off gas at the meter if trained and safe, and report it from outside.', why: 'Correct — immediate danger first.' },
      { id: 'c', text: 'Fill the bathtub with water first.', why: 'Good later; not while gas is leaking.' },
      { id: 'd', text: 'Post on social media.', why: 'Not now.' },
    ],
    answer: 'b',
    concepts: ['immediate-danger'],
    explanation: 'Question 1 of 12 — immediate danger — dominates in urban disasters too.',
  },
]

export const finalLesson: Lesson[] = [
  {
    id: 'final',
    stage: 19,
    order: 13,
    title: 'Final assessment',
    level: 'expert',
    minutes: 60,
    prerequisites: ['cap-1', 'cap-6', 'cap-12'],
    concepts: ['integration'],
    objectives: [
      'Demonstrate **judgment and prioritization** across navigation, physiology, first aid, fire, water, shelter, food, tracking, psychology and risk.',
      'Identify the domains you need to revisit before relying on them in the field.',
      'Plan the **hands-on training** that will turn knowledge into competence.',
    ],
    explanation: [
      {
        type: 'md',
        md: `This assessment tests whether you can **reason** like a survivor, not whether you remember facts. Most questions are short scenarios where several answers sound plausible — the best answer is the one that removes the biggest risk for the least cost, with a bias toward reversible actions.

Your score is broken down by domain. Anything under 80 % points to the stages to revisit; missed questions join your spaced-review queue.`,
      },
      { type: 'sim', id: 'final-assessment' },
      {
        type: 'callout',
        tone: 'warning',
        title: 'What a pass means',
        md: 'A high score means your *decision making* is sound. It does not make you physically competent. Your next steps are on the Skills page: practise every physical skill until you can mark it Practiced, and take a hands-on wilderness first aid course, a navigation course and a bushcraft course.',
      },
    ],
    whyItMatters: 'Unfamiliar emergencies are solved by transferable reasoning. The assessment deliberately mixes domains because real situations do.',
    examples: [
      { type: 'md', md: 'Questions span forest, desert, subarctic, tropical, mountain, coastal and urban settings, and every stage of the course.' },
    ],
    mistakes: [
      'Choosing the most dramatic action instead of the highest-value one.',
      'Ignoring reversibility and daylight.',
      'Treating a good score as proof of physical competence.',
    ],
    exercises: [
      {
        id: 'final-e1',
        title: 'Take the final assessment',
        level: 4,
        safety: 'virtual-only',
        minutes: 60,
        steps: ['Complete the assessment without references.', 'Write down every domain under 80 %.', 'Schedule review of those stages and redo their capstones.'],
        success: ['Overall ≥ 80 % and no domain below 60 %.'],
        skill: 'first-hour',
      },
      {
        id: 'final-e2',
        title: 'Build your training plan',
        level: 3,
        safety: 'home',
        minutes: 45,
        steps: [
          'Open the Skills page and list every physical skill not yet Practiced.',
          'For each, choose where and with whom you will practise it, within its safety class.',
          'Book a hands-on wilderness first aid course (WFA or WAFA) and a navigation course.',
        ],
        success: ['A dated plan for every physical skill.', 'A first aid course booked.'],
        skill: 'decision-loop',
      },
    ],
    simulations: ['final-assessment'],
    quiz: [
      {
        id: 'final-q1',
        kind: 'single',
        prompt: 'What does a high final-assessment score demonstrate?',
        choices: [
          { id: 'a', text: 'Sound decision making and understanding', why: 'Correct.' },
          { id: 'b', text: 'Field competence in every skill', why: 'Only real practice demonstrates that.' },
          { id: 'c', text: 'A recognised certification', why: 'This course does not certify.' },
          { id: 'd', text: 'That you can skip first aid training', why: 'No.' },
        ],
        answer: 'a',
        concepts: ['integration'],
        explanation: 'Knowledge and judgment are necessary, not sufficient.',
      },
      {
        id: 'final-q2',
        kind: 'multi',
        prompt: 'Which next steps turn this course into real capability?',
        choices: [
          { id: 'a', text: 'Hands-on WFA/WAFA course', why: 'Yes.' },
          { id: 'b', text: 'Logged practice of physical skills within their safety class', why: 'Yes.' },
          { id: 'c', text: 'Local navigation or orienteering events', why: 'Yes.' },
          { id: 'd', text: 'Unsupervised solo testing in extreme conditions', why: 'No — escalate gradually and safely.' },
        ],
        answer: ['a', 'b', 'c'],
        concepts: ['integration'],
        explanation: 'Train → consolidate → assess, as professional programs do.',
      },
      {
        id: 'final-q3',
        kind: 'order',
        prompt: 'Order the decision loop.',
        items: [
          { id: 'o', text: 'Observe' },
          { id: 'a', text: 'Assess' },
          { id: 'p', text: 'Prioritize' },
          { id: 'pl', text: 'Plan' },
          { id: 'ac', text: 'Act' },
          { id: 'r', text: 'Reassess' },
        ],
        answer: ['o', 'a', 'p', 'pl', 'ac', 'r'],
        concepts: ['decision-loop'],
        explanation: 'The loop that runs through the whole course.',
      },
      {
        id: 'final-q4',
        kind: 'truefalse',
        prompt: 'The 12 questions end with “What is my next highest-value action?”',
        answer: true,
        concepts: ['twelve-questions'],
        explanation: 'Every other question feeds that one.',
      },
    ],
    scenario: {
      id: 'final-sc',
      setup: 'You have finished the course and score 85 % overall, but 55 % in first aid.',
      question: 'What is your best next step?',
      choices: [
        { id: 'a', text: 'Plan a remote solo trip to test yourself.', why: 'Your weakest domain is the one you would need most if something went wrong alone.' },
        { id: 'b', text: 'Revisit Stage 9, redo capstone 6, and book a hands-on WFA/WAFA course before remote trips.', why: 'Best: targets the gap with both review and real training.' },
        { id: 'c', text: 'Retake the assessment until you pass first aid by memorising answers.', why: 'Memorising answers doesn’t build judgment or hands-on skill.' },
        { id: 'd', text: 'Ignore it; first aid is unlikely to be needed.', why: 'Injury is among the most common wilderness emergencies.' },
      ],
      best: 'b',
      debrief: 'The assessment exists to find gaps. Close them with review, scenarios and — for first aid especially — hands-on training.',
      concepts: ['integration'],
    },
    summary: [
      'Judgment and prioritization transfer; memorised tricks do not.',
      'Use the domain breakdown to target review.',
      'Knowledge + logged practice + hands-on courses = capability.',
    ],
    furtherReading: ['deep-survival', 'nols-wm', 'freedom-hills'],
    references: ['nols-wm', 'wms-org', 'redcross-wrfa', 'army-atp-3-50-21', 'koester-lpb'],
  },
]
