import type { Question } from '../../types'

// Stage 17 review: interleaves vehicle strandings with earlier stages — priorities, trip plans,
// heat balance, hypothermia, water, signaling, CO from Stage 16, moving water from Stage 12.
export const stage17Review: Question[] = [
  {
    id: 's17-rev-5',
    kind: 'single',
    prompt: 'Two occupants of a snowbound car have headaches and nausea after hours of idling; one is hard to wake. What is the first action?',
    choices: [
      { id: 'a', text: 'Give them painkillers and let them rest until they feel better', why: 'CO poisoning kills during sleep.' },
      { id: 'b', text: 'Engine off, doors open for fresh air, and call or signal for medical help', why: 'Correct — remove the source and get them breathing fresh air.' },
      { id: 'c', text: 'Turn up the heater so they stay warm while you wait', why: 'More engine running, more CO.' },
      { id: 'd', text: 'Crack a window a little and keep the engine running', why: 'Not enough if the tailpipe is blocked.' },
    ],
    answer: 'b',
    concepts: ['carbon-monoxide', 'vehicle-exhaust-co', 'immediate-danger'],
    explanation: 'Stage 1: deal with the immediate danger first. CO is it — and clear the tailpipe before any further engine use.',
  },
  {
    id: 's17-rev-3',
    kind: 'single',
    prompt: 'Desert, 13:00, 42 °C, car bogged, search expected tomorrow morning. You have 12 L of water for two people. Which statement is correct?',
    choices: [
      { id: 'a', text: 'Drink as little as possible so the 12 L lasts several days', why: 'Rationing water increases dehydration and core temperature; the search is coming tomorrow.' },
      { id: 'b', text: 'Drink to need, rest in raised shade through the heat, do work at dusk and dawn', why: 'Correct — ration sweat, not water.' },
      { id: 'c', text: 'Sit in the car with the windows closed to keep the hot wind out', why: 'The cabin becomes far hotter than the air.' },
      { id: 'd', text: 'Walk to find help now while you are fresh', why: 'Midday walking in 42 °C costs litres per hour and removes you from the search target.' },
    ],
    answer: 'b',
    concepts: ['water-budget', 'sweat-rate', 'hot-car-cabin', 'stay-with-vehicle'],
    explanation: 'Stage 4 and Stage 8: water is for the body; losses are what you control.',
  },
  {
    id: 's17-rev-2',
    kind: 'single',
    prompt: 'Stranded in a snowbound car at night. Which of these is NOT safe?',
    choices: [
      { id: 'a', text: 'Clearing the tailpipe before each engine run', why: 'Safe — the key CO rule.' },
      { id: 'b', text: 'Running the engine ~10 minutes each hour with a downwind window cracked', why: 'Safe — heat while saving fuel and limiting CO.' },
      { id: 'c', text: 'Using a camping stove inside the car for warmth', why: 'Correct — CO and fire in a tiny space (Stage 16 logic).' },
      { id: 'd', text: 'Taking turns sleeping so someone stays on watch', why: 'Safe — someone watches the exhaust, the others and the road.' },
    ],
    answer: 'c',
    concepts: ['vehicle-exhaust-co', 'carbon-monoxide', 'vehicle-insulation'],
    explanation: 'Insulate first (sleeping bag on, blanket underneath, windows covered), heat briefly with a clear exhaust, and never burn fuel inside the cabin.',
  },
  {
    id: 's17-rev-1',
    kind: 'single',
    prompt: 'Which single preparation most increases the chance that someone comes for you if your car breaks down on a remote road with no coverage?',
    choices: [
      { id: 'a', text: 'A larger, better-stocked first-aid kit in the boot', why: 'Useful, but it does not start a search.' },
      { id: 'b', text: 'A trip plan with route and alarm time, held by someone', why: 'Correct — with the vehicle details and a person who will act, it triggers a search along the right road.' },
      { id: 'c', text: 'A second phone, kept charged as a backup', why: 'Two phones without coverage are still silent.' },
      { id: 'd', text: 'Enough snacks and food to last three days', why: 'Food matters least in short strandings.' },
    ],
    answer: 'b',
    concepts: ['trip-plan', 'stay-with-vehicle'],
    explanation: 'Stage 1: a trip plan converts “missing” into “searched for”. A beacon is the other way to start a rescue.',
  },
  {
    id: 's17-rev-10',
    kind: 'single',
    prompt: 'A dip in a desert road is covered by fast, muddy water after a distant thunderstorm. The other side looks shallow. What is best?',
    choices: [
      { id: 'a', text: 'Drive through slowly in a low gear, keeping the revs up', why: 'Depth and road damage are unknown; moving water can float a car.' },
      { id: 'b', text: 'Wait on high ground or take another route until it passes', why: 'Correct — flash floods in washes often pass within hours.' },
      { id: 'c', text: 'Wade across first to test the depth and the current', why: 'Moving water can knock a person down at shin-to-knee depth.' },
      { id: 'd', text: 'Park in the dip and wait there for the water to drop', why: 'The worst place — the next surge comes down the wash.' },
    ],
    answer: 'b',
    concepts: ['flash-flood', 'moving-water-force', 'vehicle-roadside-safety'],
    explanation: 'Stage 12 again: turn around, don’t drown — flash floods in washes often pass within hours, and never wait in a wash.',
  },
  {
    id: 's17-rev-8',
    kind: 'single',
    prompt: 'A navigation app directs you onto a rutted track in forest country as night approaches. Which Stage 1 principle most directly applies?',
    choices: [
      { id: 'a', text: 'Prefer reversible actions while they are still easy', why: 'Correct — reversibility and daylight budgeting: turn back on the known road.' },
      { id: 'b', text: 'The rule of threes for survival time limits', why: 'Not the key idea here.' },
      { id: 'c', text: 'Food is the lowest priority in a short emergency', why: 'True but irrelevant to the choice.' },
      { id: 'd', text: 'Fire first, for warmth and for signalling', why: 'Not relevant to a driving decision.' },
    ],
    answer: 'a',
    concepts: ['reversibility', 'vehicle-nav-failure', 'daylight'],
    explanation: 'Backtracking on a known road is cheap; getting stuck on an unknown track at night is not.',
  },
  {
    id: 's17-rev-9',
    kind: 'single',
    prompt: 'Your car is stuck in snow on a closed rural road at −20 °C with wind. Which of these is NOT a sign of developing hypothermia in your passenger (Stage 8)?',
    choices: [
      { id: 'a', text: 'Intense shivering and fumbling hands', why: 'It is a sign — mild hypothermia.' },
      { id: 'b', text: 'Slurred speech and poor decisions', why: 'It is a sign.' },
      { id: 'c', text: 'Shivering that stops as they become drowsy', why: 'It is a sign — worsening hypothermia, not recovery.' },
      { id: 'd', text: 'Flushed, sweaty skin on the face and body', why: 'Correct — not typical of hypothermia.' },
    ],
    answer: 'd',
    concepts: ['hypothermia', 'vehicle-insulation'],
    explanation: 'Shivering, fumbling, slurred speech and drowsiness as shivering stops all signal hypothermia. Insulate from below and around, protect from wind, warm sweet drinks if fully alert, handle gently, get help (WMS).',
  },
  {
    id: 's17-rev-7',
    kind: 'single',
    prompt: 'You come across a single-car crash on a rural road at dusk. Which sequence is right?',
    choices: [
      { id: 'a', text: 'Park safely with hazards and hi-vis on, check for dangers, call, then check the occupants', why: 'Correct — scene safety, then help on the way, then care.' },
      { id: 'b', text: 'Park safely with hazards and hi-vis on, check the occupants, check for dangers, then call', why: 'Checking for traffic, fuel leaks and fire comes before you approach the occupants.' },
      { id: 'c', text: 'Check the occupants, park safely with hazards and hi-vis on, call, then check for dangers', why: 'Rushing in before making your own position safe risks a second casualty: you.' },
      { id: 'd', text: 'Park safely with hazards and hi-vis on, call, check the occupants, then check for dangers', why: 'Dangers such as traffic, fuel leaks or fire must be checked before you start care.' },
    ],
    answer: 'a',
    concepts: ['vehicle-roadside-safety', 'scene-safety', 'bleeding-control'],
    explanation: 'Scene safety first (Stage 9): park off the road behind the scene, then check for traffic, fuel leaks and fire; call with the location; then check the occupants and control life-threatening bleeding. A first-aid course turns this into skill.',
  },
  {
    id: 's17-rev-6',
    kind: 'single',
    prompt: 'You have just activated a PLB beside your broken-down car. What should you do next?',
    choices: [
      { id: 'a', text: 'Walk toward the nearest road so rescuers reach you faster', why: 'Rescuers go to the transmitted position; moving makes you harder to find.' },
      { id: 'b', text: 'Stay with the beacon and the vehicle and wait for rescuers', why: 'Correct.' },
      { id: 'c', text: 'Carry the beacon to the nearest hilltop and wait there', why: 'Leaving the vehicle makes you harder to find; stay where the position was sent.' },
      { id: 'd', text: 'Leave the beacon at the car and walk out to meet them', why: 'You separate yourself from the position rescuers will go to.' },
    ],
    answer: 'b',
    concepts: ['vehicle-signaling', 'stay-with-vehicle', 'signaling'],
    explanation: 'Stay with the beacon and the vehicle; rescuers go to the transmitted position, and moving makes you harder to find.',
  },
  {
    id: 's17-rev-4',
    kind: 'single',
    prompt: 'A 3-person family plans a desert drive with a 2-day stranding margin on top of a 1-day trip, at 5 L per person per day. How much water should they carry?',
    choices: [
      { id: 'a', text: '45 L', why: 'Correct — 3 people × 3 days × 5 L.' },
      { id: 'b', text: '30 L', why: 'This counts only the 2-day margin and forgets the trip day.' },
      { id: 'c', text: '15 L', why: 'This forgets to multiply by the three people.' },
      { id: 'd', text: '10 L', why: 'This counts only the margin, for one person.' },
    ],
    answer: 'a',
    concepts: ['water-budget', 'vehicle-kit'],
    explanation: '$3 \\times (1 + 2) \\times 5 = 45$ L — 45 kg, easy in a car and impossible on foot.',
  },
]
