import type { Question } from '../../types'

// Stage 17 review: interleaves vehicle strandings with earlier stages — priorities, trip plans,
// heat balance, hypothermia, water, signaling, CO from Stage 16, moving water from Stage 12.
export const stage17Review: Question[] = [
  {
    id: 's17-rev-1',
    kind: 'single',
    prompt: 'Which single preparation most increases the chance that someone comes for you if your car breaks down on a remote road with no coverage?',
    choices: [
      { id: 'a', text: 'A larger first-aid kit', why: 'Useful, but it does not start a search.' },
      { id: 'b', text: 'A trip plan with route, vehicle and alarm time, held by someone who will act', why: 'Correct — it is what triggers a search along the right road.' },
      { id: 'c', text: 'A second phone', why: 'Two phones without coverage are still silent.' },
      { id: 'd', text: 'Snacks for three days', why: 'Food matters least in short strandings.' },
    ],
    answer: 'b',
    concepts: ['trip-plan', 'stay-with-vehicle'],
    explanation: 'Stage 1: a trip plan converts “missing” into “searched for”. A beacon is the other way to start a rescue.',
  },
  {
    id: 's17-rev-2',
    kind: 'multi',
    prompt: 'Stranded in a snowbound car at night. Which actions are both safe and effective?',
    choices: [
      { id: 'a', text: 'Clearing the tailpipe before each engine run', why: 'Yes — the key CO rule.' },
      { id: 'b', text: 'Running the engine ~10 minutes each hour with a downwind window cracked', why: 'Yes — heat while saving fuel and limiting CO.' },
      { id: 'c', text: 'Using a camping stove inside the car for warmth', why: 'No — CO and fire in a tiny space (Stage 16 logic).' },
      { id: 'd', text: 'Sleeping bag on, blanket underneath, windows covered', why: 'Yes — insulation first.' },
      { id: 'e', text: 'Taking turns sleeping', why: 'Yes — someone watches the exhaust, the others and the road.' },
    ],
    answer: ['a', 'b', 'd', 'e'],
    concepts: ['vehicle-exhaust-co', 'carbon-monoxide', 'vehicle-insulation'],
    explanation: 'Insulate, heat briefly with a clear exhaust, and never burn fuel inside the cabin.',
  },
  {
    id: 's17-rev-3',
    kind: 'single',
    prompt: 'Desert, 13:00, 42 °C, car bogged, search expected tomorrow morning. You have 12 L of water for two people. Which statement is correct?',
    choices: [
      { id: 'a', text: 'Drink as little as possible so the 12 L lasts several days', why: 'Rationing water increases dehydration and core temperature; the search is coming tomorrow.' },
      { id: 'b', text: 'Drink to need, rest in raised shade through the heat, do work at dusk and dawn', why: 'Correct — ration sweat, not water.' },
      { id: 'c', text: 'Sit in the car with the windows closed to keep the hot wind out', why: 'The cabin becomes far hotter than the air.' },
      { id: 'd', text: 'Walk to find help now while you are fresh', why: 'Midday walking in 42 °C costs litres per hour and removes you from the search target.' },
    ],
    answer: 'b',
    concepts: ['water-budget', 'sweat-rate', 'hot-car-cabin', 'stay-with-vehicle'],
    explanation: 'Stage 4 and Stage 8: water is for the body; losses are what you control.',
  },
  {
    id: 's17-rev-4',
    kind: 'numeric',
    prompt: 'A 3-person family plans a desert drive with a 2-day stranding margin on top of a 1-day trip, at 5 L per person per day. How many litres should they carry?',
    unit: 'L',
    answer: 45,
    tolerance: 0,
    concepts: ['water-budget', 'vehicle-kit'],
    explanation: '$3 \\times (1 + 2) \\times 5 = 45$ L — 45 kg, easy in a car and impossible on foot.',
  },
  {
    id: 's17-rev-5',
    kind: 'single',
    prompt: 'Two occupants of a snowbound car have headaches and nausea after hours of idling; one is hard to wake. What is the first action?',
    choices: [
      { id: 'a', text: 'Give painkillers and let them rest', why: 'CO poisoning kills during sleep.' },
      { id: 'b', text: 'Engine off, doors open for fresh air, get them breathing fresh air and call or signal for medical help; clear the tailpipe before any further engine use', why: 'Correct.' },
      { id: 'c', text: 'Turn up the heater', why: 'More engine running, more CO.' },
      { id: 'd', text: 'Crack a window and continue', why: 'Not enough if the tailpipe is blocked.' },
    ],
    answer: 'b',
    concepts: ['carbon-monoxide', 'vehicle-exhaust-co', 'immediate-danger'],
    explanation: 'Stage 1: deal with the immediate danger first. CO is it.',
  },
  {
    id: 's17-rev-6',
    kind: 'truefalse',
    prompt: 'True or false: once you have activated a PLB, you should walk toward the nearest road so rescuers reach you faster.',
    answer: false,
    concepts: ['vehicle-signaling', 'stay-with-vehicle', 'signaling'],
    explanation: 'False. Stay with the beacon and the vehicle; rescuers go to the transmitted position, and moving makes you harder to find.',
  },
  {
    id: 's17-rev-7',
    kind: 'order',
    prompt: 'You come across a single-car crash on a rural road at dusk. Order your actions.',
    items: [
      { id: 'park', text: 'Park safely off the road behind the scene, hazards on, hi-vis on' },
      { id: 'hazard', text: 'Check for dangers: traffic, fuel leak, fire' },
      { id: 'call', text: 'Call the emergency number with the location' },
      { id: 'care', text: 'Check the occupants; control life-threatening bleeding' },
    ],
    answer: ['park', 'hazard', 'call', 'care'],
    concepts: ['vehicle-roadside-safety', 'scene-safety', 'bleeding-control'],
    explanation: 'Scene safety first (Stage 9), then help on the way, then care. A first-aid course turns this into skill.',
  },
  {
    id: 's17-rev-8',
    kind: 'single',
    prompt: 'A navigation app directs you onto a rutted track in forest country as night approaches. Which Stage 1 principle most directly applies?',
    choices: [
      { id: 'a', text: 'Prefer reversible actions: turn back on the known road while it is still easy', why: 'Correct — reversibility and daylight budgeting.' },
      { id: 'b', text: 'The rule of threes', why: 'Not the key idea here.' },
      { id: 'c', text: 'Food is the lowest priority', why: 'True but irrelevant to the choice.' },
      { id: 'd', text: 'Fire first', why: 'Not relevant to a driving decision.' },
    ],
    answer: 'a',
    concepts: ['reversibility', 'vehicle-nav-failure', 'daylight'],
    explanation: 'Backtracking on a known road is cheap; getting stuck on an unknown track at night is not.',
  },
  {
    id: 's17-rev-9',
    kind: 'multi',
    prompt: 'Your car is stuck in snow on a closed rural road at −20 °C with wind. Which are signs of developing hypothermia in your passenger (Stage 8)?',
    choices: [
      { id: 'a', text: 'Intense shivering and fumbling hands', why: 'Yes — mild hypothermia.' },
      { id: 'b', text: 'Slurred speech and poor decisions', why: 'Yes.' },
      { id: 'c', text: 'Shivering that stops while they become drowsy', why: 'Yes — a sign of worsening hypothermia, not recovery.' },
      { id: 'd', text: 'Flushed, sweaty skin', why: 'Not typical of hypothermia.' },
    ],
    answer: ['a', 'b', 'c'],
    concepts: ['hypothermia', 'vehicle-insulation'],
    explanation: 'Insulate from below and around, protect from wind, warm sweet drinks if fully alert, handle gently, get help (WMS).',
  },
  {
    id: 's17-rev-10',
    kind: 'single',
    prompt: 'A dip in a desert road is covered by fast, muddy water after a distant thunderstorm. The other side looks shallow. What is best?',
    choices: [
      { id: 'a', text: 'Drive through in a low gear', why: 'Depth and road damage are unknown; moving water can float a car.' },
      { id: 'b', text: 'Wait on high ground or take another route; flash floods in washes often pass within hours', why: 'Correct.' },
      { id: 'c', text: 'Wade across first to test it', why: 'Moving water can knock a person down at shin-to-knee depth.' },
      { id: 'd', text: 'Park in the dip to wait', why: 'The worst place — the next surge comes down the wash.' },
    ],
    answer: 'b',
    concepts: ['flash-flood', 'moving-water-force', 'vehicle-roadside-safety'],
    explanation: 'Stage 12 again: turn around, don’t drown — and never wait in a wash.',
  },
]
