import type { Question } from '../../types'

// Stage 13 review: interleaves rope physics and rope-safety judgement with earlier stages —
// capstan friction and lashings (7), shelter wind loads (5), slope angle and water crossings (12),
// hypothermia (8), scene safety and evacuation (9), daylight, redundancy and decisions (1).
export const stage13Review: Question[] = [
  {
    id: 's13-rev-1',
    kind: 'single',
    prompt: 'A river is too deep and fast to wade safely. A companion suggests stringing a rope across and tying each person to it with a loop round the waist. What is the main danger?',
    choices: [
      { id: 'a', text: 'The rope might be too short', why: 'Length is not the core problem.' },
      { id: 'b', text: 'Current acting on a person held by a rope can pin them under water with great force; a tied-on person may be unable to escape', why: 'Correct — moving water plus a fixed rope is a classic drowning trap.' },
      { id: 'c', text: 'Wet nylon loses a little strength', why: 'True but minor compared with the pinning hazard.' },
      { id: 'd', text: 'There is no danger if the knot is good', why: 'The knot is not what drowns people here.' },
    ],
    answer: 'b',
    concepts: ['water-crossing', 'moving-water-force', 'rescue-limits'],
    explanation: 'Stage 12’s rule stands: if it is too deep or fast to wade, do not cross. Rope work in moving water is a specialised swiftwater course.',
  },
  {
    id: 's13-rev-2',
    kind: 'numeric',
    prompt: 'A cord wraps one full turn (2π rad) round a smooth post with μ = 0.2. How many times the holding force can the load be? (capstan: $e^{\\mu\\theta}$; one decimal)',
    unit: '×',
    answer: 3.5,
    tolerance: 0.1,
    concepts: ['capstan-friction', 'friction-losses'],
    explanation: '$e^{0.2 \\times 2\\pi} = e^{1.26} \\approx 3.5$. The same exponential that makes hitches hold makes carabiners and edges waste haul force.',
  },
  {
    id: 's13-rev-3',
    kind: 'single',
    prompt: 'A tarp ridgeline is pulled so tight it barely sags. A storm is coming. Why is that a problem?',
    choices: [
      { id: 'a', text: 'A flat line multiplies the sideways wind load into very high tension in the line and at both trees', why: 'Correct — the vector-angle rule: $T = W/(2\\sin\\alpha)$ grows as sag $\\alpha$ shrinks.' },
      { id: 'b', text: 'Tight lines collect more rain', why: 'Not the main issue.' },
      { id: 'c', text: 'It is not a problem: tight lines are strongest', why: 'Myth — tighter means more tension, not more strength.' },
      { id: 'd', text: 'The tarp will be too low', why: 'Height is separate from line tension.' },
    ],
    answer: 'a',
    concepts: ['vector-angles', 'wind-loading'],
    explanation: 'Stage 5 wind loads plus this stage’s angles: leave some sag, and let a trucker’s hitch re-tension when needed.',
  },
  {
    id: 's13-rev-4',
    kind: 'multi',
    prompt: 'Which situations are **formal-training-only** uses of rope?',
    choices: [
      { id: 'a', text: 'Lowering an injured walker down a steep slope in a litter', why: 'Yes — technical rescue.' },
      { id: 'b', text: 'Tensioning a tarp ridgeline with a trucker’s hitch', why: 'No — camp rigging you can practise.' },
      { id: 'c', text: 'Descending a canyon drop on a rope', why: 'Yes — rappelling.' },
      { id: 'd', text: 'Tying a tripod lashing for a pot hanger', why: 'No — a Stage 7 camp skill.' },
      { id: 'e', text: 'Holding the rope for a friend climbing a boulder', why: 'Yes — belaying.' },
    ],
    answer: ['a', 'c', 'e'],
    concepts: ['training-scope', 'rescue-limits', 'lashings'],
    explanation: 'The line runs between gear and people: if the rope could hold a person, it needs formal training and certified equipment.',
  },
  {
    id: 's13-rev-5',
    kind: 'single',
    prompt: 'On a descent you reach a 35° slope of hard, icy snow above rocks. You have no crampons or ice axe and no training in their use. The alternative route adds 2 hours; sunset is in 4 hours. What do you do?',
    choices: [
      { id: 'a', text: 'Cross carefully, kicking steps', why: 'On hard snow a slip accelerates quickly; with rocks below, a slip becomes a serious fall.' },
      { id: 'b', text: 'Rope the group together so others can hold a slip', why: 'Untrained roped groups get pulled off together.' },
      { id: 'c', text: 'Take the longer route — it fits the daylight budget', why: 'Correct: the consequence test fails here, and the alternative is reversible and fits the daylight.' },
      { id: 'd', text: 'Wait for the snow to soften in the afternoon sun', why: 'Possibly later, but the snow may stay hard and it burns daylight; the safe route is available now.' },
    ],
    answer: 'c',
    concepts: ['terrain-classes', 'slope-angle', 'daylight', 'go-no-go'],
    explanation: 'Slope angle (Stage 12), terrain consequence (this stage) and the daylight budget (Stage 1) all point the same way.',
  },
  {
    id: 's13-rev-6',
    kind: 'truefalse',
    prompt: 'A backup that shares the same anchor, rope and knot as the main system provides true redundancy.',
    answer: false,
    concepts: ['anchor-principles', 'redundancy'],
    explanation: 'Redundancy (Stage 1 kit design, and here) means independent components: if everything goes through one point, that point is still a single point of failure.',
  },
  {
    id: 's13-rev-7',
    kind: 'order',
    prompt: 'A friend has slipped into a steep gully and is lying injured on a snow patch 20 m below you at dusk. Order your actions.',
    items: [
      { id: 'safe', text: 'Stop; make sure you and others are on safe ground; watch for rockfall' },
      { id: 'call', text: 'Call for help / activate PLB with location and injuries' },
      { id: 'talk', text: 'Talk to them: stay still, keep warm, report symptoms' },
      { id: 'warm', text: 'If you can reach safely by an easy route, bring insulation and first aid; otherwise prepare signals and light for rescuers' },
    ],
    answer: ['safe', 'call', 'talk', 'warm'],
    concepts: ['rescue-hierarchy', 'scene-safety', 'hypothermia', 'signaling'],
    explanation: 'The rescue ladder: no second casualty, call early, then care without rope — and protect against cold on the snow (Stage 8).',
  },
  {
    id: 's13-rev-8',
    kind: 'numeric',
    prompt: 'A 60 kg load hangs from two anchor legs 90° apart. What is the force in each leg, in newtons? (g = 9.81 m/s²; nearest 10 N)',
    unit: 'N',
    answer: 416,
    tolerance: 10,
    concepts: ['vector-angles'],
    explanation: '$W = 589$ N; $T = 589/(2\\cos 45°) = 589/1.414 \\approx 416$ N.',
  },
  {
    id: 's13-rev-9',
    kind: 'single',
    prompt: 'A mountain-rescue team arrives to evacuate a walker with a suspected ankle fracture from steep ground. They choose to lower the stretcher down a gully instead of raising it to the ridge path. Why is lowering often preferred?',
    choices: [
      { id: 'a', text: 'Gravity does the work; friction helps control speed; fewer people and lower anchor forces are needed', why: 'Correct.' },
      { id: 'b', text: 'Lowering needs no anchor', why: 'It does need anchors — but they carry less than a raise.' },
      { id: 'c', text: 'Raising is illegal', why: 'No.' },
      { id: 'd', text: 'Stretchers cannot be raised', why: 'They can; it is just harder and slower.' },
    ],
    answer: 'a',
    concepts: ['mechanical-advantage', 'friction-losses', 'evacuation'],
    explanation: 'Friction is the enemy of hauling and the friend of lowering. The evacuation route decision (Stage 9) is made with the terrain, the team and the patient.',
  },
  {
    id: 's13-rev-10',
    kind: 'multi',
    prompt: 'Which of these are myths?',
    choices: [
      { id: 'a', text: '“Two anchor points always halve the load.”', why: 'Myth — past 120° each leg carries more than the load.' },
      { id: 'b', text: '“Peak fall force depends on the fall factor, not the fall length.”', why: 'Fact.' },
      { id: 'c', text: '“A reef knot is a good bend for load-bearing lines.”', why: 'Myth — it capsizes.' },
      { id: 'd', text: '“More mechanical advantage is always safer.”', why: 'Myth — over-powered systems overload snagged loads and anchors.' },
      { id: 'e', text: '“Paracord is fine for body weight if doubled.”', why: 'Myth — utility cord is not life-safety rope.' },
    ],
    answer: ['a', 'c', 'd', 'e'],
    concepts: ['vector-angles', 'knot-families', 'mechanical-advantage', 'rope-types', 'fall-factor'],
    explanation: 'Each myth sounds like common sense; the physics says otherwise.',
  },
]
