import type { Question } from '../../types'

// Stage 13 review: interleaves rope physics and rope-safety judgement with earlier stages —
// capstan friction and lashings (7), shelter wind loads (5), slope angle and water crossings (12),
// hypothermia (8), scene safety and evacuation (9), daylight, redundancy and decisions (1).
export const stage13Review: Question[] = [
  {
    id: 's13-rev-1',
    kind: 'single',
    prompt: 'A river is too deep and fast to wade safely. A companion suggests stringing a rope across and tying each person to it with a loop round the waist. What is the main danger?',
    choices: [
      { id: 'a', text: 'The rope may be too short to span the river once tied off at both ends', why: 'Length is not the core problem.' },
      { id: 'b', text: 'Current on a roped person can pin them under water, and a tied-on person may not escape', why: 'Correct — moving water plus a fixed rope is a classic drowning trap.' },
      { id: 'c', text: 'Wet nylon loses some strength, so the rope may snap mid-crossing', why: 'Wet nylon does lose a little strength, but that is minor compared with the pinning hazard.' },
      { id: 'd', text: 'There is little danger as long as every waist knot is tied well', why: 'The knot is not what drowns people here.' },
    ],
    answer: 'b',
    concepts: ['water-crossing', 'moving-water-force', 'rescue-limits'],
    explanation: 'Stage 12’s rule stands: if it is too deep or fast to wade, do not cross. Rope work in moving water is a specialised swiftwater course.',
  },
  {
    id: 's13-rev-5',
    kind: 'single',
    prompt: 'On a descent you reach a 35° slope of hard, icy snow above rocks. You have no crampons or ice axe and no training in their use. The alternative route adds 2 hours; sunset is in 4 hours. What do you do?',
    choices: [
      { id: 'a', text: 'Cross carefully, kicking steps', why: 'On hard snow a slip accelerates quickly; with rocks below, a slip becomes a serious fall.' },
      { id: 'b', text: 'Rope the group together so others can hold a slip', why: 'Untrained roped groups get pulled off together.' },
      { id: 'c', text: 'Take the longer route — it fits the daylight budget', why: 'Correct: the consequence test fails here, and the alternative is reversible and fits the daylight.' },
      { id: 'd', text: 'Wait for the snow to soften in the afternoon sun', why: 'Possibly later, but the snow may stay hard and it burns daylight; the safe route is available now.' },
    ],
    answer: 'c',
    concepts: ['terrain-classes', 'slope-angle', 'daylight', 'go-no-go'],
    explanation: 'Slope angle (Stage 12), terrain consequence (this stage) and the daylight budget (Stage 1) all point the same way.',
  },
  {
    id: 's13-rev-7',
    kind: 'single',
    prompt: 'A friend has slipped into a steep gully and is lying injured on a snow patch 20 m below you at dusk. Which order of actions is best?',
    choices: [
      { id: 'a', text: 'Get safe → call/PLB → talk to them → bring warmth or prepare signals', why: 'Correct — no second casualty, call early with location and injuries, then care without rope.' },
      { id: 'b', text: 'Call/PLB → get safe → talk to them → bring warmth or prepare signals', why: 'Stop and make sure you and others are on safe ground (watch for rockfall) before anything else.' },
      { id: 'c', text: 'Get safe → talk to them → bring warmth or prepare signals → call/PLB', why: 'Call early: rescuers need time, and dusk is already falling.' },
      { id: 'd', text: 'Talk to them → get safe → call/PLB → bring warmth or prepare signals', why: 'Your own safety comes first; a second casualty helps no one.' },
    ],
    answer: 'a',
    concepts: ['rescue-hierarchy', 'scene-safety', 'hypothermia', 'signaling'],
    explanation: 'The rescue ladder: no second casualty, call early, then care without rope — reach them only by an easy, safe route, and protect against cold on the snow (Stage 8).',
  },
  {
    id: 's13-rev-3',
    kind: 'single',
    prompt: 'A tarp ridgeline is pulled so tight it barely sags. A storm is coming. Why is that a problem?',
    choices: [
      { id: 'a', text: 'A flat line turns the wind load into very high tension in the line and both trees', why: 'Correct — the vector-angle rule: $T = W/(2\\sin\\alpha)$ grows as sag $\\alpha$ shrinks.' },
      { id: 'b', text: 'A drum-tight tarp collects more rain, which overloads the fabric', why: 'Not the main issue.' },
      { id: 'c', text: 'It is not a problem, because a tight line is the strongest set-up', why: 'Myth — tighter means more tension, not more strength.' },
      { id: 'd', text: 'The tarp will sit too low to shed the wind once the storm arrives', why: 'Height is separate from line tension.' },
    ],
    answer: 'a',
    concepts: ['vector-angles', 'wind-loading'],
    explanation: 'Stage 5 wind loads plus this stage’s angles: leave some sag, and let a trucker’s hitch re-tension when needed.',
  },
  {
    id: 's13-rev-9',
    kind: 'single',
    prompt: 'A mountain-rescue team arrives to evacuate a walker with a suspected ankle fracture from steep ground. They choose to lower the stretcher down a gully instead of raising it to the ridge path. Why is lowering often preferred?',
    choices: [
      { id: 'a', text: 'Gravity does the work, friction controls speed, and anchor forces are lower', why: 'Correct — and fewer people are needed than for a raise.' },
      { id: 'b', text: 'Lowering needs no anchor, so the team can set it up much faster', why: 'It does need anchors — but they carry less than a raise.' },
      { id: 'c', text: 'Raising a stretcher is against rescue regulations on steep ground', why: 'No such rule; the choice is about forces, people and terrain.' },
      { id: 'd', text: 'Stretchers cannot be raised safely on steep ground, only lowered', why: 'They can; it is just harder and slower.' },
    ],
    answer: 'a',
    concepts: ['mechanical-advantage', 'friction-losses', 'evacuation'],
    explanation: 'Friction is the enemy of hauling and the friend of lowering. The evacuation route decision (Stage 9) is made with the terrain, the team and the patient.',
  },
  {
    id: 's13-rev-10',
    kind: 'single',
    prompt: 'Which of these statements is a fact rather than a myth?',
    choices: [
      { id: 'a', text: '“Two anchor points always halve the load.”', why: 'Myth — past 120° each leg carries more than the load.' },
      { id: 'b', text: '“Peak fall force depends on the fall factor, not the fall length.”', why: 'Correct — this is a fact: $f = h/L$ sets the peak force.' },
      { id: 'c', text: '“A reef knot is a good bend for load-bearing lines.”', why: 'Myth — it capsizes.' },
      { id: 'd', text: '“More mechanical advantage is always safer.”', why: 'Myth — over-powered systems overload snagged loads and anchors.' },
    ],
    answer: 'b',
    concepts: ['vector-angles', 'knot-families', 'mechanical-advantage', 'rope-types', 'fall-factor'],
    explanation: 'Each myth sounds like common sense; the physics says otherwise. Another one: “paracord is fine for body weight if doubled” — utility cord is not life-safety rope.',
  },
  {
    id: 's13-rev-6',
    kind: 'single',
    prompt: 'A backup shares the same anchor, rope and knot as the main system. Which statement is correct?',
    choices: [
      { id: 'a', text: 'It is not truly redundant: the shared parts are still single points of failure', why: 'Correct — redundancy means independent components.' },
      { id: 'b', text: 'It is truly redundant, because there are now two systems instead of one', why: 'Two systems through one point still fail together at that point.' },
      { id: 'c', text: 'It is truly redundant as long as the shared knot is a strong one', why: 'A strong knot is still one knot; if it fails, both systems fail.' },
      { id: 'd', text: 'It is truly redundant as long as the backup rope is kept slack', why: 'Slack in the backup does not make the shared anchor or knot independent.' },
    ],
    answer: 'a',
    concepts: ['anchor-principles', 'redundancy'],
    explanation: 'Redundancy (Stage 1 kit design, and here) means independent components: if everything goes through one point, that point is still a single point of failure.',
  },
  {
    id: 's13-rev-4',
    kind: 'single',
    prompt: 'Which of these rope uses is camp rigging you may practise without formal training?',
    choices: [
      { id: 'a', text: 'Lowering an injured walker down a slope in a litter', why: 'Formal training only — technical rescue.' },
      { id: 'b', text: 'Tensioning a tarp ridgeline with a trucker’s hitch', why: 'Correct — camp rigging you can practise.' },
      { id: 'c', text: 'Descending a canyon drop on a rope', why: 'Formal training only — rappelling.' },
      { id: 'd', text: 'Holding the rope for a friend climbing a boulder', why: 'Formal training only — belaying.' },
    ],
    answer: 'b',
    concepts: ['training-scope', 'rescue-limits', 'lashings'],
    explanation: 'The line runs between gear and people: if the rope could hold a person, it needs formal training and certified equipment. Camp skills such as hitches and Stage 7 lashings are yours to practise.',
  },
  {
    id: 's13-rev-2',
    kind: 'single',
    prompt: 'A cord wraps one full turn (2π rad) round a smooth post with μ = 0.2. How many times the holding force can the load be? (capstan: $e^{\\mu\\theta}$)',
    choices: [
      { id: 'a', text: '3.5 ×', why: 'Correct — $e^{0.2 \\times 2\\pi} = e^{1.26} \\approx 3.5$.' },
      { id: 'b', text: '1.9 ×', why: 'This uses half a turn ($\\theta = \\pi$); one full turn is $2\\pi$.' },
      { id: 'c', text: '2.3 ×', why: 'This adds $1 + 1.26$ instead of taking the exponential.' },
      { id: 'd', text: '1.2 ×', why: 'This leaves out the angle: $e^{0.2}$ ignores how far the cord wraps.' },
    ],
    answer: 'a',
    concepts: ['capstan-friction', 'friction-losses'],
    explanation: '$e^{0.2 \\times 2\\pi} = e^{1.26} \\approx 3.5$. The same exponential that makes hitches hold makes carabiners and edges waste haul force.',
  },
  {
    id: 's13-rev-8',
    kind: 'single',
    prompt: 'A 60 kg load hangs from two anchor legs 90° apart. What is the force in each leg? (g = 9.81 m/s²)',
    choices: [
      { id: 'a', text: '416 N', why: 'Correct — $589/(2\\cos 45°) \\approx 416$ N.' },
      { id: 'b', text: '294 N', why: 'This simply halves the weight and ignores the 90° angle.' },
      { id: 'c', text: '832 N', why: 'This divides by $\\cos 45°$ but forgets the 2 for the two legs.' },
      { id: 'd', text: '42 N', why: 'This uses 60 kg as if it were a force; multiply by g first.' },
    ],
    answer: 'a',
    concepts: ['vector-angles'],
    explanation: '$W = 589$ N; $T = 589/(2\\cos 45°) = 589/1.414 \\approx 416$ N.',
  },
]
