import type { Question } from '../../types'

// Stage 5 review: interleaved questions mixing shelter design, site, tarps, natural, snow, hot and tropical
// shelters and failure analysis — and re-testing Stage 1 ideas (heat balance, wet + wind, daylight,
// stay-or-move, human factors) in new contexts.
export const stage5Review: Question[] = [
  {
    id: 's5-rev-1',
    kind: 'single',
    prompt: 'Upland forest, 3 °C, rain and 40 km/h wind from the north. You have just climbed hard and your base layer is soaked with sweat. You have a tarp and 45 minutes of light. What first?',
    choices: [
      { id: 'a', text: 'Keep working hard to build fast while you are still warm', why: 'More sweat into already wet clothing in wind — the Stage 1 killer combination gets worse.' },
      { id: 'b', text: 'Shell on, then a low wedge or A-frame in the lee of a thicket, closed end to the north; bed second; change into dry layers under cover', why: 'Best: stops the wet + wind losses first, then the ground, then fixes the wet clothing.' },
      { id: 'c', text: 'A high lean-to facing north so you can watch the weather', why: 'Open to wind and rain — it will fill like a sail.' },
      { id: 'd', text: 'Build a thick bed first and pitch the tarp if time allows', why: 'On a wet, windy night staying dry comes before the bed; a soaked bed insulates poorly anyway.' },
    ],
    answer: 'b',
    concepts: ['wet-wind', 'tarp-configs', 'heat-loss'],
    explanation: 'Rank tonight’s heat-loss paths: evaporation and convection (wet + wind) dominate, so roof and wind protection come first, then conduction.',
  },
  {
    id: 's5-rev-2',
    kind: 'numeric',
    prompt: 'You lie on a bed with total resistance $R = 1.6$ m²·K/W (leaves plus clothing and soil). Contact area 0.5 m², skin 33 °C, ground 3 °C. Using $Q = A\\Delta T/R$, what is the conductive loss in **W**? (One decimal.)',
    unit: 'W',
    answer: 9.4,
    tolerance: 0.3,
    concepts: ['r-value', 'ground-insulation'],
    explanation: '$0.5 \\times 30 / 1.6 \\approx 9.4$ W — compared with over 100 W on bare ground.',
  },
  {
    id: 's5-rev-3',
    kind: 'numeric',
    prompt: 'Subarctic winter: sunset 16:30 plus 20 minutes of usable twilight. A quinzhee needs 190 minutes including the sintering wait, and you want a 20-minute margin. What is the latest time to start, in **minutes after 12:00**?',
    unit: 'min',
    answer: 80,
    tolerance: 0,
    concepts: ['daylight', 'effort-budget', 'snow-shelter'],
    explanation: 'Usable light ends 16:50. 16:50 − 0:20 margin − 3:10 = **13:20**, i.e., 80 minutes after noon. If it is later than that, dig a trench instead.',
  },
  {
    id: 's5-rev-4',
    kind: 'multi',
    prompt: 'Clear, calm night, −6 °C. Which choices reduce **radiative** heat loss?',
    choices: [
      { id: 'a', text: 'Sleeping under dense living conifers', why: 'Yes — the canopy replaces the cold sky with warmer branches.' },
      { id: 'b', text: 'A low tarp overhead', why: 'Yes — the tarp hides the sky.' },
      { id: 'c', text: 'A thicker leaf bed', why: 'No — that controls conduction, not radiation (though it is still a great idea).' },
      { id: 'd', text: 'Enclosed snow walls', why: 'Yes — you exchange radiation with walls near 0 °C instead of a sky around −30 °C.' },
      { id: 'e', text: 'A hat and hood', why: 'Yes — covering the head reduces radiant and convective loss from it.' },
    ],
    answer: ['a', 'b', 'd', 'e'],
    concepts: ['heat-loss', 'shelter-types'],
    explanation: 'Each control targets a path. On clear nights, anything between you and the sky helps.',
  },
  {
    id: 's5-rev-5',
    kind: 'single',
    prompt: 'Stranded with your vehicle in a hot desert at 12:30, 43 °C. Which plan is best?',
    choices: [
      { id: 'a', text: 'Walk for help now while you are fresh', why: 'Walking at midday maximises sweat loss; the vehicle is a bigger search target than a person.' },
      { id: 'b', text: 'Rest in the shade beside the vehicle (not inside it), rig a double sheet later in the day, and drink the water you need', why: 'Correct — stay with the vehicle, shade, rest in the heat, ration sweat not water.' },
      { id: 'c', text: 'Dig a deep dugout shelter immediately', why: 'Heavy work at the peak of the heat costs more water than it saves today.' },
      { id: 'd', text: 'Sit in the closed car out of the sun', why: 'A closed car in the sun gets far hotter than the outside air.' },
    ],
    answer: 'b',
    concepts: ['hot-shelter', 'stay-or-move', 'dehydration'],
    explanation: 'Timing is part of the design in the heat; so is the stay-or-move decision.',
  },
  {
    id: 's5-rev-6',
    kind: 'truefalse',
    prompt: 'A flame inside a well-built snow shelter is safe as long as the candle keeps burning brightly.',
    answer: false,
    concepts: ['carbon-monoxide', 'snow-shelter'],
    explanation: 'A flame is not an air-quality indicator; CO is colourless and odourless. No flames for warmth, keep the vent and door clear, and get everyone out at the first headache, nausea or drowsiness.',
  },
  {
    id: 's5-rev-7',
    kind: 'order',
    prompt: 'You are lost at 16:30 in a mountain forest, uninjured, with a tarp and a working phone; you decide to stay put. Order the next actions.',
    items: [
      { id: 'stop', text: 'STOP: sit, breathe, assess the immediate danger' },
      { id: 'comm', text: 'Call or message for help with your location' },
      { id: 'site', text: 'Choose a site: look up, upstream, down and around' },
      { id: 'bed', text: 'Build the shelter the night needs (roof or bed first, depending on the weather)' },
      { id: 'signal', text: 'Prepare a signal spot nearby for the morning' },
    ],
    answer: ['stop', 'comm', 'site', 'bed', 'signal'],
    concepts: ['stop', 'priorities', 'site-selection', 'signaling'],
    explanation: 'Control yourself, then the cheapest high-value action (communication), then site before construction, then prepare to be found.',
  },
  {
    id: 's5-rev-8',
    kind: 'single',
    prompt: 'Your group has pushed on past its planned stop to "make the proper campsite"; it is now dusk, raining, and two people are shivering. Someone says, "We’ve come this far, it’s only another hour." Which trap is this, and what is the shelter decision?',
    choices: [
      { id: 'a', text: 'Commitment (sunk cost): stop now and pitch a storm shelter on the best nearby site', why: 'Correct — past effort is not a reason to accept more risk; the shivering members need shelter now.' },
      { id: 'b', text: 'Familiarity: keep going, you know the way', why: 'Not the trap described, and continuing in the dark with shivering people is the wrong decision.' },
      { id: 'c', text: 'Scarcity: the campsite might be taken', why: 'Not the trap here.' },
      { id: 'd', text: 'No trap: an hour is short', why: 'An hour of wet, dark walking with two people already shivering is how mild hypothermia becomes serious.' },
    ],
    answer: 'a',
    concepts: ['human-factors', 'shelter-failure', 'wet-wind'],
    explanation: 'Many failed shelter nights begin with a decision to stop too late. Set a decision time and keep it.',
  },
  {
    id: 's5-rev-9',
    kind: 'multi',
    prompt: 'Tropical rainforest, wet season. Which choices make the night safer?',
    choices: [
      { id: 'a', text: 'A site on a rise well above the river', why: 'Yes — rivers can rise metres overnight.' },
      { id: 'b', text: 'A steep roof with wide overhangs pitched before the afternoon storm', why: 'Yes.' },
      { id: 'c', text: 'A mosquito net tucked in all round', why: 'Yes — the most effective night-time protection against disease-carrying mosquitoes.' },
      { id: 'd', text: 'Sleeping under a giant tree for extra shelter from rain', why: 'Only if it has no dead limbs; big trees drop heavy dead wood. Look up first.' },
      { id: 'e', text: 'Keeping one dry set of clothes only for sleeping', why: 'Yes — prevents skin damage and night chilling.' },
    ],
    answer: ['a', 'b', 'c', 'e'],
    concepts: ['tropical-shelter', 'insect-protection', 'site-hazards'],
    explanation: 'Site (flood, overhead), roof (downpours), net (insects), dry set (skin and warmth).',
  },
  {
    id: 's5-rev-10',
    kind: 'numeric',
    prompt: 'A lean-to tarp presenting 6 m² to the wind experiences about 830 N at 50 km/h. You re-pitch it low and edge-on so it presents only 2 m², and the gusts drop to 40 km/h near the ground. Using $F \\propto A v^2$, estimate the new force in **N**.',
    unit: 'N',
    answer: 177,
    tolerance: 8,
    concepts: ['wind-loading', 'tarp-configs'],
    explanation: '$830 \\times (2/6) \\times (40/50)^2 = 830 \\times 0.333 \\times 0.64 \\approx 177$ N — less than a quarter of the original load.',
  },
]
