import type { Question } from '../../types'

// Stage 5 review: interleaved questions mixing shelter design, site, tarps, natural, snow, hot and tropical
// shelters and failure analysis — and re-testing Stage 1 ideas (heat balance, wet + wind, daylight,
// stay-or-move, human factors) in new contexts.
export const stage5Review: Question[] = [
  {
    id: 's5-rev-1',
    kind: 'single',
    prompt: 'Upland forest, 3 °C, rain and 40 km/h wind from the north. You have just climbed hard and your base layer is soaked with sweat. You have a tarp and 45 minutes of light. What first?',
    choices: [
      { id: 'a', text: 'Keep working hard to build fast while you are still warm from the climb', why: 'More sweat into already wet clothing in wind — the Stage 1 killer combination gets worse.' },
      { id: 'b', text: 'Shell on, low wedge in the lee of a thicket, closed end north; then bed and dry layers', why: 'Best: stops the wet + wind losses first, then the ground, then fixes the wet clothing by changing under cover.' },
      { id: 'c', text: 'A high lean-to facing north so you can keep an eye on the weather coming in', why: 'Open to wind and rain — it will fill like a sail.' },
      { id: 'd', text: 'Build a thick bed first, then pitch the tarp over it if there is time left', why: 'On a wet, windy night staying dry comes before the bed; a soaked bed insulates poorly anyway.' },
    ],
    answer: 'b',
    concepts: ['wet-wind', 'tarp-configs', 'heat-loss'],
    explanation: 'Rank tonight’s heat-loss paths: evaporation and convection (wet + wind) dominate, so roof and wind protection come first, then conduction.',
  },
  {
    id: 's5-rev-2',
    kind: 'single',
    prompt: 'You lie on a bed with total resistance $R = 1.6$ m²·K/W (leaves plus clothing and soil). Contact area 0.5 m², skin 33 °C, ground 3 °C. Using $Q = A\\Delta T/R$, what is the conductive loss?',
    choices: [
      { id: 'a', text: '9.4 W', why: 'Correct — 0.5 × 30 ÷ 1.6.' },
      { id: 'b', text: '18.8 W', why: 'This leaves out the 0.5 m² contact area.' },
      { id: 'c', text: '24 W', why: 'This multiplies by $R$ instead of dividing by it.' },
      { id: 'd', text: '10.3 W', why: 'This uses the skin temperature (33) instead of the difference (30 K).' },
    ],
    answer: 'a',
    concepts: ['r-value', 'ground-insulation'],
    explanation: '$0.5 \\times 30 / 1.6 \\approx 9.4$ W — compared with over 100 W on bare ground.',
  },
  {
    id: 's5-rev-3',
    kind: 'single',
    prompt: 'Subarctic winter: sunset 16:30 plus 20 minutes of usable twilight. A quinzhee needs 190 minutes including the sintering wait, and you want a 20-minute margin. What is the latest time to start?',
    choices: [
      { id: 'a', text: '13:20 (80 min after noon)', why: 'Correct — 16:50 − 0:20 margin − 3:10.' },
      { id: 'b', text: '13:00 (60 min after noon)', why: 'This ignores the 20 minutes of usable twilight after sunset.' },
      { id: 'c', text: '13:40 (100 min after noon)', why: 'This forgets the 20-minute safety margin.' },
      { id: 'd', text: '14:00 (120 min after noon)', why: 'This adds the margin instead of subtracting it.' },
    ],
    answer: 'a',
    concepts: ['daylight', 'effort-budget', 'snow-shelter'],
    explanation: 'Usable light ends 16:50. 16:50 − 0:20 margin − 3:10 = **13:20**, i.e., 80 minutes after noon. If it is later than that, dig a trench instead.',
  },
  {
    id: 's5-rev-4',
    kind: 'single',
    prompt: 'Clear, calm night, −6 °C. Which choice does **NOT** reduce **radiative** heat loss?',
    choices: [
      { id: 'a', text: 'Sleeping under dense living conifers', why: 'Reduces it — the canopy replaces the cold sky with warmer branches.' },
      { id: 'b', text: 'A low tarp pitched overhead', why: 'Reduces it — the tarp hides the sky.' },
      { id: 'c', text: 'A thicker leaf bed underneath you', why: 'Correct — that controls conduction, not radiation (though it is still a great idea).' },
      { id: 'd', text: 'Enclosed snow walls around you', why: 'Reduces it — you exchange radiation with walls near 0 °C instead of a sky around −30 °C.' },
    ],
    answer: 'c',
    concepts: ['heat-loss', 'shelter-types'],
    explanation: 'Each control targets a path. On clear nights, anything between you and the sky helps — canopy, tarp, snow walls, even a hat and hood; the bed fights conduction.',
  },
  {
    id: 's5-rev-5',
    kind: 'single',
    prompt: 'Stranded with your vehicle in a hot desert at 12:30, 43 °C. Which plan is best?',
    choices: [
      { id: 'a', text: 'Walk for help now while you are still fresh and cool', why: 'Walking at midday maximises sweat loss; the vehicle is a bigger search target than a person.' },
      { id: 'b', text: 'Rest in shade beside the vehicle, not in it; rig a double sheet later', why: 'Correct — stay with the vehicle, shade, rest in the heat, ration sweat not water.' },
      { id: 'c', text: 'Dig a deep dugout shelter right away before it gets hotter', why: 'Heavy work at the peak of the heat costs more water than it saves today.' },
      { id: 'd', text: 'Sit in the closed car, out of the direct sun, and wait', why: 'A closed car in the sun gets far hotter than the outside air.' },
    ],
    answer: 'b',
    concepts: ['hot-shelter', 'stay-or-move', 'dehydration'],
    explanation: 'Stay with the vehicle, rest in the shade beside it, build in the cooler part of the day and drink the water you need. Timing is part of the design in the heat; so is the stay-or-move decision.',
  },
  {
    id: 's5-rev-6',
    kind: 'single',
    prompt: 'Which statement about a candle burning inside a well-built snow shelter is correct?',
    choices: [
      { id: 'a', text: 'A bright flame says nothing about CO, which is colourless and odourless.', why: 'Correct — a flame is not an air-quality indicator.' },
      { id: 'b', text: 'It is safe as long as the candle keeps burning brightly all night.', why: 'A flame keeps burning at CO levels that can kill you.' },
      { id: 'c', text: 'It is safe once a vent has been poked through the roof.', why: 'A vent helps but can drift shut; no flames for warmth, and watch for symptoms.' },
      { id: 'd', text: 'It is safe if you blow it out before everyone falls asleep.', why: 'CO builds up while you are awake too; drowsiness is itself a late sign.' },
    ],
    answer: 'a',
    concepts: ['carbon-monoxide', 'snow-shelter'],
    explanation: 'A flame is not an air-quality indicator; CO is colourless and odourless. No flames for warmth, keep the vent and door clear, and get everyone out at the first headache, nausea or drowsiness.',
  },
  {
    id: 's5-rev-7',
    kind: 'single',
    prompt: 'You are lost at 16:30 in a mountain forest, uninjured, with a tarp and a working phone; you decide to stay put. Which order of next actions is right?',
    choices: [
      { id: 'a', text: 'STOP → call for help → choose a site → build the shelter → prepare a signal spot', why: 'Correct — control yourself, communicate, site before construction, then prepare to be found.' },
      { id: 'b', text: 'STOP → choose a site → build the shelter → call for help → prepare a signal spot', why: 'Communication is the cheapest high-value action; do it before spending light and battery on building.' },
      { id: 'c', text: 'Call for help → STOP → choose a site → build the shelter → prepare a signal spot', why: 'Stop and assess the immediate danger first; a calm call with a clear location is worth more.' },
      { id: 'd', text: 'STOP → call for help → prepare a signal spot → choose a site → build the shelter', why: 'The signal spot is for the morning; the shelter decides whether you get through the night.' },
    ],
    answer: 'a',
    concepts: ['stop', 'priorities', 'site-selection', 'signaling'],
    explanation: 'Control yourself, then the cheapest high-value action (communication), then site before construction (roof or bed first depending on weather), then prepare to be found.',
  },
  {
    id: 's5-rev-8',
    kind: 'single',
    prompt: 'Your group has pushed on past its planned stop to "make the proper campsite"; it is now dusk, raining, and two people are shivering. Someone says, "We’ve come this far, it’s only another hour." Which trap is this, and what is the shelter decision?',
    choices: [
      { id: 'a', text: 'Sunk cost: stop now and pitch a storm shelter nearby', why: 'Correct — past effort is not a reason to accept more risk; the shivering members need shelter now.' },
      { id: 'b', text: 'Familiarity: keep going, since you know the way well', why: 'Not the trap described, and continuing in the dark with shivering people is the wrong decision.' },
      { id: 'c', text: 'Scarcity: push on before the campsite gets taken', why: 'Not the trap here.' },
      { id: 'd', text: 'No trap: one more hour is short, so keep walking', why: 'An hour of wet, dark walking with two people already shivering is how mild hypothermia becomes serious.' },
    ],
    answer: 'a',
    concepts: ['human-factors', 'shelter-failure', 'wet-wind'],
    explanation: 'This is commitment (sunk cost): stop now and pitch a storm shelter on the best nearby site. Many failed shelter nights begin with a decision to stop too late — set a decision time and keep it.',
  },
  {
    id: 's5-rev-9',
    kind: 'single',
    prompt: 'Tropical rainforest, wet season. Which choice does **NOT** reliably make the night safer?',
    choices: [
      { id: 'a', text: 'A site on a rise well above the river', why: 'Makes it safer — rivers can rise metres overnight.' },
      { id: 'b', text: 'A mosquito net tucked in all round', why: 'Makes it safer — the most effective night-time protection against disease-carrying mosquitoes.' },
      { id: 'c', text: 'Sleeping under a giant tree for extra shelter from rain', why: 'Correct — big trees drop heavy dead wood; only consider it if it has no dead limbs. Look up first.' },
      { id: 'd', text: 'Keeping one dry set of clothes only for sleeping', why: 'Makes it safer — prevents skin damage and night chilling.' },
    ],
    answer: 'c',
    concepts: ['tropical-shelter', 'insect-protection', 'site-hazards'],
    explanation: 'Site (flood, overhead hazards), roof (a steep roof pitched before the downpour), net (insects), dry set (skin and warmth).',
  },
  {
    id: 's5-rev-10',
    kind: 'single',
    prompt: 'A lean-to tarp presenting 6 m² to the wind experiences about 830 N at 50 km/h. You re-pitch it low and edge-on so it presents only 2 m², and the gusts drop to 40 km/h near the ground. Using $F \\propto A v^2$, estimate the new force.',
    choices: [
      { id: 'a', text: 'About 177 N', why: 'Correct — 830 × (2/6) × (40/50)².' },
      { id: 'b', text: 'About 221 N', why: 'This forgets to square the speed ratio (uses 0.8 instead of 0.64).' },
      { id: 'c', text: 'About 531 N', why: 'This applies the speed change but forgets the smaller area.' },
      { id: 'd', text: 'About 1 590 N', why: 'This inverts the area ratio (6/2 instead of 2/6).' },
    ],
    answer: 'a',
    concepts: ['wind-loading', 'tarp-configs'],
    explanation: '$830 \\times (2/6) \\times (40/50)^2 = 830 \\times 0.333 \\times 0.64 \\approx 177$ N — less than a quarter of the original load.',
  },
]
