import type { Stage } from './types'

// The full course map. Stage 1 lessons are fully written in ./stages/stage1.
// Later stages are outlined here; when a stage is written, add its lessons under
// ./stages/stageN and flip `status` to 'available'. Nothing else needs to change.

export const stages: Stage[] = [
  {
    n: 1,
    slug: 'foundations',
    title: 'Survival Foundations',
    level: 'beginner',
    summary:
      'The decision system every later stage builds on: priorities, situation assessment, risk, mindset, and the first-hour basics of warmth, kit, shelter, fire, water and signaling.',
    requires: [],
    status: 'available',
    environments: ['forest', 'desert', 'mountain', 'urban', 'coastal'],
    simulations: ['priority-triage', 'heat-balance', 'kit-builder', 'shelter-site', 'fire-basic', 'water-treatment', 'signal-detect', 'scenario-lost-1400'],
    outline: [
      { id: 's1-l1', title: 'Thinking like a survivor', level: 'beginner', prerequisites: [], topics: ['How emergencies develop', 'Observe → Assess → Prioritize → Plan → Act → Reassess', 'The 12 questions'] },
      { id: 's1-l2', title: 'Survival priorities', level: 'beginner', prerequisites: ['s1-l1'], topics: ['Rule of threes and its limits', 'Priorities shift with environment', 'Next highest-value action'] },
      { id: 's1-l3', title: 'Situation assessment: STOP', level: 'beginner', prerequisites: ['s1-l2'], topics: ['Stop, Think, Observe, Plan', 'Immediate danger', 'Inventory', 'Time and light budget'] },
      { id: 's1-l4', title: 'Risk management', level: 'beginner', prerequisites: ['s1-l3'], topics: ['Likelihood × consequence', 'Exposure time', 'Human factors (FACETS)', 'Turnaround times', 'Trip plans'] },
      { id: 's1-l5', title: 'Survival mindset and stress', level: 'beginner', prerequisites: ['s1-l1'], topics: ['Acute stress response', 'Freezing and the 10–80–10 pattern', 'Regaining control with tasks', 'Will to survive'] },
      { id: 's1-l6', title: 'Emergency decision making', level: 'beginner', prerequisites: ['s1-l4', 's1-l5'], topics: ['Decisions under uncertainty', 'Satisficing', 'Stay or move (first pass)', 'Reversible vs irreversible actions'] },
      { id: 's1-l7', title: 'Your body’s heat budget', level: 'beginner', prerequisites: ['s1-l2'], topics: ['Heat production', 'Radiation, convection, conduction, evaporation', 'Why wet + wind is dangerous'] },
      { id: 's1-l8', title: 'Clothing and environmental protection', level: 'beginner', prerequisites: ['s1-l7'], topics: ['Layering', 'Insulation and moisture', 'Cotton', 'Sun, feet, hands, head'] },
      { id: 's1-l9', title: 'Survival equipment and your personal kit', level: 'beginner', prerequisites: ['s1-l2', 's1-l8'], topics: ['Ten Essentials', 'Kit tiers', 'Redundancy', 'Environment-specific additions'] },
      { id: 's1-l10', title: 'Basic shelter', level: 'beginner', prerequisites: ['s1-l7', 's1-l9'], topics: ['Site selection', 'Ground insulation', 'Tarp and emergency shelters', 'Hazards overhead and underfoot'] },
      { id: 's1-l11', title: 'Basic fire', level: 'beginner', prerequisites: ['s1-l7'], topics: ['Fire triangle', 'Tinder → kindling → fuel', 'Lighter and ferro rod', 'Fire safety and law'] },
      { id: 's1-l12', title: 'Basic water', level: 'beginner', prerequisites: ['s1-l7'], topics: ['How much you need', 'Sources', 'Boil, chemical, filter, UV', 'Ration sweat, not water'] },
      { id: 's1-l13', title: 'Emergency signaling', level: 'beginner', prerequisites: ['s1-l3'], topics: ['Phones and emergency numbers', 'Whistle, mirror, light', 'Groups of three', 'Being visible'] },
      { id: 's1-l14', title: 'Putting it together: the first hour', level: 'beginner', prerequisites: ['s1-l6', 's1-l10', 's1-l11', 's1-l12', 's1-l13'], topics: ['Integrated scenario', 'Stage review'] },
    ],
  },
  {
    n: 2,
    slug: 'navigation',
    title: 'Navigation and Terrain',
    level: 'beginner',
    summary: 'From reading a map to navigating without instruments, and recovering when navigation fails.',
    requires: [1],
    status: 'available',
    environments: ['forest', 'mountain', 'desert', 'arctic'],
    simulations: ['nav-map', 'celestial', 'nav-relocation'],
    outline: [
      { id: 's2-l1', title: 'Maps and scale', level: 'beginner', prerequisites: ['s1-l3'], topics: ['Scale and distance', 'Grid references', 'Map symbols', 'Map datums'] },
      { id: 's2-l2', title: 'Reading topography', level: 'beginner', prerequisites: ['s2-l1'], topics: ['Contours', 'Slope from spacing', 'Ridges, valleys, saddles, spurs', 'Profiles'] },
      { id: 's2-l3', title: 'The compass', level: 'beginner', prerequisites: ['s2-l1'], topics: ['Baseplate compass anatomy', 'Magnetic vs true vs grid north', 'Declination'] },
      { id: 's2-l4', title: 'Bearings and azimuths', level: 'intermediate', prerequisites: ['s2-l3'], topics: ['Map to ground', 'Ground to map', 'Back bearings', 'Error per degree'] },
      { id: 's2-l5', title: 'Pacing, timing and dead reckoning', level: 'intermediate', prerequisites: ['s2-l4'], topics: ['Pace count', 'Naismith and slope corrections', 'Cumulative error'] },
      { id: 's2-l6', title: 'Terrain association and handrails', level: 'intermediate', prerequisites: ['s2-l2', 's2-l5'], topics: ['Handrails, catching features, attack points', 'Aiming off', 'Collecting features'] },
      { id: 's2-l7', title: 'Triangulation and relocation', level: 'intermediate', prerequisites: ['s2-l4', 's2-l6'], topics: ['Resection', 'Cocked hat error', 'Relocation procedures'] },
      { id: 's2-l8', title: 'Sun and shadow navigation', level: 'intermediate', prerequisites: ['s2-l3'], topics: ['Solar azimuth', 'Shadow-stick method', 'Watch method and its error'] },
      { id: 's2-l9', title: 'Stars and Moon', level: 'advanced', prerequisites: ['s2-l8'], topics: ['Polaris and latitude', 'Southern Cross', 'Orion', 'Moon phase direction'] },
      { id: 's2-l10', title: 'Natural navigation', level: 'advanced', prerequisites: ['s2-l8'], topics: ['Wind-shaped vegetation', 'Snow and sand patterns', 'Reliability limits'] },
      { id: 's2-l11', title: 'GPS and digital maps', level: 'beginner', prerequisites: ['s2-l1'], topics: ['How GNSS works', 'Coordinate formats', 'Battery strategy', 'Offline maps'] },
      { id: 's2-l12', title: 'When navigation fails', level: 'advanced', prerequisites: ['s2-l7', 's2-l10', 's2-l11'], topics: ['Recognising you are lost', 'Lost-person behavior', 'Navigating without equipment'] },
    ],
  },
  {
    n: 3,
    slug: 'fire',
    title: 'Fire and Heat',
    level: 'intermediate',
    summary: 'Combustion science, fire lays for different jobs, wet-weather and primitive ignition, and fire management.',
    requires: [1],
    status: 'available',
    environments: ['forest', 'desert', 'arctic', 'tropical'],
    simulations: ['fire-advanced', 'friction-fire'],
    outline: [
      { id: 's3-l1', title: 'Combustion science', level: 'intermediate', prerequisites: ['s1-l11'], topics: ['Pyrolysis', 'Surface-to-volume ratio', 'Moisture content and energy'] },
      { id: 's3-l2', title: 'Tinder, kindling and fuel selection', level: 'intermediate', prerequisites: ['s3-l1'], topics: ['Natural tinders by biome', 'Feather sticks', 'Hardwood vs softwood', 'Dead standing wood'] },
      { id: 's3-l3', title: 'Fire lays and their purposes', level: 'intermediate', prerequisites: ['s3-l2'], topics: ['Teepee, log cabin, lean-to, star, long log, Dakota hole', 'Cooking vs heating vs signal'] },
      { id: 's3-l4', title: 'Wet-weather fire', level: 'intermediate', prerequisites: ['s3-l3'], topics: ['Finding dry fuel', 'Platforms', 'Processing wood', 'Resin'] },
      { id: 's3-l5', title: 'Ferrocerium, flint and steel', level: 'intermediate', prerequisites: ['s3-l2'], topics: ['Spark temperatures', 'Char cloth', 'Technique'] },
      { id: 's3-l6', title: 'Friction fire', level: 'advanced', prerequisites: ['s3-l5'], topics: ['Bow drill mechanics', 'Hand drill', 'Wood pairs', 'Ember to flame'] },
      { id: 's3-l7', title: 'Heating and reflecting', level: 'intermediate', prerequisites: ['s3-l3', 's1-l7'], topics: ['Radiant heat geometry', 'Reflectors', 'Long-duration fires'] },
      { id: 's3-l8', title: 'Fire safety, law and impact', level: 'beginner', prerequisites: ['s1-l11'], topics: ['Fire bans', 'Wildfire risk', 'Extinguishing', 'Leave No Trace'] },
    ],
  },
  {
    n: 4,
    slug: 'water',
    title: 'Water',
    level: 'intermediate',
    summary: 'Requirements and dehydration physiology, finding and collecting water in every biome, and the science of treatment.',
    requires: [1],
    status: 'available',
    environments: ['desert', 'coastal', 'forest', 'arctic', 'urban'],
    simulations: ['water-advanced', 'solar-still'],
    outline: [
      { id: 's4-l1', title: 'Water requirements and dehydration', level: 'intermediate', prerequisites: ['s1-l12'], topics: ['Sweat rates', 'Body water %', 'Performance loss'] },
      { id: 's4-l2', title: 'Finding water', level: 'intermediate', prerequisites: ['s4-l1', 's2-l2'], topics: ['Terrain, vegetation and animal clues', 'Groundwater concepts'] },
      { id: 's4-l3', title: 'Collecting water', level: 'intermediate', prerequisites: ['s4-l2'], topics: ['Rain', 'Dew', 'Transpiration and condensation', 'Solar still realities'] },
      { id: 's4-l4', title: 'Contamination', level: 'intermediate', prerequisites: ['s1-l12'], topics: ['Bacteria, viruses, protozoa, helminths', 'Chemical and algal hazards'] },
      { id: 's4-l5', title: 'Treatment science', level: 'advanced', prerequisites: ['s4-l4'], topics: ['Log reductions', 'CT values', 'Filtration pore sizes', 'UV dose'] },
      { id: 's4-l6', title: 'Improvised treatment and storage', level: 'intermediate', prerequisites: ['s4-l5'], topics: ['Sediment filters', 'SODIS', 'Safe storage'] },
    ],
  },
  {
    n: 5,
    slug: 'shelter',
    title: 'Shelter',
    level: 'intermediate',
    summary: 'Designing shelters from heat-transfer principles for rain, wind, snow, cold, heat and tropics.',
    requires: [1],
    status: 'available',
    environments: ['forest', 'arctic', 'desert', 'tropical', 'mountain'],
    simulations: ['shelter-builder'],
    outline: [
      { id: 's5-l1', title: 'Shelter design principles', level: 'intermediate', prerequisites: ['s1-l10'], topics: ['Heat-loss path by path', 'Volume and warmth', 'Ground insulation R-values'] },
      { id: 's5-l2', title: 'Site selection in depth', level: 'intermediate', prerequisites: ['s5-l1', 's2-l2'], topics: ['Cold air pooling', 'Drainage', 'Wind', 'Hazards'] },
      { id: 's5-l3', title: 'Tarp configurations', level: 'intermediate', prerequisites: ['s5-l1'], topics: ['A-frame, lean-to, diamond, wedge', 'Pitching in wind'] },
      { id: 's5-l4', title: 'Natural shelters', level: 'intermediate', prerequisites: ['s5-l1'], topics: ['Debris hut', 'Lean-to with reflector', 'Natural features'] },
      { id: 's5-l5', title: 'Snow shelters', level: 'advanced', prerequisites: ['s5-l1', 's8-l2'], topics: ['Quinzhee', 'Snow trench', 'Ventilation and CO'] },
      { id: 's5-l6', title: 'Hot-climate and tropical shelters', level: 'advanced', prerequisites: ['s5-l1'], topics: ['Shade and double roofs', 'Raised beds', 'Insects'] },
      { id: 's5-l7', title: 'Shelter failure analysis', level: 'advanced', prerequisites: ['s5-l3', 's5-l4'], topics: ['Case studies', 'Optimisation'] },
    ],
  },
  {
    n: 6,
    slug: 'food',
    title: 'Food and Nutrition',
    level: 'intermediate',
    summary: 'Energy budgets, emergency food management, and safe, legal approaches to foraging, fishing, trapping and hunting concepts.',
    requires: [1, 4],
    status: 'available',
    environments: ['forest', 'coastal', 'tropical', 'arctic', 'urban'],
    simulations: ['energy-budget', 'plant-id'],
    outline: [
      { id: 's6-l1', title: 'Energy requirements', level: 'intermediate', prerequisites: ['s1-l7'], topics: ['BMR and activity', 'Macronutrients', 'Water before food'] },
      { id: 's6-l2', title: 'Emergency food management', level: 'intermediate', prerequisites: ['s6-l1'], topics: ['Rationing', 'Storage', 'Preservation', 'Spoilage'] },
      { id: 's6-l3', title: 'Food safety and cooking', level: 'intermediate', prerequisites: ['s6-l2'], topics: ['Safe temperatures', 'Food poisoning', 'Parasites'] },
      { id: 's6-l4', title: 'Plant identification discipline', level: 'advanced', prerequisites: ['s6-l3'], topics: ['Keys and features', 'Deadly look-alikes', 'Why universal edibility tests are unreliable'] },
      { id: 's6-l5', title: 'Fungi: why not', level: 'advanced', prerequisites: ['s6-l4'], topics: ['Amatoxins', 'Expert-only identification'] },
      { id: 's6-l6', title: 'Insects and small foods', level: 'intermediate', prerequisites: ['s6-l3'], topics: ['Nutrition', 'Safety', 'Cultural and legal context'] },
      { id: 's6-l7', title: 'Fishing', level: 'intermediate', prerequisites: ['s6-l3'], topics: ['Regulations', 'Simple gear', 'Energy return'] },
      { id: 's6-l8', title: 'Trapping and hunting concepts', level: 'advanced', prerequisites: ['s6-l7'], topics: ['Law and ethics', 'Energy economics', 'Supervised instruction only'] },
    ],
  },
  {
    n: 7,
    slug: 'bushcraft',
    title: 'Primitive Skills and Bushcraft',
    level: 'intermediate',
    summary: 'The engineering behind cordage, lashings, containers, tools, adhesives and charcoal.',
    requires: [1, 3],
    status: 'available',
    environments: ['forest', 'tropical', 'desert'],
    simulations: ['cordage-strength'],
    outline: [
      { id: 's7-l1', title: 'Natural fibers and cordage', level: 'intermediate', prerequisites: ['s1-l9'], topics: ['Fiber sources', 'Reverse wrap', 'Why twist adds strength'] },
      { id: 's7-l2', title: 'Knots and lashings for camp', level: 'beginner', prerequisites: ['s7-l1'], topics: ['Friction and bend radius', 'Square, diagonal, tripod lashings'] },
      { id: 's7-l3', title: 'Containers and baskets', level: 'intermediate', prerequisites: ['s7-l1'], topics: ['Bark containers', 'Weaving', 'Boiling without metal'] },
      { id: 's7-l4', title: 'Knife and wood tools', level: 'intermediate', prerequisites: ['s1-l9'], topics: ['Safe knife work', 'Batoning', 'Digging sticks', 'Mallets'] },
      { id: 's7-l5', title: 'Stone, bone and antler', level: 'advanced', prerequisites: ['s7-l4'], topics: ['Conchoidal fracture', 'Flintknapping safety', 'Bone tools'] },
      { id: 's7-l6', title: 'Adhesives, charcoal, pigments and smoke', level: 'advanced', prerequisites: ['s3-l1'], topics: ['Pine pitch glue', 'Charcoal making', 'Pigments', 'Smoke production'] },
    ],
  },
  {
    n: 8,
    slug: 'physiology',
    title: 'Physiology of Survival',
    level: 'intermediate',
    summary: 'Thermoregulation, hydration, energy metabolism, sleep, altitude and immersion — quantitatively.',
    requires: [1],
    status: 'available',
    environments: ['arctic', 'desert', 'mountain', 'coastal'],
    simulations: ['heat-balance-advanced', 'cold-water'],
    outline: [
      { id: 's8-l1', title: 'Thermoregulation and core temperature', level: 'intermediate', prerequisites: ['s1-l7'], topics: ['Core vs shell', 'Vasoconstriction', 'Shivering thermogenesis'] },
      { id: 's8-l2', title: 'Heat-loss mechanisms quantified', level: 'intermediate', prerequisites: ['s8-l1'], topics: ['Radiation', 'Convection and wind chill', 'Conduction', 'Evaporation and wet clothing'] },
      { id: 's8-l3', title: 'Hypothermia', level: 'intermediate', prerequisites: ['s8-l2'], topics: ['Stages', 'Afterdrop', 'Field rewarming'] },
      { id: 's8-l4', title: 'Heat stress', level: 'intermediate', prerequisites: ['s8-l2'], topics: ['Heat exhaustion vs heat stroke', 'Acclimatisation', 'WBGT'] },
      { id: 's8-l5', title: 'Hydration and electrolytes', level: 'intermediate', prerequisites: ['s4-l1'], topics: ['Sodium', 'Hyponatremia', 'Oral rehydration'] },
      { id: 's8-l6', title: 'Energy metabolism', level: 'advanced', prerequisites: ['s6-l1'], topics: ['Glycogen', 'Fat oxidation', 'Starvation timeline'] },
      { id: 's8-l7', title: 'Sleep, fatigue and cognition', level: 'intermediate', prerequisites: ['s1-l5'], topics: ['Sleep deprivation', 'Night vision', 'Cognitive degradation'] },
      { id: 's8-l8', title: 'Altitude', level: 'advanced', prerequisites: ['s8-l1'], topics: ['Hypoxia', 'AMS, HAPE, HACE', 'Ascent rates'] },
      { id: 's8-l9', title: 'Cold water and immersion', level: 'advanced', prerequisites: ['s8-l3'], topics: ['Cold shock', '1-10-1', 'Swim failure', 'HELP posture'] },
    ],
  },
  {
    n: 9,
    slug: 'first-aid',
    title: 'Wilderness First Aid',
    level: 'intermediate',
    summary: 'Patient assessment and remote-setting care. A knowledge primer that points to hands-on certification.',
    requires: [1, 8],
    status: 'available',
    environments: ['all'],
    simulations: ['patient-assessment', 'evac-decision'],
    outline: [
      { id: 's9-l1', title: 'Scene safety and the patient assessment system', level: 'intermediate', prerequisites: ['s1-l3'], topics: ['Scene size-up', 'Primary survey', 'Secondary survey', 'SOAP notes'] },
      { id: 's9-l2', title: 'Airway, breathing, circulation', level: 'intermediate', prerequisites: ['s9-l1'], topics: ['Recovery position', 'Major bleeding', 'Tourniquets'] },
      { id: 's9-l3', title: 'Shock', level: 'intermediate', prerequisites: ['s9-l2'], topics: ['Pathophysiology', 'Signs', 'Care'] },
      { id: 's9-l4', title: 'Musculoskeletal injuries', level: 'intermediate', prerequisites: ['s9-l1'], topics: ['Fractures, sprains, dislocations', 'Improvised splints'] },
      { id: 's9-l5', title: 'Wounds, burns and blisters', level: 'intermediate', prerequisites: ['s9-l1'], topics: ['Irrigation', 'Infection', 'Burn depth'] },
      { id: 's9-l6', title: 'Environmental emergencies', level: 'intermediate', prerequisites: ['s8-l3', 's8-l4'], topics: ['Hypothermia', 'Heat illness', 'Dehydration', 'Lightning'] },
      { id: 's9-l7', title: 'Bites, stings, allergy and poisoning', level: 'intermediate', prerequisites: ['s9-l2'], topics: ['Anaphylaxis', 'Snakebite principles', 'Animal bites'] },
      { id: 's9-l8', title: 'Head, spine, chest and abdomen', level: 'advanced', prerequisites: ['s9-l3'], topics: ['TBI signs', 'Spinal assessment', 'Chest injuries'] },
      { id: 's9-l9', title: 'Monitoring and evacuation decisions', level: 'advanced', prerequisites: ['s9-l8'], topics: ['Vital sign trends', 'Evacuation urgency', 'Improvised stretchers'] },
    ],
  },
  {
    n: 10,
    slug: 'improvisation',
    title: 'Field Improvisation',
    level: 'intermediate',
    summary: 'A problem-solving method for turning ordinary objects into what you need.',
    requires: [1, 7],
    status: 'available',
    environments: ['all'],
    simulations: ['improvise-challenge'],
    outline: [
      { id: 's10-l1', title: 'The improvisation method', level: 'intermediate', prerequisites: ['s1-l6'], topics: ['Function over form', 'Material properties', 'Test before trusting'] },
      { id: 's10-l2', title: 'Containers, water collection and transport', level: 'intermediate', prerequisites: ['s10-l1'], topics: ['Bags, bottles, bark', 'Transport'] },
      { id: 's10-l3', title: 'Frames, tripods and load carrying', level: 'intermediate', prerequisites: ['s10-l1', 's7-l2'], topics: ['Tripods', 'Pack frames', 'Stretchers'] },
      { id: 's10-l4', title: 'Repair systems', level: 'intermediate', prerequisites: ['s10-l1'], topics: ['Tape, cord, wire', 'Footwear and clothing repair'] },
      { id: 's10-l5', title: 'Field sanitation and hygiene', level: 'intermediate', prerequisites: ['s4-l4'], topics: ['Catholes', 'Hand hygiene', 'Camp layout'] },
    ],
  },
  {
    n: 11,
    slug: 'tracking',
    title: 'Tracking and Environmental Interpretation',
    level: 'intermediate',
    summary: 'Reading tracks and sign to understand ecology, find resources and support navigation.',
    requires: [1, 2],
    status: 'planned',
    environments: ['forest', 'desert', 'arctic', 'coastal'],
    simulations: ['tracking-scene'],
    outline: [
      { id: 's11-l1', title: 'Track identification', level: 'intermediate', prerequisites: ['s1-l3'], topics: ['Track anatomy', 'Major track families'] },
      { id: 's11-l2', title: 'Gaits and direction of travel', level: 'intermediate', prerequisites: ['s11-l1'], topics: ['Walk, trot, lope, gallop', 'Pressure releases'] },
      { id: 's11-l3', title: 'Aging sign', level: 'advanced', prerequisites: ['s11-l2'], topics: ['Weathering', 'Reference tracks'] },
      { id: 's11-l4', title: 'Sign: trails, feeding, beds, scat', level: 'intermediate', prerequisites: ['s11-l1'], topics: ['Disturbed vegetation', 'Feeding signs', 'Droppings'] },
      { id: 's11-l5', title: 'Reading the landscape for resources', level: 'intermediate', prerequisites: ['s11-l4', 's4-l2'], topics: ['Water-related sign', 'Game trails as handrails'] },
      { id: 's11-l6', title: 'Human tracks and search support', level: 'advanced', prerequisites: ['s11-l3'], topics: ['Sign cutting for SAR', 'Last known point'] },
    ],
  },
  {
    n: 12,
    slug: 'weather-hazards',
    title: 'Weather and Environmental Hazards',
    level: 'intermediate',
    summary: 'Recognising hazards before they become emergencies: storms, lightning, floods, fire, avalanches and terrain.',
    requires: [1, 2],
    status: 'available',
    environments: ['mountain', 'desert', 'arctic', 'forest', 'coastal'],
    simulations: ['cloud-id', 'lightning-risk'],
    outline: [
      { id: 's12-l1', title: 'Clouds and weather patterns', level: 'intermediate', prerequisites: ['s1-l4'], topics: ['Cloud types', 'Fronts', 'Pressure trends'] },
      { id: 's12-l2', title: 'Thunderstorms and lightning', level: 'intermediate', prerequisites: ['s12-l1'], topics: ['Storm development', 'Lightning physics', 'Move at first thunder, 30-minute wait'] },
      { id: 's12-l3', title: 'Flash floods and water crossings', level: 'advanced', prerequisites: ['s12-l2', 's2-l2'], topics: ['Catchments', 'Force of moving water', 'When not to cross'] },
      { id: 's12-l4', title: 'Heat, cold, wind, snow and ice', level: 'intermediate', prerequisites: ['s8-l2'], topics: ['Forecast interpretation', 'Ice hazards'] },
      { id: 's12-l5', title: 'Wildfire', level: 'intermediate', prerequisites: ['s12-l1'], topics: ['Fire behavior triangle', 'Escape routes', 'Safety zones'] },
      { id: 's12-l6', title: 'Avalanches, rockfall and landslides', level: 'advanced', prerequisites: ['s12-l4', 's2-l2'], topics: ['Slope angle', 'Avalanche problems', 'Training required'] },
    ],
  },
  {
    n: 13,
    slug: 'rope',
    title: 'Rope and Terrain',
    level: 'advanced',
    summary: 'Knots, hitches, lashings, anchors and mechanical advantage — principles, not unsupervised climbing.',
    requires: [7],
    status: 'available',
    environments: ['mountain', 'forest'],
    simulations: ['mechanical-advantage'],
    outline: [
      { id: 's13-l1', title: 'Rope materials, inspection and care', level: 'intermediate', prerequisites: ['s7-l2'], topics: ['Static vs dynamic', 'Inspection', 'Retirement'] },
      { id: 's13-l2', title: 'Knots, hitches and bends', level: 'intermediate', prerequisites: ['s13-l1'], topics: ['Knot efficiency', 'Core knot set'] },
      { id: 's13-l3', title: 'Load principles and anchors', level: 'advanced', prerequisites: ['s13-l2'], topics: ['Vector angles', 'Anchor concepts'] },
      { id: 's13-l4', title: 'Hauling systems', level: 'advanced', prerequisites: ['s13-l3'], topics: ['Mechanical advantage', 'Friction losses'] },
      { id: 's13-l5', title: 'Improvised rescue systems and their limits', level: 'expert', prerequisites: ['s13-l4'], topics: ['What requires training', 'Virtual-only demos'] },
    ],
  },
  {
    n: 14,
    slug: 'signaling-rescue',
    title: 'Emergency Signaling and Rescue',
    level: 'intermediate',
    summary: 'How search and rescue actually works, and how to make yourself findable.',
    requires: [1, 2],
    status: 'available',
    environments: ['all'],
    simulations: ['search-sim', 'signal-mirror'],
    outline: [
      { id: 's14-l1', title: 'Visual and audible signals', level: 'intermediate', prerequisites: ['s1-l13'], topics: ['Mirrors', 'Lights', 'Smoke', 'Ground-to-air'] },
      { id: 's14-l2', title: 'Radio, satellite and beacons', level: 'intermediate', prerequisites: ['s14-l1'], topics: ['PLBs and Cospas-Sarsat', 'Satellite messengers', 'Radio basics'] },
      { id: 's14-l3', title: 'How searches work', level: 'advanced', prerequisites: ['s14-l2', 's2-l12'], topics: ['Probability of area and detection', 'Search tactics'] },
      { id: 's14-l4', title: 'Stay or move', level: 'advanced', prerequisites: ['s14-l3'], topics: ['Decision model', 'Leaving signs for rescuers'] },
    ],
  },
  {
    n: 15,
    slug: 'psychology',
    title: 'Survival Psychology',
    level: 'advanced',
    summary: 'Fear, bias, fatigue, leadership and group dynamics — decision making with incomplete information.',
    requires: [1],
    status: 'available',
    environments: ['all'],
    simulations: ['priority-dilemmas'],
    outline: [
      { id: 's15-l1', title: 'Fear, panic and freezing', level: 'intermediate', prerequisites: ['s1-l5'], topics: ['Neurobiology', 'Freezing', 'Panic'] },
      { id: 's15-l2', title: 'Cognitive bias in the field', level: 'advanced', prerequisites: ['s15-l1'], topics: ['Plan continuation', 'Tunnel vision', 'Risk perception'] },
      { id: 's15-l3', title: 'Isolation, uncertainty and fatigue', level: 'advanced', prerequisites: ['s8-l7'], topics: ['Decision fatigue', 'Emotional regulation'] },
      { id: 's15-l4', title: 'Leadership and group survival', level: 'advanced', prerequisites: ['s15-l2'], topics: ['Roles', 'Conflict', 'Morale'] },
    ],
  },
  {
    n: 16,
    slug: 'urban-disaster',
    title: 'Urban and Disaster Survival',
    level: 'intermediate',
    summary: 'Earthquakes, floods, fires, outages and infrastructure failure — at home and in the city.',
    requires: [1],
    status: 'available',
    environments: ['urban', 'rural'],
    simulations: ['home-kit', 'outage-72h'],
    outline: [
      { id: 's16-l1', title: 'Household emergency planning', level: 'beginner', prerequisites: ['s1-l4'], topics: ['Family plan', 'Communication plan', 'Community resources'] },
      { id: 's16-l2', title: 'Home kits: water, food, light, power', level: 'beginner', prerequisites: ['s16-l1'], topics: ['Quantities', 'Rotation', 'Lighting and power'] },
      { id: 's16-l3', title: 'Earthquake and building evacuation', level: 'intermediate', prerequisites: ['s16-l1'], topics: ['Drop, cover, hold on', 'Aftershocks', 'Evacuation'] },
      { id: 's16-l4', title: 'Flood, wildfire and extreme weather at home', level: 'intermediate', prerequisites: ['s16-l1', 's12-l3'], topics: ['Evacuation triggers', 'Shelter in place'] },
      { id: 's16-l5', title: 'Utility and communication failure', level: 'intermediate', prerequisites: ['s16-l2'], topics: ['Water outage', 'Sanitation', 'Carbon monoxide'] },
    ],
  },
  {
    n: 17,
    slug: 'vehicle-travel',
    title: 'Vehicle and Travel Survival',
    level: 'intermediate',
    summary: 'Breakdowns and strandings in heat, cold and remote country — and whether to stay with the vehicle.',
    requires: [1, 2],
    status: 'available',
    environments: ['desert', 'arctic', 'rural', 'mountain'],
    simulations: ['stranded-vehicle'],
    outline: [
      { id: 's17-l1', title: 'Vehicle kits and trip planning', level: 'beginner', prerequisites: ['s1-l9'], topics: ['Kit', 'Route plans'] },
      { id: 's17-l2', title: 'Stranded in heat', level: 'intermediate', prerequisites: ['s17-l1', 's8-l4'], topics: ['Water budget', 'Shade', 'Stay with the vehicle'] },
      { id: 's17-l3', title: 'Stranded in cold and snow', level: 'intermediate', prerequisites: ['s17-l1', 's8-l3'], topics: ['Exhaust and CO', 'Insulation'] },
      { id: 's17-l4', title: 'Roadside emergencies and remote roads', level: 'intermediate', prerequisites: ['s17-l1'], topics: ['Visibility', 'Signaling', 'Navigation failure'] },
    ],
  },
  {
    n: 18,
    slug: 'long-duration',
    title: 'Long-Duration Survival',
    level: 'advanced',
    summary: 'Sustaining yourself for days: budgets for energy, water and food, camp systems, maintenance and morale.',
    requires: [3, 4, 5, 6, 8],
    status: 'available',
    environments: ['forest', 'tropical', 'arctic', 'coastal'],
    simulations: ['multi-day'],
    outline: [
      { id: 's18-l1', title: 'Resource and energy budgeting', level: 'advanced', prerequisites: ['s6-l1', 's8-l6'], topics: ['Energy, water and food budgets'] },
      { id: 's18-l2', title: 'Camp systems and sanitation', level: 'advanced', prerequisites: ['s10-l5'], topics: ['Layout', 'Sanitation', 'Routine'] },
      { id: 's18-l3', title: 'Maintenance and repair', level: 'advanced', prerequisites: ['s10-l4'], topics: ['Tools', 'Clothing', 'Repeated fire and water'] },
      { id: 's18-l4', title: 'Sleep, morale and planning ahead', level: 'advanced', prerequisites: ['s15-l3'], topics: ['Several-day planning', 'Morale'] },
    ],
  },
  {
    n: 19,
    slug: 'capstones',
    title: 'Capstone Scenarios',
    level: 'expert',
    summary: 'Twelve integrated scenarios combining every stage, followed by the final assessment.',
    requires: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
    status: 'available',
    environments: ['all'],
    simulations: ['capstone-engine'],
    outline: [
      { id: 'cap-1', title: 'Lost in a forest', level: 'expert', prerequisites: ['s2-l12', 's14-l4'], topics: ['Relocation', 'Stay or move', 'Overnight'] },
      { id: 'cap-2', title: 'Desert survival', level: 'expert', prerequisites: ['s4-l3', 's8-l4'], topics: ['Water budget', 'Heat', 'Travel at night'] },
      { id: 'cap-3', title: 'Cold-weather survival', level: 'expert', prerequisites: ['s8-l3', 's5-l5', 's3-l4'], topics: ['Hypothermia', 'Snow shelter', 'Fire'] },
      { id: 'cap-4', title: 'Tropical environment', level: 'expert', prerequisites: ['s5-l6', 's4-l5'], topics: ['Water', 'Insects', 'Raised shelter'] },
      { id: 'cap-5', title: 'Mountain environment', level: 'expert', prerequisites: ['s8-l8', 's12-l6'], topics: ['Altitude', 'Weather', 'Terrain'] },
      { id: 'cap-6', title: 'Injured while hiking', level: 'expert', prerequisites: ['s9-l9'], topics: ['Assessment', 'Evacuation', 'Signaling'] },
      { id: 'cap-7', title: 'Lost at night', level: 'expert', prerequisites: ['s2-l9', 's8-l7'], topics: ['Night navigation', 'When to stop'] },
      { id: 'cap-8', title: 'Unexpected overnight stay', level: 'expert', prerequisites: ['s5-l3', 's3-l7'], topics: ['Improvised bivouac'] },
      { id: 'cap-9', title: 'Navigation failure', level: 'expert', prerequisites: ['s2-l12'], topics: ['Equipment loss', 'Relocation'] },
      { id: 'cap-10', title: 'Multi-day survival', level: 'expert', prerequisites: ['s18-l4'], topics: ['Budgets', 'Routine'] },
      { id: 'cap-11', title: 'Group survival', level: 'expert', prerequisites: ['s15-l4'], topics: ['Leadership', 'Casualty', 'Division of labor'] },
      { id: 'cap-12', title: 'Disaster / urban emergency', level: 'expert', prerequisites: ['s16-l5'], topics: ['Earthquake aftermath', 'Water', 'Communication'] },
      { id: 'final', title: 'Final assessment', level: 'expert', prerequisites: ['cap-1', 'cap-6', 'cap-12'], topics: ['Judgment and prioritization across every domain'] },
    ],
  },
]

export const stageByN = (n: number) => stages.find((s) => s.n === n)
