import type { Question } from '../../types'

// Stage 10 review: interleaves improvisation with earlier stages — priorities, heat balance,
// water treatment and storage, lashings, splinting and evacuation, stay-or-move.
export const stage10Review: Question[] = [
  {
    id: 's10-rev-8',
    kind: 'single',
    prompt: 'Your boot sole fails 10 km from the trailhead in the late afternoon. You have a repair kit and 2 hours of daylight; the trail is rough and there is a sheltered spot nearby. What is the best plan?',
    choices: [
      { id: 'a', text: 'Hurry on without repairing it to beat the dark', why: 'A flapping sole on rough ground in fading light invites a fall — an irreversible outcome.' },
      { id: 'b', text: 'Repair it, test it briefly, then use a turnaround trigger', why: 'Correct — fix it (ties or cord plus tape), test it for a few hundred metres, and let a trigger decide between continuing and camping at the sheltered spot.' },
      { id: 'c', text: 'Call for rescue now, before daylight runs out', why: 'A repairable problem with shelter available is not yet a rescue.' },
      { id: 'd', text: 'Walk out in your socks to save the boot from damage', why: 'Socks on rough ground cause injuries.' },
    ],
    answer: 'b',
    concepts: ['footwear-repair', 'daylight', 'decisions'],
    explanation: 'Repair, test, then decide with a clear trigger (Stage 1’s daylight logic) — reversible options first.',
  },
  {
    id: 's10-rev-2',
    kind: 'single',
    prompt: 'It is 4 °C, raining and windy. A friend’s air pad has a leak you cannot find, and your tent has a small tear. You have one rain jacket each, a spare fleece, a foam sit-pad, tape and a bin bag. What do you use for the tent tear?',
    choices: [
      { id: 'a', text: 'A patch cut from your own rain jacket', why: 'The jacket is keeping you dry in wind and rain (Stage 1 heat balance) — critical gear.' },
      { id: 'b', text: 'Tape on dry fabric, plus a split bin bag over it', why: 'Correct — non-critical materials; the fleece and sit-pad go under your friend for insulation.' },
      { id: 'c', text: 'The spare fleece, stuffed firmly into the tear', why: 'Wet fleece insulates poorly and is needed for warmth or ground insulation.' },
      { id: 'd', text: 'The foam sit-pad, taped over the tear from outside', why: 'It is needed as ground insulation for your friend.' },
    ],
    answer: 'b',
    concepts: ['critical-gear-tradeoff', 'wet-wind', 'ground-insulation'],
    explanation: 'Match properties to functions, and keep insulation and rain protection doing their own jobs.',
  },
  {
    id: 's10-rev-10',
    kind: 'single',
    prompt: 'Where do you dig a cathole at a desert camp beside the only pool for 20 km?',
    choices: [
      { id: 'a', text: 'Next to the pool, where the soil is soft and damp', why: 'Contaminates the only water source.' },
      { id: 'b', text: 'At least 60 m from pool, camp and trail, out of washes', why: 'Correct — protects the water; if the soil is thin or the rules require it, pack it out instead.' },
      { id: 'c', text: 'In the dry wash below camp, where it is easy to dig', why: 'Flash floods (Stage 12) carry waste straight into water downstream.' },
      { id: 'd', text: 'Under a big rock near the edge of the pool', why: 'Still at the water’s edge, and rocks block decomposition.' },
    ],
    answer: 'b',
    concepts: ['catholes', 'flash-flood'],
    explanation: 'Protect scarce water; stay out of drainage lines; pack out where soil or rules demand.',
  },
  {
    id: 's10-rev-5',
    kind: 'single',
    prompt: 'You splint a friend’s injured wrist with a folded foam pad. What should you use to secure it?',
    choices: [
      { id: 'a', text: 'Cable ties, pulled tight so it cannot move', why: 'Cannot be loosened as the wrist swells — dangerous.' },
      { id: 'b', text: 'Cloth or tape over padding, firm not tight; recheck CSM', why: 'Correct — adjustable, and Stage 9’s checks of circulation, sensation and movement below catch problems.' },
      { id: 'c', text: 'Wire, because it will not stretch or slip', why: 'Wire cuts in and cannot give.' },
      { id: 'd', text: 'Nothing; hold it in place by hand on the walk out', why: 'Not practical and not stable.' },
    ],
    answer: 'b',
    concepts: ['splinting', 'material-properties'],
    explanation: 'Improvised splints follow Stage 9’s principles: padding, joint above and below, adjustable securing, CSM before and after. Take a WFA course.',
  },
  {
    id: 's10-rev-9',
    kind: 'single',
    prompt: 'After a flood, your family has no running water for several days. Which step would **raise** the risk of diarrhoea?',
    choices: [
      { id: 'a', text: 'A bucket toilet lined with bags, closed and stored away', why: 'Lowers risk — primary barrier at the source, kept away from living space.' },
      { id: 'b', text: 'A tippy tap and soap by the toilet and kitchen', why: 'Lowers risk — hand-washing with little water.' },
      { id: 'c', text: 'Washing dishes in floodwater to save drinking water', why: 'Correct — floodwater is contaminated.' },
      { id: 'd', text: 'Drinking only treated or bottled water', why: 'Lowers risk — blocks the fluids route.' },
    ],
    answer: 'c',
    concepts: ['fecal-oral-route', 'hand-hygiene', 'emergency-sanitation'],
    explanation: 'The F-diagram works in a city too: contain waste, wash hands, treat water (Stage 16).',
  },
  {
    id: 's10-rev-3',
    kind: 'single',
    prompt: 'You carry lake water in a clean dry bag and treat it into bottles. Which statement is **false**?',
    choices: [
      { id: 'a', text: 'The water in the dry bag is still untreated', why: 'True — a clean container is not treatment.' },
      { id: 'b', text: 'A cloth filter over the bag makes the water safe', why: 'Correct, this is false — cloth clarifies, it does not remove bacteria or viruses (Stage 4).' },
      { id: 'c', text: 'The dry bag should be marked as the dirty container', why: 'True — keeps clean and dirty apart.' },
      { id: 'd', text: 'Treatment by boiling or chemicals still applies', why: 'True — the water still needs treating.' },
    ],
    answer: 'b',
    concepts: ['improvised-containers', 'safe-storage', 'water-treatment'],
    explanation: 'Containers move water; treatment makes it safe; storage keeps it safe.',
  },
  {
    id: 's10-rev-7',
    kind: 'single',
    prompt: 'Rebuilding a tripod for a camp water bag, you need to join the three legs at the head. Which lashing, from Stage 7?',
    choices: [
      { id: 'a', text: 'Tripod lashing: loose figure-eight weaves, then frapping', why: 'Correct — started and finished with clove hitches; loose weaves let the legs spread, frapping locks them.' },
      { id: 'b', text: 'A single overhand knot tied round all three', why: 'Slips and gives no control of the spread.' },
      { id: 'c', text: 'Several tight wraps of duct tape round the tops', why: 'Weak in tension and creeps under load.' },
      { id: 'd', text: 'Square lashing, tied tight around the three tops', why: 'For crossing poles at right angles, not three parallel legs.' },
    ],
    answer: 'a',
    concepts: ['lashings', 'tripods'],
    explanation: 'Stage 7’s tripod lashing (clove hitch, loose figure-eight weaves, frapping turns, clove hitch) is built for exactly this. Test it at ground level with twice the working load.',
  },
  {
    id: 's10-rev-1',
    kind: 'single',
    prompt: 'Your only water bottle cracks on day 2 of a desert hike. Which sequence of improvisation steps is right?',
    choices: [
      { id: 'a', text: 'Functions → properties → candidates → build → test at the source', why: 'Correct — testing at the source means a leak costs nothing.' },
      { id: 'b', text: 'Candidates → functions → properties → build → test at the source', why: 'Starting from objects invites functional fixedness; define the functions first.' },
      { id: 'c', text: 'Functions → candidates → build → properties → test at the source', why: 'Properties must be decided before you can judge candidates or build.' },
      { id: 'd', text: 'Functions → properties → candidates → build → test on the trail', why: 'A leak found on the trail, away from water, is costly; test at the source.' },
    ],
    answer: 'a',
    concepts: ['improvisation-method', 'load-testing'],
    explanation: 'Functions (hold, stay food-safe, close, carry) → properties → candidates (zip-lock bags, liner, pot) → build (bags doubled inside the pack, neck tied) → fill and test at the source, where a leak costs nothing.',
  },
  {
    id: 's10-rev-6',
    kind: 'single',
    prompt: 'For the same load, what happens to the outward push at a tripod’s feet as you splay the legs wider?',
    choices: [
      { id: 'a', text: 'It rises steeply with the splay angle', why: 'Correct — $H = W \\tan\\theta / 3$.' },
      { id: 'b', text: 'It falls, because a wider base is more stable', why: 'A wider base resists tipping, but the feet push outward harder.' },
      { id: 'c', text: 'It stays the same; only the load matters', why: 'The splay angle enters through $\\tan\\theta$.' },
      { id: 'd', text: 'It rises only on smooth rock, not on soil', why: 'The thrust is the same; smooth rock just resists it less.' },
    ],
    answer: 'a',
    concepts: ['tripods'],
    explanation: '$H = W \\tan\\theta / 3$ rises steeply with θ; anchor or tie the feet.',
  },
  {
    id: 's10-rev-4',
    kind: 'single',
    prompt: 'Five people need 5 L each for tomorrow. You can carry 7 L per trip. How many trips?',
    choices: [
      { id: 'a', text: '4 trips', why: 'Correct — 25 L ÷ 7 L = 3.6, rounded up to 4.' },
      { id: 'b', text: '3 trips', why: 'Rounded down: 3 trips carry only 21 L.' },
      { id: 'c', text: '5 trips', why: 'One trip per person ignores that each trip carries 7 L.' },
      { id: 'd', text: '1 trip', why: 'This uses one person’s 5 L instead of the group’s 25 L.' },
    ],
    answer: 'a',
    concepts: ['water-transport', 'water-needs'],
    explanation: '$D = 25$ L; $\\lceil 25/7 \\rceil = 4$ trips.',
  },
]
