import type { Question } from '../../types'

// Stage 10 review: interleaves improvisation with earlier stages — priorities, heat balance,
// water treatment and storage, lashings, splinting and evacuation, stay-or-move.
export const stage10Review: Question[] = [
  {
    id: 's10-rev-1',
    kind: 'order',
    prompt: 'Your only water bottle cracks on day 2 of a desert hike. Order the improvisation steps.',
    items: [
      { id: 'f', text: 'Define the functions: hold, stay food-safe, close, carry' },
      { id: 'p', text: 'Decide the properties each function needs' },
      { id: 'c', text: 'Lay out the kit and list candidates (zip-lock bags, liner, pot)' },
      { id: 'b', text: 'Build: bags doubled inside the pack, neck tied' },
      { id: 't', text: 'Fill and test for leaks before leaving the water source' },
    ],
    answer: ['f', 'p', 'c', 'b', 't'],
    concepts: ['improvisation-method', 'load-testing'],
    explanation: 'Function → properties → candidates → build → test. Testing at the source means a leak costs nothing.',
  },
  {
    id: 's10-rev-2',
    kind: 'single',
    prompt: 'It is 4 °C, raining and windy. A friend’s air pad has a leak you cannot find, and your tent has a small tear. You have one rain jacket each, a spare fleece, a foam sit-pad, tape and a bin bag. What do you use for the tent tear?',
    choices: [
      { id: 'a', text: 'Your rain jacket, cut into a patch', why: 'The jacket is keeping you dry in wind and rain (Stage 1 heat balance) — critical gear.' },
      { id: 'b', text: 'Tape on dry fabric, with a split bin bag taped over the outside if needed', why: 'Correct — non-critical materials; the fleece and sit-pad go under your friend for insulation.' },
      { id: 'c', text: 'The spare fleece, stuffed into the tear', why: 'Wet fleece insulates poorly and is needed for warmth or ground insulation.' },
      { id: 'd', text: 'The foam sit-pad, taped over the tear', why: 'It is needed as ground insulation for your friend.' },
    ],
    answer: 'b',
    concepts: ['critical-gear-tradeoff', 'wet-wind', 'ground-insulation'],
    explanation: 'Match properties to functions, and keep insulation and rain protection doing their own jobs.',
  },
  {
    id: 's10-rev-3',
    kind: 'multi',
    prompt: 'You carry lake water in a clean dry bag and treat it into bottles. Which statements are true?',
    choices: [
      { id: 'a', text: 'The water in the dry bag is still untreated', why: 'True — a clean container is not treatment.' },
      { id: 'b', text: 'A cloth filter over the bag makes the water safe', why: 'False — cloth clarifies, it does not remove bacteria or viruses (Stage 4).' },
      { id: 'c', text: 'Mark the dry bag as the dirty container', why: 'True — keeps clean and dirty apart.' },
      { id: 'd', text: 'Treatment by boiling or chemicals still applies', why: 'True.' },
    ],
    answer: ['a', 'c', 'd'],
    concepts: ['improvised-containers', 'safe-storage', 'water-treatment'],
    explanation: 'Containers move water; treatment makes it safe; storage keeps it safe.',
  },
  {
    id: 's10-rev-4',
    kind: 'numeric',
    prompt: 'Five people need 5 L each for tomorrow. You can carry 7 L per trip. How many trips?',
    unit: 'trips',
    answer: 4,
    tolerance: 0,
    concepts: ['water-transport', 'water-needs'],
    explanation: '$D = 25$ L; $\\lceil 25/7 \\rceil = 4$ trips.',
  },
  {
    id: 's10-rev-5',
    kind: 'single',
    prompt: 'You splint a friend’s injured wrist with a folded foam pad. What should you use to secure it?',
    choices: [
      { id: 'a', text: 'Cable ties, pulled tight so it cannot move', why: 'Cannot be loosened as the wrist swells — dangerous.' },
      { id: 'b', text: 'Tape or cloth strips over padding, firm but not tight, then check circulation, sensation and movement below', why: 'Correct — adjustable, and Stage 9’s CSM checks catch problems.' },
      { id: 'c', text: 'Wire, because it will not stretch', why: 'Wire cuts in and cannot give.' },
      { id: 'd', text: 'Nothing; hold it in place by hand for the walk out', why: 'Not practical and not stable.' },
    ],
    answer: 'b',
    concepts: ['splinting', 'material-properties'],
    explanation: 'Improvised splints follow Stage 9’s principles: padding, joint above and below, adjustable securing, CSM before and after. Take a WFA course.',
  },
  {
    id: 's10-rev-6',
    kind: 'truefalse',
    prompt: 'A tripod with legs splayed wider pushes outward harder at its feet for the same load.',
    answer: true,
    concepts: ['tripods'],
    explanation: '$H = W \\tan\\theta / 3$ rises steeply with θ; anchor or tie the feet.',
  },
  {
    id: 's10-rev-7',
    kind: 'single',
    prompt: 'Rebuilding a tripod for a camp water bag, you need to join the three legs at the head. Which lashing, from Stage 7?',
    choices: [
      { id: 'a', text: 'Tripod lashing: clove hitch, loose figure-eight weaves, frapping turns, clove hitch', why: 'Correct — loose weaves let the legs spread, frapping locks them.' },
      { id: 'b', text: 'A single overhand knot round all three', why: 'Slips and gives no control of the spread.' },
      { id: 'c', text: 'Duct tape round the three tops', why: 'Weak in tension and creeps under load.' },
      { id: 'd', text: 'Square lashing', why: 'For crossing poles at right angles, not three parallel legs.' },
    ],
    answer: 'a',
    concepts: ['lashings', 'tripods'],
    explanation: 'Stage 7’s tripod lashing is built for exactly this. Test it at ground level with twice the working load.',
  },
  {
    id: 's10-rev-8',
    kind: 'single',
    prompt: 'Your boot sole fails 10 km from the trailhead in the late afternoon. You have a repair kit and 2 hours of daylight; the trail is rough and there is a sheltered spot nearby. What is the best plan?',
    choices: [
      { id: 'a', text: 'Hurry on without repairing it to beat the dark', why: 'A flapping sole on rough ground in fading light invites a fall — an irreversible outcome.' },
      { id: 'b', text: 'Repair it now (ties or cord plus tape), test it for a few hundred metres, and decide by a turnaround trigger whether to continue or camp at the sheltered spot', why: 'Correct — fixes the failure, tests it, and uses Stage 1’s trigger and daylight logic.' },
      { id: 'c', text: 'Call for rescue at once', why: 'A repairable problem with shelter available is not yet a rescue.' },
      { id: 'd', text: 'Walk in socks to save the boot', why: 'Socks on rough ground cause injuries.' },
    ],
    answer: 'b',
    concepts: ['footwear-repair', 'daylight', 'decisions'],
    explanation: 'Repair, test, then decide with a clear trigger — reversible options first.',
  },
  {
    id: 's10-rev-9',
    kind: 'multi',
    prompt: 'After a flood, your family has no running water for several days. Which hygiene steps reduce the risk of diarrhoea?',
    choices: [
      { id: 'a', text: 'A bucket toilet lined with bags, closed and stored away from living space', why: 'Yes — primary barrier at the source.' },
      { id: 'b', text: 'A tippy tap and soap by the toilet and kitchen', why: 'Yes — hand-washing with little water.' },
      { id: 'c', text: 'Washing dishes in floodwater to save drinking water', why: 'No — floodwater is contaminated.' },
      { id: 'd', text: 'Drinking only treated or bottled water', why: 'Yes — blocks the fluids route.' },
    ],
    answer: ['a', 'b', 'd'],
    concepts: ['fecal-oral-route', 'hand-hygiene', 'emergency-sanitation'],
    explanation: 'The F-diagram works in a city too: contain waste, wash hands, treat water (Stage 16).',
  },
  {
    id: 's10-rev-10',
    kind: 'single',
    prompt: 'Where do you dig a cathole at a desert camp beside the only pool for 20 km?',
    choices: [
      { id: 'a', text: 'Next to the pool, where the soil is soft and damp', why: 'Contaminates the only water source.' },
      { id: 'b', text: 'At least 60 m from the pool, camp and trail, out of any wash or drainage — or pack it out if the soil is thin or the rules require it', why: 'Correct — protects the water; desert soil often calls for pack-out.' },
      { id: 'c', text: 'In the dry wash below camp, where it is easy to dig', why: 'Flash floods (Stage 12) carry waste straight into water downstream.' },
      { id: 'd', text: 'Under a rock at the pool’s edge', why: 'Still at the water’s edge, and rocks block decomposition.' },
    ],
    answer: 'b',
    concepts: ['catholes', 'flash-flood'],
    explanation: 'Protect scarce water; stay out of drainage lines; pack out where soil or rules demand.',
  },
]
