import type { Question } from '../../types'

// Stage 1 review: interleaved, judgment-focused questions that mix topics from across the stage.
export const stage1Review: Question[] = [
  {
    id: 's1-rev-1',
    kind: 'single',
    prompt: 'Subarctic, −15 °C, calm, 15:00, sunset 15:40. Your snowmobile has failed 12 km from the cabin. You have a stove, insulated clothing, a bivy bag, a satellite messenger and food. Which action has the highest value right now?',
    choices: [
      { id: 'a', text: 'Start walking now so you reach the cabin tonight, before it gets colder.', why: '12 km in snow at dusk will take many hours, cause sweating, and ends in darkness far from the machine.' },
      { id: 'b', text: 'Message your position, then add insulation and set up a spot by the machine.', why: 'Best: communication is cheap and decisive; insulation counters the sudden drop in heat production; the machine is a visible marker.' },
      { id: 'c', text: 'Spend the next hour trying to repair the engine while you still have light.', why: 'Possibly worthwhile later — but not before communication and protection while light remains.' },
      { id: 'd', text: 'Eat snow as you work to stay hydrated, and save the stove fuel for later.', why: 'Eating snow costs body heat; melt it on the stove instead.' },
    ],
    answer: 'b',
    concepts: ['priorities', 'stay-or-move', 'heat-balance'],
    explanation: 'Communication and protection first; the vehicle is shelter material and a search target.',
  },
  {
    id: 's1-rev-2',
    kind: 'single',
    prompt: 'In cold, windy conditions, which choice **increases** evaporative heat loss?',
    choices: [
      { id: 'a', text: 'Slowing your pace to avoid sweating', why: 'Reduces it — less sweat to evaporate.' },
      { id: 'b', text: 'Putting a shell over damp layers', why: 'Reduces it — the shell cuts wind-driven evaporation.' },
      { id: 'c', text: 'Drying a wet shirt by wearing it in the wind', why: 'Correct — that evaporation takes its heat from you.' },
      { id: 'd', text: 'Breathing through a scarf or buff', why: 'Reduces it a little — less respiratory heat and water loss.' },
    ],
    answer: 'c',
    concepts: ['heat-loss', 'clothing'],
    explanation: 'Evaporation removes ~2.4 MJ per litre. Prevent sweat and shield damp layers from wind.',
  },
  {
    id: 's1-rev-3',
    kind: 'single',
    prompt: 'You find an unconscious hiker in a gully with thunder upstream. Which order of first actions is correct?',
    choices: [
      { id: 'a', text: 'Remove danger → airway and bleeding → call for help → insulate', why: 'Correct — scene safety, then life threats, then call and protect.' },
      { id: 'b', text: 'Airway and bleeding → remove danger → call for help → insulate', why: 'A flash flood can take you both; scene safety comes before patient care.' },
      { id: 'c', text: 'Remove danger → call for help → airway and bleeding → insulate', why: 'A blocked airway or major bleed kills in minutes; check them before calling.' },
      { id: 'd', text: 'Call for help → remove danger → airway and bleeding → insulate', why: 'With flash-flood risk, the immediate danger must be dealt with first.' },
    ],
    answer: 'a',
    concepts: ['immediate-danger', 'priorities'],
    explanation: 'Scene safety before patient care; airway and bleeding before everything else; then call and protect. (Stage 9 teaches this properly — take a hands-on course.)',
  },
  {
    id: 's1-rev-4',
    kind: 'single',
    prompt: 'Sunset 18:05; twilight gives 20 min more. Camp setup needs 1 h and you want a 15-minute safety margin. Each relocation attempt takes 30 min. It is now 16:25. How many **full** relocation attempts fit before you must start setting up?',
    choices: [
      { id: 'a', text: '1 attempt', why: 'Correct — latest setup start is 17:10, which leaves 45 min: one full attempt.' },
      { id: 'b', text: '2 attempts', why: 'This forgets the 15-minute safety margin (start by 17:25, 60 min).' },
      { id: 'c', text: '0 attempts', why: 'This ignores the 20 minutes of twilight (start by 16:50, only 25 min).' },
      { id: 'd', text: '3 attempts', why: 'This forgets to reserve the 1 h for camp setup (105 min available).' },
    ],
    answer: 'a',
    concepts: ['daylight', 'decisions'],
    explanation: 'Latest setup start = 18:05 + 0:20 − 1:00 − 0:15 = 17:10. From 16:25 that is 45 min → **1** full attempt.',
  },
  {
    id: 's1-rev-5',
    kind: 'single',
    prompt: 'Which water plan is safest for a stream below a village, using a 0.2 µm filter and chlorine tablets?',
    choices: [
      { id: 'a', text: 'Chlorine only', why: 'Leaves Cryptosporidium risk.' },
      { id: 'b', text: 'Filter only', why: 'Leaves viral risk from the village.' },
      { id: 'c', text: 'Settle/pre-filter, filter, then chlorine', why: 'Correct — the filter covers protozoa; chlorine covers viruses; clearer water improves both.' },
      { id: 'd', text: 'Neither — fast water is safe', why: 'Not below a village.' },
    ],
    answer: 'c',
    concepts: ['water-treatment'],
    explanation: 'Combine methods whose gaps don’t overlap.',
  },
  {
    id: 's1-rev-6',
    kind: 'single',
    prompt: '"Everyone else is carrying on up — let’s not be the ones who turn back." Which human-factor trap is this?',
    choices: [
      { id: 'a', text: 'Social facilitation / acceptance', why: 'Correct — the presence and opinions of others are driving risk.' },
      { id: 'b', text: 'Familiarity', why: 'No — familiarity is about a known place.' },
      { id: 'c', text: 'Scarcity', why: 'Not about a rare opportunity.' },
      { id: 'd', text: 'None; it is sound reasoning', why: 'Others’ choices are not evidence about your risk.' },
    ],
    answer: 'a',
    concepts: ['human-factors'],
    explanation: 'Name the trap out loud; then decide on the evidence.',
  },
  {
    id: 's1-rev-7',
    kind: 'single',
    prompt: 'At dusk in the rain, with 30 minutes of light left, which shelter plan is usually worth the most?',
    choices: [
      { id: 'a', text: 'A quick, low tarp and a thick leaf bed, finished before dark.', why: 'Correct — simple, finished protection covers rain, wind and the ground.' },
      { id: 'b', text: 'A well-built debris hut, even if it is unfinished at dark.', why: 'An ambitious, unfinished structure protects less than a simple, finished one.' },
      { id: 'c', text: 'A big fire first; the shelter can be built by its light.', why: 'Building in the dark and rain is slow; protection should be in place before dark.' },
      { id: 'd', text: 'Keep moving to find a natural shelter such as an overhang.', why: 'Searching in fading light spends the time you need to build simple protection.' },
    ],
    answer: 'a',
    concepts: ['shelter-types', 'priorities'],
    explanation: 'Simple, finished protection beats ambitious, unfinished structures.',
  },
  {
    id: 's1-rev-8',
    kind: 'single',
    prompt: 'You need to signal a helicopter on a sunny afternoon. What is the most detectable signal you are likely to have?',
    choices: [
      { id: 'a', text: 'Whistle', why: 'Inaudible over rotor noise.' },
      { id: 'b', text: 'A mirror flash from open ground', why: 'Correct — visible for many kilometres.' },
      { id: 'c', text: 'Shouting', why: 'Inaudible and exhausting.' },
      { id: 'd', text: 'A headlamp', why: 'Weak in daylight compared with a mirror.' },
    ],
    answer: 'b',
    concepts: ['signaling', 'visibility'],
    explanation: 'Brightness beats size at long range, and open ground beats canopy.',
  },
  {
    id: 's1-rev-9',
    kind: 'single',
    prompt: 'Which kit change does **NOT** improve **diverse redundancy**?',
    choices: [
      { id: 'a', text: 'Adding a ferro rod to a kit that has a lighter', why: 'Improves it — different failure modes.' },
      { id: 'b', text: 'Adding a second identical phone', why: 'Correct — same failure modes (cold, no coverage).' },
      { id: 'c', text: 'Adding a paper map + compass to phone navigation', why: 'Improves it — paper does not need a battery or signal.' },
      { id: 'd', text: 'Adding a PLB to a phone-only kit for remote trips', why: 'Improves it — works without coverage.' },
    ],
    answer: 'b',
    concepts: ['redundancy', 'kit'],
    explanation: 'Redundancy should fail differently.',
  },
  {
    id: 's1-rev-10',
    kind: 'single',
    prompt: 'Your partner becomes withdrawn and stops helping after dark on an unplanned bivouac. What do you do?',
    choices: [
      { id: 'a', text: 'Leave them to rest and quietly do every job yourself tonight.', why: 'Increases your load and their helplessness.' },
      { id: 'b', text: 'Give them a small task and a choice, like which wood to burn first.', why: 'Correct — restores agency and routine.' },
      { id: 'c', text: 'Tell them firmly to snap out of it and start pulling their weight.', why: 'Rarely works; may worsen things.' },
      { id: 'd', text: 'Decide to walk out right away, in the dark, to lift their spirits.', why: 'An irreversible decision driven by emotion.' },
    ],
    answer: 'b',
    concepts: ['stress-control'],
    explanation: 'Small tasks and choices — "Can you keep the fire going, birch or pine first?" — counter withdrawal and passivity.',
  },
]
