import type { Question } from '../../types'

// Stage 1 review: interleaved, judgment-focused questions that mix topics from across the stage.
export const stage1Review: Question[] = [
  {
    id: 's1-rev-1',
    kind: 'single',
    prompt: 'Subarctic, −15 °C, calm, 15:00, sunset 15:40. Your snowmobile has failed 12 km from the cabin. You have a stove, insulated clothing, a bivy bag, a satellite messenger and food. Which action has the highest value right now?',
    choices: [
      { id: 'a', text: 'Start walking immediately to reach the cabin tonight.', why: '12 km in snow at dusk will take many hours, cause sweating, and ends in darkness far from the machine.' },
      { id: 'b', text: 'Send a satellite message with position, then add insulation and prepare a sheltered spot beside the machine.', why: 'Best: communication is cheap and decisive; insulation counters the sudden drop in heat production; the machine is a visible marker.' },
      { id: 'c', text: 'Try to repair the engine for the next hour.', why: 'Possibly worthwhile later — but not before communication and protection while light remains.' },
      { id: 'd', text: 'Eat snow to stay hydrated.', why: 'Costs body heat; melt it on the stove instead.' },
    ],
    answer: 'b',
    concepts: ['priorities', 'stay-or-move', 'heat-balance'],
    explanation: 'Communication and protection first; the vehicle is shelter material and a search target.',
  },
  {
    id: 's1-rev-2',
    kind: 'multi',
    prompt: 'Which choices **reduce evaporative heat loss** in cold, windy conditions?',
    choices: [
      { id: 'a', text: 'Slowing your pace to avoid sweating', why: 'Yes.' },
      { id: 'b', text: 'Putting a shell over damp layers', why: 'Yes — reduces wind-driven evaporation.' },
      { id: 'c', text: 'Drying a wet shirt by wearing it in the wind', why: 'No — that evaporation takes heat from you.' },
      { id: 'd', text: 'Breathing through a scarf or buff', why: 'Yes — reduces respiratory heat and water loss a little.' },
    ],
    answer: ['a', 'b', 'd'],
    concepts: ['heat-loss', 'clothing'],
    explanation: 'Evaporation removes ~2.4 MJ per litre. Prevent sweat and shield damp layers from wind.',
  },
  {
    id: 's1-rev-3',
    kind: 'order',
    prompt: 'You find an unconscious hiker in a gully with thunder upstream. Order your first actions.',
    items: [
      { id: 'danger', text: 'Assess and remove immediate danger (flash-flood risk)' },
      { id: 'abc', text: 'Check airway and breathing; control major bleeding' },
      { id: 'call', text: 'Call for help with your location' },
      { id: 'warm', text: 'Insulate the person from the ground and weather' },
    ],
    answer: ['danger', 'abc', 'call', 'warm'],
    concepts: ['immediate-danger', 'priorities'],
    explanation: 'Scene safety before patient care; airway and bleeding before everything else; then call and protect. (Stage 9 teaches this properly — take a hands-on course.)',
  },
  {
    id: 's1-rev-4',
    kind: 'numeric',
    prompt: 'Sunset 18:05; twilight gives 20 min more. Camp setup needs 1 h and you want a 15-minute safety margin. Each relocation attempt takes 30 min. It is now 16:25. How many **full** relocation attempts fit before you must start setting up?',
    unit: 'attempts',
    answer: 1,
    tolerance: 0,
    concepts: ['daylight', 'decisions'],
    explanation: 'Latest setup start = 18:05 + 0:20 − 1:00 − 0:15 = 17:10. From 16:25 that is 45 min → **1** full attempt.',
  },
  {
    id: 's1-rev-5',
    kind: 'single',
    prompt: 'Which water plan is safest for a stream below a village, using a 0.2 µm filter and chlorine tablets?',
    choices: [
      { id: 'a', text: 'Chlorine only', why: 'Leaves Cryptosporidium risk.' },
      { id: 'b', text: 'Filter only', why: 'Leaves viral risk from the village.' },
      { id: 'c', text: 'Settle/pre-filter, filter, then chlorine', why: 'Correct — the filter covers protozoa; chlorine covers viruses; clearer water improves both.' },
      { id: 'd', text: 'Neither — fast water is safe', why: 'Not below a village.' },
    ],
    answer: 'c',
    concepts: ['water-treatment'],
    explanation: 'Combine methods whose gaps don’t overlap.',
  },
  {
    id: 's1-rev-6',
    kind: 'single',
    prompt: '"Everyone else is carrying on up — let’s not be the ones who turn back." Which human-factor trap is this?',
    choices: [
      { id: 'a', text: 'Social facilitation / acceptance', why: 'Correct — the presence and opinions of others are driving risk.' },
      { id: 'b', text: 'Familiarity', why: 'No — familiarity is about a known place.' },
      { id: 'c', text: 'Scarcity', why: 'Not about a rare opportunity.' },
      { id: 'd', text: 'None; it is sound reasoning', why: 'Others’ choices are not evidence about your risk.' },
    ],
    answer: 'a',
    concepts: ['human-factors'],
    explanation: 'Name the trap out loud; then decide on the evidence.',
  },
  {
    id: 's1-rev-7',
    kind: 'truefalse',
    prompt: 'At dusk in the rain, with 30 minutes of light, a quick low tarp and a thick leaf bed are usually worth more than an unfinished "perfect" shelter.',
    answer: true,
    concepts: ['shelter-types', 'priorities'],
    explanation: 'Simple, finished protection beats ambitious, unfinished structures.',
  },
  {
    id: 's1-rev-8',
    kind: 'single',
    prompt: 'You need to signal a helicopter on a sunny afternoon. What is the most detectable signal you are likely to have?',
    choices: [
      { id: 'a', text: 'Whistle', why: 'Inaudible over rotor noise.' },
      { id: 'b', text: 'A mirror flash from open ground', why: 'Correct — visible for many kilometres.' },
      { id: 'c', text: 'Shouting', why: 'Inaudible and exhausting.' },
      { id: 'd', text: 'A headlamp', why: 'Weak in daylight compared with a mirror.' },
    ],
    answer: 'b',
    concepts: ['signaling', 'visibility'],
    explanation: 'Brightness beats size at long range, and open ground beats canopy.',
  },
  {
    id: 's1-rev-9',
    kind: 'multi',
    prompt: 'Which kit changes improve **diverse redundancy**?',
    choices: [
      { id: 'a', text: 'Adding a ferro rod to a kit that has a lighter', why: 'Yes — different failure modes.' },
      { id: 'b', text: 'Adding a second identical phone', why: 'Same failure modes (cold, no coverage).' },
      { id: 'c', text: 'Adding a paper map + compass to phone navigation', why: 'Yes.' },
      { id: 'd', text: 'Adding a PLB to a phone-only kit for remote trips', why: 'Yes — works without coverage.' },
    ],
    answer: ['a', 'c', 'd'],
    concepts: ['redundancy', 'kit'],
    explanation: 'Redundancy should fail differently.',
  },
  {
    id: 's1-rev-10',
    kind: 'single',
    prompt: 'Your partner becomes withdrawn and stops helping after dark on an unplanned bivouac. What do you do?',
    choices: [
      { id: 'a', text: 'Leave them to rest and do everything yourself.', why: 'Increases your load and their helplessness.' },
      { id: 'b', text: 'Give them a small, concrete task and a choice ("Can you keep the fire going — birch or pine first?").', why: 'Correct — restores agency and routine.' },
      { id: 'c', text: 'Tell them to snap out of it.', why: 'Rarely works; may worsen things.' },
      { id: 'd', text: 'Decide to walk out immediately to cheer them up.', why: 'An irreversible decision driven by emotion.' },
    ],
    answer: 'b',
    concepts: ['stress-control'],
    explanation: 'Small tasks and choices counter withdrawal and passivity.',
  },
]
