import type { Question } from '../../types'

// Stage 4 review: interleaved questions that mix water topics with Stage 1 foundations
// (priorities, heat balance, stay-or-move, daylight, risk, kit redundancy).
export const stage4Review: Question[] = [
  {
    id: 's4-rev-1',
    kind: 'single',
    prompt: 'Lost at 14:00 in 36 °C semi-desert with 1.5 L of water, a phone with 30 % battery and one bar of signal. What is the highest-value first action?',
    choices: [
      { id: 'a', text: 'Hike to the nearest ridge to look for water', why: 'Midday travel costs ~1.3 L/h — nearly all your water — for an uncertain gain.' },
      { id: 'b', text: 'Call or message for help with your location, then get into shade and cut sweat until the cool of the evening', why: 'Best: communication is cheap and decisive; shade protects the water inside you.' },
      { id: 'c', text: 'Drink only sips to stretch the 1.5 L', why: 'Rationing does not reduce sweat; judgment degrades as you dehydrate.' },
      { id: 'd', text: 'Dig a solar still immediately', why: 'Digging at 14:00 costs more sweat than a still returns in a day.' },
    ],
    answer: 'b',
    concepts: ['priorities', 'water-budget', 'solar-still'],
    explanation: 'Stage 1 priorities first (communication, protection), then a water plan built on cutting losses.',
  },
  {
    id: 's4-rev-2',
    kind: 'numeric',
    prompt: 'You weighed 68.0 kg before a 2.5 h desert walk and 66.3 kg after, having drunk 0.8 L and not urinated. What was your sweat rate in **L/h**? (Two decimals.)',
    unit: 'L/h',
    answer: 1.0,
    tolerance: 0.03,
    concepts: ['sweat-rate'],
    explanation: '(68.0 − 66.3 + 0.8) / 2.5 = 2.5 / 2.5 = **1.00 L/h**. You also ended 2.5 % down.',
  },
  {
    id: 's4-rev-3',
    kind: 'multi',
    prompt: 'Evaporating water absorbs about 2.4 MJ per litre (Stage 1). Which statements follow from that one number?',
    choices: [
      { id: 'a', text: 'A solar still can never yield more than about H × A / 2.4 litres per day, and in practice ~15 % of that at best', why: 'Yes — the energy ceiling of a still.' },
      { id: 'b', text: 'Wet clothing in wind chills you fast', why: 'Yes — evaporation removes a lot of body heat.' },
      { id: 'c', text: 'Sweat that drips off without evaporating (humid tropics) removes water but little heat', why: 'Yes — cooling comes from evaporation, not from sweating itself.' },
      { id: 'd', text: 'Boiling water at altitude is ineffective', why: 'No — unrelated; boiling still works at altitude.' },
    ],
    answer: ['a', 'b', 'c'],
    concepts: ['solar-still', 'heat-loss', 'body-water'],
    explanation: 'The latent heat of evaporation links heat balance, sweating and still yields.',
  },
  {
    id: 's4-rev-4',
    kind: 'single',
    prompt: 'A stream runs through a sheep pasture and past a mountain hut before reaching you. You have a 0.1 µm filter and chlorine tablets. The water is clear and 4 °C. Best chain?',
    choices: [
      { id: 'a', text: 'Filter only', why: 'Leaves viral risk from the hut.' },
      { id: 'b', text: 'Chlorine only, 30 minutes', why: 'Misses Crypto from the sheep; Giardia under-treated in cold water.' },
      { id: 'c', text: 'Filter, then chlorine with a longer contact time because the water is cold', why: 'Correct — filter covers protozoa and bacteria, chlorine covers viruses; CT rises in cold water.' },
      { id: 'd', text: 'Nothing — it is clear and cold', why: 'Clear and cold says nothing about pathogens.' },
    ],
    answer: 'c',
    concepts: ['log-reduction', 'ct-disinfection', 'pathogen-classes'],
    explanation: 'Read upstream, then stack barriers whose gaps don’t overlap; adjust contact time for temperature.',
  },
  {
    id: 's4-rev-5',
    kind: 'order',
    prompt: 'Your car is stranded in the desert; help is 24–48 h away. Order these actions.',
    items: [
      { id: 'danger', text: 'Move away from traffic or other immediate danger' },
      { id: 'comms', text: 'Send your location and situation' },
      { id: 'shade', text: 'Rig shade raised off the hot ground next to the vehicle' },
      { id: 'water', text: 'Inventory water and set a drink plan based on low-sweat routine' },
      { id: 'dusk', text: 'At dusk, prepare signals and consider a nearby, low-cost water search' },
    ],
    answer: ['danger', 'comms', 'shade', 'water', 'dusk'],
    concepts: ['priorities', 'stay-or-move', 'water-budget'],
    explanation: 'Immediate danger → communication → protection (which is also water conservation) → water plan → cool-hours tasks.',
  },
  {
    id: 's4-rev-6',
    kind: 'truefalse',
    prompt: 'Because boiling kills every pathogen class, boiling floodwater makes it safe to drink.',
    answer: false,
    concepts: ['chemical-contamination'],
    explanation: 'Floodwater carries fuel, pesticides and industrial chemicals that boiling does not remove (and slightly concentrates). Use stored water or another source.',
  },
  {
    id: 's4-rev-7',
    kind: 'numeric',
    prompt: 'Your winter trip: 2 people × 4 days × 3.5 L/day, all from snow at −10 °C, brought to a boil (~800 kJ per litre total). Your stove delivers ~23 kJ per gram of gas. How many **grams** of gas do you need for water alone? (Nearest 10 g.)',
    unit: 'g',
    answer: 970,
    tolerance: 30,
    concepts: ['snowmelt', 'water-budget'],
    explanation: '28 L × 800 kJ = 22,400 kJ; / 23 ≈ **970 g** — about four 230 g canisters. Finding open water, melting without boiling and treating chemically cuts this dramatically.',
  },
  {
    id: 's4-rev-8',
    kind: 'single',
    prompt: 'Redundancy (Stage 1 kit design) applied to water treatment means…',
    choices: [
      { id: 'a', text: 'Carrying two identical filters', why: 'Better than one, but both share the same gap (viruses) and the same failure (freezing, clogging).' },
      { id: 'b', text: 'Carrying methods with different failure modes: e.g., filter + chemical tablets + a way to boil', why: 'Correct — diverse redundancy covers both hazard gaps and equipment failures.' },
      { id: 'c', text: 'Carrying extra water so you never need treatment', why: 'Weight limits make this impossible for longer trips.' },
      { id: 'd', text: 'Using the strongest single method only', why: 'Every single method has a hole.' },
    ],
    answer: 'b',
    concepts: ['redundancy', 'kit', 'water-treatment'],
    explanation: 'Critical functions need backups that fail differently — the Stage 1 kit rule, applied to water.',
  },
  {
    id: 's4-rev-9',
    kind: 'multi',
    prompt: 'Which make SODIS **fail**?',
    choices: [
      { id: 'a', text: 'Water too cloudy to read print through the bottle', why: 'Yes — particles shade microbes.' },
      { id: 'b', text: 'A 10 L clear container', why: 'Yes — too deep for UV to reach all the water.' },
      { id: 'c', text: 'Only 3 hours of sun on a cloudy day', why: 'Yes — needs ≥ 6 h sun or 2 days under cloud.' },
      { id: 'd', text: 'Laying bottles flat on a sheet-metal roof', why: 'No — that is the recommended way.' },
    ],
    answer: ['a', 'b', 'c'],
    concepts: ['sodis', 'turbidity'],
    explanation: 'SODIS is a dose of UV-A and heat; clarity, depth and time control the dose.',
  },
  {
    id: 's4-rev-10',
    kind: 'single',
    prompt: 'At 17:00 you spot a line of green reeds 3 km away across rough ground. Sunset is 18:30 and twilight adds 20 min. You have 0.5 L, a tarp, and a known spring 1 km behind you on the trail you came in on. What is the best choice?',
    choices: [
      { id: 'a', text: 'Head for the reeds — more water there', why: '3 km of rough ground plus finding the water won’t fit in 1 h 50 min of light with any margin; you would arrive in the dark at an uncertain source.' },
      { id: 'b', text: 'Return to the known spring on the trail, treat water, and camp nearby', why: 'Best: certain water, known route, fits the daylight budget; the reeds can wait for morning.' },
      { id: 'c', text: 'Stay put and wait for rain', why: 'No rain forecast; 0.5 L is not enough for the night and morning.' },
      { id: 'd', text: 'Dig a still where you are', why: 'Late in the day, no damp soil — negligible yield, real sweat cost.' },
    ],
    answer: 'b',
    concepts: ['daylight', 'water-finding', 'decisions'],
    explanation: 'A certain source within the daylight budget beats an uncertain one beyond it (Stage 1 daylight and reversibility).',
  },
]
