import type { Question } from '../../types'

// Stage 4 review: interleaved questions that mix water topics with Stage 1 foundations
// (priorities, heat balance, stay-or-move, daylight, risk, kit redundancy).
export const stage4Review: Question[] = [
  {
    id: 's4-rev-1',
    kind: 'single',
    prompt: 'Lost at 14:00 in 36 °C semi-desert with 1.5 L of water, a phone with 30 % battery and one bar of signal. What is the highest-value first action?',
    choices: [
      { id: 'a', text: 'Hike to the nearest ridge to look for water and a signal', why: 'Midday travel costs ~1.3 L/h — nearly all your water — for an uncertain gain.' },
      { id: 'b', text: 'Call or message your location, then shade up until evening', why: 'Best: communication is cheap and decisive; shade cuts sweat and protects the water inside you until the cool of the evening.' },
      { id: 'c', text: 'Drink only small sips to make the 1.5 L last until rescue', why: 'Rationing does not reduce sweat; judgment degrades as you dehydrate.' },
      { id: 'd', text: 'Dig a solar still at once, while you still have the energy', why: 'Digging at 14:00 costs more sweat than a still returns in a day.' },
    ],
    answer: 'b',
    concepts: ['priorities', 'water-budget', 'solar-still'],
    explanation: 'Stage 1 priorities first (communication, protection), then a water plan built on cutting losses.',
  },
  {
    id: 's4-rev-2',
    kind: 'single',
    prompt: 'You weighed 68.0 kg before a 2.5 h desert walk and 66.3 kg after, having drunk 0.8 L and not urinated. What was your sweat rate?',
    choices: [
      { id: 'a', text: '0.68 L/h', why: 'This forgets to add the 0.8 L you drank: 1.7 / 2.5 = 0.68.' },
      { id: 'b', text: '2.50 L/h', why: '2.5 L is the total sweat loss; it still needs dividing by 2.5 hours.' },
      { id: 'c', text: '0.36 L/h', why: 'This subtracts the drink instead of adding it: (1.7 − 0.8) / 2.5.' },
      { id: 'd', text: '1.00 L/h', why: 'Correct — (68.0 − 66.3 + 0.8) / 2.5 = 2.5 / 2.5 = 1.00 L/h.' },
    ],
    answer: 'd',
    concepts: ['sweat-rate'],
    explanation: '(68.0 − 66.3 + 0.8) / 2.5 = 2.5 / 2.5 = **1.00 L/h**. You also ended 2.5 % down.',
  },
  {
    id: 's4-rev-3',
    kind: 'single',
    prompt: 'Evaporating water absorbs about 2.4 MJ per litre (Stage 1). Which statement does **not** follow from that one number?',
    choices: [
      { id: 'a', text: 'A solar still’s yield is capped near H × A / 2.4 litres per day', why: 'Follows — the energy ceiling of a still, and in practice ~15 % of that at best.' },
      { id: 'b', text: 'Wet clothing in wind chills you fast', why: 'Follows — evaporation removes a lot of body heat.' },
      { id: 'c', text: 'Sweat that drips off unevaporated removes water but little heat', why: 'Follows — cooling comes from evaporation, not from sweating itself (humid tropics).' },
      { id: 'd', text: 'Boiling water at altitude is ineffective', why: 'Correct — this does not follow and is false anyway; boiling still works at altitude.' },
    ],
    answer: 'd',
    concepts: ['solar-still', 'heat-loss', 'body-water'],
    explanation: 'The latent heat of evaporation links heat balance, sweating and still yields — but has nothing to do with boiling as a treatment, which still works at altitude.',
  },
  {
    id: 's4-rev-4',
    kind: 'single',
    prompt: 'A stream runs through a sheep pasture and past a mountain hut before reaching you. You have a 0.1 µm filter and chlorine tablets. The water is clear and 4 °C. Best chain?',
    choices: [
      { id: 'a', text: 'Filter only, since it removes protozoa and bacteria', why: 'Leaves viral risk from the hut.' },
      { id: 'b', text: 'Chlorine only, with the usual 30-minute contact time', why: 'Misses Crypto from the sheep; Giardia under-treated in cold water.' },
      { id: 'c', text: 'Filter, then chlorine with a longer contact time', why: 'Correct — filter covers protozoa and bacteria, chlorine covers viruses; CT rises in cold water.' },
      { id: 'd', text: 'Nothing, because clear 4 °C water is low-risk', why: 'Clear and cold says nothing about pathogens.' },
    ],
    answer: 'c',
    concepts: ['log-reduction', 'ct-disinfection', 'pathogen-classes'],
    explanation: 'Read upstream, then stack barriers whose gaps don’t overlap; adjust contact time for temperature.',
  },
  {
    id: 's4-rev-5',
    kind: 'single',
    prompt: 'Your car is stranded in the desert; help is 24–48 h away. Which order of actions is right?',
    choices: [
      { id: 'a', text: 'Clear danger → send location → rig shade → water plan → dusk tasks', why: 'Correct — danger, communication, protection (which is also water conservation), water plan, cool-hours tasks.' },
      { id: 'b', text: 'Send location → rig shade → clear danger → water plan → dusk tasks', why: 'Immediate danger such as traffic comes before everything else.' },
      { id: 'c', text: 'Clear danger → water plan → send location → rig shade → dusk tasks', why: 'Communication is cheap and decisive; send your location before planning water.' },
      { id: 'd', text: 'Clear danger → send location → water plan → dusk tasks → rig shade', why: 'Shade raised off the hot ground is your main water saver; rig it early, not at dusk.' },
    ],
    answer: 'a',
    concepts: ['priorities', 'stay-or-move', 'water-budget'],
    explanation: 'Immediate danger → communication → protection (shade off the hot ground, which is also water conservation) → water plan → cool-hours tasks such as signals and a low-cost water search.',
  },
  {
    id: 's4-rev-6',
    kind: 'single',
    prompt: 'After a flood, a neighbour plans to boil floodwater from the street for drinking. What should you tell them?',
    choices: [
      { id: 'a', text: 'Fine: boiling kills every pathogen class, so it is then safe', why: 'Boiling handles pathogens but not the chemicals floodwater carries.' },
      { id: 'b', text: 'Don’t: boiling leaves fuel and chemicals, even concentrating them', why: 'Correct — use stored water or another source.' },
      { id: 'c', text: 'Fine, if they boil it for 10 minutes rather than just one', why: 'Longer boiling does not remove chemicals; it concentrates them further.' },
      { id: 'd', text: 'Fine, if they let it settle first and boil only the clear top', why: 'Settling removes silt, not dissolved fuel, pesticides or industrial chemicals.' },
    ],
    answer: 'b',
    concepts: ['chemical-contamination'],
    explanation: 'Floodwater carries fuel, pesticides and industrial chemicals that boiling does not remove (and slightly concentrates). Use stored water or another source.',
  },
  {
    id: 's4-rev-7',
    kind: 'single',
    prompt: 'Your winter trip: 2 people × 4 days × 3.5 L/day, all from snow at −10 °C, brought to a boil (~800 kJ per litre total). Your stove delivers ~23 kJ per gram of gas. How much gas do you need for water alone?',
    choices: [
      { id: 'a', text: '≈ 490 g', why: 'That covers one person only: 14 L × 800 / 23.' },
      { id: 'b', text: '≈ 240 g', why: 'That covers one day only: 7 L × 800 / 23.' },
      { id: 'c', text: '≈ 970 g', why: 'Correct — 28 L × 800 kJ = 22,400 kJ; / 23 ≈ 970 g.' },
      { id: 'd', text: '≈ 460 g', why: 'This uses only the ~376 kJ/L to melt; bringing it to a boil makes it ~800 kJ/L.' },
    ],
    answer: 'c',
    concepts: ['snowmelt', 'water-budget'],
    explanation: '28 L × 800 kJ = 22,400 kJ; / 23 ≈ **970 g** — about four 230 g canisters. Finding open water, melting without boiling and treating chemically cuts this dramatically.',
  },
  {
    id: 's4-rev-8',
    kind: 'single',
    prompt: 'Redundancy (Stage 1 kit design) applied to water treatment means…',
    choices: [
      { id: 'a', text: 'Carrying two identical filters in case one breaks', why: 'Better than one, but both share the same gap (viruses) and the same failure (freezing, clogging).' },
      { id: 'b', text: 'Methods that fail differently: filter + tablets + a way to boil', why: 'Correct — diverse redundancy covers both hazard gaps and equipment failures.' },
      { id: 'c', text: 'Carrying enough extra water that you never need treatment', why: 'Weight limits make this impossible for longer trips.' },
      { id: 'd', text: 'Using only the strongest single method, done very carefully', why: 'Every single method has a hole.' },
    ],
    answer: 'b',
    concepts: ['redundancy', 'kit', 'water-treatment'],
    explanation: 'Critical functions need backups that fail differently — the Stage 1 kit rule, applied to water.',
  },
  {
    id: 's4-rev-9',
    kind: 'single',
    prompt: 'Which of these does **not** make SODIS fail?',
    choices: [
      { id: 'a', text: 'Water too cloudy to read print through the bottle', why: 'Makes it fail — particles shade microbes.' },
      { id: 'b', text: 'A 10 L clear container', why: 'Makes it fail — too deep for UV to reach all the water.' },
      { id: 'c', text: 'Only 3 hours of sun on a cloudy day', why: 'Makes it fail — needs ≥ 6 h sun or 2 days under cloud.' },
      { id: 'd', text: 'Laying bottles flat on a sheet-metal roof', why: 'Correct — that is the recommended way.' },
    ],
    answer: 'd',
    concepts: ['sodis', 'turbidity'],
    explanation: 'SODIS is a dose of UV-A and heat; clarity, depth and time control the dose.',
  },
  {
    id: 's4-rev-10',
    kind: 'single',
    prompt: 'At 17:00 you spot a line of green reeds 3 km away across rough ground. Sunset is 18:30 and twilight adds 20 min. You have 0.5 L, a tarp, and a known spring 1 km behind you on the trail you came in on. What is the best choice?',
    choices: [
      { id: 'a', text: 'Head for the reeds now, since they promise more water', why: '3 km of rough ground plus finding the water won’t fit in 1 h 50 min of light with any margin; you would arrive in the dark at an uncertain source.' },
      { id: 'b', text: 'Go back to the known spring, treat water, camp nearby', why: 'Best: certain water, known route, fits the daylight budget; the reeds can wait for morning.' },
      { id: 'c', text: 'Stay put under the tarp and wait for rain to collect', why: 'No rain forecast; 0.5 L is not enough for the night and morning.' },
      { id: 'd', text: 'Dig a solar still right here before it gets dark', why: 'Late in the day, no damp soil — negligible yield, real sweat cost.' },
    ],
    answer: 'b',
    concepts: ['daylight', 'water-finding', 'decisions'],
    explanation: 'A certain source within the daylight budget beats an uncertain one beyond it (Stage 1 daylight and reversibility).',
  },
]
