import type { Question } from '../../types'

// Stage 11 review: interleaves tracking with earlier stages — STOP and immediate danger,
// daylight budgeting, water treatment, navigation handrails, shelter sites and stay-or-move.
export const stage11Review: Question[] = [
  {
    id: 's11-rev-3',
    kind: 'single',
    prompt: 'You come across a trail of very fresh, large bear prints crossing your route to a lake camp at 17:00. Sunset is 19:30. Using the STOP routine, what is the best plan?',
    choices: [
      { id: 'a', text: 'Follow the prints to see where the bear went, so you can avoid it', why: 'Following fresh large-predator sign moves you toward the animal.' },
      { id: 'b', text: 'Make noise, stay together, and camp well away from the trail before dark', why: 'Correct — the evidence changes the plan, and the daylight budget still allows a safe alternative.' },
      { id: 'c', text: 'Continue to the planned camp, since bears usually avoid people', why: 'Often true, but very fresh sign on your route is exactly the situation where an encounter is likely.' },
      { id: 'd', text: 'Turn back and walk out to the car, even if it means walking in the dark', why: 'Night travel creates new hazards and is rarely needed here.' },
    ],
    answer: 'b',
    concepts: ['stop', 'trk-wildlife-distance', 'daylight'],
    explanation: 'Tracks are information for decisions. Stage 1’s STOP and daylight budgeting apply: change the plan early while you still have light — an alternative camp away from the trail and any food sources, set up well before dark, with food stored properly.',
  },
  {
    id: 's11-rev-10',
    kind: 'single',
    prompt: 'Hiking alone, you realise you left the trail following what you took to be a path, and it has faded into dense scrub. You can see your own boot prints behind you in soft ground. What is the best first move?',
    choices: [
      { id: 'a', text: 'Push on through the scrub; the path must reappear soon', why: 'Pushing on is how “slightly off route” becomes “lost”.' },
      { id: 'b', text: 'STOP, then backtrack along your own prints to your last sure point', why: 'Correct — your own trail is the best handrail back to a known point; mark your way as you go.' },
      { id: 'c', text: 'Head straight downhill through the scrub to find water', why: 'Downhill in dense scrub often leads to steeper, harder ground; you have a better option.' },
      { id: 'd', text: 'Climb a nearby tree to look around for the lost path', why: 'Risky and rarely effective in scrub; backtracking is simpler.' },
    ],
    answer: 'b',
    concepts: ['stop', 'direction-of-travel', 'lost-person-behavior'],
    explanation: 'Stage 1’s STOP and Stage 2’s relocation logic: return to your last known point. Reading your own trail is tracking too.',
  },
  {
    id: 's11-rev-5',
    kind: 'single',
    prompt: 'A clear pool at the end of converging game trails is ringed by hoof prints and dung. You have a filter and chlorine tablets. How do you use it?',
    choices: [
      { id: 'a', text: 'Drink it directly, since the water in the pool looks perfectly clear', why: 'Clarity says nothing about pathogens, and this pool is heavily used by animals.' },
      { id: 'b', text: 'Collect from the cleanest point, filter, then disinfect for the full contact time', why: 'Correct — the Stage 4 multi-barrier approach suits heavily contaminated sources.' },
      { id: 'c', text: 'Skip the filter and rely on the chlorine tablets alone for this pool', why: 'Some protozoa (e.g. Cryptosporidium) resist chlorine; filtration plus disinfection or boiling is better here.' },
      { id: 'd', text: 'Skip it entirely and look elsewhere, since animal water is never usable', why: 'It can be used with proper treatment.' },
    ],
    answer: 'b',
    concepts: ['water-sign', 'water-treatment'],
    explanation: 'Animal-used sources are among the most contaminated; treat with more than one barrier — pre-filter or settle if cloudy, filter, then disinfect with the tablets for the full contact time.',
  },
  {
    id: 's11-rev-1',
    kind: 'single',
    prompt: 'A print in firm mud: round, four toes with one leading toe, no claw marks, and a large heel pad with a three-lobed rear edge. Which family?',
    diagram: 's11-track-families',
    choices: [
      { id: 'a', text: 'Dog family', why: 'Dog prints are oval, symmetrical, usually show claws, and have a small heel pad.' },
      { id: 'b', text: 'Cat family', why: 'Correct — round, asymmetrical, clawless, big three-lobed pad.' },
      { id: 'c', text: 'Weasel family', why: 'Weasel-family prints usually show five toes and a C-shaped pad.' },
      { id: 'd', text: 'Bear', why: 'Bears have five toes and a very wide pad.' },
    ],
    answer: 'b',
    concepts: ['track-families', 'track-anatomy'],
    explanation: 'Describe, then match: roundness, asymmetry, missing claws and pad shape point to the cat family.',
  },
  {
    id: 's11-rev-8',
    kind: 'single',
    prompt: 'Where should you **not** pitch an emergency shelter?',
    choices: [
      { id: 'a', text: 'On a well-used game trail with fresh scat', why: 'Correct — animals (and predators following them) use it at night.' },
      { id: 'b', text: 'On a small rise 80 m from water with no animal sign and no dead trees overhead', why: 'This is a good site.' },
      { id: 'c', text: 'In the lee of a boulder on a south-facing (sunny) slope in cold weather, checked for rockfall', why: 'A reasonable warm site if hazards are checked.' },
      { id: 'd', text: 'In a clearing 100 m from the nearest trail, with no dead branches overhead', why: 'Away from animal traffic and overhead hazards: a reasonable site.' },
    ],
    answer: 'a',
    concepts: ['beds-trails-runs', 'site-hazards'],
    explanation: 'Stage 5 site selection plus this stage’s sign reading: stay off animal highways.',
  },
  {
    id: 's11-rev-4',
    kind: 'single',
    prompt: 'Which statement about direction of travel is **not** correct?',
    choices: [
      { id: 'a', text: 'In a hare’s bound, the two long hind prints are at the front of each group', why: 'This is correct — the hind feet land ahead of the front feet.' },
      { id: 'b', text: 'The toe end of a print is usually deeper, as weight rolls forward at push-off', why: 'This is correct.' },
      { id: 'c', text: 'Vegetation is pressed in the direction of travel', why: 'This is correct.' },
      { id: 'd', text: 'One blurred print is enough to be sure of the direction', why: 'Correct — this statement is false: check several prints and several cues.' },
    ],
    answer: 'd',
    concepts: ['direction-of-travel', 'gait-patterns'],
    explanation: 'Hind prints lead in a bound, toe ends dig deeper, and vegetation leans the way of travel — but use several independent cues along several prints.',
  },
  {
    id: 's11-rev-6',
    kind: 'single',
    prompt: 'You are using a game trail as a handrail toward your destination. Which rule is correct?',
    choices: [
      { id: 'a', text: 'Use it only while it goes your way, checking your bearing at junctions', why: 'Correct — animals travel to their destinations, not yours.' },
      { id: 'b', text: 'Follow it to its end, since game trails lead to roads or water', why: 'Trails lead to the animals’ destinations, which may not be yours.' },
      { id: 'c', text: 'At junctions, take the more-used branch, as it is the main route', why: 'Animal traffic does not know where you are going; check your bearing instead.' },
      { id: 'd', text: 'Avoid game trails entirely, as they never help with navigation', why: 'They are good handrails while they go your way.' },
    ],
    answer: 'a',
    concepts: ['game-trails', 'handrails'],
    explanation: 'Game trails are good handrails only while they go your way; check your bearing at every junction. Animals travel to their destinations, not yours (Stage 2).',
  },
  {
    id: 's11-rev-7',
    kind: 'single',
    prompt: 'A friend is overdue from a day walk and their car is at the trailhead. Which sequence of actions is right?',
    choices: [
      { id: 'a', text: 'Call emergency number; protect car and trail start; gather details; brief searchers', why: 'Correct — alert early, protect the IPP, collect information, then work within the search structure.' },
      { id: 'b', text: 'Protect car and trail start; gather details; brief searchers; call emergency number', why: 'There are no searchers to brief until you call; the alert comes first.' },
      { id: 'c', text: 'Gather details; call emergency number; brief searchers; protect car and trail start', why: 'Protecting the IPP late lets people and vehicles destroy the first sign.' },
      { id: 'd', text: 'Call emergency number; search the trail yourself; gather details; brief searchers', why: 'Searching alone tramples the IPP and risks a second missing person.' },
    ],
    answer: 'a',
    concepts: ['trk-lkp', 'trk-scene-protection', 'trip-plan'],
    explanation: 'Call and give the trip plan details, keep people and vehicles away from the car and trail start, gather footwear (sole photo), clothing, phone number, plans and time last seen, then brief the arriving searchers and do what you are assigned.',
  },
  {
    id: 's11-rev-2',
    kind: 'single',
    prompt: 'It is 16:00. Prints lie on top of a tyre track made at 09:00, and a tyre track made at 13:00 crosses and deforms them. What is the **minimum** age of the prints?',
    choices: [
      { id: 'a', text: '3 hours', why: 'Correct — made before 13:00, so at least 16:00 − 13:00 = 3 h old.' },
      { id: 'b', text: '7 hours', why: 'That is the maximum age, set by the 09:00 track underneath.' },
      { id: 'c', text: '4 hours', why: 'That is the gap between the two tyre tracks, not an age.' },
      { id: 'd', text: '5 hours', why: 'That is the middle of the 3–7 h window; averaging hides the real bracket.' },
    ],
    answer: 'a',
    concepts: ['age-bracketing'],
    explanation: 'Made before 13:00 → at least 16:00 − 13:00 = 3 h old; made after 09:00 → at most 7 h. Window: 3–7 h.',
  },
  {
    id: 's11-rev-9',
    kind: 'single',
    prompt: 'A lost person could move at up to 1.5 km/h. By what factor is the circle of possible area larger after 6 hours than after 3 hours?',
    choices: [
      { id: 'a', text: '4 times', why: 'Correct — area grows with t²: doubling time gives 2² = 4.' },
      { id: 'b', text: '2 times', why: 'That is the radius ratio; area grows with the square of the radius.' },
      { id: 'c', text: '8 times', why: 'This cubes the time ratio; area grows with t², not t³.' },
      { id: 'd', text: '16 times', why: 'This squares the ratio twice; area grows with t², not t⁴.' },
    ],
    answer: 'a',
    concepts: ['trk-search-area'],
    explanation: 'Area ∝ t². Doubling time multiplies area by 4 — the reason to report early.',
  },
]
