import type { Question } from '../../types'

// Stage 11 review: interleaves tracking with earlier stages — STOP and immediate danger,
// daylight budgeting, water treatment, navigation handrails, shelter sites and stay-or-move.
export const stage11Review: Question[] = [
  {
    id: 's11-rev-1',
    kind: 'single',
    prompt: 'A print in firm mud: round, four toes with one leading toe, no claw marks, and a large heel pad with a three-lobed rear edge. Which family?',
    diagram: 's11-track-families',
    choices: [
      { id: 'a', text: 'Dog family', why: 'Dog prints are oval, symmetrical, usually show claws, and have a small heel pad.' },
      { id: 'b', text: 'Cat family', why: 'Correct — round, asymmetrical, clawless, big three-lobed pad.' },
      { id: 'c', text: 'Weasel family', why: 'Weasel-family prints usually show five toes and a C-shaped pad.' },
      { id: 'd', text: 'Bear', why: 'Bears have five toes and a very wide pad.' },
    ],
    answer: 'b',
    concepts: ['track-families', 'track-anatomy'],
    explanation: 'Describe, then match: roundness, asymmetry, missing claws and pad shape point to the cat family.',
  },
  {
    id: 's11-rev-2',
    kind: 'numeric',
    prompt: 'It is 16:00. Prints lie on top of a tyre track made at 09:00, and a tyre track made at 13:00 crosses and deforms them. What is the **minimum** age of the prints, in hours?',
    unit: 'h',
    answer: 3,
    tolerance: 0,
    concepts: ['age-bracketing'],
    explanation: 'Made before 13:00 → at least 16:00 − 13:00 = 3 h old; made after 09:00 → at most 7 h. Window: 3–7 h.',
  },
  {
    id: 's11-rev-3',
    kind: 'single',
    prompt: 'You come across a trail of very fresh, large bear prints crossing your route to a lake camp at 17:00. Sunset is 19:30. Using the STOP routine, what is the best plan?',
    choices: [
      { id: 'a', text: 'Follow the prints to see where the bear went, so you can avoid it later', why: 'Following fresh large-predator sign moves you toward the animal.' },
      { id: 'b', text: 'Stop, think: make noise, keep together, and choose an alternative camp away from the trail and any food sources, set up well before dark, and store food properly', why: 'Correct — the evidence changes the plan, and the daylight budget still allows a safe alternative.' },
      { id: 'c', text: 'Continue to the planned camp — bears avoid people', why: 'Often true, but very fresh sign on your route is exactly the situation where an encounter is likely.' },
      { id: 'd', text: 'Walk back to the car in the dark', why: 'Night travel creates new hazards and is rarely needed here.' },
    ],
    answer: 'b',
    concepts: ['stop', 'trk-wildlife-distance', 'daylight'],
    explanation: 'Tracks are information for decisions. Stage 1’s STOP and daylight budgeting apply: change the plan early while you still have light.',
  },
  {
    id: 's11-rev-4',
    kind: 'multi',
    prompt: 'Which statements about direction of travel are correct?',
    choices: [
      { id: 'a', text: 'In a hare’s bound, the two long hind prints are at the front of each group', why: 'Correct.' },
      { id: 'b', text: 'The toe end of a print is usually deeper, because weight rolls forward at push-off', why: 'Correct.' },
      { id: 'c', text: 'Vegetation is pressed in the direction of travel', why: 'Correct.' },
      { id: 'd', text: 'One blurred print is enough to be sure of the direction', why: 'No — check several prints and several cues.' },
    ],
    answer: ['a', 'b', 'c'],
    concepts: ['direction-of-travel', 'gait-patterns'],
    explanation: 'Use several independent cues along several prints.',
  },
  {
    id: 's11-rev-5',
    kind: 'single',
    prompt: 'A clear pool at the end of converging game trails is ringed by hoof prints and dung. You have a filter and chlorine tablets. How do you use it?',
    choices: [
      { id: 'a', text: 'Drink directly — clear water from a pool is safe', why: 'Clarity says nothing about pathogens, and this pool is heavily used by animals.' },
      { id: 'b', text: 'Collect from the cleanest point, pre-filter or settle if cloudy, filter, then disinfect with the tablets for the full contact time', why: 'Correct — the Stage 4 multi-barrier approach suits heavily contaminated sources.' },
      { id: 'c', text: 'Chlorine alone is always enough', why: 'Some protozoa (e.g. Cryptosporidium) resist chlorine; filtration plus disinfection or boiling is better here.' },
      { id: 'd', text: 'Skip it: animal water is never usable', why: 'It can be used with proper treatment.' },
    ],
    answer: 'b',
    concepts: ['water-sign', 'water-treatment'],
    explanation: 'Animal-used sources are among the most contaminated; treat with more than one barrier.',
  },
  {
    id: 's11-rev-6',
    kind: 'truefalse',
    prompt: 'Game trails are good handrails only while they go your way; you should check your bearing at every junction.',
    answer: true,
    concepts: ['game-trails', 'handrails'],
    explanation: 'Animals travel to their destinations, not yours (Stage 2).',
  },
  {
    id: 's11-rev-7',
    kind: 'order',
    prompt: 'Order the steps for helping when a friend is overdue from a day walk and their car is at the trailhead.',
    items: [
      { id: 'call', text: 'Call the emergency number and give the trip plan details' },
      { id: 'protect', text: 'Keep people and vehicles away from the car and trail start' },
      { id: 'info', text: 'Gather footwear (sole photo), clothing, phone number, plans, time last seen' },
      { id: 'brief', text: 'Brief the arriving searchers and do what you are assigned' },
    ],
    answer: ['call', 'protect', 'info', 'brief'],
    concepts: ['trk-lkp', 'trk-scene-protection', 'trip-plan'],
    explanation: 'Alert early, protect the IPP, collect the information searchers need, then work within the search structure.',
  },
  {
    id: 's11-rev-8',
    kind: 'single',
    prompt: 'Where should you **not** pitch an emergency shelter?',
    choices: [
      { id: 'a', text: 'On a well-used game trail with fresh scat', why: 'Correct — animals (and predators following them) use it at night.' },
      { id: 'b', text: 'On a small rise 80 m from water with no animal sign and no dead trees overhead', why: 'This is a good site.' },
      { id: 'c', text: 'In the lee of a boulder on a south-facing (sunny) slope in cold weather, checked for rockfall', why: 'A reasonable warm site if hazards are checked.' },
    ],
    answer: 'a',
    concepts: ['beds-trails-runs', 'site-hazards'],
    explanation: 'Stage 5 site selection plus this stage’s sign reading: stay off animal highways.',
  },
  {
    id: 's11-rev-9',
    kind: 'numeric',
    prompt: 'A lost person could move at up to 1.5 km/h. By what factor is the circle of possible area larger after 6 hours than after 3 hours?',
    unit: '×',
    answer: 4,
    tolerance: 0,
    concepts: ['trk-search-area'],
    explanation: 'Area ∝ t². Doubling time multiplies area by 4 — the reason to report early.',
  },
  {
    id: 's11-rev-10',
    kind: 'single',
    prompt: 'Hiking alone, you realise you left the trail following what you took to be a path, and it has faded into dense scrub. You can see your own boot prints behind you in soft ground. What is the best first move?',
    choices: [
      { id: 'a', text: 'Push on — the path must reappear', why: 'Pushing on is how “slightly off route” becomes “lost”.' },
      { id: 'b', text: 'STOP; then backtrack carefully along your own prints to the last point you were sure of, marking your way', why: 'Correct — your own trail is the best handrail back to a known point.' },
      { id: 'c', text: 'Head straight downhill to find water', why: 'Downhill in dense scrub often leads to steeper, harder ground; you have a better option.' },
      { id: 'd', text: 'Climb a tree to look around', why: 'Risky and rarely effective in scrub; backtracking is simpler.' },
    ],
    answer: 'b',
    concepts: ['stop', 'direction-of-travel', 'lost-person-behavior'],
    explanation: 'Stage 1’s STOP and Stage 2’s relocation logic: return to your last known point. Reading your own trail is tracking too.',
  },
]
