import type { Question } from '../../types'

// Stage 15 review: interleaves psychology with earlier stages — immediate danger, lightning, stay-or-move,
// hypothermia, carbon monoxide, trip plans, daylight and lost-person behaviour.
export const stage15Review: Question[] = [
  {
    id: 's15-rev-1',
    kind: 'single',
    prompt: 'On a ridge you hear the first thunder at 11:40. Your turnaround time is 12:30 and the summit is 30 minutes away. A friend says: “We’ve got 50 minutes before turnaround — plenty of time.” What is the best response?',
    choices: [
      { id: 'a', text: 'Agree — you are still inside your turnaround time', why: 'The turnaround was not the only trigger: first thunder means lightning is within reach (Stage 12).' },
      { id: 'b', text: 'Descend now: first thunder is its own trigger, whatever the clock says', why: 'Correct — the weather trigger overrides the time trigger.' },
      { id: 'c', text: 'Summit quickly, then descend as fast as you safely can', why: 'Plan continuation on the most exposed ground.' },
      { id: 'd', text: 'Wait on the ridge to see whether the storm gets closer', why: 'Waiting high wastes the margin; if you wait, wait lower.' },
    ],
    answer: 'b',
    concepts: ['plan-continuation', 'lightning', 'go-no-go'],
    explanation: 'A trip needs several triggers (time, weather, group, daylight). Any one of them firing is enough. Treating the turnaround time as permission to continue is plan continuation in disguise.',
  },
  {
    id: 's15-rev-9',
    kind: 'single',
    prompt: 'At the trailhead, the most experienced person in your group says conditions are fine; you have a nagging doubt about the avalanche forecast. What is the most useful thing to do?',
    choices: [
      { id: 'a', text: 'Stay quiet — they know much more about avalanches than you', why: 'Expert halo (FACETS) and self-censorship.' },
      { id: 'b', text: 'Say you are uneasy, why, and propose the south-facing option', why: 'Correct — concern, reason and proposal: assertive, specific, CRM-style speaking up.' },
      { id: 'c', text: 'Go along with the plan, but choose to ski at the back', why: 'Your doubt goes unheard and you are still exposed.' },
      { id: 'd', text: 'Quietly go home without telling the group why', why: 'Better for you than silence, but the group loses your information.' },
    ],
    answer: 'b',
    concepts: ['groupthink', 'human-factors', 'avalanche'],
    explanation: 'Concern + reason + proposal (“I’m uneasy — the forecast says considerable on north aspects. Can we pick the south-facing option?”), repeated if not acknowledged. Good leaders invite exactly this.',
  },
  {
    id: 's15-rev-2',
    kind: 'single',
    prompt: 'Lost at dusk in a forest, you feel a strong urge to walk fast to “find the path before dark”. Which response goes **against** both Stage 1 and this stage?',
    choices: [
      { id: 'a', text: 'Stop, sit down and do a minute of slow breathing', why: 'A good response — STOP and arousal control.' },
      { id: 'b', text: 'Say out loud what you know and what you do not know', why: 'A good response — labelling and structuring thought.' },
      { id: 'c', text: 'Walk quickly in the direction that “feels right”', why: 'Correct — the classic panic walk; lost people often travel far and become harder to find.' },
      { id: 'd', text: 'Use the last light for shelter and signals; decide in the morning', why: 'A good response — big decisions after rest and in daylight.' },
    ],
    answer: 'c',
    concepts: ['stop', 'stress-control', 'lost-person-behavior', 'daylight'],
    explanation: 'Stress pushes towards movement; STOP, breathing and naming the situation bring the planning brain back online. Dusk is for shelter and signals; decide on moving in daylight.',
  },
  {
    id: 's15-rev-8',
    kind: 'single',
    prompt: 'Day 3, lost with two friends in a tropical forest, waiting near a clearing where you have made a signal. Which measure does **not** protect judgment and morale?',
    choices: [
      { id: 'a', text: 'Fixed times for signalling, drinking treated water and checking the shelter', why: 'Protective — routines shrink uncertainty.' },
      { id: 'b', text: 'Avoiding all talk about rescue so as not to raise anyone’s hopes', why: 'Correct — honest, realistic hope (the search timeline) is protective.' },
      { id: 'c', text: 'Giving each person a role and rotating the hard jobs fairly', why: 'Protective — purpose and fairness.' },
      { id: 'd', text: 'Deciding whether to move at a set morning time after food and water', why: 'Protective — decisions made in the best condition.' },
    ],
    answer: 'b',
    concepts: ['isolation-uncertainty', 'group-morale', 'signaling', 'water-treatment'],
    explanation: 'Routines, a written log, roles and timed decisions are the practical form of Hobfoll’s calming, efficacy and hope — and hope needs honest talk about rescue.',
  },
  {
    id: 's15-rev-10',
    kind: 'single',
    prompt: 'After a close call on a river crossing, everyone is safe but shaken. The next evening your group meets. Which is the best approach?',
    choices: [
      { id: 'a', text: 'Ask each person to describe in detail how frightened they were', why: 'Pressing people to relive distress is not recommended.' },
      { id: 'b', text: 'A blame-free after-action review; feelings shared only if wished', why: 'Correct — learns from the near-miss without forcing anyone.' },
      { id: 'c', text: 'Agree as a group not to mention the crossing again', why: 'The near-miss becomes “normal”.' },
      { id: 'd', text: 'Work out whose fault it was so it does not happen again', why: 'Blame closes down honest review.' },
    ],
    answer: 'b',
    concepts: ['after-action-review', 'psychological-first-aid', 'normalization-of-deviance', 'water-crossing'],
    explanation: 'Review the decisions — planned, happened, why, next time — without blame, and let anyone share feelings if they wish. Operational learning (AAR) and humane support (PFA) are different jobs; do both, without blame or pressure.',
  },
  {
    id: 's15-rev-3',
    kind: 'single',
    prompt: 'Your group has crossed the same snow slope on three previous trips without incident, although each time you noticed cracks. Today the cracks are longer. Someone says: “It’s always like this.” Which trap is this?',
    choices: [
      { id: 'a', text: 'Sunk cost', why: 'That would be about effort already spent.' },
      { id: 'b', text: 'Normalization of deviance', why: 'Correct — repeated unpunished warning signs have become “normal”.' },
      { id: 'c', text: 'Risk perception of dread hazards', why: 'The opposite: the hazard feels less dangerous than it is.' },
      { id: 'd', text: 'Tonic immobility', why: 'A freezing response, not a judgement bias.' },
    ],
    answer: 'b',
    concepts: ['normalization-of-deviance', 'avalanche'],
    explanation: 'Shooting cracks are a classic avalanche warning sign (Stage 12). Past crossings without incident are misleading feedback, not evidence of safety.',
  },
  {
    id: 's15-rev-4',
    kind: 'single',
    prompt: 'A normally talkative companion becomes quiet, clumsy and irritable after hours in cold rain. What is the most likely explanation to act on first?',
    choices: [
      { id: 'a', text: 'Early giving up; give them a motivational talk', why: 'Psychology comes second — rule out cold first.' },
      { id: 'b', text: 'Mild hypothermia (the “umbles”): warm, dry, shelter, food', why: 'Correct — cold degrades mood, speech and coordination.' },
      { id: 'c', text: 'Groupthink pulling the whole group’s mood down', why: 'A group bias, not an individual’s change in behaviour.' },
      { id: 'd', text: 'Normal tiredness; carry on to the planned camp', why: 'Carrying on in cold rain lets hypothermia progress.' },
    ],
    answer: 'b',
    concepts: ['hypothermia', 'give-up-itis', 'cognitive-degradation'],
    explanation: 'Mumbles, fumbles, grumbles and stumbles are early hypothermia signs (Stage 8). Physical causes of apathy and irritability always come first.',
  },
  {
    id: 's15-rev-5',
    kind: 'single',
    prompt: 'A kitchen fire starts in a holiday flat; your friend Maya freezes, staring at it. What do you do first?',
    choices: [
      { id: 'a', text: 'Short command using her name: “Maya! Out! Now!”', why: 'Correct — break the freeze first so everyone can get out.' },
      { id: 'b', text: 'Call the emergency number from inside the flat', why: 'Call from outside, once everyone is out.' },
      { id: 'c', text: 'Check that everyone in the flat is accounted for', why: 'That comes last, outside — after getting out and calling.' },
      { id: 'd', text: 'Gather your belongings and then close the doors', why: 'Never delay for belongings; get out, closing doors behind you.' },
    ],
    answer: 'a',
    concepts: ['freezing', 'building-evacuation', 'immediate-danger'],
    explanation: 'Break the freeze with a clear command, get out (closing doors slows the fire — Stage 16), then call and account for everyone, stopping anyone going back in. Never go back in for belongings.',
  },
  {
    id: 's15-rev-7',
    kind: 'single',
    prompt: 'You have a written trip plan with a turnaround time. Which statement about the psychological traps from Lesson 2 is correct?',
    choices: [
      { id: 'a', text: 'They no longer matter, because the plan decides for you', why: 'Plans only help if they are kept; the traps still push to renegotiate them.' },
      { id: 'b', text: 'They still work by renegotiating triggers on the spot', why: 'Correct — “just 30 more minutes”; agree in advance the triggers are not up for debate.' },
      { id: 'c', text: 'They matter only for groups, not for solo travellers', why: 'Plan continuation and sunk cost act on individuals too.' },
      { id: 'd', text: 'They matter only if the plan was not shared with a contact', why: 'Sharing the plan helps rescue, but does not stop on-the-spot renegotiation.' },
    ],
    answer: 'b',
    concepts: ['trip-plan', 'plan-continuation', 'debiasing'],
    explanation: 'Plans only help if they are kept. The traps work by renegotiating triggers on the spot (“just 30 more minutes”). Tell the group in advance that the triggers are not up for debate.',
  },
  {
    id: 's15-rev-6',
    kind: 'single',
    prompt: 'Stranded in a snowed-in car, three people rotate a watch to keep the exhaust clear and the engine run times short. The night is 13.5 hours. How long is each watch if one person is awake at a time?',
    choices: [
      { id: 'a', text: '4.5 h', why: 'Correct — 13.5 / 3 = 4.5 h.' },
      { id: 'b', text: '6.75 h', why: 'This divides by 2, leaving one of the three people out of the rota.' },
      { id: 'c', text: '3.4 h', why: 'This divides by 4, as if there were four people in the car.' },
      { id: 'd', text: '40.5 h', why: 'This multiplies by 3 instead of dividing the night among three.' },
    ],
    answer: 'a',
    concepts: ['group-roles', 'carbon-monoxide'],
    explanation: '$13.5 / 3 = 4.5$ h. The watcher keeps the exhaust pipe clear of snow and the engine runs short (carbon monoxide — Stage 16) — a role that protects everyone while the others sleep.',
  },
]
