import type { Question } from '../../types'

// Stage 3 review: interleaved questions mixing fire science with Stage 1 concepts
// (heat balance, priorities, fire safety, redundancy, daylight).
export const stage3Review: Question[] = [
  {
    id: 's3-rev-1',
    kind: 'single',
    prompt: 'Wet temperate forest, 5 °C, rain, 17:00, sunset 18:30. You are soaked and starting to shiver; you have a tarp, a knife, a lighter and carried tinder. Fires are legal. What is the highest-value first action?',
    choices: [
      { id: 'a', text: 'Start a fire immediately with ground wood.', why: 'Likely to fail, and heat loss continues while you struggle.' },
      { id: 'b', text: 'Pitch the tarp, get out of the wind, add dry layers and ground insulation; then process dry cores for a fire.', why: 'Best: stops the biggest losses in minutes; a well-prepared fire then adds heat.' },
      { id: 'c', text: 'Walk briskly to warm up until dark.', why: 'Wet clothing and sweat at dusk worsen the heat budget later.' },
      { id: 'd', text: 'Eat your food to generate heat.', why: 'Helps a little, but does not stop wet-wind losses.' },
    ],
    answer: 'b',
    concepts: ['priorities', 'heat-balance', 'wet-weather-fire'],
    explanation: 'Reduce heat loss first (shelter, dry, insulate), then add heat (fire). Wet-weather fire success depends on preparation, not speed.',
  },
  {
    id: 's3-rev-2',
    kind: 'numeric',
    prompt: 'You gather 12 kg of wood at 40 % moisture (wet basis). Evaporating water costs about 2.44 MJ/kg. How many **MJ** go just into evaporating its water? (One decimal.)',
    unit: 'MJ',
    answer: 11.7,
    tolerance: 0.15,
    concepts: ['moisture-content'],
    explanation: '12 × 0.4 = 4.8 kg of water; 4.8 × 2.44 ≈ **11.7 MJ** — heat that never reaches you, plus the smoke and cooler flame that come with it.',
  },
  {
    id: 's3-rev-3',
    kind: 'multi',
    prompt: 'Which pairs correctly match a fire lay to a purpose?',
    choices: [
      { id: 'a', text: 'Teepee → fast start and signal flame', why: 'Yes.' },
      { id: 'b', text: 'Star → long, fuel-thrifty burn and cooking', why: 'Yes.' },
      { id: 'c', text: 'Dakota hole → warming a sleeping person', why: 'No — its heat goes up into the pot, not sideways.' },
      { id: 'd', text: 'Long log → overnight warmth along the body', why: 'Yes.' },
      { id: 'e', text: 'Log cabin → stable pot platform and even coal bed', why: 'Yes.' },
    ],
    answer: ['a', 'b', 'd', 'e'],
    concepts: ['fire-lays', 'fire-purpose'],
    explanation: 'Choose the lay for where the heat must go and how often you can tend it.',
  },
  {
    id: 's3-rev-4',
    kind: 'single',
    prompt: 'At −20 °C your lighter will not light. Which Stage 1 principle does carrying a ferro rod as well illustrate?',
    choices: [
      { id: 'a', text: 'Redundancy of critical functions', why: 'Correct: two independent ways to do a life-critical job.' },
      { id: 'b', text: 'The rule of threes', why: 'Unrelated.' },
      { id: 'c', text: 'Stay or move', why: 'Unrelated.' },
      { id: 'd', text: 'Risk = likelihood × consequence', why: 'Related, but the specific principle is redundancy.' },
    ],
    answer: 'a',
    concepts: ['redundancy', 'spark-ignition'],
    explanation: 'Ignition is a critical function: carry at least two methods that fail in different ways (cold, wet, empty).',
  },
  {
    id: 's3-rev-5',
    kind: 'numeric',
    prompt: 'A bow-drill user presses with 70 N; the friction coefficient is 0.45; the average rubbing speed is 1.1 m/s. What is the friction power in **W**? (Nearest whole number.)',
    unit: 'W',
    answer: 35,
    tolerance: 1,
    concepts: ['friction-power'],
    explanation: '0.45 × 70 × 1.1 ≈ **35 W** — close to the limit of what arm muscles sustain for long.',
  },
  {
    id: 's3-rev-6',
    kind: 'single',
    prompt: 'Your 10 kW fire radiates 30 % of its output. At 1.5 m, the point-source flux is about 106 W/m². Your net heat loss sitting on bare ground on a clear night is ~150 W. What is the best interpretation?',
    choices: [
      { id: 'a', text: 'The fire alone solves the problem.', why: 'You receive only ~50 W on the side facing it.' },
      { id: 'b', text: 'The fire helps, but you must also cut conduction (a bed) and back radiation (tarp/reflector behind you).', why: 'Correct: fix the big losses, then add radiant gain.' },
      { id: 'c', text: 'Move to 3 m for safety; the heat is the same.', why: 'At 3 m you get about a quarter of the heat at 1.5 m.' },
      { id: 'd', text: 'Enclose the fire with the tarp to trap its heat.', why: 'Fire and carbon-monoxide hazard.' },
    ],
    answer: 'b',
    concepts: ['radiant-heat', 'heat-balance', 'heat-loss'],
    explanation: 'Radiant gain is real but modest; combine it with insulation and shelter.',
  },
  {
    id: 's3-rev-7',
    kind: 'order',
    prompt: 'Order the steps for leaving a campsite fire safely.',
    items: [
      { id: 'burn', text: 'Stop adding fuel early so it burns down to ash' },
      { id: 'drown', text: 'Drown with water' },
      { id: 'stir', text: 'Stir and drown again' },
      { id: 'feel', text: 'Feel for heat with the back of your hand' },
      { id: 'restore', text: 'Pack out rubbish and restore the site' },
    ],
    answer: ['burn', 'drown', 'stir', 'feel', 'restore'],
    concepts: ['extinguishing', 'leave-no-trace', 'fire-safety'],
    explanation: 'Plan the burn-down, extinguish cold, then leave no trace.',
  },
  {
    id: 's3-rev-8',
    kind: 'truefalse',
    prompt: 'Using a small charcoal grill inside a tent is safe as long as the door is partly open.',
    answer: false,
    concepts: ['carbon-monoxide', 'fire-safety'],
    explanation: 'Charcoal produces large amounts of CO even when it looks “finished”. Never burn it in tents, vehicles or closed rooms.',
  },
  {
    id: 's3-rev-9',
    kind: 'single',
    prompt: 'It is 15:30, sunset 17:00, 0 °C forecast overnight. You plan a long-log fire burning 2 kg/h for 14 hours. Processing wood takes you about 10 minutes per 5 kg armful. What should you do?',
    choices: [
      { id: 'a', text: 'Gather wood after dinner, by headlamp.', why: 'Gathering and sawing in the dark is slow, cold and dangerous.' },
      { id: 'b', text: 'Start now: 28 kg ≈ 6 armfuls ≈ 1 hour of processing, leaving daylight margin for shelter.', why: 'Correct: fuel budget = rate × time; gather it in daylight (daylight budgeting, Stage 1).' },
      { id: 'c', text: 'Gather two armfuls; you can always get more.', why: 'That lasts about 5 hours — you will run out in the coldest part of the night.' },
      { id: 'd', text: 'Skip the fire; cold nights are fine with a jacket.', why: 'At 0 °C overnight, a legal fire and insulation both matter.' },
    ],
    answer: 'b',
    concepts: ['long-duration-fire', 'daylight'],
    explanation: '2 × 14 = 28 kg ≈ six armfuls ≈ 60 minutes of work. Budget it before dark.',
  },
  {
    id: 's3-rev-10',
    kind: 'multi',
    prompt: 'A friend’s bow-drill attempts keep failing. Which observations point to the cause correctly?',
    choices: [
      { id: 'a', text: 'Steam, pale dust, temperature stalls → wood too damp', why: 'Yes.' },
      { id: 'b', text: 'Squeaking, glossy surfaces → resin or too little pressure (glazing)', why: 'Yes.' },
      { id: 'c', text: 'Good smoke but dust scatters out of the socket → notch missing or too shallow', why: 'Yes.' },
      { id: 'd', text: 'Arm gives out after 40 s of fast, short strokes → spindle too thin', why: 'No — this is fatigue from inefficient form; use long, full strokes and body weight.' },
    ],
    answer: ['a', 'b', 'c'],
    concepts: ['friction-fire', 'friction-power'],
    explanation: 'Diagnose from symptoms: moisture, glazing, notch and form each leave a signature.',
  },
  {
    id: 's3-rev-11',
    kind: 'single',
    prompt: 'Hot afternoon, 29 °C, humidity 25 %, gusty wind, dry grassland. A friend is lost and you want to light a signal fire to guide them back. Best choice?',
    choices: [
      { id: 'a', text: 'Light a large smoky fire in the grass for visibility.', why: 'High chance of a grass fire that endangers your friend and you.' },
      { id: 'b', text: 'Do not light a fire; use whistle blasts in threes, a bright marker, a mirror, and call emergency services with your location.', why: 'Correct: extreme fire weather; other signals work without the wildfire risk.' },
      { id: 'c', text: 'Light a small fire and add green boughs.', why: 'Still a spark risk in crossover conditions and cured grass.' },
      { id: 'd', text: 'Dig a Dakota hole signal fire.', why: 'Hidden by design, and still a risk.' },
    ],
    answer: 'b',
    concepts: ['wildfire-risk', 'signaling', 'fire-purpose'],
    explanation: 'Temperature above humidity, gusts and cured grass: no open fire. Signal by sound, light and phone (Stage 1).',
  },
]
