import type { Question } from '../../types'

// Stage 3 review: interleaved questions mixing fire science with Stage 1 concepts
// (heat balance, priorities, fire safety, redundancy, daylight).
export const stage3Review: Question[] = [
  {
    id: 's3-rev-1',
    kind: 'single',
    prompt: 'Wet temperate forest, 5 °C, rain, 17:00, sunset 18:30. You are soaked and starting to shiver; you have a tarp, a knife, a lighter and carried tinder. Fires are legal. What is the highest-value first action?',
    choices: [
      { id: 'a', text: 'Start a fire right away with wood picked up from the ground.', why: 'Likely to fail, and heat loss continues while you struggle.' },
      { id: 'b', text: 'Pitch the tarp, add dry layers and insulation, then process dry cores.', why: 'Best: stops the biggest losses in minutes; a well-prepared fire then adds heat.' },
      { id: 'c', text: 'Walk briskly to warm up for as long as the daylight lasts.', why: 'Wet clothing and sweat at dusk worsen the heat budget later.' },
      { id: 'd', text: 'Eat all your food now so your body generates more heat.', why: 'Helps a little, but does not stop wet-wind losses.' },
    ],
    answer: 'b',
    concepts: ['priorities', 'heat-balance', 'wet-weather-fire'],
    explanation: 'Reduce heat loss first (shelter, dry, insulate), then add heat (fire). Wet-weather fire success depends on preparation, not speed.',
  },
  {
    id: 's3-rev-6',
    kind: 'single',
    prompt: 'Your 10 kW fire radiates 30 % of its output. At 1.5 m, the point-source flux is about 106 W/m². Your net heat loss sitting on bare ground on a clear night is ~150 W. What is the best interpretation?',
    choices: [
      { id: 'a', text: 'The fire alone solves it, since 106 W/m² is close to your loss.', why: 'You receive only ~50 W on the side facing it.' },
      { id: 'b', text: 'It helps, but you must also cut conduction and back radiation.', why: 'Correct: add a bed and a tarp or reflector behind you, then the radiant gain.' },
      { id: 'c', text: 'Move back to 3 m for safety, as the heat will be about the same.', why: 'At 3 m you get about a quarter of the heat at 1.5 m.' },
      { id: 'd', text: 'Enclose the fire with the tarp so that none of its heat escapes.', why: 'Fire and carbon-monoxide hazard.' },
    ],
    answer: 'b',
    concepts: ['radiant-heat', 'heat-balance', 'heat-loss'],
    explanation: 'Radiant gain is real but modest; combine it with insulation (a bed against conduction) and shelter (against back radiation).',
  },
  {
    id: 's3-rev-9',
    kind: 'single',
    prompt: 'It is 15:30, sunset 17:00, 0 °C forecast overnight. You plan a long-log fire burning 2 kg/h for 14 hours. Processing wood takes you about 10 minutes per 5 kg armful. What should you do?',
    choices: [
      { id: 'a', text: 'Gather wood after dinner by headlamp, once camp is set up.', why: 'Gathering and sawing in the dark is slow, cold and dangerous.' },
      { id: 'b', text: 'Start now: 28 kg is about 6 armfuls, roughly an hour of work.', why: 'Correct: fuel budget = rate × time; gather it in daylight, leaving margin for shelter.' },
      { id: 'c', text: 'Gather two armfuls now; you can always fetch more in the night.', why: 'That lasts about 5 hours — you will run out in the coldest part of the night.' },
      { id: 'd', text: 'Skip the fire; a good jacket is enough for a night at 0 °C.', why: 'At 0 °C overnight, a legal fire and insulation both matter.' },
    ],
    answer: 'b',
    concepts: ['long-duration-fire', 'daylight'],
    explanation: '2 × 14 = 28 kg ≈ six armfuls ≈ 60 minutes of work. Budget it before dark (daylight budgeting, Stage 1).',
  },
  {
    id: 's3-rev-11',
    kind: 'single',
    prompt: 'Hot afternoon, 29 °C, humidity 25 %, gusty wind, dry grassland. A friend is lost and you want to light a signal fire to guide them back. Best choice?',
    choices: [
      { id: 'a', text: 'Light a large, smoky fire out in the grass so it is seen from afar.', why: 'High chance of a grass fire that endangers your friend and you.' },
      { id: 'b', text: 'No fire: whistle blasts in threes, a mirror, and call for help.', why: 'Correct: extreme fire weather; sound, light and a call with your location work without the wildfire risk.' },
      { id: 'c', text: 'Light a small fire and add green boughs for a thick smoke column.', why: 'Still a spark risk in crossover conditions and cured grass.' },
      { id: 'd', text: 'Dig a Dakota hole signal fire so sparks stay below ground level.', why: 'Hidden by design, and still a risk.' },
    ],
    answer: 'b',
    concepts: ['wildfire-risk', 'signaling', 'fire-purpose'],
    explanation: 'Temperature above humidity, gusts and cured grass: no open fire. Signal by sound, light and phone (Stage 1).',
  },
  {
    id: 's3-rev-3',
    kind: 'single',
    prompt: 'Which pairing of fire lay and purpose is **wrong**?',
    choices: [
      { id: 'a', text: 'Teepee → fast start and signal flame', why: 'A correct match.' },
      { id: 'b', text: 'Star → fuel-thrifty burn and cooking', why: 'A correct match.' },
      { id: 'c', text: 'Dakota hole → warming a sleeper', why: 'Correct: its heat goes up into the pot, not sideways to you.' },
      { id: 'd', text: 'Long log → overnight warmth for a sleeper', why: 'A correct match: even heat along the body.' },
    ],
    answer: 'c',
    concepts: ['fire-lays', 'fire-purpose'],
    explanation: 'Choose the lay for where the heat must go and how often you can tend it. Teepee starts and signals, star and log cabin cook, long log warms overnight; the Dakota hole is a low-signature cooking fire.',
  },
  {
    id: 's3-rev-10',
    kind: 'single',
    prompt: 'A friend’s bow-drill attempts keep failing. Which observation is matched to the **wrong** cause?',
    choices: [
      { id: 'a', text: 'Steam, pale dust, temperature stalls → the wood is too damp', why: 'A correct diagnosis.' },
      { id: 'b', text: 'Squeaking, glossy surfaces → resin or too little pressure', why: 'A correct diagnosis: glazing.' },
      { id: 'c', text: 'Good smoke, but dust scatters → notch missing or too shallow', why: 'A correct diagnosis.' },
      { id: 'd', text: 'Arm gives out after 40 s of short, fast strokes → spindle too thin', why: 'Correct: this is fatigue from inefficient form; use long, full strokes and body weight.' },
    ],
    answer: 'd',
    concepts: ['friction-fire', 'friction-power'],
    explanation: 'Diagnose from symptoms: moisture, glazing, notch and form each leave a signature.',
  },
  {
    id: 's3-rev-7',
    kind: 'single',
    prompt: 'Which sequence is correct for leaving a campsite fire safely?',
    choices: [
      { id: 'a', text: 'Burn down → drown → stir and drown → feel → restore site', why: 'Correct: plan the burn-down, extinguish cold, then leave no trace.' },
      { id: 'b', text: 'Drown → burn down → stir and drown → feel → restore site', why: 'Let it burn down to ash first; drowning big pieces leaves hot cores.' },
      { id: 'c', text: 'Burn down → drown → feel → stir and drown → restore site', why: 'Feel last, after stirring has exposed and drowned hidden hot spots.' },
      { id: 'd', text: 'Burn down → drown → stir and drown → restore site → feel', why: 'Confirm it is cold before you restore the site and pack out.' },
    ],
    answer: 'a',
    concepts: ['extinguishing', 'leave-no-trace', 'fire-safety'],
    explanation: 'Stop adding fuel early so it burns to ash, drown, stir and drown again, feel with the back of your hand, then pack out rubbish and restore the site.',
  },
  {
    id: 's3-rev-8',
    kind: 'single',
    prompt: 'On a cold night, a friend suggests bringing a small charcoal grill into the tent for warmth. Which statement is correct?',
    choices: [
      { id: 'a', text: 'Never inside: charcoal gives off CO even when it looks finished', why: 'Correct: never burn it in tents, vehicles or closed rooms.' },
      { id: 'b', text: 'It is safe as long as the tent door is left partly open', why: 'A partly open door does not stop CO building up to dangerous levels.' },
      { id: 'c', text: 'It is safe once the coals stop flaming and look finished', why: 'Cooling charcoal still produces large amounts of CO.' },
      { id: 'd', text: 'It is safe in a large tent if someone stays awake to watch', why: 'CO is colourless and odourless; a watcher cannot see it.' },
    ],
    answer: 'a',
    concepts: ['carbon-monoxide', 'fire-safety'],
    explanation: 'Charcoal produces large amounts of CO even when it looks “finished”. Never burn it in tents, vehicles or closed rooms.',
  },
  {
    id: 's3-rev-2',
    kind: 'single',
    prompt: 'You gather 12 kg of wood at 40 % moisture (wet basis). Evaporating water costs about 2.44 MJ/kg. How much energy goes just into evaporating its water?',
    choices: [
      { id: 'a', text: '≈ 11.7 MJ', why: 'Correct: 12 × 0.4 = 4.8 kg of water, × 2.44.' },
      { id: 'b', text: '≈ 29.3 MJ', why: 'That treats all 12 kg as water.' },
      { id: 'c', text: '≈ 17.6 MJ', why: 'That uses the 60 % dry wood (7.2 kg) instead of the 40 % water.' },
      { id: 'd', text: '≈ 1.0 MJ', why: 'That is the cost per kg of wood (0.4 × 2.44); it forgets the 12 kg.' },
    ],
    answer: 'a',
    concepts: ['moisture-content'],
    explanation: '12 × 0.4 = 4.8 kg of water; 4.8 × 2.44 ≈ **11.7 MJ** — heat that never reaches you, plus the smoke and cooler flame that come with it.',
  },
  {
    id: 's3-rev-4',
    kind: 'single',
    prompt: 'At −20 °C your lighter will not light. Which Stage 1 principle does carrying a ferro rod as well illustrate?',
    choices: [
      { id: 'a', text: 'Redundancy of critical functions', why: 'Correct: two independent ways to do a life-critical job.' },
      { id: 'b', text: 'The rule of threes', why: 'That ranks survival time limits; it says nothing about backup gear.' },
      { id: 'c', text: 'Stay or move', why: 'That is a navigation and rescue decision, not about ignition.' },
      { id: 'd', text: 'Risk = likelihood × consequence', why: 'Related, but the specific principle is redundancy.' },
    ],
    answer: 'a',
    concepts: ['redundancy', 'spark-ignition'],
    explanation: 'Ignition is a critical function: carry at least two methods that fail in different ways (cold, wet, empty).',
  },
  {
    id: 's3-rev-5',
    kind: 'single',
    prompt: 'A bow-drill user presses with 70 N; the friction coefficient is 0.45; the average rubbing speed is 1.1 m/s. What is the friction power?',
    choices: [
      { id: 'a', text: '≈ 35 W', why: 'Correct: 0.45 × 70 × 1.1.' },
      { id: 'b', text: '≈ 77 W', why: 'That leaves out the friction coefficient μ.' },
      { id: 'c', text: '≈ 32 W', why: 'That leaves out the rubbing speed (0.45 × 70).' },
      { id: 'd', text: '≈ 171 W', why: 'That divides by μ instead of multiplying.' },
    ],
    answer: 'a',
    concepts: ['friction-power'],
    explanation: '0.45 × 70 × 1.1 ≈ **35 W** — close to the limit of what arm muscles sustain for long.',
  },
]
