import type { Question } from '../../types'

// Stage 16 review: interleaves urban/disaster decisions with earlier stages — immediate danger,
// water treatment, heat balance, signaling, trip and communication plans.
export const stage16Review: Question[] = [
  {
    id: 's16-rev-10',
    kind: 'single',
    prompt: 'After a strong earthquake your block is visibly cracked. It is 4 °C and dropping; a community shelter has opened 1 km away. Aftershocks continue. Where do you spend the night?',
    choices: [
      { id: 'a', text: 'Back in the flat — it is warmer and the cracks may be cosmetic', why: 'An uninspected, visibly damaged building during aftershocks is the highest-consequence option.' },
      { id: 'b', text: 'In the community shelter, registered, with the go-bag, medicines and the elderly neighbour', why: 'Correct — safe from collapse, warm, with water, sanitation, first aid and information.' },
      { id: 'c', text: 'In the car parked beside the building', why: 'Beside the building is where debris falls; cold car, no support.' },
      { id: 'd', text: 'Walk to relatives 25 km away through the damaged city at night', why: 'Long exposure, darkness, damaged routes — a stay-or-move decision that favours staying at the shelter tonight.' },
    ],
    answer: 'b',
    concepts: ['temporary-shelter', 'aftershocks', 'stay-or-move', 'immediate-danger'],
    explanation: 'Stay or move (Stage 1) in a city: move away from the collapse hazard, but not into a long night journey. Community shelters exist for this night.',
  },
  {
    id: 's16-rev-8',
    kind: 'single',
    prompt: 'Heatwave, 39 °C, the power is out. Your 80-year-old neighbour is confused, hot to the touch and has stopped sweating. What do you do?',
    choices: [
      { id: 'a', text: 'Give her plenty of water to drink and let her sleep it off', why: 'Confusion with a hot body is possible heat stroke — a medical emergency; she may not be able to drink safely.' },
      { id: 'b', text: 'Call the emergency number and cool her fast: wet skin, fanning, cold packs', why: 'Correct — rapid cooling first (cold packs at neck, armpits, groin; cool-water immersion if possible), and emergency care.' },
      { id: 'c', text: 'Drive her to the cooling centre in your car without calling anyone', why: 'Delays cooling and medical care.' },
      { id: 'd', text: 'Wrap her in a wet sheet and leave her to rest in the closed flat', why: 'Better than nothing, but she needs active cooling and emergency help, and should not be alone.' },
    ],
    answer: 'b',
    concepts: ['heat-illness', 'vulnerable-neighbours', 'extreme-weather-home'],
    explanation: 'Stage 8: for heat stroke, cool first and fast, and get help. In heatwaves the victims are mostly older people alone — which is why neighbour checks matter.',
  },
  {
    id: 's16-rev-1',
    kind: 'single',
    prompt: 'A gas explosion has damaged a neighbouring house. A man lies in the front garden, bleeding heavily from the thigh; there is a strong smell of gas. Which order of actions is correct?',
    choices: [
      { id: 'a', text: 'Assess the scene → call for help → move him clear → control bleeding', why: 'Correct — scene safety, early call, then move only as needed and treat.' },
      { id: 'b', text: 'Control bleeding → assess the scene → call for help → move him clear', why: 'Rushing in before checking for gas, fire and unstable walls can make you a second casualty.' },
      { id: 'c', text: 'Move him clear → control bleeding → assess the scene → call for help', why: 'Entering the danger zone before assessing it puts the rescuer at risk, and help is called late.' },
      { id: 'd', text: 'Assess the scene → control bleeding where he lies → call for help → move him clear', why: 'Treating him beside the gas leak keeps both of you in danger and delays the call.' },
    ],
    answer: 'a',
    concepts: ['immediate-danger', 'gas-leak', 'bleeding-control'],
    explanation: 'Scene safety first (Stage 1): with gas and a damaged structure, the rescuer must not become a casualty. Call the emergency number early from a safe distance, move the casualty only as far as needed, then control life-threatening bleeding with firm direct pressure (Stage 9 — take a hands-on course).',
  },
  {
    id: 's16-rev-2',
    kind: 'single',
    prompt: 'Your water supply is back on under a boil-water notice. The only fuel you have is a camping stove. Which plan is best for a family of four for today?',
    choices: [
      { id: 'a', text: 'Boil a large pot on the stove in the kitchen, windows shut to keep heat in', why: 'A camping stove indoors produces carbon monoxide.' },
      { id: 'b', text: 'Boil water outdoors for 1 minute, or bleach it at the label dose for 30 minutes', why: 'Correct — both methods deal with the microbes a boil notice is about; use the treated water for drinking, teeth, formula and washing food.' },
      { id: 'c', text: 'Run the cold tap for 10 minutes to flush the pipes, then drink it', why: 'Flushing pipes does not disinfect.' },
      { id: 'd', text: 'Pour it through a coffee filter to strip out the contamination', why: 'Removes particles, not bacteria or viruses.' },
    ],
    answer: 'b',
    concepts: ['water-treatment', 'water-outage', 'carbon-monoxide'],
    explanation: 'Stage 4’s treatment logic plus this stage’s CO rule: treat for microbes (rolling boil or unscented bleach), and keep fuel-burning devices outdoors.',
  },
  {
    id: 's16-rev-4',
    kind: 'single',
    prompt: 'You are trapped under debris after an earthquake, uninjured but unable to move out. Your phone has 20 % battery and one bar. What is the best way to be found?',
    choices: [
      { id: 'a', text: 'Shout for help continuously so anyone nearby will hear you', why: 'Exhausting, draws in dust, and voices carry poorly through rubble.' },
      { id: 'b', text: 'Text your location, then tap on a pipe or blow a whistle in threes at intervals', why: 'Correct — a text gets through congested networks; tapping and whistle blasts carry through structures and use little energy.' },
      { id: 'c', text: 'Call the emergency number repeatedly until someone answers', why: 'Drains the battery and often fails on congested networks.' },
      { id: 'd', text: 'Stay silent to save energy until you hear rescuers close by', why: 'Signal periodically so rescuers know to look for you.' },
    ],
    answer: 'b',
    concepts: ['signaling', 'comms-failure', 'post-quake-checks'],
    explanation: 'Stage 1 signaling in a city: sound in threes, conserve energy, and use the channel most likely to get through — a text to your out-of-area contact and the emergency number if supported.',
  },
  {
    id: 's16-rev-5',
    kind: 'single',
    prompt: 'You are driving home through a city in a storm. The underpass ahead has water across it; a car ahead made it through. What do you do?',
    choices: [
      { id: 'a', text: 'Follow the other car slowly', why: '“Someone else did it” is a heuristic trap (tracks/social proof); depth and current are unknown and can change in seconds.' },
      { id: 'b', text: 'Turn around and take a higher route, or wait somewhere safe', why: 'Correct — turn around, don’t drown.' },
      { id: 'c', text: 'Drive through fast to get momentum', why: 'A bow wave and loss of control; engines stall.' },
      { id: 'd', text: 'Get out and wade to check the depth', why: 'Moving water knocks adults down at about 15 cm.' },
    ],
    answer: 'b',
    concepts: ['flood-home', 'human-factors', 'go-no-go'],
    explanation: 'The FACETS traps from Stage 1 apply in towns too. Underpasses are among the deadliest places in urban floods.',
  },
  {
    id: 's16-rev-3',
    kind: 'single',
    prompt: 'Day 2 of a winter power cut, 8 °C indoors. Which measure does **not** belong in a safe plan to improve your household’s **heat balance**?',
    choices: [
      { id: 'a', text: 'Gathering everyone in one small interior room, door closed', why: 'Belongs — less volume to heat, body heat shared.' },
      { id: 'b', text: 'Hats, layers, sleeping bags and mats under anyone lying down', why: 'Belongs — insulation and reduced conduction to cold floors.' },
      { id: 'c', text: 'Leaving the gas oven on with its door open for warmth', why: 'Correct — it adds carbon monoxide and fire risk.' },
      { id: 'd', text: 'Covering the windows with blankets or plastic sheeting', why: 'Belongs — less radiative and convective loss.' },
    ],
    answer: 'c',
    concepts: ['heat-balance', 'extreme-weather-home', 'carbon-monoxide'],
    explanation: 'The same heat-balance terms as in Stage 1: reduce losses (insulation, smaller space, windows), increase production (warm, high-energy food and drinks), never add a CO source.',
  },
  {
    id: 's16-rev-6',
    kind: 'single',
    prompt: 'Your family plan and a hiking trip plan (Stage 1) share several features. Which one is **not** shared?',
    choices: [
      { id: 'a', text: 'A named contact who is not with you', why: 'Shared — the trip-plan contact and the out-of-area contact.' },
      { id: 'b', text: 'Decisions made in advance, such as turnaround times or triggers', why: 'Shared — pre-commitment beats in-the-moment judgment.' },
      { id: 'c', text: 'A time or condition that starts action by others', why: 'Shared — the overdue time and the check-in.' },
      { id: 'd', text: 'Relying on memory rather than paper, to keep it light', why: 'Correct — both plans are written on paper as well as the phone.' },
    ],
    answer: 'd',
    concepts: ['family-plan', 'trip-plan', 'comms-plan'],
    explanation: 'Both plans are written down, convert a chaotic moment into pre-made decisions, and tell someone outside the situation what to do and when.',
  },
  {
    id: 's16-rev-9',
    kind: 'single',
    prompt: 'During a long outage you want to charge phones from the car. Which way of doing it is safe?',
    choices: [
      { id: 'a', text: 'Run the car outdoors, away from windows — or use power banks', why: 'Correct — exhaust stays outside.' },
      { id: 'b', text: 'Run it in the closed garage for an hour while you stay in the house', why: 'CO from a garage seeps into the house.' },
      { id: 'c', text: 'Run it in the garage with the big door left half open', why: 'A garage is never safe for running engines; CO still enters the house.' },
      { id: 'd', text: 'Run it in the garage only in short 15-minute bursts', why: 'Even short runs in a garage build up CO that seeps indoors.' },
    ],
    answer: 'a',
    concepts: ['carbon-monoxide', 'generator-safety'],
    explanation: 'CO from a garage seeps into the house. Charge from a car only outdoors, away from windows — or use power banks.',
  },
  {
    id: 's16-rev-7',
    kind: 'single',
    prompt: 'A household of 3 wants water for 7 days at 4 L per person per day. They already have 30 L. How many **20 L containers** must they add?',
    choices: [
      { id: 'a', text: '3 containers', why: 'Correct — 54 L ÷ 20 = 2.7, rounded up.' },
      { id: 'b', text: '2 containers', why: 'This rounds 2.7 down and leaves them 14 L short.' },
      { id: 'c', text: '4 containers', why: 'This ignores the 30 L they already have (84 ÷ 20 = 4.2) and rounds down.' },
      { id: 'd', text: '5 containers', why: 'This ignores the 30 L they already have (84 ÷ 20 = 4.2 → 5).' },
    ],
    answer: 'a',
    concepts: ['emergency-water-food', 'water-needs'],
    explanation: '3 × 4 × 7 = 84 L; 84 − 30 = 54 L; 54 ÷ 20 = 2.7 → **3** containers.',
  },
]
