import type { Question } from '../../types'

// Stage 16 review: interleaves urban/disaster decisions with earlier stages — immediate danger,
// water treatment, heat balance, signaling, trip and communication plans.
export const stage16Review: Question[] = [
  {
    id: 's16-rev-1',
    kind: 'order',
    prompt: 'A gas explosion has damaged a neighbouring house. A man lies in the front garden, bleeding heavily from the thigh; there is a strong smell of gas. Order your actions.',
    items: [
      { id: 'danger', text: 'Assess the scene: gas, fire, unstable walls — keep yourself out of the danger zone' },
      { id: 'call', text: 'Call the emergency number (from a safe distance) and report gas and a casualty' },
      { id: 'move', text: 'If he can be reached safely, move him away from the house and gas' },
      { id: 'bleed', text: 'Control the bleeding with firm direct pressure (tourniquet if pressure fails)' },
    ],
    answer: ['danger', 'call', 'move', 'bleed'],
    concepts: ['immediate-danger', 'gas-leak', 'bleeding-control'],
    explanation: 'Scene safety first (Stage 1): with gas and a damaged structure, the rescuer must not become a casualty. Calling early brings help sooner; then move the casualty only as far as needed and control life-threatening bleeding (Stage 9 — take a hands-on course).',
  },
  {
    id: 's16-rev-2',
    kind: 'single',
    prompt: 'Your water supply is back on under a boil-water notice. The only fuel you have is a camping stove. Which plan is best for a family of four for today?',
    choices: [
      { id: 'a', text: 'Boil a large pot on the stove in the kitchen with the windows shut to save heat', why: 'A camping stove indoors produces carbon monoxide.' },
      { id: 'b', text: 'Boil water outdoors (rolling boil 1 minute), or use unscented bleach at the label dose with 30 minutes contact; use the treated water for drinking, teeth, formula and washing food', why: 'Correct — both methods deal with the microbes a boil notice is about; the stove stays outdoors.' },
      { id: 'c', text: 'Run the tap for 10 minutes; then it is safe', why: 'Flushing pipes does not disinfect.' },
      { id: 'd', text: 'Filter through a coffee filter', why: 'Removes particles, not bacteria or viruses.' },
    ],
    answer: 'b',
    concepts: ['water-treatment', 'water-outage', 'carbon-monoxide'],
    explanation: 'Stage 4’s treatment logic plus this stage’s CO rule: treat for microbes, and keep fuel-burning devices outdoors.',
  },
  {
    id: 's16-rev-3',
    kind: 'multi',
    prompt: 'Day 2 of a winter power cut, 8 °C indoors. Which measures improve the **heat balance** of your household without creating new hazards?',
    choices: [
      { id: 'a', text: 'Everyone in one small interior room with the door closed', why: 'Yes — less volume to heat, body heat shared.' },
      { id: 'b', text: 'Hats, layers and sleeping bags; insulating mats under anyone sitting or lying', why: 'Yes — insulation and reduced conduction to cold floors.' },
      { id: 'c', text: 'Warm, high-energy food and drinks', why: 'Yes — heat production.' },
      { id: 'd', text: 'Leaving the gas oven on with its door open', why: 'No — carbon monoxide and fire risk.' },
      { id: 'e', text: 'Covering windows with blankets or plastic', why: 'Yes — less radiative and convective loss.' },
    ],
    answer: ['a', 'b', 'c', 'e'],
    concepts: ['heat-balance', 'extreme-weather-home', 'carbon-monoxide'],
    explanation: 'The same heat-balance terms as in Stage 1: reduce losses (insulation, smaller space, windows), increase production (food), never add a CO source.',
  },
  {
    id: 's16-rev-4',
    kind: 'single',
    prompt: 'You are trapped under debris after an earthquake, uninjured but unable to move out. Your phone has 20 % battery and one bar. What is the best way to be found?',
    choices: [
      { id: 'a', text: 'Shout continuously', why: 'Exhausting, draws in dust, and voices carry poorly through rubble.' },
      { id: 'b', text: 'Text your location to your out-of-area contact and the emergency number if supported; then tap on a pipe or wall or use a whistle in groups of three at intervals', why: 'Correct — a text gets through congested networks; tapping and whistle blasts carry through structures and use little energy.' },
      { id: 'c', text: 'Call repeatedly until someone answers', why: 'Drains the battery and often fails on congested networks.' },
      { id: 'd', text: 'Stay silent to save energy until you hear rescuers', why: 'Signal periodically so rescuers know to look for you.' },
    ],
    answer: 'b',
    concepts: ['signaling', 'comms-failure', 'post-quake-checks'],
    explanation: 'Stage 1 signaling in a city: sound in threes, conserve energy, and use the channel most likely to get through — text.',
  },
  {
    id: 's16-rev-5',
    kind: 'single',
    prompt: 'You are driving home through a city in a storm. The underpass ahead has water across it; a car ahead made it through. What do you do?',
    choices: [
      { id: 'a', text: 'Follow the other car slowly', why: '“Someone else did it” is a heuristic trap (tracks/social proof); depth and current are unknown and can change in seconds.' },
      { id: 'b', text: 'Turn around and take a higher route, or wait somewhere safe', why: 'Correct — turn around, don’t drown.' },
      { id: 'c', text: 'Drive through fast to get momentum', why: 'A bow wave and loss of control; engines stall.' },
      { id: 'd', text: 'Get out and wade to check the depth', why: 'Moving water knocks adults down at about 15 cm.' },
    ],
    answer: 'b',
    concepts: ['flood-home', 'human-factors', 'go-no-go'],
    explanation: 'The FACETS traps from Stage 1 apply in towns too. Underpasses are among the deadliest places in urban floods.',
  },
  {
    id: 's16-rev-6',
    kind: 'multi',
    prompt: 'Your family plan and a hiking trip plan (Stage 1) share which features?',
    choices: [
      { id: 'a', text: 'A named contact who is not with you', why: 'Yes — the trip-plan contact and the out-of-area contact.' },
      { id: 'b', text: 'Decisions made in advance (turnaround times / evacuation triggers)', why: 'Yes — pre-commitment beats in-the-moment judgment.' },
      { id: 'c', text: 'Written on paper as well as the phone', why: 'Yes.' },
      { id: 'd', text: 'A time or condition that starts action by others (overdue time / check-in)', why: 'Yes.' },
      { id: 'e', text: 'Relying on memory to save weight', why: 'No.' },
    ],
    answer: ['a', 'b', 'c', 'd'],
    concepts: ['family-plan', 'trip-plan', 'comms-plan'],
    explanation: 'Both plans convert a chaotic moment into pre-made decisions and tell someone outside the situation what to do and when.',
  },
  {
    id: 's16-rev-7',
    kind: 'numeric',
    prompt: 'A household of 3 wants water for 7 days at 4 L per person per day. They already have 30 L. How many **20 L containers** must they add (round up)?',
    unit: 'containers',
    answer: 3,
    tolerance: 0,
    concepts: ['emergency-water-food', 'water-needs'],
    explanation: '3 × 4 × 7 = 84 L; 84 − 30 = 54 L; 54 ÷ 20 = 2.7 → **3** containers.',
  },
  {
    id: 's16-rev-8',
    kind: 'single',
    prompt: 'Heatwave, 39 °C, the power is out. Your 80-year-old neighbour is confused, hot to the touch and has stopped sweating. What do you do?',
    choices: [
      { id: 'a', text: 'Give her water and let her sleep it off', why: 'Confusion with a hot body is possible heat stroke — a medical emergency; she may not be able to drink safely.' },
      { id: 'b', text: 'Call the emergency number, move her to the coolest place, and cool her aggressively (wet her skin and fan, cold packs at neck, armpits, groin; cool-water immersion if possible)', why: 'Correct — rapid cooling first, and emergency care.' },
      { id: 'c', text: 'Drive her to the cooling centre in your hot car without calling anyone', why: 'Delays cooling and medical care.' },
      { id: 'd', text: 'Wrap her in a wet sheet and leave her to rest in the closed flat', why: 'Better than nothing, but she needs active cooling and emergency help, and should not be alone.' },
    ],
    answer: 'b',
    concepts: ['heat-illness', 'vulnerable-neighbours', 'extreme-weather-home'],
    explanation: 'Stage 8: for heat stroke, cool first and fast, and get help. In heatwaves the victims are mostly older people alone — which is why neighbour checks matter.',
  },
  {
    id: 's16-rev-9',
    kind: 'truefalse',
    prompt: 'During a long outage, running a car in a closed garage for an hour to charge phones is safe as long as you stay in the house.',
    answer: false,
    concepts: ['carbon-monoxide', 'generator-safety'],
    explanation: 'CO from a garage seeps into the house. Charge from a car only outdoors, away from windows — or use power banks.',
  },
  {
    id: 's16-rev-10',
    kind: 'single',
    prompt: 'After a strong earthquake your block is visibly cracked. It is 4 °C and dropping; a community shelter has opened 1 km away. Aftershocks continue. Where do you spend the night?',
    choices: [
      { id: 'a', text: 'Back in the flat — it is warmer and the cracks may be cosmetic', why: 'An uninspected, visibly damaged building during aftershocks is the highest-consequence option.' },
      { id: 'b', text: 'In the community shelter, registered, with the go-bag, medicines and the elderly neighbour', why: 'Correct — safe from collapse, warm, with water, sanitation, first aid and information.' },
      { id: 'c', text: 'In the car parked beside the building', why: 'Beside the building is where debris falls; cold car, no support.' },
      { id: 'd', text: 'Walk to relatives 25 km away through the damaged city at night', why: 'Long exposure, darkness, damaged routes — a stay-or-move decision that favours staying at the shelter tonight.' },
    ],
    answer: 'b',
    concepts: ['temporary-shelter', 'aftershocks', 'stay-or-move', 'immediate-danger'],
    explanation: 'Stay or move (Stage 1) in a city: move away from the collapse hazard, but not into a long night journey. Community shelters exist for this night.',
  },
]
